/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2025-09-06 05:23:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.credit_005frisk;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Vector;
import com.etrm.fms.util.CommonVariable;
import com.etrm.fms.util.EncryptTest;

public final class frm_005ftcs_005ftds_005ftax_005fstructure_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/credit_risk/../util/common_val.jsp", Long.valueOf(1754630867617L));
    _jspx_dependants.put("/credit_risk/../util/common_js.jsp", Long.valueOf(1754630867617L));
    _jspx_dependants.put("/credit_risk/../util/../sess/Expire.jsp", Long.valueOf(1754630867476L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("com.etrm.fms.util.CommonVariable");
    _jspx_imports_classes.add("com.etrm.fms.util.EncryptTest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n<html>\n<head>\n");
      out.write('\n');

String expire_msg = request.getParameter("expire_msg")==null?"":request.getParameter("expire_msg");
if(session.getAttribute("emp_uid")==null || session.getAttribute("emp_uid") == ""|| session.getAttribute("emp_uid").toString().equals("null"))
{
      out.write("\r\n		<script>\r\n			alert(\"Please Enter Login Detail!\")\r\n			var url = \"../home/login.jsp\";\r\n			location.replace(url);\r\n		</script>\r\n");
}
else
{
	if(expire_msg.equals("Timeout"))
	{
		session.invalidate();
	
      out.write("\r\n		<script>\r\n		var url = \"../home/login.jsp?sess=Session Expired\";\r\n		location.replace(url);\r\n		</script>\r\n	");

	}
	else if(expire_msg.equals("PwdChng"))
	{
		session.invalidate();
	
      out.write("\r\n		<script>\r\n		var url = \"../home/login.jsp\";\r\n		location.replace(url);\r\n		</script>\r\n	");
}
}

      out.write("\r\n\r\n");
      out.write('\n');
String COMMlogo="";
if(session.getAttribute("comp_logo")==null||session.getAttribute("comp_logo")==""||session.getAttribute("comp_logo").toString().equals("null"))
{
	COMMlogo="";
}  
else
{
	COMMlogo=""+session.getAttribute("comp_logo");
}

String sel_comp_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	sel_comp_cd="";
}  
else
{
	sel_comp_cd=""+session.getAttribute("comp_cd");
}

      out.write("\n<link rel=\"SHORTCUT ICON\" href=\"../images/");
      out.print(COMMlogo);
      out.write("\">\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<meta http-equiv=\"refresh\" content=\"");
      out.print(session.getMaxInactiveInterval());
      out.write(";url=../sess/Expire.jsp?expire_msg=Timeout\"/>\n<title>");
      out.print(CommonVariable.app_name);
      out.write("</title>\n\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap/bootstrap5/css/bootstrap.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../font-awesome-4.7.0/css/font-awesome.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/datepicker/bootstrap-datepicker3.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/util.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/main.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/navbar.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/responsive.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">\n\n");
 if ("2".equals(sel_comp_cd)) { 
      out.write("\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common_2.css\">  <!-- CSS for comp_cd = \"2\" -->\n");
 } else { 
      out.write("\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">  <!-- CSS for comp_cd = \"1\" -->\n");
 } 
      out.write("\n\n<script type=\"text/javascript\" src=\"../bootstrap/bootstrap5/js/bootstrap.bundle.min.js\"></script>\n<script type=\"text/javascript\" src=\"../js/jquery.min.js\"></script>\n<script type=\"text/javascript\" src=\"../js/datepicker/bootstrap-datepicker.min.js\"></script>\n<script type=\"text/javascript\" src=\"../js/datepicker/bootstrap-datepicker.es.min.js\"></script>\n\n<script type=\"text/javascript\" src=\"../js/util.js\"></script>\n");
      out.write("\n<script type=\"text/javascript\" src=\"../js/session.js\"></script>\n\n");
      out.write('\r');
      out.write('\n');
      com.etrm.fms.util.DataBean_Menu menu_access = null;
      menu_access = (com.etrm.fms.util.DataBean_Menu) _jspx_page_context.getAttribute("menu_access", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (menu_access == null){
        menu_access = new com.etrm.fms.util.DataBean_Menu();
        _jspx_page_context.setAttribute("menu_access", menu_access, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

String formCd="";
String mod_cd="";
String u=request.getParameter("u")==null?"":request.getParameter("u");

String msg=request.getParameter("msg")==null?"":request.getParameter("msg");
String msg_type=request.getParameter("msg_type")==null?"":request.getParameter("msg_type");

String owner_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	owner_cd="";
}  
else
{
	owner_cd=""+session.getAttribute("comp_cd");
}

String owner_abbr="";
if(session.getAttribute("comp_abbr")==null||session.getAttribute("comp_abbr")==""||session.getAttribute("comp_abbr").toString().equals("null"))
{
	owner_abbr="";
}  
else
{
	owner_abbr=""+session.getAttribute("comp_abbr");
}

String emp_cd="";
if(session.getAttribute("emp_cd")==null||session.getAttribute("emp_cd")==""||session.getAttribute("emp_cd").toString().equals("null"))
{
	emp_cd="";
}  
else
{
	emp_cd=""+session.getAttribute("emp_cd");
}

if(!u.equals(""))
{
	StringBuffer decryt=new EncryptTest().URLdecrypt(u);
	String dec=""+decryt;
	if(!dec.equals("") && dec.contains("-"))
	{
		String temp[]=dec.split("-");
		if(temp.length==2)
		{
			formCd=temp[0];
			mod_cd=temp[1];
		}
	}
}

menu_access.setCallFlag("MENU_ACCESS");
menu_access.setEmpCd(emp_cd);
menu_access.setComp_cd(owner_cd);
menu_access.setModule_cd(mod_cd);
menu_access.setForm_cd(formCd);
menu_access.init();


String formNm = menu_access.getForm_nm();
String mod_nm = menu_access.getModule_nm();
String read_access = menu_access.getRead_access();
String write_access = menu_access.getWrite_access();
String check_access = menu_access.getCheck_access();
String print_access = menu_access.getPrint_access();
String delete_access = menu_access.getDelete_access();
String audit_access = menu_access.getAudit_access();
String authorize_access = menu_access.getAuthorize_access();
String approve_access = menu_access.getApprove_access();
String execute_access = menu_access.getExecute_access();


      out.write("\n\n<script type=\"text/javascript\">\ndocument.title = \"");
      out.print(CommonVariable.app_name);
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(owner_abbr);
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(formNm);
      out.write("\";\n</script>\n");
      out.write("\n\n<script>\nfunction setValue(VTAX_STRUCT_CD,VTAX_STRUCT_NM,VTAX_STRUCT_APP_DT,SAP_TAX_CODE)\n{\n	var index = document.forms[0].index.value;\n	var type = document.forms[0].type.value;\n	var tax_app = document.forms[0].tax_app.value;\n	\n	window.opener.setTcsTdsStructDetail(VTAX_STRUCT_CD,VTAX_STRUCT_NM,VTAX_STRUCT_APP_DT,tax_app);\n	window.close();	\n}\n</script>\n</head>\n");
      com.etrm.fms.master.DataBean_Master dbmaster = null;
      dbmaster = (com.etrm.fms.master.DataBean_Master) _jspx_page_context.getAttribute("dbmaster", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (dbmaster == null){
        dbmaster = new com.etrm.fms.master.DataBean_Master();
        _jspx_page_context.setAttribute("dbmaster", dbmaster, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      com.etrm.fms.util.MessageUtil utilmsg = null;
      utilmsg = (com.etrm.fms.util.MessageUtil) _jspx_page_context.getAttribute("utilmsg", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (utilmsg == null){
        utilmsg = new com.etrm.fms.util.MessageUtil();
        _jspx_page_context.setAttribute("utilmsg", utilmsg, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');

String type=request.getParameter("type")==null?"":request.getParameter("type");
String tax_app=request.getParameter("tax_app")==null?"":request.getParameter("tax_app");

String index=request.getParameter("index")==null?"":request.getParameter("index");

dbmaster.setCallFlag("TCS_TDS_TAX_STRUCTURE_LIST");
dbmaster.setComp_cd(owner_cd);
dbmaster.setTax_category(type);
dbmaster.setTax_app(tax_app);
//dbmaster.setPay_recv("R");
dbmaster.init();

Vector VTAX_STRUCT_CD = dbmaster.getVTAX_STRUCT_CD();
Vector VTAX_STRUCT_NM = dbmaster.getVTAX_STRUCT_NM();
Vector VTAX_STRUCT_APP_DT = dbmaster.getVTAX_STRUCT_APP_DT();
Vector VTAX_STRUCT_STATUS = dbmaster.getVTAX_STRUCT_STATUS();
Vector VTAX_STRUCT_RMK = dbmaster.getVTAX_STRUCT_RMK();
Vector VTAX_CATEGORY = dbmaster.getVTAX_CATEGORY();
Vector VTAX_CATEGORY_NM = dbmaster.getVTAX_CATEGORY_NM();
Vector VSAP_TAX_CODE = dbmaster.getVSAP_TAX_CODE();
Vector VSAP_GL = dbmaster.getVSAP_GL();
Vector VPAY_RECV_NM  = dbmaster.getVPAY_RECV_NM();

      out.write("\n<body>\n<form method=\"post\" action=\"../servlet/Frm_master\">\n\n<div class=\"box-body\">\n	<div class=\"row\">\n		<div class=\"col-md-12 col-sm-12 col-xs-12\">\n			");
if(!msg.equals("")){
				if(msg_type.equals("S")){
      out.write("\n					<div class=\"fadealert\">");
      out.print(utilmsg.successMessage(msg));
      out.write("</div>\n				");
}else if(msg_type.equals("E")){
      out.write("\n					<div class=\"fadealert\">");
      out.print( utilmsg.errorMessage(msg));
      out.write("</div>\n				");
}
			} 
      out.write("\n			<div class=\"card cardmain\">\n				<div class=\"card-header cdheader\">\n					<div class=\"d-flex justify-content-between\">\n						<div class=\"topheader\">\n							Tax Structure List\n						</div>					  	\n					</div>\n				</div>\n				<div class=\"card-body cdbody\">\n					<div class=\"row\">\n						<div class=\"table-responsive\">\n							<table class=\"table table-bordered table-hover\" id=\"example\">\n								<thead>\n									<tr>\n										<th></th>\n										<th>Tax Structure<br>(Internal Code)</th>\n										<th>Effective Date</th>\n										<th>\n											Tax Structure\n											<br><div align=\"center\"><input class=\"form-control form-control-sm\" type=\"text\" id=\"table_Description\" onkeyup=\"Search(this,'3');\" placeholder=\"Search..\" style=\"width:100px\"/></div>	\n										</th>\n										<th>Tax Category</th>\n										<th>SAP Tax Code</th>\n										<th>SAP GL</th>\n										<th>Status</th>\n										<th>Payable / Receivable</th>\n										<th>Remark</th>\n									</tr>\n								</thead>\n								<tbody>\n								");
if(VTAX_STRUCT_CD.size() > 0){ 
      out.write("\n									");
for(int i=0; i<VTAX_STRUCT_CD.size(); i++){ 
      out.write("\n									<tr>\n										<td width=\"5%\" align=\"center\">\n											<div align=\"center\">\n												<input type=\"radio\" name=\"rdbtn\" \n												onclick=\"setValue('");
      out.print(VTAX_STRUCT_CD.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VTAX_STRUCT_NM.elementAt(i));
      out.write("',\n												'");
      out.print(VTAX_STRUCT_APP_DT.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VSAP_TAX_CODE.elementAt(i) );
      out.write("');\" ");
if(VTAX_STRUCT_STATUS.elementAt(i).equals("0")){
      out.write("disabled");
} 
      out.write(">\n											</div>\n										</td>\n										<td align=\"center\">");
      out.print(VTAX_STRUCT_CD.elementAt(i));
      out.write("</td>\n										<td align=\"center\">");
      out.print(VTAX_STRUCT_APP_DT.elementAt(i) );
      out.write("</td>\n										<td>");
      out.print(VTAX_STRUCT_NM.elementAt(i));
      out.write("</td>\n										<td align=\"center\">");
      out.print(VTAX_CATEGORY_NM.elementAt(i));
      out.write("</td>\n										<td align=\"center\">");
      out.print(VSAP_TAX_CODE.elementAt(i));
      out.write("</td>\n										<td align=\"center\">");
      out.print(VSAP_GL.elementAt(i));
      out.write("</td>\n										<td align=\"center\">\n											<div align=\"center\">\n												<font style=\"color:");
if(VTAX_STRUCT_STATUS.elementAt(i).equals("1")){
      out.write("#a6ff4d");
}else{
      out.write('r');
      out.write('e');
      out.write('d');
}
      out.write("\">\n													<i class=\"fa fa-circle fa-lg\" ></i>\n													&nbsp;\n												</font>\n												");
if(VTAX_STRUCT_STATUS.elementAt(i).equals("1")){
      out.write("\n												Active\n												");
}else{ 
      out.write("\n												In-Active\n												");
} 
      out.write("\n											</div>\n										</td>\n										<td align=\"center\">");
      out.print(VPAY_RECV_NM.elementAt(i) );
      out.write("</td>\n										<td>");
      out.print(VTAX_STRUCT_RMK.elementAt(i));
      out.write("</td>\n									</tr>\n									");
} 
      out.write("\n								");
}else{ 
      out.write("\n									<tr>\n										<td align=\"center\" colspan=\"9\">");
      out.print(utilmsg.infoMessage("<b>No Tax Structure is Configured!</b>") );
      out.write("</td>\n									</tr>\n								");
} 
      out.write("\n								</tbody>\n							</table>\n						</div>\n					</div>\n				</div>\n			</div>\n		</div>\n	</div>\n</div>\n\n<input type=\"hidden\" name=\"index\" value=\"");
      out.print(index);
      out.write("\">\n<input type=\"hidden\" name=\"type\" value=\"");
      out.print(type);
      out.write("\">\n<input type=\"hidden\" name=\"tax_app\" value=\"");
      out.print(tax_app);
      out.write("\">\n\n<input type=\"hidden\" name=\"prev_sel_index\" value=\"\">\n\n<input type=\"hidden\" name=\"tax_struct_cd\" value=\"\">\n<input type=\"hidden\" name=\"tax_struct_nm\" value=\"\">\n\n\n<input type=\"hidden\" name=\"read_access\" value=\"");
      out.print(read_access);
      out.write("\">\n<input type=\"hidden\" name=\"write_access\" value=\"");
      out.print(write_access);
      out.write("\">\n<input type=\"hidden\" name=\"check_access\" value=\"");
      out.print(check_access);
      out.write("\">\n<input type=\"hidden\" name=\"print_access\" value=\"");
      out.print(print_access);
      out.write("\">\n<input type=\"hidden\" name=\"delete_access\" value=\"");
      out.print(delete_access);
      out.write("\">  	\n<input type=\"hidden\" name=\"audit_access\" value=\"");
      out.print(audit_access);
      out.write("\">\n<input type=\"hidden\" name=\"authorize_access\" value=\"");
      out.print(authorize_access);
      out.write("\">\n<input type=\"hidden\" name=\"approve_access\" value=\"");
      out.print(approve_access);
      out.write("\">\n<input type=\"hidden\" name=\"execute_access\" value=\"");
      out.print(execute_access);
      out.write("\">\n<input type=\"hidden\" name=\"form_cd\" value=\"");
      out.print(formCd);
      out.write("\">\n<input type=\"hidden\" name=\"form_nm\" value=\"");
      out.print(formNm);
      out.write("\">\n<input type=\"hidden\" name=\"mod_cd\" value=\"");
      out.print(mod_cd);
      out.write("\">\n<input type=\"hidden\" name=\"mod_nm\" value=\"");
      out.print(mod_nm);
      out.write("\">\n<input type=\"hidden\" name=\"u\" value=\"");
      out.print(u);
      out.write("\">\n\n</form>\n</body>\n\n<script>\nfunction Search(obj, indx) \n{\n  	var input, filter, table, tr, td, i, txtValue,count=0;\n  	input = document.getElementById(obj.id);\n  	\n  	filter = input.value.toLocaleLowerCase();\n  	table = document.getElementById(\"example\");\n  	\n  	tr = table.getElementsByTagName(\"tr\");\n  	for (i = 1; i < tr.length; i++) \n  	{\n    	td = tr[i].getElementsByTagName(\"td\")[indx];\n    	if (td) \n    	{\n      		txtValue = td.textContent || td.innerText;\n      		if (txtValue.toLocaleLowerCase().indexOf(filter) > -1) {\n        		tr[i].style.display = \"\";\n        		count++;\n      		} else {\n      			tr[i].style.display = \"none\";\n      		}\n    	}       \n  	}\n}\n</script>\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
