/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2026-04-03 14:50:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.credit_005frisk;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Vector;
import com.etrm.fms.util.CommonVariable;
import com.etrm.fms.util.EncryptTest;
import com.etrm.fms.util.CommonVariable;
import java.util.Vector;
import java.util.Set;

public final class frm_005fcredit_005fexceed_005fdays_005fapproval_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/credit_risk/../util/common_val.jsp", Long.valueOf(1747068186000L));
    _jspx_dependants.put("/credit_risk/../home/header.jsp", Long.valueOf(1747068184000L));
    _jspx_dependants.put("/credit_risk/../home/../menu/menu.jsp", Long.valueOf(1772450856000L));
    _jspx_dependants.put("/credit_risk/../util/common_js.jsp", Long.valueOf(1772512616937L));
    _jspx_dependants.put("/credit_risk/../home/loading.jsp", Long.valueOf(1747068184000L));
    _jspx_dependants.put("/credit_risk/../util/../sess/Expire.jsp", Long.valueOf(1754630867476L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("com.etrm.fms.util.CommonVariable");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("com.etrm.fms.util.EncryptTest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n<html>\n<head>\n");
      out.write('\n');

String expire_msg = request.getParameter("expire_msg")==null?"":request.getParameter("expire_msg");
if(session.getAttribute("emp_uid")==null || session.getAttribute("emp_uid") == ""|| session.getAttribute("emp_uid").toString().equals("null"))
{
      out.write("\r\n		<script>\r\n			alert(\"Please Enter Login Detail!\")\r\n			var url = \"../home/login.jsp\";\r\n			location.replace(url);\r\n		</script>\r\n");
}
else
{
	if(expire_msg.equals("Timeout"))
	{
		session.invalidate();
	
      out.write("\r\n		<script>\r\n		var url = \"../home/login.jsp?sess=Session Expired\";\r\n		location.replace(url);\r\n		</script>\r\n	");

	}
	else if(expire_msg.equals("PwdChng"))
	{
		session.invalidate();
	
      out.write("\r\n		<script>\r\n		var url = \"../home/login.jsp\";\r\n		location.replace(url);\r\n		</script>\r\n	");
}
}

      out.write("\r\n\r\n");
      out.write('\n');
String COMMlogo="";
if(session.getAttribute("comp_logo")==null||session.getAttribute("comp_logo")==""||session.getAttribute("comp_logo").toString().equals("null"))
{
	COMMlogo="";
}  
else
{
	COMMlogo=""+session.getAttribute("comp_logo");
}

String sel_comp_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	sel_comp_cd="";
}  
else
{
	sel_comp_cd=""+session.getAttribute("comp_cd");
}
String wmk_comp_abbr="";
if(session.getAttribute("comp_abbr")==null||session.getAttribute("comp_abbr")==""||session.getAttribute("comp_abbr").toString().equals("null"))
{
	wmk_comp_abbr="";
}  
else
{
	wmk_comp_abbr=""+session.getAttribute("comp_abbr");
}

      out.write("\n<link rel=\"SHORTCUT ICON\" href=\"../images/");
      out.print(COMMlogo);
      out.write("\">\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<meta http-equiv=\"refresh\" content=\"");
      out.print(session.getMaxInactiveInterval());
      out.write(";url=../sess/Expire.jsp?expire_msg=Timeout\"/>\n<title>");
      out.print(CommonVariable.app_name);
      out.write("</title>\n\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap/bootstrap5/css/bootstrap.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../font-awesome-4.7.0/css/font-awesome.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/datepicker/bootstrap-datepicker3.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/util.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/main.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/navbar.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/responsive.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">\n\n");
 if ("2".equals(sel_comp_cd)) { 
      out.write("\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common_2.css\">  <!-- CSS for comp_cd = \"2\" -->\n");
 } else { 
      out.write("\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">  <!-- CSS for comp_cd = \"1\" -->\n");
 } 
      out.write("\n\n<script type=\"text/javascript\" src=\"../js/jquery.min.js\"></script>\n<script type=\"text/javascript\" src=\"../bootstrap/bootstrap5/js/bootstrap.bundle.min.js\"></script>\n<script type=\"text/javascript\" src=\"../js/datepicker/bootstrap-datepicker.min.js\"></script>\n<script type=\"text/javascript\" src=\"../js/datepicker/bootstrap-datepicker.es.min.js\"></script>\n\n<!-- HM20251210 : Bootstrap Searchable Select -->\n<link href=\"../css/serchable_select.css\" rel=\"stylesheet\" />\n<script src=\"../js/searchable_select.js\"></script>\n\n<script type=\"text/javascript\" src=\"../js/util.js\"></script>\n<script type=\"text/javascript\" src=\"../js/tableUtil.js\"></script>\n");
      out.write("\n<script type=\"text/javascript\" src=\"../js/session.js\"></script>\n\n");
      out.write('\n');
      com.etrm.fms.util.DataBean_Menu menu_access = null;
      menu_access = (com.etrm.fms.util.DataBean_Menu) _jspx_page_context.getAttribute("menu_access", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (menu_access == null){
        menu_access = new com.etrm.fms.util.DataBean_Menu();
        _jspx_page_context.setAttribute("menu_access", menu_access, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');

String formCd="";
String mod_cd="";
String u=request.getParameter("u")==null?"":request.getParameter("u");

String msg=request.getParameter("msg")==null?"":request.getParameter("msg");
String msg_type=request.getParameter("msg_type")==null?"":request.getParameter("msg_type");

String owner_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	owner_cd="";
}  
else
{
	owner_cd=""+session.getAttribute("comp_cd");
}

String owner_abbr="";
if(session.getAttribute("comp_abbr")==null||session.getAttribute("comp_abbr")==""||session.getAttribute("comp_abbr").toString().equals("null"))
{
	owner_abbr="";
}  
else
{
	owner_abbr=""+session.getAttribute("comp_abbr");
}

String emp_cd="";
if(session.getAttribute("emp_cd")==null||session.getAttribute("emp_cd")==""||session.getAttribute("emp_cd").toString().equals("null"))
{
	emp_cd="";
}  
else
{
	emp_cd=""+session.getAttribute("emp_cd");
}

if(!u.equals(""))
{
	StringBuffer decryt=new EncryptTest().URLdecrypt(u);
	String dec=""+decryt;
	if(!dec.equals("") && dec.contains("-"))
	{
		String temp[]=dec.split("-");
		if(temp.length==2)
		{
			formCd=temp[0];
			mod_cd=temp[1];
		}
	}
}

menu_access.setCallFlag("MENU_ACCESS");
menu_access.setEmpCd(emp_cd);
menu_access.setComp_cd(owner_cd);
menu_access.setModule_cd(mod_cd);
menu_access.setForm_cd(formCd);
menu_access.init();


String formNm = menu_access.getForm_nm();
String mod_nm = menu_access.getModule_nm();
String read_access = menu_access.getRead_access();
String write_access = menu_access.getWrite_access();
String check_access = menu_access.getCheck_access();
String print_access = menu_access.getPrint_access();
String delete_access = menu_access.getDelete_access();
String audit_access = menu_access.getAudit_access();
String authorize_access = menu_access.getAuthorize_access();
String approve_access = menu_access.getApprove_access();
String execute_access = menu_access.getExecute_access();


      out.write("\n\n<script type=\"text/javascript\">\ndocument.title = \"");
      out.print(CommonVariable.app_name);
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(owner_abbr);
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(formNm);
      out.write("\";\n</script>\n<script>\n$(function () {\n    function initSelect2(container) {\n        $(container).find('.searchable-select').each(function () {\n            if (!$(this).data('select2')) {\n                $(this).select2({\n                    theme: 'bootstrap-5',\n                    width: '100%',\n                    minimumResultsForSearch: 0,\n                    dropdownParent: $(this).closest('.modal').length \n                        ? $(this).closest('.modal') \n                        : $('body')\n                });\n            }\n        });\n    }\n\n    // Initialize non-modal selects\n    initSelect2(document);\n\n    // Initialize selects when ANY modal opens\n    $(document).on('shown.bs.modal', function (e) {\n        initSelect2(e.target);\n    });\n});\n</script>\n\n\n<!-- TAB Counter -->\n<script>\n(function() {\n    // Always generate a unique tabId for this tab (even if duplicated)\n    const tabId = 'tab_' + crypto.randomUUID();\n    sessionStorage.setItem('tabId', tabId);\n\n    const servletURL = '");
      out.print(request.getContextPath());
      out.write("/TabTrackerServlet';\n\n    // Notify server that tab is opened\n    fetch(servletURL, {\n        method: 'POST',\n        body: new URLSearchParams({ action: 'open', tabId: tabId })\n    })\n    .then(res => res.json())\n    .then(data => {\n        const tabCountElem = document.getElementById('tabCount');\n        if (tabCountElem) tabCountElem.innerText = data.tabCount;\n    });\n\n    // Notify server when tab closes\n    window.addEventListener('beforeunload', () => {\n        navigator.sendBeacon(servletURL, new URLSearchParams({ action: 'close', tabId: tabId }));\n    });\n\n})();\n</script>\n<script>\n//HM20260213:Added this Script to handle In-Active/E-Rate Counterparty actions restriction accross system\n//Global variable to track Counterparty status and allow or block edit\nvar editAllowedOnCpStatus= true;\nvar max_eff_dt  = \"\";\nvar enableButton = false;\n\nfunction fetchCounterpartyDetails()\n{\n	// Check if form exists\n    if (!document.forms || document.forms.length === 0) {\n        return;\n    }\n    var form = document.forms[0];\n");
      out.write("    // Check if counterparty_cd field exists in form\n    if (!form.counterparty_cd) {\n        return;\n    }\n\n	var counterparty_cd = document.forms[0].counterparty_cd.value;\n	if(counterparty_cd != \"\" && counterparty_cd!=\"0\")\n	{\n		$.post(\"../servlet/DBCounterpartyInfo?counterparty_cd=\" + counterparty_cd + \"&setCallType=fetchCounterpartyDetails\",\n		function(responseJson) \n		{\n			if (responseJson.length > 0) \n			{\n				var counterpartyInfo = responseJson[0].COUNTERPARTY_INFO;\n				if (counterpartyInfo.length > 0) \n				{\n					var status = counterpartyInfo[0].STATUS;\n					max_eff_dt = counterpartyInfo[0].EFF_DT;\n					\n					if(status == \"N\")//HM20260217: Removed as per Vijay feedback only for deacive CP edit is disabled || status == \"E\"\n					{\n						editAllowedOnCpStatus = false;\n					} else {\n						editAllowedOnCpStatus = true;\n					}\n					\n					// Gettinh today's system date (without time)\n					var today = new Date();\n					today.setHours(0,0,0,0);\n\n					var isFutureEffective = false;\n					if (max_eff_dt && max_eff_dt !== \"\") {\n");
      out.write("\n						// Split DD/MM/YYYY\n						var parts = max_eff_dt.split(\"/\");\n\n						var day   = parseInt(parts[0], 10);\n						var month = parseInt(parts[1], 10) - 1;\n						var year  = parseInt(parts[2], 10);\n\n						var effDate = new Date(year, month, day);\n						effDate.setHours(0,0,0,0);\n\n						if (effDate > today) {\n							isFutureEffective = true;\n						}\n					}\n					\n					if (editAllowedOnCpStatus === false && !isFutureEffective) {\n						//disableAllInputs();\n						if(!enableButton)\n						{\n							disableSubmitButtons();\n						}\n					}\n					\n					var alertHtml = \"\";\n					if(status == \"N\")\n					{\n						alertHtml = \n						'<div class=\"row m-b-5 dynamic-alert\" >' +\n							'<div class=\"col-sm-3 col-xs-3 col-md-3\"></div>' +\n							'<div class=\"col-sm-6 col-xs-6 col-md-6\">' +\n								'<div class=\"form-group row\">' +\n									'<div class=\"col-sm-12 col-xs-12 col-md-12\">' +\n										'<div class=\"container\">' +\n											'<div class=\"alert alert-danger\">' +\n												'<i class=\"fa fa-exclamation-triangle fa-lg\"></i>&nbsp;' +\n");
      out.write("												'<b>Counterparty Status : Deactive (Effective from : '+ max_eff_dt +')</b>' +\n											'</div>' +\n										'</div>' +\n									'</div>' +\n								'</div>' +\n							'</div>' +\n						'</div>';\n					}\n					else if(status == \"E\")\n					{\n						alertHtml = \n						'<div class=\"row m-b-5 dynamic-alert\" >' +\n							'<div class=\"col-sm-3 col-xs-3 col-md-3\"></div>' +\n							'<div class=\"col-sm-6 col-xs-6 col-md-6\">' +\n								'<div class=\"form-group row\">' +\n									'<div class=\"col-sm-12 col-xs-12 col-md-12\">' +\n										'<div class=\"container\">' +\n											'<div class=\"alert alert-warning\">' +\n												'<i class=\"fa fa-exclamation-triangle fa-lg\"></i>&nbsp;' +\n												'<b>Counterparty Status : E-Rate (Effective from : '+ max_eff_dt +')</b>' +\n											'</div>' +\n										'</div>' +\n									'</div>' +\n								'</div>' +\n							'</div>' +\n						'</div>';\n					}\n					// Remove old alert if already added\n					$(\".dynamic-alert\").remove();\n\n					// Insert INSIDE as first element\n					$(\".card-body.cdbody\").first().prepend(alertHtml);\n");
      out.write("				}\n			}\n		});\n	}\n}\n$(document).ready(function() {\n    fetchCounterpartyDetails();\n});\n\nfunction disableSubmitButtons() {\n   $(\"input[type='button'][value='Submit']\")\n    .prop(\"disabled\", true);\n}\n\n/* function disableAllInputs() {\n    var form = document.forms[0];\n    if (!form) return;\n\n    $(form).find(\"input, select, textarea\").each(function () {\n\n        // Skip hidden fields\n        if (this.tagName.toLowerCase() === \"input\" && this.type === \"hidden\") {\n            return;\n        }\n\n        // Skip buttons (button, submit, reset)\n        if (this.tagName.toLowerCase() === \"input\" && \n            (this.type === \"button\" || this.type === \"submit\" || this.type === \"reset\")) {\n            return;\n        }\n\n        // Skip <button> elements\n        if (this.tagName.toLowerCase() === \"button\") {\n            return;\n        }\n\n        this.disabled = true;\n    });\n} */\n\n\n//Override the native submit function\n(function() {\n	const originalSubmit = HTMLFormElement.prototype.submit;\n	HTMLFormElement.prototype.submit = function() {\n");
      out.write("		\n		// Gettinh today's system date (without time)\n		var today = new Date();\n		today.setHours(0,0,0,0);\n\n		var isFutureEffective = false;\n		if (max_eff_dt && max_eff_dt !== \"\") {\n\n			// Split DD/MM/YYYY\n			var parts = max_eff_dt.split(\"/\");\n\n			var day   = parseInt(parts[0], 10);\n			var month = parseInt(parts[1], 10) - 1;\n			var year  = parseInt(parts[2], 10);\n\n			var effDate = new Date(year, month, day);\n			effDate.setHours(0,0,0,0);\n\n			if (effDate > today) {\n				isFutureEffective = true;\n			}\n		}\n		\n		if(!editAllowedOnCpStatus && !isFutureEffective) \n		{\n			alert(\"Submission Blocked! Counterparty Status must be Active!!\");\n			document.getElementById(\"loading\").style.visibility = \"hidden\";\n			return false; // block submission\n		} \n		else\n		{\n			return originalSubmit.apply(this, arguments); // allow submission\n		}\n	};\n})();\n\n</script>\n\n<!-- Watermark CSS -->\n<style type=\"text/css\">\n    /* Apply the watermark globally on the body */\n    body {\n        position: relative;\n        height: 100vh; /* Ensuring here that body takes the full viewport height */\n");
      out.write("        margin: 0; /* Remove default margin */\n    }\n\n    body::after {\n        content: \"");
      out.print(wmk_comp_abbr);
      out.write("\";  /* Watermark text */\n        font-size: 10vw; /* This is used for viewport width for scalability */\n        /*color: var(--header_color); */        /* Header color */\n    	color: rgba(0, 0, 0, 0.1);\n    	opacity: 0.4;                       /* 40% opacity to watermark */\n    	position: fixed;  /* Make it fixed so it stays in place */\n        top: 50%;  /* Center vertically */\n        left: 50%;  /* Center horizontally */\n        transform: translate(-50%, -50%) rotate(-45deg); /* Center it properly and rotate */\n        pointer-events: none;  /* Make sure it doesn't block any interactions */\n        z-index: 9999;  /* Make sure it's on top */\n        white-space: nowrap;\n        transform-origin: center;\n    }\n\n    /* Make the watermark size smaller on mobile devices */\n    @media screen and (max-width: 767px) {\n        body::after {\n            font-size: 20vw; /* Larger watermark on small screens */\n        }\n    }\n\n    /* Adjust watermark for tablets or medium devices */\n    @media screen and (max-width: 1024px) and (min-width: 768px) {\n");
      out.write("        body::after {\n            font-size: 15vw; /* Moderate size for tablet screens */\n        }\n    }\n    \n    /* Adjust watermark for larger screens (Desktops) */\n    @media screen and (min-width: 1025px) {\n        body::after {\n            font-size: 10vw; /* Default size for desktops */\n        }\n    }\n</style>");
      out.write("\n<script>\nfunction refresh(clearance)\n{\n	var counterparty_cd = document.forms[0].counterparty_cd.value;\n	var contract_map = document.forms[0].contract_map.value;\n	var prev_clearance = document.forms[0].prev_clearance.value;\n	\n	var prev_counterparty_cd = document.forms[0].prev_counterparty_cd.value;\n	if(prev_clearance!=clearance)\n	{\n		counterparty_cd=\"0\";\n		contract_map=\"\";\n	}\n	\n	var u = document.forms[0].u.value;\n	\n	var url = \"frm_credit_exceed_days_approval.jsp?u=\"+u+\n			\"&counterparty_cd=\"+counterparty_cd+\"&contract_map=\"+contract_map+\"&clearance=\"+clearance;\n\n	document.getElementById(\"loading\").style.visibility = \"visible\";\n	location.replace(url);\n}\n\nvar creditExceedWindow;\nfunction creditExceedDaysConfig(cont_type,agmt,agmt_rev,cont,cont_rev,counterparty_cd,temp_start_dt,temp_end_dt)\n{\n	var isDealFm=\"N\";\n	\n	var u = document.forms[0].u.value;\n	\n	var url = \"../credit_risk/frm_credit_exceed_days.jsp?counterparty_cd=\"+counterparty_cd+\"&cont_no=\"+cont+\"&cont_rev_no=\"+cont_rev+\n		\"&agmt_no=\"+agmt+\"&agmt_rev_no=\"+agmt_rev+\"&contract_type=\"+cont_type+\n");
      out.write("		\"&start_dt=\"+temp_start_dt+\"&end_dt=\"+temp_end_dt+\"&isDealFm=\"+isDealFm+\n		\"&u=\"+u;\n	\n	if(!creditExceedWindow || creditExceedWindow.closed)\n	{\n		creditExceedWindow = window.open(url,\"Credit Exceed Days Configuration\",\"top=10,left=100,width=1200,height=600,scrollbars=1\");\n	}\n	else\n	{\n		creditExceedWindow.close();\n		creditExceedWindow = window.open(url,\"Credit Exceed Days Configuration\",\"top=10,left=100,width=1200,height=600,scrollbars=1\");\n	}\n}\n\n</script>\n</head>\n");
      com.etrm.fms.credit_risk.DataBean_CreditRisk credit_risk = null;
      credit_risk = (com.etrm.fms.credit_risk.DataBean_CreditRisk) _jspx_page_context.getAttribute("credit_risk", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (credit_risk == null){
        credit_risk = new com.etrm.fms.credit_risk.DataBean_CreditRisk();
        _jspx_page_context.setAttribute("credit_risk", credit_risk, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      com.etrm.fms.util.MessageUtil utilmsg = null;
      utilmsg = (com.etrm.fms.util.MessageUtil) _jspx_page_context.getAttribute("utilmsg", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (utilmsg == null){
        utilmsg = new com.etrm.fms.util.MessageUtil();
        _jspx_page_context.setAttribute("utilmsg", utilmsg, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      com.etrm.fms.util.DateUtil utildate = null;
      utildate = (com.etrm.fms.util.DateUtil) _jspx_page_context.getAttribute("utildate", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (utildate == null){
        utildate = new com.etrm.fms.util.DateUtil();
        _jspx_page_context.setAttribute("utildate", utildate, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');

String sysdate = utildate.getSysdate();

String counterparty_cd = request.getParameter("counterparty_cd")==null?"0":request.getParameter("counterparty_cd");
String contract_map=request.getParameter("contract_map")==null?"":request.getParameter("contract_map");
String clearance = request.getParameter("clearance")==null?"KYC":request.getParameter("clearance");

credit_risk.setCallFlag("CONT_LIST_FOR_EXCEED_CREDIT");
credit_risk.setClearance(clearance);
credit_risk.setCounterparty_cd(counterparty_cd);
credit_risk.setCont_mapp(contract_map);
credit_risk.setComp_cd(owner_cd);

credit_risk.init();

Vector VCOUNTERPARTY_CD = credit_risk.getVCOUNTERPARTY_CD();
Vector VCOUNTERPARTY_NAME = credit_risk.getVCOUNTERPARTY_NAME();
Vector VCOUNTERPARTY_ABBR = credit_risk.getVCOUNTERPARTY_ABBR();
Vector VCONTRACT_TYPE = credit_risk.getVCONTRACT_TYPE();
Vector VCONT_NO = credit_risk.getVCONT_NO();
Vector VCONT_REV_NO = credit_risk.getVCONT_REV_NO();
Vector VAGMT_NO = credit_risk.getVAGMT_NO();
Vector VAGMT_REV_NO = credit_risk.getVAGMT_REV_NO();
Vector VSTART_DT = credit_risk.getVSTART_DT();
Vector VEND_DT = credit_risk.getVEND_DT();
Vector VCONT_REF_NO = credit_risk.getVCONT_REF_NO();
Vector VDIS_CONT_MAPP = credit_risk.getVDIS_CONT_MAPP();
Vector VCOUNT_CREDIT_LINE=credit_risk.getVCOUNT_CREDIT_LINE();

Vector VMST_COUNTERPARTY_CD=credit_risk.getVMST_COUNTERPARTY_CD();
Vector VMST_COUNTERPARTY_ABBR = credit_risk.getVMST_COUNTERPARTY_ABBR();
Vector VMST_COUNTERPARTY_NM = credit_risk.getVMST_COUNTERPARTY_NM();
Vector VCONT_MAP_LIST = credit_risk.getVCONT_MAP_LIST();
Vector VDIS_CONT_MAP_LIST = credit_risk.getVDIS_CONT_MAP_LIST();


      out.write("\n<body>\n");
      out.write("\r\n\r\n\r\n<script>\r\nfunction changePage(form_path,u)\r\n{\r\n	document.getElementById(\"loading\").style.visibility = \"visible\";\r\n	var url = form_path+\"?u=\"+u;\r\n			\r\n	location.replace(url);\r\n}\r\n\r\nfunction logout()\r\n{\r\n	var url = \"../home/logout.jsp\";\r\n	location.replace(url);\r\n	\r\n}\r\n\r\nfunction homepage()\r\n{\r\n	var url = \"../home/fms.jsp\";\r\n	location.replace(url);\r\n	\r\n}\r\n\r\nasync function changeProfile(comp_cd, exists_comp_abbr, comp_abbr)\r\n{\r\n    const activeTabsCnt = await fetchActiveTabCount(); \r\n	if((parseInt(activeTabsCnt))>1)\r\n	{\r\n		alert(\"Multiple Tabs \"+(parseInt(activeTabsCnt))+\" are open for the Application!\\nProfile switching is permitted only when a single tab is open!\");\r\n	}\r\n	else\r\n	{\r\n		var a = confirm(\"Do you want to Switch Profile \"+exists_comp_abbr+\" to \"+comp_abbr+\"?\");\r\n		if(a)\r\n		{\r\n			document.getElementById(\"loading\").style.visibility = \"visible\";\r\n			var url = \"../home/profile_selection.jsp?comp_profile=\"+comp_cd;\r\n				\r\n			location.replace(url);\r\n		}\r\n	}\r\n}\r\n\r\nfunction fetchActiveTabCount() {\r\n	const servletURL = '");
      out.print(request.getContextPath());
      out.write("/TabTrackerServlet';\r\n    return fetch(servletURL, {\r\n        method: 'POST',\r\n        body: new URLSearchParams({ action: 'getCount' })\r\n    })\r\n    .then(res => res.json())\r\n    .then(data => {\r\n        const tabCount = data.tabCount;   //activeTabs.size()\r\n        console.log('Active tabs:', tabCount);\r\n        return tabCount;\r\n    });\r\n}\r\n</script>\r\n\r\n<style type=\"text/css\">\r\n.navbar .megamenu{ padding: 1rem; }\r\n/* ============ desktop view ============ */\r\n@media all and (min-width: 992px) {\r\n	.navbar .has-megamenu{position:static!important;}\r\n	.navbar .megamenu{left:15%; right:15%; width:auto; margin-top:0;  }\r\n}	\r\n/* ============ desktop view .end// ============ */\r\n/* ============ mobile view ============ */\r\n@media(max-width: 991px){\r\n	.navbar.fixed-top .navbar-collapse, .navbar.sticky-top .navbar-collapse{\r\n		overflow-y: auto;\r\n	    max-height: 90vh;\r\n	    margin-top:10px;\r\n	}\r\n}\r\n/* ============ mobile view .end// ============ */\r\n</style>\r\n\r\n");
      com.etrm.fms.util.DataBean_Menu menu = null;
      menu = (com.etrm.fms.util.DataBean_Menu) _jspx_page_context.getAttribute("menu", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (menu == null){
        menu = new com.etrm.fms.util.DataBean_Menu();
        _jspx_page_context.setAttribute("menu", menu, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

String username = "";
String menu_emp_cd = "";
String comp_cd="";
String comp_logo="";
int activeTabsCnt=0;
if(session.getAttribute("emp_uid")==null||session.getAttribute("emp_uid")==""||session.getAttribute("emp_uid").toString().equals("null"))
{
	username="";
}  
else
{
	username=""+session.getAttribute("emp_uid");
}

if(session.getAttribute("emp_cd")==null||session.getAttribute("emp_cd")==""||session.getAttribute("emp_cd").toString().equals("null"))
{
	menu_emp_cd="";
}  
else
{
	menu_emp_cd=""+session.getAttribute("emp_cd");
}

if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	comp_cd="";
}  
else
{
	comp_cd=""+session.getAttribute("comp_cd");
}

if(session.getAttribute("comp_logo")==null||session.getAttribute("comp_logo")==""||session.getAttribute("comp_logo").toString().equals("null"))
{
	comp_logo="";
}  
else
{
	comp_logo=""+session.getAttribute("comp_logo");
}

//Set<String> activeTabs = (Set<String>) session.getAttribute("activeTabs");
//activeTabsCnt = activeTabs.size();

menu.setCallFlag("MODULE_MST");
menu.setUsername(username);
menu.setComp_cd(comp_cd);
menu.setEmpCd(menu_emp_cd);
menu.init();

Vector VMENU_MODULE_CD = menu.getVMENU_MODULE_CD();
Vector VMENU_MODULE_NM = menu.getVMENU_MODULE_NM();

Vector VMENU_COMPANY_CD = menu.getVMENU_COMPANY_CD();
Vector VMENU_COMPANY_NM = menu.getVMENU_COMPANY_NM();
Vector VMENU_COMPANY_ABBR = menu.getVMENU_COMPANY_ABBR();
String menu_default_prof=menu.getDefault_profile();

      out.write("\r\n<nav class=\"navbar navbar-expand-lg navbar-dark\" style=\"background-color: var(--header_color);\">\r\n	<div class=\"container-fluid\">\r\n    	<a class=\"navbar-brand\" href=\"#\" style=\"padding-top: 2px;padding-left: 4px;padding-right: 2px;\" onclick=\"homepage();\">\r\n    		<img src=\"");
if(!comp_logo.equals("")){
      out.write('.');
      out.write('.');
      out.write('/');
      out.print(CommonVariable.company_logo_path );
      out.write('/');
      out.print(comp_logo);
} 
      out.write("\" height=\"30px\">&nbsp;<font style=\"color:var(--header_font_color); font-size:24px;\"> ");
      out.print(CommonVariable.app_name);
      out.write("</font>\r\n    	</a>\r\n    	<button class=\"navbar-toggler\" style=\"border-color:var(--header_font_color);\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n      		<!-- <span class=\"navbar-toggler-icon\"></span> -->\r\n      		<font><i class=\"fa fa-bars\" style=\"color:var(--header_font_color);\"></i></font>\r\n    	</button>\r\n    	<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n      		<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\" style=\"flex-wrap: wrap;\">\r\n      		");
for(int i=0; i < VMENU_MODULE_CD.size(); i++){
      out.write("\r\n        		<li class=\"nav-item dropdown has-megamenu\" >\r\n          			<a class=\"nav-link dropdown-toggle\" style=\"padding: 3px;\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n            		");
      out.print(VMENU_MODULE_NM.elementAt(i));
      out.write("\r\n          			</a>\r\n          			<div class=\"dropdown-menu megamenu\" role=\"menu\">\r\n						<div class=\"row g-3\">\r\n							<div class=\"col-sm-12 col-xs-12 col-md-12\">  \r\n								<div class=\"form-group row\">\r\n					          	");

					    		menu.setCallFlag("MENU_MST");
					    		menu.setUsername(username);
					    		menu.setComp_cd(comp_cd);
					    		menu.setModule_cd(""+VMENU_MODULE_CD.elementAt(i));
					    		menu.init();
					    		
					    		Vector VFORM_CD = menu.getVFORM_CD();
					    		Vector VFORM_NM = menu.getVFORM_NM();
					    		Vector VFORM_PATH = menu.getVFORM_PATH();
					    		Vector VREAD_ACCESS = menu.getVREAD_ACCESS();
					    		Vector VWRITE_ACCESS = menu.getVWRITE_ACCESS();
					    		Vector VCHECK_ACCESS = menu.getVCHECK_ACCESS();
					    		Vector VPRINT_ACCESS = menu.getVPRINT_ACCESS();
					    		Vector VDELETE_ACCESS = menu.getVDELETE_ACCESS();
					    		Vector VAUDIT_ACCESS = menu.getVAUDIT_ACCESS();
					    		Vector VAUTHORIZE_ACCESS = menu.getVAUTHORIZE_ACCESS();
					    		Vector VAPPROVE_ACCESS = menu.getVAPPROVE_ACCESS();
					    		Vector VEXECUTE_ACCESS = menu.getVEXECUTE_ACCESS();
					    		Vector VGRP_CD = menu.getVGRP_CD();
					    		Vector VU = menu.getVU();
					    		Vector VSEI_CENTRAL = menu.getVSEI_CENTRAL();
					    		
					    		Vector VSUB_MENU_CD = menu.getVSUB_MENU_CD();
					    		Vector VSUB_MENU_NM = menu.getVSUB_MENU_NM();
					    		
					    		for(int k=0; k<VSUB_MENU_CD.size(); k++)
					    		{
      out.write("\r\n					    			<div class=\"col-auto\"> \r\n										<div class=\"col-megamenu\">\r\n					            			<ul>\r\n					              				<li><a class=\"dropdown-item\">");
      out.print(VSUB_MENU_NM.elementAt(k));
      out.write("</a></li>\r\n								              	");
for(int j=0; j<VFORM_CD.size(); j++)
									    		{
									    			if(VSUB_MENU_CD.elementAt(k).equals(VGRP_CD.elementAt(j)))
									    			{
      out.write("\r\n											    		<li>\r\n											            	<a class=\"dropdown-item\" href=\"#\" onclick=\"changePage('");
      out.print(VFORM_PATH.elementAt(j));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VU.elementAt(j));
      out.write("')\">\r\n																");
      out.print(VFORM_NM.elementAt(j));
if(VSEI_CENTRAL.elementAt(j).toString().equals("Y")){
      out.write("&nbsp;<span style=\"color:var(--top_header_font_color);\"><i class=\"fa fa-universal-access\" aria-hidden=\"true\"></i></span>");
}
      out.write("\r\n															</a>\r\n														</li>\r\n											         ");
} 
      out.write("\r\n											     ");
} 
      out.write("\r\n					            			</ul>\r\n					            		</div>\r\n					            	</div>\r\n			            		");
} 
			            		VFORM_CD.clear();
			            		VFORM_NM.clear();
			            		VFORM_PATH.clear();
			            		VREAD_ACCESS.clear();
			            		VWRITE_ACCESS.clear();
			            		VCHECK_ACCESS.clear();
			            		VPRINT_ACCESS.clear();
			            		VDELETE_ACCESS.clear();
			            		VAUDIT_ACCESS.clear();
			            		VAUTHORIZE_ACCESS.clear();
			            		VAPPROVE_ACCESS.clear();
			            		VEXECUTE_ACCESS.clear();
			            		VGRP_CD.clear();
			            		VU.clear();
			            		VSEI_CENTRAL.clear();
			            		VSUB_MENU_CD.clear();
			            		VSUB_MENU_NM.clear();
			            		
      out.write("\r\n			            		</div>\r\n			            	</div>\r\n			            </div>\r\n        			</div>\r\n        		</li>\r\n        		");
} 
      out.write("\r\n      		</ul>\r\n      		<div class=\"d-flex navbar-brand\">\r\n	      		<label class=\"btn\" onclick=\"\" style=\"color:var(--header_font_color); padding-left:0px;\"><b><span id = \"min\"></span>:<span id = \"sec\"></span></b></label>\r\n	      		<label class=\"btn\" onclick=\"\" style=\"color:var(--header_font_color); padding-left:0px;\">\r\n	      			<b>\r\n	      				<i class=\"fa fa-building-o fa-lg\"></i>&nbsp;");
      out.print(session.getAttribute("comp_abbr")==null?"":session.getAttribute("comp_abbr"));
      out.write("\r\n	      			</b>\r\n	      		</label>\r\n	      		<div class=\"flex-shrink-0 dropdown\">\r\n			   		<a href=\"#\" class=\"d-block link-dark text-decoration-none dropdown-toggle\" id=\"dropdownUser2\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" style=\"color:var(--header_font_color);\">\r\n			  			<!--  <img src=\"../");
      out.print(CommonVariable.company_logo_path );
      out.write("/default_user.png\" alt=\"mdo\" width=\"32\" height=\"32\" class=\"rounded-circle\"> -->\r\n			            <i class=\"fa fa-user-circle-o fa-2x\" aria-hidden=\"true\" > </i>\r\n			   		</a>\r\n			   		<ul class=\"dropdown-menu profile_dp_menu dropdown-menu-end text-small shadow\" aria-labelledby=\"dropdownUser2\" data-popper-placement=\"bottom-end\"> \r\n			   		<!-- style=\"position: absolute;inset: 0px auto auto 0px;margin: 0px;transform: translate(-80px, 34px);\" -->\r\n	            		<li><a class=\"dropdown-item\" href=\"#\"><i class=\"fa fa-user-circle fa-lg\"></i>&nbsp;");
      out.print(session.getAttribute("emp_nm")==null?"":session.getAttribute("emp_nm"));
      out.write("</a></li>\r\n	            		<li><hr class=\"dropdown-divider\"></li>\r\n	            		<li><a class=\"dropdown-item\" href=\"#\" style=\"font-weight: bold;font-size: var(--header_font_size);text-transform: uppercase;color: #dc3545; pointer-events: none;\">Switch Profile</a></li>\r\n			            ");
for(int i=0; i<VMENU_COMPANY_CD.size(); i++){ 
      out.write("\r\n			            <li>\r\n			            	<a class=\"dropdown-item\" href=\"#\" onclick=\"changeProfile('");
      out.print(VMENU_COMPANY_CD.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(session.getAttribute("comp_abbr")==null?"":session.getAttribute("comp_abbr"));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VMENU_COMPANY_ABBR.elementAt(i));
      out.write("');\"\r\n			            	");
if(comp_cd.equals(VMENU_COMPANY_CD.elementAt(i).toString())) { 
      out.write("\r\n			            		style=\"background-color: #95c674;color:white;font-weight:bold;pointer-events: none;\"\r\n			            	");
} 
      out.write(">\r\n			            	");
      out.print(VMENU_COMPANY_ABBR.elementAt(i));
      out.write("&nbsp;");
if(menu_default_prof.equals(VMENU_COMPANY_CD.elementAt(i).toString())){ 
      out.write("<i class=\"fa fa-dot-circle-o\"></i>");
} 
      out.write("\r\n			            	</a>\r\n			           	</li>\r\n			            ");
}
      out.write("\r\n			            <li><hr class=\"dropdown-divider\"></li>\r\n			            <li><a class=\"dropdown-item\" href=\"#\" onclick=\"logout();\"><b><i title=\"Logout\" class=\"fa fa-sign-out fa-lg\"></i>&nbsp;Sign Out</b></a></li>\r\n					</ul>\r\n				</div>\r\n			</div>\r\n    	</div>\r\n  	</div>\r\n</nav>\r\n\r\n");
      out.write("\r\n\r\n<!-- Alert Model -->\r\n<div class=\"modal fade\" id=\"myAlertModal\" style=\"z-index: 3055;\" data-bs-backdrop=\"static\" data-bs-keyboard=\"false\"> \r\n	<div class=\"modal-dialog modal-dialog-scrollable\">\r\n    	<div class=\"modal-content\">\r\n    		<div class=\"modal-header\">\r\n        		<div class=\"topheader\">\r\n					Alert\r\n				</div>\r\n      		</div>\r\n      		<div class=\"modal-body\">\r\n      			<p id=\"alertMsg\"></p>\r\n      		</div>\r\n      		<div class=\"modal-footer\" align=\"right\">\r\n        		<input type=\"button\" class=\"btn btn-primary\" id=\"alertok\" value=\"Ok\" onclick=\"alertHide();\">\r\n        		<!-- <input type=\"button\" class=\"btn btn-danger\" value=\"Cancel\"> -->\r\n      		</div>\r\n      	</div>\r\n	</div>\r\n</div>  \r\n\r\n<script>\r\nfunction alertShow(msg)\r\n{\r\n	$(\"#myAlertModal\").modal(\"show\");\r\n	document.getElementById(\"alertMsg\").innerHTML=msg;\r\n}\r\nfunction alertHide()\r\n{\r\n	$(\"#myAlertModal\").modal(\"hide\");\r\n}\r\n</script>   ");
      out.write('\n');
      out.write("<div id=\"loading\" style=\"visibility: hidden;\">\n	<div id=\"loading-image\">\n		<div class=\"btn-group\">\n			<label class=\"btn\" style=\"color:var(--header_color);border:none;font-size:20px;align-self: center;font-weight:bold;\">\n				<i class=\"fa fa-spinner fa-pulse fa-lg\"></i>&nbsp;Loading\n			</label>\n		</div>\n	</div>\n</div>");
      out.write('\n');
      out.write("\n<form action=\"\">\n\n<div class=\"box-body\">\n	<div class=\"row\">\n		<div class=\"col-md-12 col-sm-12 col-xs-12\">\n			");
if(!msg.equals("")){
				if(msg_type.equals("S")){
      out.write("\n					<div class=\"fadealert\">");
      out.print(utilmsg.successMessage(msg));
      out.write("</div>\n				");
}else if(msg_type.equals("E")){
      out.write("\n					<div class=\"fadealert\">");
      out.print( utilmsg.errorMessage(msg));
      out.write("</div>\n				");
}
			} 
      out.write("\n			<div class=\"card cardmain\">\n				<div class=\"card-header cdheader\">\n					<div class=\"d-flex justify-content-between\">\n					    <div class=\"topheader\">\n					    	Credit Exceed Days\n					    </div>\n					</div>\n				</div>\n				<div class=\"card-body cdbody\">\n					<div class=\"row m-b-5\">\n						<div class=\"col-sm-12 col-xs-12 col-md-12\">  \n							<div class=\"form-group row\">\n				    			<div class=\"col-sm-12 col-xs-12 col-md-12\" align=\"center\">\n				    				<div class=\"btn-group\">\n										<label class=\"btn btn-outline-secondary subbtngrp1 ");
if(clearance.equals("KYC")){
      out.write("btnactive");
}
      out.write("\" onclick=\"refresh('KYC');\">KYC</label>\n										<label class=\"btn btn-outline-secondary subbtngrp1 ");
if(clearance.equals("IGX")){
      out.write("btnactive");
}
      out.write("\" onclick=\"refresh('IGX');\">IGX</label>\n									</div>\n				    				<!-- <input type=\"radio\" name=\"rd_clear\">&nbsp; KYC &nbsp;&nbsp;\n				    				<input type=\"radio\" name=\"rd_clear\">&nbsp; IGX -->\n				    			</div>\n				  			</div>\n						</div>\n					</div>\n					&nbsp;\n					<div class=\"row\">\n						<div class=\"col-sm-3 col-xs-3 col-md-3\">  \n							<div class=\"form-group row\">\n								<div class=\"col-auto\">\n									<label class=\"form-label\"><b>Customer</b></label>\n								</div>\n								<div class=\"col\">\n									<select class=\"form-select form-select-sm\" name=\"counterparty_cd\" onchange=\"refresh('");
      out.print(clearance);
      out.write("')\">\n										<option value=\"0\">--Select--</option>\n										");
for(int i=0;i<VMST_COUNTERPARTY_CD.size();i++){ 
      out.write("\n										<option value=\"");
      out.print(VMST_COUNTERPARTY_CD.elementAt(i));
      out.write('"');
      out.write('>');
      out.print(VMST_COUNTERPARTY_ABBR.elementAt(i));
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(VMST_COUNTERPARTY_NM.elementAt(i) );
      out.write("</option>\n										");
} 
      out.write("\n									</select>\n									<script>document.forms[0].counterparty_cd.value=\"");
      out.print(counterparty_cd);
      out.write("\"</script>\n								</div>\n							</div>\n						</div>\n						<div class=\"col-sm-3 col-xs-3 col-md-3\">  \n							<div class=\"form-group row\">\n								<div class=\"col-auto\">\n									<label class=\"form-label\"><b>Contract</b></label>\n								</div>\n								<div class=\"col\">\n									<select class=\"form-select form-select-sm\" name=\"contract_map\" onchange=\"refresh('");
      out.print(clearance);
      out.write("')\">\n										<option value=\"\">--All--</option>\n										");
for(int i=0;i<VDIS_CONT_MAP_LIST.size();i++){ 
      out.write("\n										<option value=\"");
      out.print(VCONT_MAP_LIST.elementAt(i));
      out.write('"');
      out.write('>');
      out.print(VDIS_CONT_MAP_LIST.elementAt(i));
      out.write("</option>\n										");
} 
      out.write("\n									</select>\n									<script>document.forms[0].contract_map.value=\"");
      out.print(contract_map);
      out.write("\"</script>\n								</div>\n							</div>\n						</div>\n					</div>	\n				</div>\n				<div class=\"card-body cdbody\">\n					<div class=\"row\">\n						<div class=\"col-sm-12 col-xs-12 col-md-12\">\n						");
if(!counterparty_cd.equals("0")){ 
      out.write("\n							<div class=\"table-responsive\">\n								<table class=\"table table-bordered table-hover\" id=\"example\">\n									<thead>\n										<tr>\n											<th>SR#</th>\n											<th>Counterparty</th>\n											<th>Contract#</th>\n											<th>Contract/Trade Ref#</th>\n											<th>Contract Period</th>\n											<th>#Credit Lines</th>\n											<th>Credit Exceed Days</th>\n										</tr>\n									</thead>\n									<tbody>\n									");
if(VCOUNTERPARTY_CD.size() > 0){ 
      out.write("\n										");
for(int i=0; i<VCOUNTERPARTY_CD.size(); i++){ 
      out.write("\n										<tr>\n											<td align=\"center\">");
      out.print(i+1);
      out.write("</td>\n											<td align=\"left\">");
      out.print(VCOUNTERPARTY_NAME.elementAt(i));
      out.write("</td>\n											<td align=\"center\">");
      out.print(VDIS_CONT_MAPP.elementAt(i));
      out.write("</td>\n											<td align=\"center\">");
      out.print(VCONT_REF_NO.elementAt(i));
      out.write("</td>\n											<td align=\"center\">");
      out.print(VSTART_DT.elementAt(i));
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(VEND_DT.elementAt(i));
      out.write("</td>\n											<td align=\"center\" ");
if(!VCOUNT_CREDIT_LINE.elementAt(i).equals("")) {
      out.write("style=\"background:#99ffcc;\"");
} 
      out.write(">\n												");
      out.print(VCOUNT_CREDIT_LINE.elementAt(i));
      out.write("\n											</td>\n											<td align=\"center\">\n												<input type=\"button\" name=\"credit_exceed_btn\" class=\"btn btn-sm config_btn\" value=\"Configure\" \n												onclick=\"creditExceedDaysConfig('");
      out.print(VCONTRACT_TYPE.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VAGMT_NO.elementAt(i));
      out.write("',\n												'");
      out.print(VAGMT_REV_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VCONT_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VCONT_REV_NO.elementAt(i));
      out.write("',\n												'");
      out.print(VCOUNTERPARTY_CD.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VSTART_DT.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VEND_DT.elementAt(i));
      out.write("');\">\n											</td>\n										</tr>\n										");
}
      out.write("\n									");
}else{
      out.write("\n										<tr>\n											<td colspan=\"7\" align=\"center\">");
      out.print(utilmsg.infoMessage("<b>No Contract for Selected Counterparty!</b>") );
      out.write("</td>\n										</tr>\n									");
}
      out.write("	\n									</tbody>\n								</table>\n							</div>\n						</div>\n						");
}else{ 
      out.write("\n							<div colspan=\"7\" align=\"center\">");
      out.print(utilmsg.infoMessage("<b>Please Select any Counterparty!</b>") );
      out.write("</div>\n						");
} 
      out.write("\n					</div>\n				</div>\n			</div>\n		</div>\n	</div>\n</div>\n\n<input type=\"hidden\" name=\"prev_counterparty_cd\" value=\"");
      out.print(counterparty_cd);
      out.write("\">\n<input type=\"hidden\" name=\"prev_clearance\" value=\"");
      out.print(clearance);
      out.write("\">\n\n<input type=\"hidden\" name=\"read_access\" value=\"");
      out.print(read_access);
      out.write("\">\n<input type=\"hidden\" name=\"write_access\" value=\"");
      out.print(write_access);
      out.write("\">\n<input type=\"hidden\" name=\"check_access\" value=\"");
      out.print(check_access);
      out.write("\">\n<input type=\"hidden\" name=\"print_access\" value=\"");
      out.print(print_access);
      out.write("\">\n<input type=\"hidden\" name=\"delete_access\" value=\"");
      out.print(delete_access);
      out.write("\">  	\n<input type=\"hidden\" name=\"audit_access\" value=\"");
      out.print(audit_access);
      out.write("\">\n<input type=\"hidden\" name=\"authorize_access\" value=\"");
      out.print(authorize_access);
      out.write("\">\n<input type=\"hidden\" name=\"approve_access\" value=\"");
      out.print(approve_access);
      out.write("\">\n<input type=\"hidden\" name=\"execute_access\" value=\"");
      out.print(execute_access);
      out.write("\">\n<input type=\"hidden\" name=\"form_cd\" value=\"");
      out.print(formCd);
      out.write("\">\n<input type=\"hidden\" name=\"form_nm\" value=\"");
      out.print(formNm);
      out.write("\">\n<input type=\"hidden\" name=\"mod_cd\" value=\"");
      out.print(mod_cd);
      out.write("\">\n<input type=\"hidden\" name=\"mod_nm\" value=\"");
      out.print(mod_nm);
      out.write("\">\n<input type=\"hidden\" name=\"u\" value=\"");
      out.print(u);
      out.write("\">\n\n</form>\n</body>\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
