/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2026-02-17 09:04:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.credit_005frisk;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Vector;

public final class view_005fadvance_005fremittance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/credit_risk/../home/loading.jsp", Long.valueOf(1747068184000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Vector");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n<!DOCTYPE html>\n<html>\n<head>\n<title>Remittance</title>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../font-awesome-4.7.0/css/font-awesome.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">\n\n<script>\nfunction refreshParent(gx)\n{\n	window.close();\n	window.opener.refresh(gx);\n}\n\nfunction setInvoiceNo()\n{\n	var e = document.forms[0].invoice_id_seq;\n	var invoiceNo = e.options[e.selectedIndex].text;\n	if(document.forms[0].invoice_id_seq.value==\"\")\n	{\n		document.forms[0].invoice_no.value=\"\";\n	}\n	else\n	{\n		document.forms[0].invoice_no.value=invoiceNo;\n	}\n}\n\nvar newWindow;\nfunction printPDF(obj,counterparty_cd,seq_no, seq_rev_no, gx, isReversal,cont_type)\n{\n	var invoice_no = document.forms[0].invoice_no.value;\n	var u = document.forms[0].u.value;\n	var crdr = document.forms[0].crdr.value;\n	\n	var msgLbl=\"Receipet\";\n	if(crdr==\"DR\")\n	{\n		msgLbl=\"Refund\";\n	}\n	\n	var a=false;\n	if(cont_type==\"O\" || cont_type==\"Q\")\n	{\n		var invoice_id_seq = document.forms[0].invoice_id_seq.value;\n		\n		if(invoice_id_seq==\"\")\n");
      out.write("		{\n			\n			alert(\"Select \"+msgLbl+\" Voucher Seq No!\");\n			obj.checked=false;\n		}\n		else\n		{\n			a=confirm(msgLbl+\" Voucher No : \"+invoice_no+\"\\n\\nDo you want to Generate Advance \"+msgLbl+\" Voucher PDF?\");\n		}		\n	}\n	else\n	{\n		a=confirm(\"Do you want to Generate Advance Remittance PDF?\");\n	}\n	\n	if(a)\n	{\n		var url = \"pdf_advance_remittance.jsp?counterparty_cd=\"+counterparty_cd+\"&seq_no=\"+seq_no+\n			\"&seq_rev_no=\"+seq_rev_no+\"&gx=\"+gx+\"&isReversal=\"+isReversal+\"&invoice_no=\"+invoice_no+\"&u=\"+u;\n		\n		if(!newWindow || newWindow.closed)\n		{\n			newWindow = window.open(url,\"Advance Remittance PDF\",\"top=10,left=10,width=1200,height=600,scrollbars=1\");\n		}\n		else\n		{\n			newWindow.close();\n			newWindow = window.open(url,\"Advance Remittance PDF\",\"top=10,left=10,width=1200,height=600,scrollbars=1\");\n		}\n	}\n	else\n	{\n		obj.checked=false;\n	}\n}\n</script>\n</head>\n");
      com.etrm.fms.credit_risk.DataBean_Advance cr_inv = null;
      cr_inv = (com.etrm.fms.credit_risk.DataBean_Advance) _jspx_page_context.getAttribute("cr_inv", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (cr_inv == null){
        cr_inv = new com.etrm.fms.credit_risk.DataBean_Advance();
        _jspx_page_context.setAttribute("cr_inv", cr_inv, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');

String owner_cd=session.getAttribute("comp_cd").toString().equals("null")?"":""+session.getAttribute("comp_cd");
String owner_abbr=""+session.getAttribute("comp_abbr")==null?"":""+session.getAttribute("comp_abbr");
String owner_nm=""+session.getAttribute("comp_nm")==null?"":""+session.getAttribute("comp_nm");

String counterparty_cd=request.getParameter("counterparty_cd")==null?"":request.getParameter("counterparty_cd");
String seq_no=request.getParameter("seq_no")==null?"":request.getParameter("seq_no");
String seq_rev_no=request.getParameter("seq_rev_no")==null?"":request.getParameter("seq_rev_no");
String gx=request.getParameter("gx")==null?"":request.getParameter("gx");
String isReversal=request.getParameter("isReversal")==null?"":request.getParameter("isReversal");
String u=request.getParameter("u")==null?"":request.getParameter("u");

cr_inv.setCallFlag("VIEW_REMITTANCE");
cr_inv.setCounterparty_cd(counterparty_cd);
cr_inv.setSeq_no(seq_no);
cr_inv.setSeq_rev_no(seq_rev_no);
cr_inv.setGx(gx);
cr_inv.setIsReversal(isReversal);
cr_inv.setComp_cd(owner_cd);
cr_inv.init();

String counterparty_nm = cr_inv.getCounterparty_nm();
String gx_counterparty_nm = cr_inv.getGx_counterparty_nm();
String received_dt = cr_inv.getReceived_date();
String value = cr_inv.getValue();
String currency = cr_inv.getCurrency();
String pg_ref = cr_inv.getPg_ref();
String contRef = cr_inv.getContRef();
String signing_dt = cr_inv.getSigning_dt();
String remittance_no = cr_inv.getRemittance_no();
String status = cr_inv.getStatus();
String contract_type = cr_inv.getContract_type();
String agmtSigningDt=cr_inv.getAgmtSigningDt();
String cr_dr=cr_inv.getCr_dr();
String invoice_id_seq=cr_inv.getInvoice_id_seq();

String plantAddress=cr_inv.getPlantAddress();
String plantCity=cr_inv.getPlantCity();
String plantState=cr_inv.getPlantState();
String plantPin=cr_inv.getPlantPin();
String plantNm=cr_inv.getPlantNm();

String bu_plantAddress=cr_inv.getBu_plantAddress();
String bu_plantCity=cr_inv.getBu_plantCity();
String bu_plantState=cr_inv.getBu_plantState();
String bu_plantPin=cr_inv.getBu_plantPin();
String bu_plantNm=cr_inv.getBu_plantNm();

String tax_info=cr_inv.getTax_info();
String bu_tax_info=cr_inv.getBu_tax_info();

Vector VPDF_COL1 = cr_inv.getVPDF_COL1();
Vector VPDF_COL2 = cr_inv.getVPDF_COL2();
Vector VPDF_COL3 = cr_inv.getVPDF_COL3();
Vector VPDF_COL4 = cr_inv.getVPDF_COL4();
Vector VPDF_COL5 = cr_inv.getVPDF_COL5();

Vector VINVOICE_ID_SEQ = cr_inv.getVINVOICE_ID_SEQ();
Vector VINVOICE_NO = cr_inv.getVINVOICE_NO();

      out.write("\n<body ");
if(contract_type.equals("O") || contract_type.equals("Q")) {
      out.write("onload=\"setInvoiceNo();\"");
} 
      out.write('>');
      out.write('\n');
      out.write("<div id=\"loading\" style=\"visibility: hidden;\">\n	<div id=\"loading-image\">\n		<div class=\"btn-group\">\n			<label class=\"btn\" style=\"color:var(--header_color);border:none;font-size:20px;align-self: center;font-weight:bold;\">\n				<i class=\"fa fa-spinner fa-pulse fa-lg\"></i>&nbsp;Loading\n			</label>\n		</div>\n	</div>\n</div>");
      out.write("\n<form>\n<table width=\"100%\"  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\n	<tr valign=\"middle\">\n		<td colspan=\"7\">\n			<div align=\"center\">\n				<font face=\"Arial\" style=\"font-size: 14px;font-weight: bold;\">\n				");
if(contract_type.equals("O") || contract_type.equals("Q")) {
      out.write("\n					<!-- INVOICE -->\n				");
}else{ 
      out.write("\n					REMITTANCE ADVISE\n				");
} 
      out.write("\n					<br>\n				</font>				\n				<font face=\"Arial\" style=\"font-size: 20px;font-weight: bold;\">\n					");
      out.print(owner_nm);
      out.write("\n				</font>	\n				<br>\n				<font face=\"Arial\" style=\"font-size: 14px;font-weight: bold;\">	\n					");
if(contract_type.equals("O") || contract_type.equals("Q")) {
      out.write("\n						");
if(cr_dr.equals("DR")) {
      out.write("\n						REFUND VOUCHER\n						");
}else{ 
      out.write("\n						RECEIPT VOUCHER\n						");
} 
      out.write("\n					");
}else{ 
      out.write("\n						");
      out.write("\n						");
if(cr_dr.equals("CR")){ 
      out.write("ADVANCE ");
} else {
      out.write("ADVANCE REVERSAL");
}
      out.write(" \n					");
} 
      out.write("\n				</font>\n				");
if(contract_type.equals("Q") || contract_type.equals("O")) {
      out.write("\n				<font face=\"Arial\" style=\"font-size: 12px;font-weight: bold;\">\n					<br>\n					");
if(cr_dr.equals("DR")) {
      out.write("\n					Refund Voucher issued under Rule 51 of the Central Goods and Services Tax Rules, 2017\n					");
}else{ 
      out.write("\n					Receipt Voucher issued under Rule 50 of the Central Goods and Services Tax Rules, 2017\n					");
} 
      out.write("\n				</font>\n				");
} 
      out.write("\n			</div>\n		</td>\n	</tr>\n	<tr valign=\"middle\">\n		<td colspan=\"7\">\n			<div align=\"center\">\n				<font size=\"1px\" face=\"Arial\">\n					<b></b>\n				</font>\n			</div>\n		</td>\n	</tr>\n	<tr valign=\"middle\">\n		<td colspan=\"7\">\n			<div align=\"center\">&nbsp;</div>\n		</td>\n	</tr>\n	<tr valign=\"middle\">\n		<td colspan=\"7\">\n			<div align=\"center\">\n				<font size=\"1px\" face=\"Arial\"> \n				");
if(gx.equals("I")){
      out.write("\n					In respect of Exchange Transaction (");
      out.print(counterparty_nm );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(contRef);
      out.write(") executed on ");
      out.print(signing_dt);
      out.write("\n					<br>\n					between ");
      out.print(gx_counterparty_nm);
      out.write(" and ");
      out.print(owner_nm);
      out.write("\n				");
}else if(contract_type.equals("D") || contract_type.equals("T") || contract_type.equals("G") || contract_type.equals("P")){ 
      out.write("\n					In respect of ");
if(contract_type.equals("G") || contract_type.equals("P")){
      out.write("LTCORA ");
}
      out.write("Purchase Contract(");
      out.print(contRef);
      out.write(") executed on ");
      out.print(signing_dt);
      out.write("\n					<br>\n					between ");
      out.print(counterparty_nm);
      out.write(" and ");
      out.print(owner_nm);
      out.write("\n				");
}else{ 
      out.write("\n					In respect of \n					");
if(contract_type.equals("S")){ 
      out.write("Supply Notice (");
      out.print(contRef);
      out.write(") executed on ");
      out.print(signing_dt);
      out.write(" pursuant to Framework Gas Sales Agreement executed on ");
      out.print(agmtSigningDt);
      out.write("\n					");
}else if(contract_type.equals("O")){ 
      out.write(" LTCORA Agreement executed on ");
      out.print(agmtSigningDt);
      out.write(" & CN (");
      out.print(contRef);
      out.write(") executed on ");
      out.print(signing_dt);
      out.write("\n					");
}else if(contract_type.equals("Q")){ 
      out.write(" LTCORA Agreement executed on ");
      out.print(agmtSigningDt);
      out.write("\n					");
}else if(contract_type.equals("L")){ 
      out.write("Letter of Agreement (");
      out.print(contRef);
      out.write(") executed on ");
      out.print(signing_dt);
      out.write(" \n					");
}else if(contract_type.equals("X")){ 
      out.write("Exchange Transaction (");
      out.print(contRef);
      out.write(") executed on ");
      out.print(signing_dt);
      out.write("\n					");
} 
      out.write(" \n					<br>\n					between ");
      out.print(owner_nm);
      out.write(" and ");
      out.print(counterparty_nm);
      out.write("\n				");
} 
      out.write("	\n				</font>\n			</div>\n		</td>\n	</tr>\n	<tr valign=\"middle\">\n		<td colspan=\"7\">\n			<div align=\"center\">&nbsp;</div>\n		</td>\n	</tr>\n	<tr valign=\"top\">\n		<td colspan=\"3\" width=\"50%\">\n			<div align=\"left\">\n				<font size=\"1.5px\" face=\"Arial\">\n					<b>From:</b> \n					<br>");
      out.print(owner_nm);
      out.write("\n					<br>");
      out.print(bu_plantAddress);
      out.write(',');
      out.print(bu_plantCity);
      out.write("\n					<br>");
      out.print(bu_plantState);
      out.write("&nbsp;-&nbsp;");
      out.print(bu_plantPin);
      out.write("\n				</font>\n			</div>\n		</td>\n		<td colspan=\"1\" width=\"10%\"><div align=\"left\"><font size=\"1.5px\" face=\"Arial\"></font></div></td>\n		<td colspan=\"3\" width=\"40%\">\n			<div align=\"left\">\n				<font size=\"1.5px\" face=\"Arial\">\n					");
      out.write("\n					<b>To:</b>\n					<br>");
if(gx.equals("I")){
      out.print(gx_counterparty_nm);
}else{
      out.print(counterparty_nm);
} 
      out.write("\n					<br>");
      out.print(plantAddress);
      out.write(',');
      out.print(plantCity);
      out.write("\n					<br>");
      out.print(plantState );
      out.write("&nbsp;-&nbsp;");
      out.print(plantPin);
      out.write("					\n				</font>\n			</div>\n		</td>\n	</tr>\n	<tr valign=\"top\"><td colspan=\"7\"><div align=\"center\">&nbsp;</div></td></tr>\n	<tr valign=\"top\">\n		<td colspan=\"3\">\n			<div>\n				<font size=\"1.5px\" face=\"Arial\">\n					");
      out.print(bu_tax_info );
      out.write("\n				</font>\n			</div>\n		</td>\n		<td colspan=\"1\">&nbsp;</td>\n 		<td colspan=\"3\">\n 			<div>\n 				<font size=\"1.5px\" face=\"Arial\">\n 					");
      out.print(tax_info );
      out.write("\n				</font>\n			</div>\n		</td>\n	</tr>\n	<tr valign=\"top\">\n		<td colspan=\"7\">&nbsp;</td>\n	</tr>\n</table>\n");
if(contract_type.equals("O") || contract_type.equals("Q")) {
      out.write("\n<table width=\"100%\"  border=\"0\" align=\"center\" cellpadding=\"2\" cellspacing=\"0\">	\n	<tr valign=\"middle\">\n		<td colspan=\"4\"></td>\n		<td colspan=\"2\" width=\"25%\">\n			<div align=\"center\">\n				<table width=\"100%\"  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\n					<tr><td><div align=\"right\"><font size=\"1.5px\" face=\"Arial\"><b>");
if(cr_dr.equals("DR")) {
      out.write("Refund");
}else{
      out.write("Receipet");
} 
      out.write(" Voucher Date :&nbsp;</b></font></div></td></tr>\n					<tr><td><div align=\"right\"><font size=\"1.5px\" face=\"Arial\"><b>");
      out.print(owner_abbr);
      out.write(' ');
if(cr_dr.equals("DR")) {
      out.write("Refund");
}else{
      out.write("Receipet");
} 
      out.write(" Voucher Seq No.:&nbsp;</b></font></div></td></tr>\n				</table>\n			</div>\n		</td>\n		<td colspan=\"1\" width=\"15%\">\n			<div align=\"center\">\n				<table width=\"100%\"  border=\"1\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\n					<tr><td><div align=\"right\"><font size=\"1.5px\" face=\"Arial\"><b>&nbsp;");
      out.print(received_dt);
      out.write("</b></font></div></td></tr>\n					<tr>\n						<td>\n						");
if(status.equals("O")){ 
      out.write("\n							<select name=\"invoice_id_seq\" style=\"background:yellow;font-weight:bold;\" onchange=\"setInvoiceNo();\">\n								<option value=\"\">--Select--</option>\n								");
for(int i=0; i<VINVOICE_ID_SEQ.size();i++){ 
      out.write("\n								<option value=\"");
      out.print(VINVOICE_ID_SEQ.elementAt(i));
      out.write('"');
      out.write('>');
      out.print(VINVOICE_NO.elementAt(i));
      out.write("</option>\n								");
} 
      out.write("\n							</select>\n							<script>document.forms[0].invoice_id_seq.value=\"");
      out.print(invoice_id_seq);
      out.write("\"</script>\n						");
}else{ 
      out.write("\n							<div align=\"right\">\n								<font size=\"1.5px\" face=\"Arial\"><b>");
//=invoice_no
      out.write("&nbsp;</b></font>\n							</div>\n						");
} 
      out.write("\n						</td>\n					</tr>\n				\n				</table>\n			</div>\n		</td>\n	</tr>\n	<tr valign=\"middle\"><td colspan=\"7\">&nbsp;</td></tr>\n</table>\n<table width=\"100%\"  border=\"1\" align=\"center\" cellpadding=\"2\" cellspacing=\"0\">\n	<tr valign=\"bottom\">\n		<td width=\"6%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Sr. No.</b></font></div></td>\n		<td width=\"34%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Item</b></font></div></td>\n		<td width=\"10%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Currency</b></font></div></td>\n		<td width=\"15%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Quantity</b></font></div></td>\n		<td width=\"15%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Amount</b></font></div></td>\n	</tr>\n	");
for(int i=0; i<VPDF_COL1.size(); i++){ 
      out.write("\n	<tr valign=\"top\">\n		<td>\n			<div align=\"center\">\n				<font size=\"1.5px\" face=\"Arial\">");
      out.print(VPDF_COL1.elementAt(i) );
      out.write("</font>\n			</div>\n		</td>\n		<td>\n			<div ");
if(Double.parseDouble(""+VPDF_COL1.elementAt(i))/(int)Double.parseDouble(""+VPDF_COL1.elementAt(i))>1){
      out.write("align=\"right\"");
}else{
      out.write("align=\"left\"");
} 
      out.write(">\n				<font size=\"1.5px\" face=\"Arial\">");
      out.print(VPDF_COL2.elementAt(i) );
      out.write("</font>\n			</div>\n		</td>\n		<td>\n			<div align=\"center\">\n				<font size=\"1.5px\" face=\"Arial\">");
      out.print(VPDF_COL3.elementAt(i) );
      out.write("</font>\n			</div>\n		</td>\n		<td>\n			<div align=\"center\">\n				<font size=\"1.5px\" face=\"Arial\">");
      out.print(VPDF_COL4.elementAt(i) );
      out.write("</font>\n			</div>\n		</td>\n		<td>\n			<div ");
if(Double.parseDouble(""+VPDF_COL1.elementAt(i))/(int)Double.parseDouble(""+VPDF_COL1.elementAt(i))>1){
      out.write("align=\"left\"");
}else{
      out.write("align=\"right\"");
} 
      out.write(">\n				<font size=\"1.5px\" face=\"Arial\">");
      out.print(VPDF_COL5.elementAt(i) );
      out.write("</font>\n			</div>\n		</td>\n	</tr>\n	");
} 
      out.write("\n</table>\n");
}else{ 
      out.write("\n<table width=\"100%\"  border=\"0\" align=\"center\" cellpadding=\"2\" cellspacing=\"0\">	\n	<tr valign=\"middle\">\n		<td colspan=\"4\"></td>\n		<td colspan=\"2\" width=\"25%\">\n			<div align=\"center\">\n				<table width=\"100%\"  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\n					<tr>\n						<td>\n							<div align=\"right\">\n								<font size=\"1.5px\" face=\"Arial\"><b>Remittance#:&nbsp;</b></font>\n							</div>\n						</td>\n					</tr>\n					<tr>\n						<td>\n							<div align=\"right\">\n								<font size=\"1.5px\" face=\"Arial\"><b>Payment Due Date:&nbsp;</b></font>\n							</div>\n						</td>\n					</tr>\n					<tr>\n						<td>\n							<div align=\"right\">\n								<font size=\"1.5px\" face=\"Arial\"><b>Invoice#:&nbsp;</b></font>\n							</div>\n						</td>\n					</tr>\n				</table>\n			</div>\n		</td>\n		<td colspan=\"1\" width=\"15%\">\n			<div align=\"center\">\n				<table width=\"100%\"  border=\"1\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\n					<tr>\n						<td>\n							<div align=\"right\">\n								<font size=\"1.5px\" face=\"Arial\"><b>&nbsp;");
      out.print(remittance_no);
      out.write("</b></font>\n							</div>\n						</td>\n					</tr>\n					<tr>\n						<td>\n							<div align=\"right\">\n								<font size=\"1.5px\" face=\"Arial\"><b>&nbsp;");
      out.print(received_dt);
      out.write("</b></font>\n							</div>\n						</td>\n					</tr>\n					<tr>\n						<td>\n							<div align=\"right\">\n								<font size=\"1.5px\" face=\"Arial\"><b>&nbsp;");
      out.print(pg_ref);
      out.write("</b></font>\n							</div>\n						</td>\n					</tr>\n				</table>\n			</div>\n		</td>\n	</tr>\n	<tr valign=\"middle\"><td colspan=\"7\">&nbsp;</td></tr>\n</table>\n<table width=\"100%\"  border=\"1\" align=\"center\" cellpadding=\"2\" cellspacing=\"0\">\n	<tr valign=\"bottom\">\n		<td width=\"6%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Sr. No.</b></font></div></td>\n		<td width=\"34%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Item</b></font></div></td>\n		<td width=\"10%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Currency</b></font></div></td>\n		<td width=\"15%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Amount</b></font></div></td>\n	</tr>\n	<tr valign=\"top\">\n		<td>\n			<div align=\"center\">\n				<font size=\"1.5px\" face=\"Arial\">1</font>\n			</div>\n		</td>\n		<td>\n			<div align=\"left\">\n				<font size=\"1.5px\" face=\"Arial\">Gas Purchase AUD</font>\n			</div>\n		</td>\n		<td>\n			<div align=\"center\">\n				<font size=\"1.5px\" face=\"Arial\">");
      out.print(currency);
      out.write("</font>\n			</div>\n		</td>\n		<td>\n			<div align=\"right\">\n				<font size=\"1.5px\" face=\"Arial\">");
      out.print(value);
      out.write("</font>\n			</div>\n		</td>\n	</tr>\n	<tr valign=\"top\">\n		<td>\n			<div align=\"center\">\n				<font size=\"1.5px\" face=\"Arial\"><b>2</b></font>\n			</div>\n		</td>\n		<td>\n			<div align=\"left\">\n				<font size=\"1.5px\" face=\"Arial\"><b>Net Amount Payable</b></font>\n			</div>\n		</td>\n		<td>\n			<div align=\"center\">\n				<font size=\"1.5px\" face=\"Arial\"><b>");
      out.print(currency);
      out.write("</b></font>\n			</div>\n		</td>\n		<td>\n			<div align=\"right\">\n				<font size=\"1.5px\" face=\"Arial\"><b>");
      out.print(value);
      out.write("</b></font>\n			</div>\n		</td>\n	</tr>\n</table>\n");
} 
      out.write("\n<br>\n<br>\n<table border=\"0\" width=\"100%\" align=\"center\" cellpadding=\"2\" cellspacing=\"0\">\n	<tr valign=\"middle\"><td colspan=\"7\"><div align=\"center\">&nbsp;</div></td></tr>\n	");
if(contract_type.equals("O") || contract_type.equals("Q")) {
      out.write("\n	<tr valign=\"middle\">\n		<td colspan=\"7\">\n			<div align=\"left\">\n				<font size=\"1.5px\" face=\"Arial\"><b>For ");
      out.print(owner_nm);
      out.write("<br><br><br><br>Authorised Signatory</b></font>\n			</div>\n		</td>\n	</tr>\n	");
}else{ 
      out.write("\n	<tr valign=\"middle\">\n		<td colspan=\"7\">\n			<div align=\"center\">\n				<br><br><br><br><br><br><br><br>\n				<font size=\"1.5px\" face=\"Arial\"><i>*** This is Computer Generated Report and No Signature Required ***</i></font>\n			</div>\n		</td>\n	</tr>\n	");
} 
      out.write("\n	<tr valign=\"middle\"><td colspan=\"7\"><div align=\"center\">&nbsp;</div></td></tr>\n	<tr valign=\"middle\"><td colspan=\"7\"><div align=\"center\">&nbsp;</div></td></tr>\n	<tr valign=\"middle\">\n		<td colspan=\"7\">\n			<div align=\"center\">\n				");
if(status.equals("O")){ 
      out.write("\n					<font style=\"color: blue;\"><I><b>Do you want to Generate PDF?</b></I></font>&nbsp;\n					<input type=\"radio\" name=\"rd\" value=\"Y\" \n					onclick=\"printPDF(this,'");
      out.print(counterparty_cd);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(seq_no);
      out.write("', '");
      out.print(seq_rev_no);
      out.write("', '");
      out.print(gx);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(isReversal);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(contract_type);
      out.write("');\">&nbsp;<b>Yes</b>&nbsp;&nbsp;&nbsp;&nbsp;\n				");
}else {
      out.write("\n					<font style=\"color: red;\"><I><b>Post Approval PDF Generation will be enabled!</b></I></font>\n				");
} 
      out.write("\n			</div>\n		</td>\n	</tr>\n</table>\n<br>\n<br>\n\n<input type=\"hidden\" name=\"invoice_no\" value=\"\">\n<input type=\"hidden\" name=\"u\" value=\"");
      out.print(u);
      out.write("\">\n<input type=\"hidden\" name=\"crdr\" value=\"");
      out.print(cr_dr);
      out.write("\">\n</form>\n</body>\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
