package com.etrm.fms.migration;


import java.util.HashMap;

public class Migration_Plants_Exceptions {

	 // Arrays
	public static final String[] customer_delete = {"BPL-1", "EPL-1", "MGL-2", "NTPC-7", "NTPC-8", "NTPC-9", "NTPC-10", "NTPC-11", "NTPC-12","KRIBHCO-2", "VSIL-1", "GGCL-1", "TPL-2", "IGL-7", "AMNS-3", "AMNS-5", "SGIPL-6", "GGL-2", "GGL-3", "HSIL-2", "VVF-1", "VVF-2", "VVF-3", "SISECAM-2", "OPAL-2","RCF-3", "RCF-4", "GNFC-3", "GLIL-5", "GLIL-6", "GLIL-7", "PPL-2", "YARALTD-2", "RATNAGI-2","MGRPL-2", "BP-2"};
	    
	public static final String[] trader_delete = {"BP-2", "RIL-D6-2"};
	
	
	//jsp data structures
	public static final String[] module_names = {"MASTER", "PURCHASE", "SALES", "TRANSPORT", "TERMINAL OPERATIONS", "DLNG" , "RISK MGMT" , "DERIVATIVES", "INTERFACE", "OTHER INVOICE"};

	public static final String function_names[] = {
			"FMS_COUNTERPARTY_MST, FMS_COUNTERPARTY_ADDR_MST, FMS_ENTITY_REQ_DTL, FMS_SECTOR_MST, FMS_ENTITY_ADDR_MST, FMS_COMPANY_OWNER_MST, FMS_COMPANY_OWNER_ADDR_MST, FMS_COUNTERPARTY_PLANT_DTL, FMS_COUNTERPARTY_BU_DTL, FMS_INT_PAY_RATE_ENTRY, FMS_EXCHG_RATE_ENTRY, FMS_BANK_MST, FMS_ENTITY_TURNOVER_DTL, FMS_SHIP_MST, FMS_ENTITY_CONTACT_MST, FMS_METER_MST, FMS_COUNTERPARTY_PLANT_TAX, FMS_COUNTERPARTY_BU_TAX, FMS_ENTITY_TAX_STRUCT_DTL, FMS_ENTITY_SERVICE_TAX_DTL, FMS_ENTITY_BU_SVC_TAX_DTL, FMS_CUSTOM_TAX_STRUCT_DTL, FMS_HOLIDAY_DTL, FMS_PRODUCT_MST, FMS_PRODUCT_MOLECULE_MST, FMS_SAC_MST, FMS_ENTITY_TCS_TDS_MST",
			"FMS_TRADER_AGMT_MST, FMS_TRADER_AGMT_BU, FMS_TRADER_AGMT_PLANT, FMS_TRADER_AGMT_BILLING_DTL, FMS_TRADER_CN_MST, FMS_TRADER_CARGO_MST, FMS_PSEUDO_CARGO_DTL, FMS_CARGO_SVC_CONT_MST, FMS_CARGO_SVC_CONT_SVC_BU, FMS_BUY_CARGO_NOM, FMS_BUY_CARGO_NOM_BL, FMS_BUY_CARGO_NOM_BOE, FMS_BUY_CARGO_ALLOC, FMS_BUY_CARGO_ALLOC_BL, FMS_BUY_CARGO_ALLOC_BOE, FMS_TRADER_CONT_MST, FMS_TRADER_CONT_BU, FMS_TRADER_CONT_SPLIT_PLANT, FMS_TRADER_CONT_PLANT, FMS_TRADER_CONT_PLANT_CHRG, FMS_TRADER_BILLING_DTL, FMS_CONT_PRICE_DTL(P), FMS_CONT_PRICE_MIN_DTL(P), FMS_BUY_DAILY_BUYER_NOM, FMS_BUY_DAILY_SELLER_NOM, FMS_BUY_DAILY_ALLOCATION, FMS_BUY_DAILY_ALLOCATION_MM, FMS_PUR_SG_INV_MST, FMS_CUSTOM_PD_BOND_DTL, FMS_PUR_PG_INV_MST, LOG_TRADER_CONT_MST, LOG_TRADER_CN_MST, LOG_TRADER_CARGO_MST",	//, LOG_FMS_SECURITY_MST(P), FMS_SECURITY_MST(P)", //, LOG_FMS_SECURITY_MST(P) - Commented as per instructed by Saibal Sir
			//"FMS_AGMT_MST, FMS_AGMT_TRANSPTR, FMS_AGMT_PLANT, FMS_AGMT_BU, FMS_SUPPLY_AGMT_LIABILITY, FMS_AGMT_BILLING_DTL, FMS_AGMT_DEACTIVATION_DTL, FMS_SUPPLY_CONT_MST, FMS_SUPPLY_CONT_TRANSPTR, FMS_SUPPLY_CONT_PLANT, FMS_SUPPLY_CONT_BU, FMS_SUPPLY_CONT_LIABILITY, FMS_SUPPLY_BILLING_DTL, FMS_CONT_PRICE_DTL(S), FMS_CONT_PRICE_MIN_DTL(S), FMS_SECURITY_DEAL_MAP(S), FMS_SECURITY_MST(S), FMS_SUPPLY_CONT_DCQ_DTL, FMS_SUPPLY_CONT_PLANT_CHRG, FMS_SUPPLY_PURCHASE_MAP_DTL, FMS_SUPPLY_ALLOC_REVISED, FMS_DAILY_BUYER_NOM, FMS_DAILY_BUYER_NOM_DTL, FMS_DAILY_SELLER_NOM, FMS_DAILY_SELLER_NOM_DTL, FMS_METER_TICKET_READING, FMS_DAILY_ALLOCATION_DTL, FMS_DAILY_ALLOCATION_DTL_CT, FMS_INVOICE_MST, FMS_INVOICE_DTL", // LOG_FMS_SECURITY_MST(S),LOG_SUPPLY_CONT_MST - Commented as per instructed by Saibal Sir
			"FMS_AGMT_MST, FMS_AGMT_TRANSPTR, FMS_AGMT_PLANT, FMS_AGMT_BU, FMS_SUPPLY_AGMT_LIABILITY, FMS_AGMT_BILLING_DTL, FMS_AGMT_DEACTIVATION_DTL, FMS_SUPPLY_CONT_MST, LOG_SUPPLY_CONT_MST, FMS_SUPPLY_CONT_TRANSPTR, FMS_SUPPLY_CONT_PLANT, FMS_SUPPLY_CONT_BU, FMS_SUPPLY_CONT_LIABILITY, FMS_SUPPLY_BILLING_DTL, FMS_SUPPLY_CONT_DCQ_DTL, FMS_SUPPLY_CONT_PLANT_CHRG, FMS_SUPPLY_PURCHASE_MAP_DTL, FMS_SUPPLY_ALLOC_REVISED, FMS_LTCORA_AGMT_MST, FMS_LTCORA_AGMT_TRANSPTR, FMS_LTCORA_AGMT_PLANT, FMS_LTCORA_AGMT_LIABILITY, FMS_LTCORA_AGMT_BILLING_DTL, FMS_LTCORA_CONT_MST, LOG_LTCORA_CONT_MST, FMS_LTCORA_CONT_TRANSPTR, FMS_LTCORA_CONT_PLANT, FMS_LTCORA_CONT_LIABILITY, FMS_LTCORA_CONT_BILLING_DTL, FMS_LTCORA_CONT_STRG_CRG, FMS_LTCORA_CONT_CARGO_DTL, FMS_LTCORA_CONT_CARGO_ADQ, FMS_LTCORA_CONT_CARGO_CSOC, FMS_LTCORA_CONT_CARGO_MOD, FMS_CONT_PRICE_DTL(S), FMS_CONT_PRICE_MIN_DTL(S), FMS_DAILY_BUYER_NOM, FMS_DAILY_BUYER_NOM_DTL, FMS_DAILY_SELLER_NOM, FMS_DAILY_SELLER_NOM_DTL, FMS_METER_TICKET_READING, FMS_DAILY_ALLOCATION_DTL, FMS_DAILY_ALLOCATION_DTL_CT, FMS_INVOICE_MST, FMS_INVOICE_MST_UPDATE, FMS_INVOICE_MST_TAXCD_UPDATE, FMS_INVOICE_DTL, FMS_INVOICE_IRN_DTL, FMS_INV_STORAGE_CRG_DTL, FMS_FFLOW_INV_MST, FMS_FFLOW_INV_MST_UPDATE, FMS_FFLOW_INV_DTL, FMS_INV_FILE_DTL, FMS_INV_FILE_DTL_UPDATE, FMS_FFLOW_INV_FILE_DTL, FMS_FFLOW_INV_FILE_DTL_UPDATE, FMS_INV_ADV_DTL, FMS_INV_PAY_RECV_DTL, FMS_INVOICE_MST_CR_DR, FMS_INV_CRDR_REF, FMS_INV_FILE_DTL_CR_DR, FMS_INVOICE_MST_LP, FMS_INV_FILE_DTL_LP, FMS_INV_ADV_DTL_UPDATE", // LOG_FMS_SECURITY_MST(S),LOG_SUPPLY_CONT_MST - Commented as per instructed by Saibal Sir
			"FMS_GTA_AGMT_MST, FMS_GTA_ENTRY_POINT, FMS_GTA_EXIT_POINT, FMS_GTA_AGMT_BILLING_DTL, FMS_GTA_CONT_MST, FMS_GTA_CONT_MAP, FMS_GTA_BILLING_DTL, FMS_DAILY_TRANSPORTER_NOM, FMS_DAILY_TRANSPORTER_SCH, FMS_DAILY_TRANSPORTER_ALLOC, FMS_GTA_SG_INV_MST, FMS_GTA_PG_INV_MST, FMS_GTA_FFLOW_INV_MST, FMS_GTA_FFLOW_INV_DTL",
			"FMS_TANK_MST, FMS_TANK_CONSUMPTION_MST, FMS_TANK_INVENTORY_DTL",
			"FMS_TRUCK_TRANSPORTER_MST, FMS_TRUCK_TRANS_CONTACT_MST, FMS_TRUCK_MST, FMS_TRUCK_DRIVER_MST, FMS_FILLING_STATION_MST, FMS_BAY_SLOT_MST, FMS_CHECKPOST_MST, FMS_TRUCK_TRANSPORTER_LINK, FMS_TRUCK_DRIVER_TRANS_LINK, FMS_TRUCK_DRIVER_LINK, FMS_LINK_CHECKPOST_PLANT, FMS_AGMT_MST(DLNG), FMS_AGMT_BILLING_DTL(DLNG), FMS_SUPPLY_CONT_MST(DLNG), FMS_SUPPLY_CONT_PLANT(DLNG), FMS_SUPPLY_CONT_FILLING_STN, FMS_SUPPLY_BILLING_DTL(DLNG), FMS_SUPPLY_CFORM_DTL(DLNG), FMS_CFORM_MST, FMS_CFORM_DTL, FMS_SUPPLY_CONT_LIABILITY(DLNG), FMS_SUPPLY_CONT_TRUCK_TRANS, FMS_SUPPLY_PURCHASE_MAP_DTL(DLNG), FMS_SUPPLY_CONT_DCQ_DTL(DLNG), FMS_SUPPLY_ALLOC_REVISED(DLNG), FMS_CONT_PRICE_DTL(DLNG), FMS_CONT_PRICE_MIN_DTL(DLNG), FMS_AGMT_SVC_MST, FMS_SVC_CONT_MST, FMS_SVC_CONT_MAP, FMS_DLNG_BUYER_NOM(D), FMS_DLNG_BUYER_NOM_DTL(D), FMS_DLNG_SELLER_NOM_DTL(D), FMS_DLNG_ALLOC_MST(D), FMS_DLNG_INVOICE_MST, FMS_DLNG_INV_FILE_DTL, FMS_DLNG_INV_FILE_DTL_UPDATE, FMS_DLNG_INV_PAY_RECV_DTL, FMS_DLNG_FFLOW_INV_MST, FMS_DLNG_FFLOW_INV_DTL, FMS_DLNG_FFLOW_INV_FILE_DTL, FMS_DLNG_FFLOW_INV_FILE_DTL_UPDATE, FMS_SVC_CONT_BILLING_DTL, FMS_DLNG_SVC_INVOICE_MST, FMS_DLNG_SVC_INVOICE_DTL, FMS_DLNG_SVC_INV_FILE_DTL, FMS_SVC_CONT_MST_UPDATE, FMS_DLNG_INVOICE_MST_CR_DR, FMS_DLNG_INV_CRDR_REF, FMS_DLNG_INVOICE_MST_LP, FMS_DLNG_INV_FILE_DTL_LP, FMS_DLNG_FFLOW_INV_MST_SERV, FMS_DLNG_FFLOW_INV_FILE_DTL_SERV, FMS_DLNG_INV_CRDR_FILE_DTL",
			"FMS_LIMIT_MST, FMS_LIMIT_DTL, FMS_FORWARD_PRICE_DTL, FMS_SPOT_PRICE_DTL, FMS_CURVE_HOLIDAY_CALND, FMS_CURVE_SETTLE_CALND, FMS_MR_CONT_TAQ_DTL, FMS_MR_EXPO_EOD_MST, FMS_MR_EXPO_EOD_DTL, FMS_SECURITY_DEAL_MAP, FMS_SECURITY_MST, LOG_FMS_SECURITY_MST, FMS_SECURITY_FILE_DTL",
			"FMS_DERV_AGMT_MST, FMS_DERV_CONT_MST, FMS_DERV_INSTRUMENT_MST, FMS_DERV_CONT_BILLING_DTL, FMS_DERV_INVOICE_MST, FMS_DERV_INV_FILE_DTL, FMS_DERV_HEDGE_EXPOSURE_DTL, FMS_DERV_INV_FILE_DTL_UPDATE",
			"FMS_ENTITY_ACCOUNT_CODE_SUN, FMS_TAX_STRUCTURE_SUN",
			"FMS_OTH_ENTITY_MST, FMS_OTH_ENTITY_ADDR_MST, FMS_OTH_INVOICE_MST, FMS_OTH_INVOICE_DTL, FMS_OTH_INV_CRDR_REF, FMS_OTH_INV_FILE_DTL, FMS_OTH_INV_IRN_DTL"
		};

	public static final String independent_function_names = "FMS_COUNTERPARTY_MST, FMS_COUNTERPARTY_ADDR_MST, FMS_ENTITY_REQ_DTL, FMS_SECTOR_MST, FMS_COMPANY_OWNER_MST, FMS_ENTITY_TCS_TDS_MST, "
			+ " FMS_COMPANY_OWNER_ADDR_MST, FMS_INT_PAY_RATE_ENTRY, FMS_EXCHG_RATE_ENTRY, FMS_BANK_MST, FMS_SHIP_MST, FMS_CUSTOM_TAX_STRUCT_DTL, FMS_HOLIDAY_DTL, FMS_PRODUCT_MOLECULE_MST,"
			+ " FMS_PRODUCT_MST, FMS_SAC_MST, FMS_TRADER_CN_MST, FMS_CARGO_SVC_CONT_MST, FMS_TANK_MST, FMS_TANK_CONSUMPTION_MST, FMS_TRADER_AGMT_MST, FMS_TRADER_AGMT_PLANT, FMS_TRADER_AGMT_BU,"
			+ " FMS_TRADER_AGMT_BILLING_DTL, FMS_LIMIT_MST, FMS_LIMIT_DTL, FMS_TRADER_CONT_MST,"
			+ " FMS_TRUCK_TRANSPORTER_MST, FMS_TRUCK_MST, FMS_TRUCK_DRIVER_MST, FMS_FILLING_STATION_MST, FMS_CHECKPOST_MST, FMS_AGMT_MST(DLNG), FMS_AGMT_SVC_MST,"
			+ " FMS_AGMT_MST, FMS_FORWARD_PRICE_DTL,FMS_SPOT_PRICE_DTL,FMS_CURVE_HOLIDAY_CALND,FMS_CURVE_SETTLE_CALND,FMS_MR_CONT_TAQ_DTL,"//FMS_MR_EXPO_EOD_MST,FMS_MR_EXPO_EOD_DTL,"
			+ "	FMS_GTA_AGMT_MST,"
			+ " FMS_LTCORA_AGMT_MST,FMS_INV_STORAGE_CRG_DTL,"
			+ "	FMS_PSEUDO_CARGO_DTL"
			+ " FMS_DERV_AGMT_MST, FMS_DERV_CONT_MST, FMS_DERV_INSTRUMENT_MST";

	//tables used for each function
	public static final String[][] fn_name = {
			{
				"FMS9_COUNTERPARTY_MST, FMS7_CUSTOMER_MST, FMS7_TRADER_MST, FMS7_TRANSPORTER_MST, FMS7_HOUSE_AGENT_MST, FMS7_VESSEL_AGENT_MST, FMS7_SURVEYOR_MST",
				"FMS9_COUNTERPARTY_MST, FMS9_COUNTERPARTY_ADD_MST, FMS7_CUS_HOUSE_AGENT_MST, FMS7_CUS_HOUSE_AGENT_ADDR_MST, FMS7_VESSEL_AGENT_MST, FMS7_VESSEL_AGENT_ADDR_MST, FMS7_SURVEYOR_MST, FMS7_SURVEYOR_ADDRESS_MST",
				"FMS9_COUNTERPARTY_MST, FMS7_CUSTOMER_MST, FMS7_TRADER_MST, FMS7_TRANSPORTER_MST, FMS7_CUS_HOUSE_AGENT_MST, FMS7_VESSEL_AGENT_MST, FMS7_SURVEYOR_MST",
				"FMS7_SECTOR_MST",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_ADDRESS_MST, FMS7_CUSTOMER_MST, FMS7_TRADER_ADDRESS_MST, FMS7_TRADER_MST, FMS7_TRANSPORTER_ADDRESS_MST, FMS7_TRANSPORTER_MST",
				"FMS7_SUPPLIER_MST",
				"FMS9_COUNTERPTY_MST, FMS7_SUPPLIER_ADDRESS_MST, FMS7_SUPPLIER_MST",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_PLANT_DTL, FMS7_CUSTOMER_MST, FMS7_SECTOR_MST, FMS7_TRADER_PLANT_DTL, FMS7_TRADER_MST, FMS7_TRANSPORTER_PLANT_DTL, FMS7_TRANSPORTER_MST, FMS7_SUPPLIER_ADDRESS_MST, FMS7_SUPPLIER_MST",
				"FMS7_SURVEYOR_ADDRESS_MST, FMS7_SURVEYOR_MST, FMS7_VESSEL_AGENT_ADDR_MST, FMS7_VESSEL_AGENT_MST, FMS7_CUS_HOUSE_AGENT_ADDR_MST, FMS7_CUS_HOUSE_AGENT_MST",
				"FMS7_INT_PAY_RATE_ENTRY, FMS7_CONT_INT_RATE_MST",
				"FMS7_EXCHG_RATE_ENTRY, FMS7_CONT_EXCHG_RATE_MST",
				"FMS7_BANK_MST",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_TURNOVER_DTL, FMS7_CUSTOMER_MST, FMS7_TRADER_TURNOVER_DTL, FMS7_TRADER_MST, FMS7_SUPPLIER_TURNOVER_DTL, FMS7_SUPPLIER_MST",
				"FMS7_SHIP_MST",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_CONTACT_MST, FMS7_CUSTOMER_MST, FMS7_TRADER_CONTACT_MST, FMS7_TRADER_MST, FMS7_TRANSPORTER_CONTACT_MST, FMS7_TRANSPORTER_MST, FMS7_CUS_HUS_AGT_CONTACT_MST, FMS7_CUS_HOUSE_AGENT_MST, FMS7_VESSEL_AGENT_CONTACT_MST, FMS7_VESSEL_AGENT_MST, FMS7_SURVEYOR_CONTACT_MST, FMS7_SURVEYOR_MST, FMS7_SUPPLIER_CONTACT_MST, FMS7_SUPPLIER_MST",
				"FMS7_METER_MST, FMS7_TRANSPORTER_MST, FMS7_METER_DTL",
				"FMS7_TRADER_PLANT_DTL, FMS7_TRADER_MST, FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_PLANT_TAX_CDS, FMS7_CUSTOMER_MST, FMS7_GOVT_STAT_NO, FMS7_TRADER_PLANT_TAX_CDS, FMS7_TRADER_MST, FMS7_SUPPLIER_MST, FMS7_SUPPLIER_PLANT_TAX_CDS, FMS7_SUPPLIER_MST",
				"FMS7_SURVEYOR_MST, FMS7_GOVT_STAT_NO, FMS7_VESSEL_AGENT_MST, FMS7_CUS_HOUSE_AGENT_MST",
				"FMS7_TRADER_PLANT_DTL, FMS7_TRADER_MST, FMS7_CUSTOMER_TAX_STRUCT_DTL, FMS7_TRADER_TAX_STRUCT_DTL",
				"FMS7_CUSTOMER_SERVICE_TAX_DTL, FMS7_TAX_DTL_INVOICEWISE, FMS7_TRADER_SERVICE_TAX_DTL",
				"FMS7_CARGO_ENTITY_TAX_DTL, FMS7_CUS_HOUSE_AGENT_MST, FMS7_SURVEYOR_MST, FMS7_VESSEL_AGENT_MST",
				"FMS7_CARGO_TAX_MST, FMS7_TAX_STRUCTURE",
				"FMS9_HOLIDAY_DTL",
				"",
				"FMS7_PRODUCT_MST",
				"FMS8_SERVICE_MST",
				""
			},
			
			{
				"",
				"",
				"",
				"",
				"FMS9_COUNTERPTY_MST, FMS7_MAN_REQ_MST, FMS7_TRADER_MST, FMS7_MAN_REQ_CARGO_DTL, FMS7_MAN_CONFIRM_MST, FMS7_MAN_CONFIRM_CARGO_DTL, FMS7_CARGO_NOMINATION",
				"FMS9_COUNTERPTY_MST, FMS7_MAN_REQ_MST, FMS7_TRADER_MST, FMS7_MAN_CONFIRM_CARGO_DTL",
				"FMS9_PSEUDO_CARGO_DTL",
				"FMS7_SURVEYOR_MST, FMS7_CARGO_ENTITY_SERV_CHARGES, FMS7_VESSEL_AGENT_MST, FMS7_CUS_HOUSE_AGENT_MST",
				"FMS7_SURVEYOR_MST, FMS7_CARGO_ENTITY_SERV_CHARGES, FMS7_VESSEL_AGENT_MST, FMS7_CUS_HOUSE_AGENT_MST",
				"FMS9_COUNTERPARTY_MST, FMS7_TRADER_MST, FMS7_CARGO_NOMINATION, FMS7_SHIP_MST, FMS7_CARGO_BL_DTL, FMS7_CARGO_ARRIVAL_DTL, FMS7_SURVEYOR_MST, FMS7_CUS_HOUSE_AGENT_MST, FMS7_VESSEL_AGENT_MST",
				"FMS9_COUNTERPARTY_MST, FMS7_TRADER_MST, FMS7_CARGO_NOMINATION, FMS7_CARGO_BL_DTL",
				"FMS9_COUNTERPARTY_MST, FMS7_TRADER_MST, FMS7_CARGO_NOMINATION, FMS7_CARGO_ARRIVAL_DTL",
				"FMS7_CARGO_ARRIVAL_DTL, FMS7_CARGO_QQ_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_CARGO_NOMINATION, FMS7_TRADER_MST, FMS7_CARGO_BL_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_CARGO_NOMINATION, FMS7_TRADER_MST, FMS7_CARGO_ARRIVAL_DTL",
				"FMS7_TRADER_CONT_MST, FMS7_TRADER_CLAUSE_MST, FMS7_TRADER_MST, FMS7_MAN_CONFIRM_CARGO_DTL",
				"FMS7_TRADER_SUPPLIER_PLANT_MST, FMS7_TRADER_CONT_MST, FMS7_TRADER_MST, FMS7_MAN_CONFIRM_CARGO_DTL",
				"FMS7_TRADER_OTHER_PLANT_MST, FMS7_TRADER_OTHER_PLANT_DTL, FMS7_MAN_CONFIRM_CARGO_DTL, FMS7_TRADER_CONT_MST, FMS7_TRADER_MST",
				"FMS7_TRADER_PLANT_MST, FMS7_TRADER_CONT_MST, FMS7_TRADER_MST, FMS7_MAN_CONFIRM_CARGO_DTL",
				"FMS7_TRD_OTH_TARIFF_DTL, FMS7_TRADER_CONT_MST, FMS7_OTHER_CHARGES_MST",
				"FMS7_TRADER_BILLING_DTL, FMS7_TRADER_CONT_MST, FMS7_TRADER_CLAUSE_MST, FMS7_MAN_CONFIRM_CARGO_DTL, FMS7_TRADER_MST",
				"FMS9_COUNTERPTY_MST, FMS7_MAN_REQ_MST, FMS7_TRADER_MST, FMS7_MAN_CONFIRM_CARGO_DTL, FMS9_MRCR_CONT_PRICE_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_MAN_REQ_MST, FMS7_TRADER_MST, FMS7_MAN_CONFIRM_CARGO_DTL, FMS9_MRCR_CONT_FIN_PRICE_DTL",
				"FMS9_PO_ALLOC_MST, FMS9_PO_ALLOC_DTL, FMS7_MAN_CONFIRM_CARGO_DTL, FMS7_TRADER_CONT_MST, FMS7_TRADER_MST",
				"FMS9_PO_ALLOC_MST, FMS9_PO_ALLOC_DTL, FMS7_MAN_CONFIRM_CARGO_DTL, FMS7_TRADER_CONT_MST, FMS7_TRADER_MST",
				"FMS9_PO_ALLOC_MST, FMS9_PO_ALLOC_DTL, FMS7_MAN_CONFIRM_CARGO_DTL, FMS7_TRADER_CONT_MST, FMS7_TRADER_MST",
				"FMS9_PO_ALLOC_MST, FMS9_PO_ALLOC_DTL, FMS7_MAN_CONFIRM_CARGO_DTL, FMS7_TRADER_CONT_MST, FMS7_TRADER_MST, FMS7_PRODUCT_MST",
				"FMS7_CARGO_NOMINATION, FMS7_TRADER_MST, FMS7_PROV_SELLER_PAY, FMS7_MAN_CONFIRM_CARGO_DTL, FMS7_FINAL_SELLER_PAY, FMS7_CUSTOM_DUTY, FMS7_EXCHG_RATE_ENTRY, FMS7_FINAL_CUSTOM_DUTY, FMS7_MAN_REQ_MST, FMS7_DOM_PUR_INV_DTL, FMS7_TRADER_CONT_MST, FMS7_TRADER_TAX_STRUCT_DTL,",
				"FMS7_CUSTOM_DUTY",
				"FMS7_DOM_PUR_INV_DTL_PG",
				"FMS_TRADER_CONT_MST",
				"FMS_TRADER_CN_MST",
				"FMS_TRADER_CARGO_MST"
			},
			
			{
//				"FMS9_COUNTERPTY_MST, FMS7_FGSA_MST, FMS7_CUSTOMER_MST, FMS7_FGSA_CLAUSE_MST, FMS7_CLAUSE_MST",
//				"FMS9_COUNTERPTY_MST, FMS7_FGSA_TRANSPORTER_MST, FMS7_CUSTOMER_MST, FMS7_TRANSPORTER_MST, FMS7_TRANSPORTER_PLANT_DTL",
//				"FMS9_COUNTERPTY_MST, FMS7_FGSA_PLANT_MST, FMS7_CUSTOMER_MST",
//				"FMS9_COUNTERPTY_MST, FMS7_FGSA_SUPPLIER_PLANT_MST, FMS7_CUSTOMER_MST",
//				"FMS9_COUNTERPTY_MST, FMS7_FGSA_MST, FMS7_FGSA_LD_DTL, FMS7_FGSA_TOP_DTL, FMS7_FGSA_MAKEUPGAS_DTL, FMS7_CUSTOMER_MST",
//				"FMS7_FGSA_BILLING_DTL, FMS7_FGSA_MST, FMS7_FGSA_CLAUSE_MST, FMS7_CUSTOMER_MST",
//				"FMS7_FGSA_DEACTIVATION_DTL, FMS7_FGSA_MST, FMS7_CUSTOMER_MST",
//				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS7_CUSTOMER_MST, FMS7_SN_CLAUSE_MST, FMS7_LOA_CLAUSE_MST, FMS10_IGX_CLAUSE_MST",
//				"FMS9_COUNTERPTY_MST, FMS7_SN_TRANSPORTER_MST, FMS7_LOA_TRANSPORTER_MST, FMS10_IGX_TRANSPORTER_MST, FMS7_CUSTOMER_MST, FMS7_TRANSPORTER_MST, FMS7_TRANSPORTER_PLANT_DTL",
//				"FMS9_COUNTERPTY_MST, FMS7_SN_PLANT_MST, FMS7_LOA_PLANT_MST, FMS10_IGX_PLANT_MST, FMS7_CUSTOMER_MST",
//				"FMS9_COUNTERPTY_MST, FMS7_SN_SUPPLIER_PLANT_MST, FMS7_LOA_SUPPLIER_PLANT_MST, FMS10_IGX_SUPPLIER_PLANT_MST, FMS7_CUSTOMER_MST",
//				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_SN_LD_DTL, FMS7_SN_TOP_DTL, FMS7_SN_MAKEUPGAS_DTL, FMS7_LOA_MST, FMS7_LOA_LD_DTL, FMS7_LOA_TOP_DTL, FMS7_LOA_MAKEUPGAS_DTL, FMS10_IGX_MST, FMS10_IGX_LD_DTL, FMS10_IGX_TOP_DTL, FMS10_IGX_MAKEUPGAS_DTL, FMS7_CUSTOMER_MST",
//				"FMS7_SN_BILLING_DTL, FMS7_SN_MST, FMS7_SN_CLAUSE_MST, FMS7_LOA_MST, FMS7_LOA_CLAUSE_MST, FMS10_IGX_MST, FMS10_IGX_BILLING_DTL, FMS7_CUSTOMER_MST",
//				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS7_CUSTOMER_MST, FMS9_MRCR_CONT_PRICE_DTL",
//				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS7_CUSTOMER_MST, FMS9_MRCR_CONT_FIN_PRICE_DTL",
//				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS7_CUSTOMER_MST, FMS9_SECURITY_POST_MST",
//				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS7_CUSTOMER_MST, FMS9_SECURITY_POST_MST, FMS7_BANK_MST",
//				"FMS9_COUNTERPTY_MST, FMS7_SN_DCQ_DTL, FMS7_SN_MST, FMS7_LOA_DCQ_DTL, FMS7_LOA_MST, FMS10_IGX_MST, FMS10_IGX_DCQ_DTL",
//				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS7_CUSTOMER_MST, FMS7_CONT_OTHER_TARIFF_DTL, FMS7_OTHER_CHARGES_MST",
//				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS7_SN_MST, FMS7_SN_CARGO_DTL, FMS7_LOA_MST, FMS7_LOA_CARGO_DTL, FMS10_IGX_MST, FMS10_IGX_CARGO_DTL, FMS7_MAN_CONFIRM_CARGO_DTL",
//				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS7_SN_MST, FMS7_SN_CARGO_DTL, FMS7_LOA_MST, FMS7_LOA_CARGO_DTL, FMS10_IGX_MST, FMS10_IGX_CARGO_DTL, FMS7_MAN_CONFIRM_CARGO_DTL",
//				"FMS9_COUNTERPTY_MST, FMS7_DAILY_BUYER_NOM_DTL, FMS7_CUSTOMER_MST",
//				"FMS9_COUNTERPTY_MST, FMS7_DAILY_BUYER_NOM_DTL, FMS7_CUSTOMER_MST",
//				"FMS9_COUNTERPTY_MST, FMS7_DAILY_SELLER_NOM_DTL, FMS7_CUSTOMER_MST",
//				"FMS9_COUNTERPTY_MST, FMS7_DAILY_SELLER_NOM_DTL, FMS7_CUSTOMER_MST",
//				"FMS7_METER_TICKET_READING, FMS7_TRANSPORTER_MST,FMS7_METER_DTL, FMS7_METER_MST ",
//				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS7_CUSTOMER_MST, FMS7_TRANSPORTER_MST, FMS7_DAILY_ALLOCATION_DTL",
//				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS7_CUSTOMER_MST, FMS7_TRANSPORTER_MST, FMS7_DAILY_ALLOCATION_DTL",
//				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS7_INVOICE_MST, FMS7_INVOICE_TCS_DTL, FMS7_INVOICE_TDS_DTL",
//				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS7_INVOICE_MST, FMS7_INVOICE_DTL"
//				//"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, LOG_FMS10_IGX_MST, LOG_FMS8_CONTRACT_MST",
//				//"FMS9_COUNTERPARTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS7_CUSTOMER_MST, LOG_FMS9_SECURITY_POST_MST", // Commented as per instructed by Saibal Sir
				"FMS9_COUNTERPTY_MST, FMS7_FGSA_MST, FMS7_CUSTOMER_MST, FMS7_FGSA_CLAUSE_MST, FMS7_CLAUSE_MST",
				"FMS9_COUNTERPTY_MST, FMS7_FGSA_TRANSPORTER_MST, FMS7_CUSTOMER_MST, FMS7_TRANSPORTER_MST, FMS7_TRANSPORTER_PLANT_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_FGSA_PLANT_MST, FMS7_CUSTOMER_MST",
				"FMS9_COUNTERPTY_MST, FMS7_FGSA_SUPPLIER_PLANT_MST, FMS7_CUSTOMER_MST",
				"FMS9_COUNTERPTY_MST, FMS7_FGSA_MST, FMS7_FGSA_LD_DTL, FMS7_FGSA_TOP_DTL, FMS7_FGSA_MAKEUPGAS_DTL, FMS7_CUSTOMER_MST",
				"FMS7_FGSA_BILLING_DTL, FMS7_FGSA_MST, FMS7_FGSA_CLAUSE_MST, FMS7_CUSTOMER_MST",
				"FMS7_FGSA_DEACTIVATION_DTL, FMS7_FGSA_MST, FMS7_CUSTOMER_MST",
				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS7_CUSTOMER_MST, FMS7_SN_CLAUSE_MST, FMS7_LOA_CLAUSE_MST, FMS10_IGX_CLAUSE_MST",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, LOG_FMS10_IGX_MST, LOG_FMS8_CONTRACT_MST",
				"FMS9_COUNTERPTY_MST, FMS7_SN_TRANSPORTER_MST, FMS7_LOA_TRANSPORTER_MST, FMS10_IGX_TRANSPORTER_MST, FMS7_CUSTOMER_MST, FMS7_TRANSPORTER_MST, FMS7_TRANSPORTER_PLANT_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_SN_PLANT_MST, FMS7_LOA_PLANT_MST, FMS10_IGX_PLANT_MST, FMS7_CUSTOMER_MST",
				"FMS9_COUNTERPTY_MST, FMS7_SN_SUPPLIER_PLANT_MST, FMS7_LOA_SUPPLIER_PLANT_MST, FMS10_IGX_SUPPLIER_PLANT_MST, FMS7_CUSTOMER_MST",
				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_SN_LD_DTL, FMS7_SN_TOP_DTL, FMS7_SN_MAKEUPGAS_DTL, FMS7_LOA_MST, FMS7_LOA_LD_DTL, FMS7_LOA_TOP_DTL, FMS7_LOA_MAKEUPGAS_DTL, FMS10_IGX_MST, FMS10_IGX_LD_DTL, FMS10_IGX_TOP_DTL, FMS10_IGX_MAKEUPGAS_DTL, FMS7_CUSTOMER_MST",
				"FMS7_SN_BILLING_DTL, FMS7_SN_MST, FMS7_SN_CLAUSE_MST, FMS7_LOA_MST, FMS7_LOA_CLAUSE_MST, FMS10_IGX_MST, FMS10_IGX_BILLING_DTL, FMS7_CUSTOMER_MST",
				"FMS9_COUNTERPTY_MST, FMS7_SN_DCQ_DTL, FMS7_SN_MST, FMS7_LOA_DCQ_DTL, FMS7_LOA_MST, FMS10_IGX_MST, FMS10_IGX_DCQ_DTL,",
				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS7_CUSTOMER_MST, FMS7_CONT_OTHER_TARIFF_DTL, FMS7_OTHER_CHARGES_MST",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS7_SN_MST, FMS7_SN_CARGO_DTL, FMS7_LOA_MST, FMS7_LOA_CARGO_DTL, FMS10_IGX_MST, FMS10_IGX_CARGO_DTL, FMS7_MAN_CONFIRM_CARGO_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS7_SN_MST, FMS7_SN_CARGO_DTL, FMS7_LOA_MST, FMS7_LOA_CARGO_DTL, FMS10_IGX_MST, FMS10_IGX_CARGO_DTL, FMS7_MAN_CONFIRM_CARGO_DTL",
				"FMS9_COUNTERPTY_MST, FMS8_LNG_REGAS_MST, FMS7_CUSTOMER_MST",
				"FMS9_COUNTERPTY_MST, FMS8_LNG_REGAS_MST, FMS7_CUSTOMER_MST, FMS8_LNG_REGAS_TRANS_DTL, FMS7_TRANSPORTER_MST, FMS7_TRANSPORTER_PLANT_DTL",
				"FMS9_COUNTERPTY_MST, FMS8_LNG_REGAS_MST, FMS7_CUSTOMER_MST, FMS8_LNG_REGAS_PLANT_DTL ",
				"FMS9_COUNTERPTY_MST, FMS8_LNG_REGAS_MST, FMS7_CUSTOMER_MST, FMS8_LNG_REGAS_LIABILITY_DTL ",
				"FMS8_LNG_REGAS_MST, FMS8_LNG_REGAS_BILLING_DTL, FMS7_CUSTOMER_MST, ",
				"FMS9_COUNTERPTY_MST, FMS8_LNG_REGAS_MST, FMS7_CUSTOMER_MST, FMS8_LNG_REGAS_CLAUSE_MST ",
				"FMS9_COUNTERPTY_MST, LOG_FMS8_LNG_REGAS_MST, FMS7_CUSTOMER_MST, FMS8_LNG_REGAS_CLAUSE_MST ",
				"FMS9_COUNTERPTY_MST, FMS8_LNG_REGAS_MST, FMS7_CUSTOMER_MST, FMS8_LNG_REGAS_TRANS_DTL, FMS7_TRANSPORTER_MST, FMS7_TRANSPORTER_PLANT_DTL ",
				"FMS9_COUNTERPTY_MST, FMS8_LNG_REGAS_MST, FMS7_CUSTOMER_MST, FMS8_LNG_REGAS_PLANT_DTL ",
				"FMS9_COUNTERPTY_MST, FMS8_LNG_REGAS_MST, FMS7_CUSTOMER_MST, FMS8_LNG_REGAS_LIABILITY_DTL ",
				"FMS8_LNG_REGAS_MST A, FMS8_LNG_REGAS_BILLING_DTL, FMS7_CUSTOMER_MST ",
				"FMS9_COUNTERPTY_MST, FMS8_LNG_REGAS_MST, FMS8_STORAGE_CHARGES_DTL, FMS7_CUSTOMER_MST",
				"FMS9_COUNTERPTY_MST, FMS8_LNG_REGAS_MST, FMS8_LNG_REGAS_CARGO_DTL, FMS7_CUSTOMER_MST, FMS7_TRADER_MST",
				"FMS9_COUNTERPTY_MST, FMS9_CARGO_UNLOADED_QTY_DTL, FMS7_CUSTOMER_MST, FMS8_LNG_REGAS_MST ",
				"FMS9_COUNTERPTY_MST, FMS8_LNG_REGAS_CSOC_DTL, FMS7_CUSTOMER_MST, FMS8_LNG_REGAS_MST, FMS8_LNG_REGAS_CARGO_DTL",
				"FMS9_COUNTERPTY_MST, FMS8_LNG_REGAS_MST, FMS7_CONT_PRICE_DTL, FMS8_LNG_REGAS_CARGO_DTL, FMS7_CUSTOMER_MST",
				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS7_CUSTOMER_MST, FMS9_MRCR_CONT_PRICE_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS7_CUSTOMER_MST, FMS9_MRCR_CONT_FIN_PRICE_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS8_LNG_REGAS_MST, FMS7_RE_GAS_MST, FMS7_DAILY_BUYER_NOM_DTL, FMS7_CUSTOMER_MST",
				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS8_LNG_REGAS_MST, FMS7_RE_GAS_MST, FMS7_DAILY_BUYER_NOM_DTL, FMS7_CUSTOMER_MST",
				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS8_LNG_REGAS_MST, FMS7_RE_GAS_MST, FMS7_DAILY_SELLER_NOM_DTL, FMS7_CUSTOMER_MST",
				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS8_LNG_REGAS_MST, FMS7_RE_GAS_MST, FMS7_DAILY_SELLER_NOM_DTL, FMS7_CUSTOMER_MST",
				"FMS7_METER_TICKET_READING, FMS7_TRANSPORTER_MST,FMS7_METER_DTL, FMS7_METER_MST ",
				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS8_LNG_REGAS_MST, FMS7_RE_GAS_MST, FMS7_CUSTOMER_MST, FMS7_TRANSPORTER_MST, FMS7_DAILY_ALLOCATION_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS8_LNG_REGAS_MST, FMS7_RE_GAS_MST, FMS7_CUSTOMER_MST, FMS7_TRANSPORTER_MST, FMS7_DAILY_ALLOCATION_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS8_LNG_REGAS_MST, FMS8_LNG_REGAS_CARGO_DTL, FMS7_RE_GAS_MST, FMS7_RE_GAS_CARGO_DTL, FMS7_INVOICE_MST, FMS7_INVOICE_TCS_DTL, FMS7_INVOICE_TDS_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS8_LNG_REGAS_MST, FMS8_LNG_REGAS_CARGO_DTL, FMS7_RE_GAS_MST, FMS7_RE_GAS_CARGO_DTL, FMS7_INVOICE_MST, FMS7_INVOICE_TCS_DTL, FMS7_INVOICE_TDS_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS8_LNG_REGAS_MST, FMS8_LNG_REGAS_CARGO_DTL, FMS7_RE_GAS_MST, FMS7_RE_GAS_CARGO_DTL, FMS7_INVOICE_MST, FMS7_INVOICE_TCS_DTL, FMS7_INVOICE_TDS_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, FMS8_LNG_REGAS_MST, FMS7_RE_GAS_MST, FMS7_INVOICE_MST, FMS7_INVOICE_DTL",
				"FMS7_INVOICE_IRN_DTL",
				"FMS9_COUNTERPTY_MST, FMS8_STORAGE_INV_CHARGES_DTL, FMS7_INVOICE_MST",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS8_LNG_REGAS_MST, FMS7_INVOICE_MST",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS8_LNG_REGAS_MST, FMS7_INVOICE_MST",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS7_INVOICE_MST, FMS8_OTHER_INVOICE_DTL",
				"FMS7_CUSTOMER_MST, FMS7_INVOICE_MST, FMS8_INV_PDF_DTL",
				"FMS7_CUSTOMER_MST, FMS7_INVOICE_MST, FMS8_INV_PDF_DTL",
				"FMS7_CUSTOMER_MST, FMS7_INVOICE_MST, FMS8_INV_PDF_DTL",
				"FMS7_CUSTOMER_MST, FMS7_INVOICE_MST, FMS8_INV_PDF_DTL",
				"FMS7_CUSTOMER_MST, FMS7_INVOICE_MST,FMS8_LNG_REGAS_MST,FMS8_ADV_INV_DTL",
				"FMS8_PAY_RECV_DTL",
				"FMS7_INVOICE_MST,FMS7_DR_CR_NOTE",
                "FMS7_INVOICE_MST,FMS7_DR_CR_NOTE",
                "FMS7_INVOICE_MST,FMS7_DR_CR_NOTE.FMS8_INV_PDF_DTL",
                "FMS7_CUSTOMER_MST, FMS7_INVOICE_MST",
				"FMS7_CUSTOMER_MST, FMS7_INVOICE_MST, FMS8_INV_PDF_DTL",
				""

				//"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS10_IGX_MST, LOG_FMS10_IGX_MST, LOG_FMS8_CONTRACT_MST",
				//"FMS9_COUNTERPARTY_MST, FMS7_SN_MST, FMS7_LOA_MST, FMS7_CUSTOMER_MST, LOG_FMS9_SECURITY_POST_MST", // Commented as per instructed by Saibal Sir
			},
			
			{
				"FMS9_COUNTERPTY_MST, FMS7_TRANSPORTER_MST, FMS7_TRANSPORTER_PLANT_DTL, FMS_AGREEMENT_MST, FMS_UNIT_MST",
				"FMS9_COUNTERPTY_MST, FMS_CONT_MST, FMS7_TRANSPORTER_MST, ",
				"FMS9_COUNTERPTY_MST, FMS_CONT_MST, FMS7_TRANSPORTER_MST, FMS_DELV_MST, FMS7_CUSTOMER_MST, FMS7_CUSTOMER_PLANT_DTL",
				"FMS_CONT_SECU_PAY_INV",
				"FMS9_COUNTERPTY_MST, FMS_CONT_MST, FMS7_TRANSPORTER_MST, FMS7_TRANSPORTER_PLANT_DTL, FMS7_CUSTOMER_MST, FMS_CONT_PRICE_DTL",
				"FMS9_COUNTERPTY_MST, FMS_CONT_MST, FMS7_TRANSPORTER_MST, FMS7_CUSTOMER_MST",
				"FMS_CONT_MST, FMS7_TRANSPORTER_MST, FMS_CONT_SECU_PAY_INV,FMS_MODE_MST,FMS_CONT_INT_RATE_MST,FMS7_TRANSPORTER_PLANT_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_DAILY_TRANSPORTER_NOM_DTL, FMS7_TRANSPORTER_MST",
				"FMS9_COUNTERPTY_MST, FMS_DAILY_SCHEDULE, FMS7_TRANSPORTER_MST, FMS_CONT_MST",
				"FMS9_COUNTERPTY_MST, FMS_ALLOC_MST, FMS7_TRANSPORTER_MST, FMS_CONT_MST",
				"FMS9_COUNTERPTY_MST, FMS_INV_BILL_DTL, FMS_COMPO_INV_DTL, FMS7_TRANSPORTER_MST, FMS_CONT_MST",
				"FMS9_COUNTERPTY_MST, FMS_INV_BILL_DTL, FMS_COMPO_INV_DTL, FMS7_TRANSPORTER_MST, FMS_CONT_MST",
				"FMS9_COUNTERPTY_MST, FMS_INV_BILL_DTL, FMS_COMPO_INV_DTL, FMS7_TRANSPORTER_MST, FMS_CONT_MST",
				"FMS9_COUNTERPTY_MST, FMS_INV_BILL_DTL, FMS_COMPO_INV_DTL, FMS7_TRANSPORTER_MST, FMS_CONT_MST"

			},
			
			{
				"FMS7_TANK_MASTER_DTL",
				"FMS7_CONSUMPTION_MST",
				"FMS7_INVENTORY_LEVEL_DTL"
			},
			{
				"DLNG_TRANS_MST",
				"DLNG_TRANSPORTER_CONTACT_MST",
				"DLNG_TANK_TRUCK_MST",
				"DLNG_DRIVER_MST",
				"DLNG_SUPPLY_STATION_MST",
				"",
				"DLNG_CHECKOUT_MST",
				"DLNG_TRUCK_DRIVER_LINK_DTL,DLNG_TRANS_MST,DLNG_TANK_TRUCK_MST",
				"DLNG_TRUCK_DRIVER_LINK_DTL,DLNG_TRANS_MST,DLNG_DRIVER_MST",
				"DLNG_TRUCK_DRIVER_LINK_DTL,DLNG_TRANS_MST,DLNG_TANK_TRUCK_MST,DLNG_DRIVER_MST",
				"FMS7_CUSTOMER_MST,DLNG_LINK_CUST_CHECKPOST,DLNG_CHECKPOST_MST",
				"FMS7_CUSTOMER_MST,DLNG_FLSA_CLAUSE_MST,DLNG_FLSA_MST",
//				"FMS7_CUSTOMER_MST,DLNG_FLSA_TRANSPORTER_MST",
//				"FMS7_CUSTOMER_MST,DLNG_FLSA_PLANT_MST",
				"FMS7_CUSTOMER_MST,FMS7_CONT_INT_RATE_MST,FMS7_CONT_EXCHG_RATE_MST,DLNG_FLSA_PLANT_MST,DLNG_FLSA_BILLING_DTL",
//				"FMS7_CUSTOMER_MST,DLNG_TRANS_MST,DLNG_SN_TRANSPORTER_MST",
				"FMS7_CUSTOMER_MST,DLNG_SN_MST,DLNG_LOA_MST",
				"FMS7_CUSTOMER_MST, DLNG_SN_PLANT_MST,DLNG_LOA_PLANT_MST",
				"DLNG_SN_MST,DLNG_LOA_MST,DLNG_SN_TRANSPORTER_MST,DLNG_LOA_TRANSPORTER_MST",
				"DLNG_SN_BILLING_DTL,DLNG_SN_MST,DLNG_LOA_MST",
				"FMS7_CUSTOMER_MST,FMS7_CFORM_CONTRACT_DTL,DLNG_SN_BILLING_DTL",
				"FMS7_CUSTOMER_MST,STATE_MST,FMS7_CFORM_MST",
				"FMS7_CFORM_MST,FMS7_CFORM_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST,DLNG_SN_MST, DLNG_SN_LD_DTL, DLNG_SN_TOP_DTL, DLNG_SN_MAKEUPGAS_DTL, DLNG_LOA_MST, DLNG_LOA_LD_DTL, DLNG_LOA_TOP_DTL, DLNG_LOA_MAKEUPGAS_DTL",
				"DLNG_CUST_TRANS_DTL,DLNG_SN_MST,DLNG_LOA_MST",
				"DLNG_SN_DCQ_DTL, DLNG_LOA_DCQ_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, DLNG_SN_MST, DLNG_SN_CARGO_DTL, DLNG_LOA_MST, DLNG_LOA_CARGO_DTL, FMS7_MAN_CONFIRM_CARGO_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, DLNG_CARGO_ALLOC_REVISED_DTL, DLNG_SN_MST, DLNG_LOA_MST, FMS7_MAN_CONFIRM_CARGO_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST,DLNG_SN_MST, DLNG_LOA_MST,FMS9_MRCR_CONT_PRICE_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST,DLNG_SN_MST, DLNG_LOA_MST,FMS9_MRCR_CONT_FIN_PRICE_DTL",
				"DLNG_SALES_TRANSPORTER_MST",
				"DLNG_SALES_TRANSPORTER_MST",
				"DLNG_SALES_TRANSPORTER_MST",
				"DLNG_DAILY_NOM",
				"DLNG_DAILY_NOM, DLNG_DAILY_TRUCK_NOM_DTL",
				"DLNG_DAILY_SCH, DLNG_DAILY_TRUCK_SCH_DTL",
				"DLNG_ALLOC_MST, DLNG_TANK_VOL_DTL",
				"DLNG_INVOICE_MST",
				"FMS7_CUSTOMER_MST, DLNG_INVOICE_MST, DLNG_INV_PDF_DTL",
				"FMS7_CUSTOMER_MST, DLNG_SN_MST, DLNG_LOA_MST, DLNG_INVOICE_MST",
				"FMS7_CUSTOMER_MST, DLNG_INVOICE_MST,FMS7_INVOICE_MST",
				"FMS7_CUSTOMER_MST, DLNG_INVOICE_MST,FMS7_INVOICE_MST",
				"FMS7_CUSTOMER_MST, DLNG_INVOICE_MST, DLNG_INV_PDF_DTL, FMS8_INV_PDF_DTL",
				"",
				"",
				"",
				"DLNG_SALES_TRANSPORTER_MST, DLNG_INVOICE_MST",
				"DLNG_SALES_TRANSPORTER_MST, DLNG_INVOICE_MST, DLNG_SERVICE_INVOICE_ATTACH",
				"DLNG_INV_PDF_DTL",
				"",
				"FMS_DLNG_INVOICE_MST_CR_DR",
				"DLNG_DR_CR_NOTE,DLNG_INVOICE_MST",
				"FMS7_CUSTOMER_MST, DLNG_INVOICE_MST,FMS7_INVOICE_MST",
				"DLNG_INV_PDF_DTL",
				"",
				"DLNG_INV_PDF_DTL",
				"DLNG_INV_PDF_DTL"
				},
			{
				"FMS9_LIMIT_MST, FMS7_BANK_MST",
				"FMS9_LIMIT_DTL, FMS7_BANK_MST",
				"FMS9_FORWARD2_PRICE_DTL",
				"FMS9_CURVE2_PRICE_DTL",
				"FMS9_CURVE_HOLIDAY_DTL",
				"FMS9_SETTLE_CALND_DTL",
				"FMS9_CONT_TAQ_DTL, FMS9_COUNTERPTY_MST",
				"FMS7_CUSTOMER_MST, FMS7_TRADER_MST, FMS7_MAN_CONFIRM_CARGO_DTL, FMS7_TRADER_CONT_MST, FMS9_EOD_EXPOSURE_MST",
				"FMS7_CUSTOMER_MST,FMS7_MAN_CONFIRM_CARGO_DTL,FMS7_TRADER_MST,FMS9_EOD_EXPOSURE_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_MAN_REQ_MST, FMS7_TRADER_MST, FMS7_MAN_CONFIRM_CARGO_DTL, FMS9_SECURITY_POST_MST",
				"FMS9_COUNTERPTY_MST, FMS7_MAN_REQ_MST, FMS7_TRADER_MST, FMS7_MAN_CONFIRM_CARGO_DTL, FMS9_SECURITY_POST_MST, FMS7_BANK_MST",
				"",
				""
			},
				
			{
				"FMS9_COUNTERPTY_MST, FMS7_TRADER_MST, FMS9_MR_DERI_DEAL_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_TRADER_MST, FMS9_MR_DERI_DEAL_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_TRADER_MST, FMS9_MR_DERI_DEAL_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_TRADER_MST, FMS9_MR_DERI_DEAL_DTL",
				"FMS9_COUNTERPTY_MST, FMS7_TRADER_MST, FMS9_MR_DERI_DEAL_DTL, AC_INVOICE_MST, AC_INVOICE_DTL",
				"FMS7_TRADER_MST, AC_INVOICE_MST, FMS8_INV_PDF_DTL ",
				"FMS9_HEDGE_QTY_DTL",
				""
			},
			
			{
				"FMS9_COUNTERPTY_MST, FMS7_CUSTOMER_MST, FMS7_CUSTOMER_MAPPING",
				"FMS7_TAX_MST"
				
			},
			{
				"FMS7_SUPPLIER_MST, FMS8_VENDOR_MST",
				"FMS7_SUPPLIER_ADDRESS_MST, FMS7_SUPPLIER_MST, FMS8_VENDOR_ADDRESS_MST",
				"FMS7_SUPPLIER_MST, FMS7_INVOICE_MST, FMS8_OTHER_INVOICE_DTL, FMS7_CONT_EXCHG_RATE_MST, FMS8_OTHINV_DR_CR_NOTE",
				"FMS7_SUPPLIER_MST, FMS7_INVOICE_MST, FMS8_OTHER_INVOICE_DTL, FMS7_SHIP_MST, FMS8_LNG_REGAS_CARGO_DTL, FMS7_CARGO_QQ_DTL, FMS8_OTHINV_DR_CR_NOTE",
				"FMS7_INVOICE_MST, FMS8_OTHINV_DR_CR_NOTE, FMS7_SUPPLIER_MST, FMS8_OTHER_INVOICE_DTL",
				"FMS7_INVOICE_MST, FMS8_INV_PDF_DTL",
				"FMS7_INVOICE_IRN_DTL"
			}
			
		};
	
	
	// HashMaps
	HashMap <String, String> customer_map = new HashMap<String, String>();
	HashMap <String, String> trader_map = new HashMap<String, String>();
	HashMap <String, String> transporter_map = new HashMap<String, String>();
	HashMap <String, String> counterparty_map = new HashMap<String, String>();
	HashMap <String, String> meter_map = new HashMap<String, String>();
	
	
	//jsp data structures
	public HashMap<String, String> depend = new HashMap<String, String>();
	 
	
	{
		//BU:
		
		//1-GJ
		//2-MH
		//3-AP
		//COUNTERPARTY- PLANT , BU 
		customer_map.put("RIL-1", "1-2");
		customer_map.put("RIL-18", "18-2");
		customer_map.put("RIL-D6-2", "2-3");
		customer_map.put("MGL-2", "1-2");
		customer_map.put("GSPCL-3", "3-2");
		customer_map.put("Gail-3", "3-2");
		customer_map.put("NTPC-7", "1-2");
		customer_map.put("NTPC-8", "2-2");
		customer_map.put("NTPC-9", "3-2"); 
		customer_map.put("NTPC-10", "4-2");
		customer_map.put("NTPC-11", "5-2");
		customer_map.put("NTPC-12", "6-2");
		customer_map.put("KRIBHCO-2", "1-2");
		customer_map.put("DFPCL-1", "1-2");
		customer_map.put("IGL-7", "1-2");
		customer_map.put("BPCL-3", "3-2");
		customer_map.put("BPCL-4", "4-2");
		customer_map.put("HPCL-3", "3-2");
		customer_map.put("AMNS-3", "1-2");
		customer_map.put("AMNS-4", "4-2");
		customer_map.put("AMNS-5", "1-3");
		customer_map.put("SEMTIPL-4", "4-2");
		customer_map.put("SEMTIPL-6", "6-2");
		customer_map.put("SEMTIPL-7", "7-2");
		customer_map.put("SEMTIPL-9", "9-2");
		customer_map.put("SGIPL-6", "1-2");
		customer_map.put("GGL-3", "1-2");
		customer_map.put("GGL-2", "1-2");
		customer_map.put("HSIL-2", "1-3");
		customer_map.put("HIL-4", "4-2");
		customer_map.put("KAJARIA-2", "2-2");
		customer_map.put("SISECAM-2", "1-1");
		customer_map.put("ATPL-2", "2-2");
		customer_map.put("OPAL-1", "1-2");
		customer_map.put("OPAL-2", "1-1");
		customer_map.put("RCF-3", "1-2");
		customer_map.put("RCF-4", "2-1");
		customer_map.put("RCF-2", "2-2");
		customer_map.put("VVF India-1", "1-2");
		customer_map.put("CPL-1", "1-2");
		customer_map.put("PPL-2", "1-1");
		customer_map.put("PPL-1", "1-2");
		customer_map.put("YARALTD-2", "1-1");
		customer_map.put("YARALTD-1", "1-2");
		customer_map.put("RAFECHL-1", "1-2");
		customer_map.put("IGSPL-1", "1-2");
		customer_map.put("GOAGLSF-1", "1-2");
		customer_map.put("MGRPL-1", "1-2");
		customer_map.put("PEFORCV-1", "1-2");
		customer_map.put("HMEL-6", "6-3");
		customer_map.put("HMEL-3", "3-2");
		customer_map.put("SOMANY-1", "1-2");
		customer_map.put("RATNAGI-2", "1-2");
		customer_map.put("SEMTEXP-1", "1-2");
		customer_map.put("ROCKMAN-1", "1-2");
		customer_map.put("NESTLIN-1", "1-2");
		customer_map.put("HINAGIL-1", "1-2");
		customer_map.put("BHEL-1", "1-2");
		customer_map.put("BHEL-2", "2-2");
		customer_map.put("CRMNDEL-1", "1-3");
		customer_map.put("GNFC-3", "2-2");
		customer_map.put("TASTELI-1", "1-2");
		customer_map.put("AMNS-5","1-3");
		customer_map.put("GLIL-5","1-2");
		customer_map.put("GLIL-6","2-2");
		customer_map.put("GLIL-7","3-2");
		
		
		trader_map.put("AMNS-2", "1-2");
		trader_map.put("SEMTIPL-1", "1-2");
		trader_map.put("MGRPL-2", "1-2");
		trader_map.put("EFSPL-2", "2-2");
		trader_map.put("DIL-1", "1-2");
		trader_map.put("BP-2", "1-3");
		trader_map.put("RIL-2", "1-3");
		
		transporter_map.put("GAIL-Haz", "Gail");
		transporter_map.put("D6Gadimoga", "Gail");
		transporter_map.put("PANKGA", "PipeInfra");
		transporter_map.put("PBHDGS", "PipeInfra");
		transporter_map.put("PLLD", "Gail");
		transporter_map.put("PMSKGA", "PipeInfra");
		transporter_map.put("PMSKP", "PipeInfra");
		transporter_map.put("PURCHASE-T", "Gail");
		transporter_map.put("PHUCBM", "RGPL");
		transporter_map.put("PIL-Haz", "PipeInfra");
		
		counterparty_map.put("AGL", "AVGL");
		counterparty_map.put("GRAINDU", "GRINDUS");
		counterparty_map.put("Gunvor", "GUNSPL");
		counterparty_map.put("LANCO", "LANCOKO");
		counterparty_map.put("MEIL", "MEGHHQX");
		counterparty_map.put("NFL-Nangal", "NFL");
		counterparty_map.put("ROCKMAN", "ROCKIND");
//		counterparty_map.put("SEMTIPL", "SEMTPL");
		counterparty_map.put("VWPL", "VIDUWIL");
		counterparty_map.put("SGS", "SGSINDIA");
		counterparty_map.put("HHFG DLNG", "HALHFGL");
		counterparty_map.put("SOMANY", "SOMANYL");
		counterparty_map.put("ESSARRM", "NEL");
		counterparty_map.put("AMNST", "AMNS");
		counterparty_map.put("AMNS-T", "AMNS");
		counterparty_map.put("ACER", "ACEGRAL");
		counterparty_map.put("PGPL", "PGPGPL");
		counterparty_map.put("VVF", "VVF India");
		counterparty_map.put("DERL", "DEEPENER");
		counterparty_map.put("KSFL", "KFL");
		
		meter_map.put("PLLD", "GAIL DAHEJ");
		meter_map.put("PURCHASE-T", "GAILHAZSEI");
		meter_map.put("GAIL-Haz", "GAIL HAZ");
		meter_map.put("PIL-Haz", "PIL HAZ");
		meter_map.put("PBHDGS", "PIL BHAD");
		meter_map.put("PANKGA", "PIL ANK");
		meter_map.put("PMSKGA", "PIL MSK");
		meter_map.put("D6Gadimoga", "GAIL HAZ");
		meter_map.put("PHUCBM", "RGPL SHAHD");
		meter_map.put("PMSKP", "PIL HAZ");
	}
	
	//jsp data structures
	{
		//Master Dictionary
		depend.put("FMS_ENTITY_ADDR_MST","FMS_ENTITY_REQ_DTL");
		depend.put("FMS_COUNTERPARTY_PLANT_DTL","FMS_ENTITY_REQ_DTL");
		depend.put("FMS_COUNTERPARTY_BU_DTL","FMS_ENTITY_REQ_DTL");
		depend.put("FMS_ENTITY_TURNOVER_DTL","FMS_ENTITY_REQ_DTL");
		depend.put("FMS_ENTITY_CONTACT_MST","FMS_ENTITY_REQ_DTL,FMS_ENTITY_ADDR_MST,FMS_COUNTERPARTY_PLANT_DTL");
		depend.put("FMS_METER_MST","FMS_ENTITY_REQ_DTL,FMS_COUNTERPARTY_PLANT_DTL");
		depend.put("FMS_COUNTERPARTY_PLANT_TAX","FMS_ENTITY_REQ_DTL,FMS_COUNTERPARTY_PLANT_DTL");
		depend.put("FMS_COUNTERPARTY_BU_TAX","FMS_ENTITY_REQ_DTL,FMS_COUNTERPARTY_BU_DTL");
		depend.put("FMS_ENTITY_TAX_STRUCT_DTL","FMS_ENTITY_REQ_DTL,FMS_COUNTERPARTY_PLANT_DTL");
		depend.put("FMS_ENTITY_SERVICE_TAX_DTL","FMS_ENTITY_REQ_DTL,FMS_COUNTERPARTY_PLANT_DTL");
		depend.put("FMS_ENTITY_BU_SVC_TAX_DTL","FMS_ENTITY_REQ_DTL,FMS_COUNTERPARTY_BU_DTL");

		//Purchase Dictionary
		depend.put("FMS_TRADER_CARGO_MST","FMS_TRADER_CN_MST");
		depend.put("FMS_SECURITY_DEAL_MAP(P)","FMS_TRADER_CN_MST");
		depend.put("FMS_SECURITY_MST(P)","FMS_TRADER_CN_MST");
//		depend.put("LOG_FMS_SECURITY_MST(P)","FMS_TRADER_CN_MST,FMS_SECURITY_MST(P)");
		depend.put("FMS_CONT_PRICE_DTL(P)","FMS_TRADER_CN_MST");
		depend.put("FMS_CONT_PRICE_MIN_DTL(P)","FMS_TRADER_CN_MST");
		depend.put("FMS_CARGO_SVC_CONT_SVC_BU","FMS_CARGO_SVC_CONT_MST");
		depend.put("FMS_BUY_CARGO_NOM","FMS_TRADER_CN_MST,FMS_TRADER_CARGO_MST,FMS_CARGO_SVC_CONT_MST"); //13-5,11
		depend.put("FMS_BUY_CARGO_NOM_BL","FMS_TRADER_CN_MST,FMS_TRADER_CARGO_MST,FMS_CARGO_SVC_CONT_MST,FMS_BUY_CARGO_NOM");
		depend.put("FMS_BUY_CARGO_NOM_BOE","FMS_TRADER_CN_MST,FMS_TRADER_CARGO_MST,FMS_CARGO_SVC_CONT_MST,FMS_BUY_CARGO_NOM");
		depend.put("FMS_BUY_CARGO_ALLOC","FMS_TRADER_CN_MST,FMS_TRADER_CARGO_MST");
		depend.put("FMS_BUY_CARGO_ALLOC_BL","FMS_TRADER_CN_MST,FMS_TRADER_CARGO_MST,FMS_BUY_CARGO_ALLOC");
		depend.put("FMS_BUY_CARGO_ALLOC_BOE","FMS_TRADER_CN_MST,FMS_TRADER_CARGO_MST,FMS_BUY_CARGO_ALLOC");
		depend.put("FMS_TRADER_CONT_BU", "FMS_TRADER_CONT_MST");
		depend.put("FMS_TRADER_CONT_SPLIT_PLANT", "FMS_TRADER_CONT_MST");
		depend.put("FMS_TRADER_CONT_PLANT", "FMS_TRADER_CONT_MST,FMS_TRADER_CONT_SPLIT_PLANT");
		depend.put("FMS_TRADER_BILLING_DTL", "FMS_TRADER_CONT_MST");
		depend.put("FMS_BUY_DAILY_BUYER_NOM", "FMS_TRADER_CONT_MST,FMS_TRADER_CONT_PLANT,FMS_TRADER_CONT_SPLIT_PLANT,FMS_TRADER_CONT_BU,FMS_TRADER_BILLING_DTL");
		depend.put("FMS_BUY_DAILY_SELLER_NOM", "FMS_TRADER_CONT_MST,FMS_TRADER_CONT_PLANT,FMS_TRADER_CONT_SPLIT_PLANT,FMS_TRADER_CONT_BU,FMS_TRADER_BILLING_DTL");
		depend.put("FMS_BUY_DAILY_ALLOCATION", "FMS_TRADER_CONT_MST,FMS_TRADER_CONT_PLANT,FMS_TRADER_CONT_SPLIT_PLANT,FMS_TRADER_CONT_BU,FMS_TRADER_BILLING_DTL");
		depend.put("FMS_BUY_DAILY_ALLOCATION_MM", "FMS_TRADER_CONT_MST,FMS_TRADER_CONT_PLANT,FMS_TRADER_CONT_SPLIT_PLANT,FMS_TRADER_CONT_BU,FMS_TRADER_BILLING_DTL");
		depend.put("FMS_TRADER_CONT_PLANT_CHRG", "FMS_TRADER_CONT_MST");
		depend.put("FMS_PUR_SG_INV_MST", "FMS_BUY_DAILY_ALLOCATION,FMS_BUY_CARGO_ALLOC_BOE");
		depend.put("FMS_CUSTOM_PD_BOND_DTL", "FMS_BUY_DAILY_ALLOCATION,FMS_BUY_CARGO_ALLOC_BOE");
		depend.put("FMS_PUR_PG_INV_MST_PURCHASE", "FMS_BUY_DAILY_ALLOCATION");


		//SALES DICTIONARY
		depend.put("FMS_AGMT_TRANSPTR", "FMS_AGMT_MST");
		depend.put("FMS_AGMT_PLANT", "FMS_AGMT_MST");
		depend.put("FMS_AGMT_BU", "FMS_AGMT_MST");
		depend.put("FMS_SUPPLY_AGMT_LIABILITY", "FMS_AGMT_MST");
		depend.put("FMS_AGMT_BILLING_DTL", "FMS_AGMT_MST");
		depend.put("FMS_AGMT_DEACTIVATION_DTL", "FMS_AGMT_MST");
		depend.put("FMS_SUPPLY_CONT_MST", "FMS_AGMT_MST");
		depend.put("FMS_SUPPLY_CONT_TRANSPTR", "FMS_SUPPLY_CONT_MST");
		depend.put("FMS_SUPPLY_CONT_PLANT", "FMS_SUPPLY_CONT_MST");
		depend.put("FMS_SUPPLY_CONT_BU", "FMS_SUPPLY_CONT_MST");
		depend.put("FMS_SUPPLY_CONT_LIABILITY", "FMS_SUPPLY_CONT_MST");
		depend.put("FMS_SUPPLY_BILLING_DTL", "FMS_SUPPLY_CONT_MST,FMS_SUPPLY_CONT_PLANT");	
		depend.put("FMS_CONT_PRICE_DTL(S)", "FMS_SUPPLY_CONT_MST");
		depend.put("FMS_CONT_PRICE_MIN_DTL(S)", "FMS_SUPPLY_CONT_MST");
		depend.put("FMS_SECURITY_DEAL_MAP(S)", "FMS_SUPPLY_CONT_MST");
		depend.put("FMS_SECURITY_MST(S)", "FMS_SUPPLY_CONT_MST");
//		depend.put("LOG_FMS_SECURITY_MST(S)", "FMS_SUPPLY_CONT_MST");
		depend.put("FMS_SUPPLY_CONT_DCQ_DTL", "FMS_SUPPLY_CONT_MST");
		depend.put("FMS_SUPPLY_CONT_PLANT_CHRG", "FMS_SUPPLY_CONT_MST,FMS_SUPPLY_CONT_TRANSPTR");
//		depend.put("LOG_SUPPLY_CONT_MST", "FMS_SUPPLY_CONT_MST");
		depend.put("FMS_SUPPLY_PURCHASE_MAP_DTL", "FMS_SUPPLY_CONT_MST,FMS_SUPPLY_CONT_PLANT,FMS_SUPPLY_CONT_BU");
		depend.put("FMS_SUPPLY_ALLOC_REVISED", "FMS_SUPPLY_CONT_MST,FMS_SUPPLY_CONT_PLANT,FMS_SUPPLY_CONT_BU");
		depend.put("FMS_DAILY_BUYER_NOM", "FMS_SUPPLY_CONT_MST,FMS_SUPPLY_CONT_PLANT,FMS_SUPPLY_CONT_BU,FMS_SUPPLY_PURCHASE_MAP_DTL,FMS_SUPPLY_ALLOC_REVISED");
		depend.put("FMS_DAILY_BUYER_NOM_DTL", "FMS_SUPPLY_CONT_MST,FMS_SUPPLY_CONT_PLANT,FMS_SUPPLY_CONT_BU,FMS_SUPPLY_PURCHASE_MAP_DTL,FMS_SUPPLY_ALLOC_REVISED");
		depend.put("FMS_DAILY_SELLER_NOM", "FMS_SUPPLY_CONT_MST,FMS_SUPPLY_CONT_PLANT,FMS_SUPPLY_CONT_BU,FMS_SUPPLY_PURCHASE_MAP_DTL,FMS_SUPPLY_ALLOC_REVISED");
		depend.put("FMS_DAILY_SELLER_NOM_DTL", "FMS_SUPPLY_CONT_MST,FMS_SUPPLY_CONT_PLANT,FMS_SUPPLY_CONT_BU,FMS_SUPPLY_PURCHASE_MAP_DTL,FMS_SUPPLY_ALLOC_REVISED");
		depend.put("FMS_METER_TICKET_READING", "FMS_SUPPLY_CONT_MST,FMS_SUPPLY_CONT_PLANT,FMS_SUPPLY_PURCHASE_MAP_DTL,FMS_SUPPLY_ALLOC_REVISED,FMS_DAILY_BUYER_NOM,FMS_DAILY_BUYER_NOM_DTL,FMS_DAILY_SELLER_NOM,FMS_DAILY_SELLER_NOM_DTL");
		depend.put("FMS_DAILY_ALLOCATION_DTL", "FMS_SUPPLY_CONT_MST,FMS_SUPPLY_CONT_BU,FMS_DAILY_BUYER_NOM,FMS_DAILY_BUYER_NOM_DTL,FMS_DAILY_SELLER_NOM,FMS_DAILY_SELLER_NOM_DTL");
		depend.put("FMS_DAILY_ALLOCATION_DTL_CT", "FMS_SUPPLY_CONT_MST,FMS_SUPPLY_CONT_BU,FMS_DAILY_BUYER_NOM,FMS_DAILY_BUYER_NOM_DTL,FMS_DAILY_SELLER_NOM,FMS_DAILY_SELLER_NOM_DTL");
		depend.put("FMS_INVOICE_MST", "FMS_SUPPLY_CONT_MST,FMS_SUPPLY_CONT_PLANT,FMS_SUPPLY_CONT_BU,FMS_SUPPLY_PURCHASE_MAP_DTL,FMS_SUPPLY_ALLOC_REVISED,FMS_DAILY_ALLOCATION_DTL");
		depend.put("FMS_INVOICE_DTL", "FMS_SUPPLY_CONT_MST,FMS_SUPPLY_CONT_PLANT,FMS_SUPPLY_CONT_BU,FMS_SUPPLY_PURCHASE_MAP_DTL,FMS_SUPPLY_ALLOC_REVISED,FMS_DAILY_ALLOCATION_DTL,FMS_INVOICE_MST");	
		
		// LTCORA
		depend.put("FMS_LTCORA_AGMT_TRANSPTR", "FMS_LTCORA_AGMT_MST");
		depend.put("FMS_LTCORA_AGMT_PLANT", "FMS_LTCORA_AGMT_MST");
		depend.put("FMS_LTCORA_AGMT_LIABILITY", "FMS_LTCORA_AGMT_MST");
		depend.put("FMS_LTCORA_AGMT_BILLING_DTL", "FMS_LTCORA_AGMT_MST");
		depend.put("FMS_LTCORA_CONT_MST", "FMS_LTCORA_AGMT_MST");
		depend.put("FMS_LTCORA_CONT_TRANSPTR", "FMS_LTCORA_CONT_MST");
		depend.put("FMS_LTCORA_CONT_PLANT", "FMS_LTCORA_CONT_MST");
		depend.put("FMS_LTCORA_CONT_LIABILITY", "FMS_LTCORA_CONT_MST");
		depend.put("FMS_LTCORA_CONT_BILLING_DTL", "FMS_LTCORA_CONT_MST");
		depend.put("FMS_LTCORA_CONT_CARGO_DTL", "FMS_LTCORA_CONT_MST");
		depend.put("FMS_LTCORA_CONT_STRG_CRG", "FMS_LTCORA_CONT_CARGO_DTL");
		depend.put("FMS_LTCORA_CONT_CARGO_ADQ", "FMS_LTCORA_CONT_CARGO_DTL");
		depend.put("FMS_LTCORA_CONT_CARGO_CSOC", "FMS_LTCORA_CONT_CARGO_DTL");
		depend.put("FMS_LTCORA_CONT_CARGO_MOD", "FMS_LTCORA_CONT_CARGO_DTL");
		
		//TRANSPORT DICTIONARY
		depend.put("FMS_GTA_ENTRY_POINT", "FMS_GTA_AGMT_MST");
		depend.put("FMS_GTA_EXIT_POINT", "FMS_GTA_AGMT_MST");
		depend.put("FMS_GTA_CONT_MST", "FMS_GTA_AGMT_MST,FMS_GTA_ENTRY_POINT,FMS_GTA_EXIT_POINT");
		depend.put("FMS_GTA_CONT_MAP", "FMS_GTA_AGMT_MST,FMS_GTA_ENTRY_POINT,FMS_GTA_EXIT_POINT,FMS_GTA_CONT_MST");
		depend.put("FMS_DAILY_TRANSPORTER_NOM", "FMS_GTA_AGMT_MST,FMS_GTA_ENTRY_POINT,FMS_GTA_EXIT_POINT,FMS_GTA_CONT_MST,FMS_GTA_CONT_MAP");
		depend.put("FMS_GTA_BILLING_DTL", "FMS_GTA_AGMT_MST,FMS_GTA_ENTRY_POINT,FMS_GTA_EXIT_POINT,FMS_GTA_CONT_MST,FMS_GTA_CONT_MAP");
		depend.put("FMS_DAILY_TRANSPORTER_SCH", "FMS_GTA_AGMT_MST,FMS_GTA_ENTRY_POINT,FMS_GTA_EXIT_POINT,FMS_GTA_CONT_MST,FMS_GTA_CONT_MAP,FMS_DAILY_TRANSPORTER_NOM");
		depend.put("FMS_DAILY_TRANSPORTER_ALLOC", "FMS_GTA_AGMT_MST,FMS_GTA_ENTRY_POINT,FMS_GTA_EXIT_POINT,FMS_GTA_CONT_MST,FMS_GTA_CONT_MAP,FMS_DAILY_TRANSPORTER_NOM,FMS_DAILY_TRANSPORTER_SCH");
		
		// Risk Mgmt Dictionary
		depend.put("FMS_TANK_INVENTORY_DTL", "FMS_TANK_MST");	
		
		// LTCORA
		depend.put("FMS_LTCORA_AGMT_TRANSPTR", "FMS_LTCORA_AGMT_MST");
		depend.put("FMS_LTCORA_AGMT_PLANT", "FMS_LTCORA_AGMT_MST");
		depend.put("FMS_LTCORA_AGMT_LIABILITY", "FMS_LTCORA_AGMT_MST");
		depend.put("FMS_LTCORA_AGMT_BILLING_DTL", "FMS_LTCORA_AGMT_MST");
		depend.put("FMS_LTCORA_CONT_MST", "FMS_LTCORA_AGMT_MST");
		depend.put("FMS_LTCORA_CONT_TRANSPTR", "FMS_LTCORA_CONT_MST");
		depend.put("FMS_LTCORA_CONT_PLANT", "FMS_LTCORA_CONT_MST");
		depend.put("FMS_LTCORA_CONT_LIABILITY", "FMS_LTCORA_CONT_MST");
		depend.put("FMS_LTCORA_CONT_BILLING_DTL", "FMS_LTCORA_CONT_MST");
		depend.put("FMS_LTCORA_CONT_STRG_CRG", "FMS_LTCORA_CONT_MST");
		depend.put("FMS_LTCORA_CONT_CARGO_DTL", "FMS_LTCORA_CONT_MST");
		depend.put("FMS_LTCORA_CONT_CARGO_ADQ", "FMS_LTCORA_CONT_CARGO_DTL");
		depend.put("FMS_LTCORA_CONT_CARGO_CSOC", "FMS_LTCORA_CONT_CARGO_DTL");
		depend.put("FMS_LTCORA_CONT_CARGO_MOD", "FMS_LTCORA_CONT_CARGO_DTL");
		
		//DLNG DICTIONARY
		depend.put("FMS_TRUCK_TRANS_CONTACT_MST", "FMS_TRUCK_TRANSPORTER_MST");
		depend.put("FMS_TRUCK_TRANSPORTER_LINK", "FMS_TRUCK_TRANSPORTER_MST,FMS_TRUCK_MST");
		depend.put("FMS_TRUCK_DRIVER_TRANS_LINK", "FMS_TRUCK_TRANSPORTER_MST,FMS_TRUCK_DRIVER_MST");
		depend.put("FMS_TRUCK_DRIVER_LINK", "FMS_TRUCK_TRANSPORTER_MST,FMS_TRUCK_DRIVER_MST,FMS_TRUCK_MST");
		depend.put("FMS_LINK_CHECKPOST_PLANT", "FMS_CHECKPOST_MST");
		depend.put("FMS_AGMT_FILLING_STN", "FMS_AGMT_MST(DLNG)");
		depend.put("FMS_AGMT_PLANT(DLNG)", "FMS_AGMT_MST(DLNG)");
		depend.put("FMS_AGMT_BILLING_DTL(DLNG)", "FMS_AGMT_MST(DLNG)");
		depend.put("FMS_AGMT_TRUCK_TRANS", "FMS_AGMT_MST(DLNG)");
		depend.put("FMS_SUPPLY_CONT_MST(DLNG)", "FMS_AGMT_MST(DLNG)");
		depend.put("FMS_SUPPLY_BILLING_DTL(DLNG)", "FMS_SUPPLY_CONT_MST(DLNG)");
		depend.put("FMS_SUPPLY_CONT_PLANT(DLNG)", "FMS_SUPPLY_CONT_MST(DLNG)");
		depend.put("FMS_SUPPLY_CONT_FILLING_STN", "FMS_SUPPLY_CONT_MST(DLNG)");
		depend.put("FMS_SUPPLY_CONT_TRUCK_TRANS", "FMS_SUPPLY_CONT_MST(DLNG)");
		depend.put("FMS_SECURITY_DEAL_MAP(DLNG),", "FMS_SUPPLY_CONT_MST(DLNG)");
		depend.put("FMS_SECURITY_MST(DLNG)", "FMS_SUPPLY_CONT_MST(DLNG)");
		depend.put("FMS_SUPPLY_CONT_DCQ_DTL(DLNG)", "FMS_SUPPLY_CONT_MST(DLNG)");
		depend.put("FMS_SUPPLY_PURCHASE_MAP_DTL(DLNG)", "FMS_SUPPLY_CONT_MST(DLNG),FMS_SUPPLY_CONT_PLANT(DLNG)");
		depend.put("FMS_SUPPLY_ALLOC_REVISED(DLNG)", "FMS_SUPPLY_CONT_MST(DLNG),FMS_SUPPLY_CONT_PLANT(DLNG)");
		depend.put("FMS_SVC_CONT_MST", "FMS_AGMT_SVC_MST");
		depend.put("FMS_SVC_CONT_MAP", "FMS_SVC_CONT_MST,FMS_SUPPLY_CONT_MST(DLNG)");
		depend.put("FMS_CONT_PRICE_DTL(DLNG)", "FMS_SUPPLY_CONT_MST(DLNG)");
		depend.put("FMS_CONT_PRICE_MIN_DTL(DLNG)", "FMS_SUPPLY_CONT_MST(DLNG)");
		
	}
}
