/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2026-04-06 05:03:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.market_005frisk;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Vector;
import com.etrm.fms.util.CommonVariable;
import com.etrm.fms.util.EncryptTest;

public final class rpt_005fvariable_005fprice_005finfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/market_risk/../util/common_js.jsp", Long.valueOf(1772512616937L));
    _jspx_dependants.put("/market_risk/../util/common_val.jsp", Long.valueOf(1747068186000L));
    _jspx_dependants.put("/market_risk/../home/loading.jsp", Long.valueOf(1747068184000L));
    _jspx_dependants.put("/market_risk/../util/../sess/Expire.jsp", Long.valueOf(1754630867476L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("com.etrm.fms.util.CommonVariable");
    _jspx_imports_classes.add("com.etrm.fms.util.EncryptTest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n");
      out.write('\n');

String expire_msg = request.getParameter("expire_msg")==null?"":request.getParameter("expire_msg");
if(session.getAttribute("emp_uid")==null || session.getAttribute("emp_uid") == ""|| session.getAttribute("emp_uid").toString().equals("null"))
{
      out.write("\r\n		<script>\r\n			alert(\"Please Enter Login Detail!\")\r\n			var url = \"../home/login.jsp\";\r\n			location.replace(url);\r\n		</script>\r\n");
}
else
{
	if(expire_msg.equals("Timeout"))
	{
		session.invalidate();
	
      out.write("\r\n		<script>\r\n		var url = \"../home/login.jsp?sess=Session Expired\";\r\n		location.replace(url);\r\n		</script>\r\n	");

	}
	else if(expire_msg.equals("PwdChng"))
	{
		session.invalidate();
	
      out.write("\r\n		<script>\r\n		var url = \"../home/login.jsp\";\r\n		location.replace(url);\r\n		</script>\r\n	");
}
}

      out.write("\r\n\r\n");
      out.write('\n');
String COMMlogo="";
if(session.getAttribute("comp_logo")==null||session.getAttribute("comp_logo")==""||session.getAttribute("comp_logo").toString().equals("null"))
{
	COMMlogo="";
}  
else
{
	COMMlogo=""+session.getAttribute("comp_logo");
}

String sel_comp_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	sel_comp_cd="";
}  
else
{
	sel_comp_cd=""+session.getAttribute("comp_cd");
}
String wmk_comp_abbr="";
if(session.getAttribute("comp_abbr")==null||session.getAttribute("comp_abbr")==""||session.getAttribute("comp_abbr").toString().equals("null"))
{
	wmk_comp_abbr="";
}  
else
{
	wmk_comp_abbr=""+session.getAttribute("comp_abbr");
}

      out.write("\n<link rel=\"SHORTCUT ICON\" href=\"../images/");
      out.print(COMMlogo);
      out.write("\">\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<meta http-equiv=\"refresh\" content=\"");
      out.print(session.getMaxInactiveInterval());
      out.write(";url=../sess/Expire.jsp?expire_msg=Timeout\"/>\n<title>");
      out.print(CommonVariable.app_name);
      out.write("</title>\n\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap/bootstrap5/css/bootstrap.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../font-awesome-4.7.0/css/font-awesome.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/datepicker/bootstrap-datepicker3.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/util.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/main.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/navbar.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/responsive.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">\n\n");
 if ("2".equals(sel_comp_cd)) { 
      out.write("\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common_2.css\">  <!-- CSS for comp_cd = \"2\" -->\n");
 } else { 
      out.write("\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">  <!-- CSS for comp_cd = \"1\" -->\n");
 } 
      out.write("\n\n<script type=\"text/javascript\" src=\"../js/jquery.min.js\"></script>\n<script type=\"text/javascript\" src=\"../bootstrap/bootstrap5/js/bootstrap.bundle.min.js\"></script>\n<script type=\"text/javascript\" src=\"../js/datepicker/bootstrap-datepicker.min.js\"></script>\n<script type=\"text/javascript\" src=\"../js/datepicker/bootstrap-datepicker.es.min.js\"></script>\n\n<!-- HM20251210 : Bootstrap Searchable Select -->\n<link href=\"../css/serchable_select.css\" rel=\"stylesheet\" />\n<script src=\"../js/searchable_select.js\"></script>\n\n<script type=\"text/javascript\" src=\"../js/util.js\"></script>\n<script type=\"text/javascript\" src=\"../js/tableUtil.js\"></script>\n");
      out.write("\n<script type=\"text/javascript\" src=\"../js/session.js\"></script>\n\n");
      out.write('\n');
      com.etrm.fms.util.DataBean_Menu menu_access = null;
      menu_access = (com.etrm.fms.util.DataBean_Menu) _jspx_page_context.getAttribute("menu_access", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (menu_access == null){
        menu_access = new com.etrm.fms.util.DataBean_Menu();
        _jspx_page_context.setAttribute("menu_access", menu_access, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');

String formCd="";
String mod_cd="";
String u=request.getParameter("u")==null?"":request.getParameter("u");

String msg=request.getParameter("msg")==null?"":request.getParameter("msg");
String msg_type=request.getParameter("msg_type")==null?"":request.getParameter("msg_type");

String owner_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	owner_cd="";
}  
else
{
	owner_cd=""+session.getAttribute("comp_cd");
}

String owner_abbr="";
if(session.getAttribute("comp_abbr")==null||session.getAttribute("comp_abbr")==""||session.getAttribute("comp_abbr").toString().equals("null"))
{
	owner_abbr="";
}  
else
{
	owner_abbr=""+session.getAttribute("comp_abbr");
}

String emp_cd="";
if(session.getAttribute("emp_cd")==null||session.getAttribute("emp_cd")==""||session.getAttribute("emp_cd").toString().equals("null"))
{
	emp_cd="";
}  
else
{
	emp_cd=""+session.getAttribute("emp_cd");
}

if(!u.equals(""))
{
	StringBuffer decryt=new EncryptTest().URLdecrypt(u);
	String dec=""+decryt;
	if(!dec.equals("") && dec.contains("-"))
	{
		String temp[]=dec.split("-");
		if(temp.length==2)
		{
			formCd=temp[0];
			mod_cd=temp[1];
		}
	}
}

menu_access.setCallFlag("MENU_ACCESS");
menu_access.setEmpCd(emp_cd);
menu_access.setComp_cd(owner_cd);
menu_access.setModule_cd(mod_cd);
menu_access.setForm_cd(formCd);
menu_access.init();


String formNm = menu_access.getForm_nm();
String mod_nm = menu_access.getModule_nm();
String read_access = menu_access.getRead_access();
String write_access = menu_access.getWrite_access();
String check_access = menu_access.getCheck_access();
String print_access = menu_access.getPrint_access();
String delete_access = menu_access.getDelete_access();
String audit_access = menu_access.getAudit_access();
String authorize_access = menu_access.getAuthorize_access();
String approve_access = menu_access.getApprove_access();
String execute_access = menu_access.getExecute_access();


      out.write("\n\n<script type=\"text/javascript\">\ndocument.title = \"");
      out.print(CommonVariable.app_name);
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(owner_abbr);
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(formNm);
      out.write("\";\n</script>\n<script>\n$(function () {\n    function initSelect2(container) {\n        $(container).find('.searchable-select').each(function () {\n            if (!$(this).data('select2')) {\n                $(this).select2({\n                    theme: 'bootstrap-5',\n                    width: '100%',\n                    minimumResultsForSearch: 0,\n                    dropdownParent: $(this).closest('.modal').length \n                        ? $(this).closest('.modal') \n                        : $('body')\n                });\n            }\n        });\n    }\n\n    // Initialize non-modal selects\n    initSelect2(document);\n\n    // Initialize selects when ANY modal opens\n    $(document).on('shown.bs.modal', function (e) {\n        initSelect2(e.target);\n    });\n});\n</script>\n\n\n<!-- TAB Counter -->\n<script>\n(function() {\n    // Always generate a unique tabId for this tab (even if duplicated)\n    const tabId = 'tab_' + crypto.randomUUID();\n    sessionStorage.setItem('tabId', tabId);\n\n    const servletURL = '");
      out.print(request.getContextPath());
      out.write("/TabTrackerServlet';\n\n    // Notify server that tab is opened\n    fetch(servletURL, {\n        method: 'POST',\n        body: new URLSearchParams({ action: 'open', tabId: tabId })\n    })\n    .then(res => res.json())\n    .then(data => {\n        const tabCountElem = document.getElementById('tabCount');\n        if (tabCountElem) tabCountElem.innerText = data.tabCount;\n    });\n\n    // Notify server when tab closes\n    window.addEventListener('beforeunload', () => {\n        navigator.sendBeacon(servletURL, new URLSearchParams({ action: 'close', tabId: tabId }));\n    });\n\n})();\n</script>\n<script>\n//HM20260213:Added this Script to handle In-Active/E-Rate Counterparty actions restriction accross system\n//Global variable to track Counterparty status and allow or block edit\nvar editAllowedOnCpStatus= true;\nvar max_eff_dt  = \"\";\nvar enableButton = false;\n\nfunction fetchCounterpartyDetails()\n{\n	// Check if form exists\n    if (!document.forms || document.forms.length === 0) {\n        return;\n    }\n    var form = document.forms[0];\n");
      out.write("    // Check if counterparty_cd field exists in form\n    if (!form.counterparty_cd) {\n        return;\n    }\n\n	var counterparty_cd = document.forms[0].counterparty_cd.value;\n	if(counterparty_cd != \"\" && counterparty_cd!=\"0\")\n	{\n		$.post(\"../servlet/DBCounterpartyInfo?counterparty_cd=\" + counterparty_cd + \"&setCallType=fetchCounterpartyDetails\",\n		function(responseJson) \n		{\n			if (responseJson.length > 0) \n			{\n				var counterpartyInfo = responseJson[0].COUNTERPARTY_INFO;\n				if (counterpartyInfo.length > 0) \n				{\n					var status = counterpartyInfo[0].STATUS;\n					max_eff_dt = counterpartyInfo[0].EFF_DT;\n					\n					if(status == \"N\")//HM20260217: Removed as per Vijay feedback only for deacive CP edit is disabled || status == \"E\"\n					{\n						editAllowedOnCpStatus = false;\n					} else {\n						editAllowedOnCpStatus = true;\n					}\n					\n					// Gettinh today's system date (without time)\n					var today = new Date();\n					today.setHours(0,0,0,0);\n\n					var isFutureEffective = false;\n					if (max_eff_dt && max_eff_dt !== \"\") {\n");
      out.write("\n						// Split DD/MM/YYYY\n						var parts = max_eff_dt.split(\"/\");\n\n						var day   = parseInt(parts[0], 10);\n						var month = parseInt(parts[1], 10) - 1;\n						var year  = parseInt(parts[2], 10);\n\n						var effDate = new Date(year, month, day);\n						effDate.setHours(0,0,0,0);\n\n						if (effDate > today) {\n							isFutureEffective = true;\n						}\n					}\n					\n					if (editAllowedOnCpStatus === false && !isFutureEffective) {\n						//disableAllInputs();\n						if(!enableButton)\n						{\n							disableSubmitButtons();\n						}\n					}\n					\n					var alertHtml = \"\";\n					if(status == \"N\")\n					{\n						alertHtml = \n						'<div class=\"row m-b-5 dynamic-alert\" >' +\n							'<div class=\"col-sm-3 col-xs-3 col-md-3\"></div>' +\n							'<div class=\"col-sm-6 col-xs-6 col-md-6\">' +\n								'<div class=\"form-group row\">' +\n									'<div class=\"col-sm-12 col-xs-12 col-md-12\">' +\n										'<div class=\"container\">' +\n											'<div class=\"alert alert-danger\">' +\n												'<i class=\"fa fa-exclamation-triangle fa-lg\"></i>&nbsp;' +\n");
      out.write("												'<b>Counterparty Status : Deactive (Effective from : '+ max_eff_dt +')</b>' +\n											'</div>' +\n										'</div>' +\n									'</div>' +\n								'</div>' +\n							'</div>' +\n						'</div>';\n					}\n					else if(status == \"E\")\n					{\n						alertHtml = \n						'<div class=\"row m-b-5 dynamic-alert\" >' +\n							'<div class=\"col-sm-3 col-xs-3 col-md-3\"></div>' +\n							'<div class=\"col-sm-6 col-xs-6 col-md-6\">' +\n								'<div class=\"form-group row\">' +\n									'<div class=\"col-sm-12 col-xs-12 col-md-12\">' +\n										'<div class=\"container\">' +\n											'<div class=\"alert alert-warning\">' +\n												'<i class=\"fa fa-exclamation-triangle fa-lg\"></i>&nbsp;' +\n												'<b>Counterparty Status : E-Rate (Effective from : '+ max_eff_dt +')</b>' +\n											'</div>' +\n										'</div>' +\n									'</div>' +\n								'</div>' +\n							'</div>' +\n						'</div>';\n					}\n					// Remove old alert if already added\n					$(\".dynamic-alert\").remove();\n\n					// Insert INSIDE as first element\n					$(\".card-body.cdbody\").first().prepend(alertHtml);\n");
      out.write("				}\n			}\n		});\n	}\n}\n$(document).ready(function() {\n    fetchCounterpartyDetails();\n});\n\nfunction disableSubmitButtons() {\n   $(\"input[type='button'][value='Submit']\")\n    .prop(\"disabled\", true);\n}\n\n/* function disableAllInputs() {\n    var form = document.forms[0];\n    if (!form) return;\n\n    $(form).find(\"input, select, textarea\").each(function () {\n\n        // Skip hidden fields\n        if (this.tagName.toLowerCase() === \"input\" && this.type === \"hidden\") {\n            return;\n        }\n\n        // Skip buttons (button, submit, reset)\n        if (this.tagName.toLowerCase() === \"input\" && \n            (this.type === \"button\" || this.type === \"submit\" || this.type === \"reset\")) {\n            return;\n        }\n\n        // Skip <button> elements\n        if (this.tagName.toLowerCase() === \"button\") {\n            return;\n        }\n\n        this.disabled = true;\n    });\n} */\n\n\n//Override the native submit function\n(function() {\n	const originalSubmit = HTMLFormElement.prototype.submit;\n	HTMLFormElement.prototype.submit = function() {\n");
      out.write("		\n		// Gettinh today's system date (without time)\n		var today = new Date();\n		today.setHours(0,0,0,0);\n\n		var isFutureEffective = false;\n		if (max_eff_dt && max_eff_dt !== \"\") {\n\n			// Split DD/MM/YYYY\n			var parts = max_eff_dt.split(\"/\");\n\n			var day   = parseInt(parts[0], 10);\n			var month = parseInt(parts[1], 10) - 1;\n			var year  = parseInt(parts[2], 10);\n\n			var effDate = new Date(year, month, day);\n			effDate.setHours(0,0,0,0);\n\n			if (effDate > today) {\n				isFutureEffective = true;\n			}\n		}\n		\n		if(!editAllowedOnCpStatus && !isFutureEffective) \n		{\n			alert(\"Submission Blocked! Counterparty Status must be Active!!\");\n			document.getElementById(\"loading\").style.visibility = \"hidden\";\n			return false; // block submission\n		} \n		else\n		{\n			return originalSubmit.apply(this, arguments); // allow submission\n		}\n	};\n})();\n\n</script>\n\n<!-- Watermark CSS -->\n<style type=\"text/css\">\n    /* Apply the watermark globally on the body */\n    body {\n        position: relative;\n        height: 100vh; /* Ensuring here that body takes the full viewport height */\n");
      out.write("        margin: 0; /* Remove default margin */\n    }\n\n    body::after {\n        content: \"");
      out.print(wmk_comp_abbr);
      out.write("\";  /* Watermark text */\n        font-size: 10vw; /* This is used for viewport width for scalability */\n        /*color: var(--header_color); */        /* Header color */\n    	color: rgba(0, 0, 0, 0.1);\n    	opacity: 0.4;                       /* 40% opacity to watermark */\n    	position: fixed;  /* Make it fixed so it stays in place */\n        top: 50%;  /* Center vertically */\n        left: 50%;  /* Center horizontally */\n        transform: translate(-50%, -50%) rotate(-45deg); /* Center it properly and rotate */\n        pointer-events: none;  /* Make sure it doesn't block any interactions */\n        z-index: 9999;  /* Make sure it's on top */\n        white-space: nowrap;\n        transform-origin: center;\n    }\n\n    /* Make the watermark size smaller on mobile devices */\n    @media screen and (max-width: 767px) {\n        body::after {\n            font-size: 20vw; /* Larger watermark on small screens */\n        }\n    }\n\n    /* Adjust watermark for tablets or medium devices */\n    @media screen and (max-width: 1024px) and (min-width: 768px) {\n");
      out.write("        body::after {\n            font-size: 15vw; /* Moderate size for tablet screens */\n        }\n    }\n    \n    /* Adjust watermark for larger screens (Desktops) */\n    @media screen and (min-width: 1025px) {\n        body::after {\n            font-size: 10vw; /* Default size for desktops */\n        }\n    }\n</style>");
      out.write("\r\n<script>\r\n</script>\r\n</head>\r\n");
      com.etrm.fms.market_risk.DataBean_VariablePricing market_risk = null;
      market_risk = (com.etrm.fms.market_risk.DataBean_VariablePricing) _jspx_page_context.getAttribute("market_risk", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (market_risk == null){
        market_risk = new com.etrm.fms.market_risk.DataBean_VariablePricing();
        _jspx_page_context.setAttribute("market_risk", market_risk, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.etrm.fms.util.MessageUtil utilmsg = null;
      utilmsg = (com.etrm.fms.util.MessageUtil) _jspx_page_context.getAttribute("utilmsg", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (utilmsg == null){
        utilmsg = new com.etrm.fms.util.MessageUtil();
        _jspx_page_context.setAttribute("utilmsg", utilmsg, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.etrm.fms.util.DateUtil utildate = null;
      utildate = (com.etrm.fms.util.DateUtil) _jspx_page_context.getAttribute("utildate", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (utildate == null){
        utildate = new com.etrm.fms.util.DateUtil();
        _jspx_page_context.setAttribute("utildate", utildate, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');

String sysdate = utildate.getSysdate();

String counterparty_cd = request.getParameter("counterparty_cd")==null?"0":request.getParameter("counterparty_cd");
String agmt_no = request.getParameter("agmt_no")==null?"":request.getParameter("agmt_no");
String agmt_rev_no = request.getParameter("agmt_rev_no")==null?"":request.getParameter("agmt_rev_no");
String cont_no = request.getParameter("cont_no")==null?"":request.getParameter("cont_no");
String cont_rev_no = request.getParameter("cont_rev_no")==null?"":request.getParameter("cont_rev_no");
String contract_type=request.getParameter("contract_type")==null?"":request.getParameter("contract_type");
String cont_start_dt = request.getParameter("start_dt")==null?"":request.getParameter("start_dt");
String cont_end_dt=request.getParameter("end_dt")==null?"":request.getParameter("end_dt");
String cont_ref=request.getParameter("cont_ref")==null?"":request.getParameter("cont_ref");
String cont_status=request.getParameter("cont_status")==null?"":request.getParameter("cont_status");
String cargo_no=request.getParameter("cargo_no")==null?"":request.getParameter("cargo_no");
String cn_contract_status=request.getParameter("cn_contract_status")==null?"":request.getParameter("cn_contract_status");

String contract_no ="";
if(contract_type.equalsIgnoreCase("S"))
{
	contract_no = contract_type+""+agmt_no+"-"+cont_no+"-"+cargo_no;
}
else if(contract_type.equalsIgnoreCase("S"))
{
	contract_no = contract_type+""+agmt_no+"-"+cont_no;
}
else
{
	contract_no = contract_type+""+cont_no;
}


String mapping_id=counterparty_cd+"-"+agmt_no+"-"+cont_no;
if(contract_type.equals("N"))
{
	mapping_id+="-"+cargo_no;
}

market_risk.setCallFlag("VARIABLE_PRICE_INFO");
market_risk.setCounterparty_cd(counterparty_cd);
market_risk.setComp_cd(owner_cd);
market_risk.setAgmt_no(agmt_no);
market_risk.setAgmt_rev_no(agmt_rev_no);
market_risk.setCont_no(cont_no);
market_risk.setCont_rev_no(cont_rev_no);
market_risk.setContract_type(contract_type);
market_risk.setCargo_no(cargo_no);
market_risk.setMapping_id(mapping_id);
market_risk.setStart_dt(cont_start_dt);
market_risk.setEnd_dt(cont_end_dt);
market_risk.init();

String counterparty_abbr=market_risk.getCounterparty_abbr();
String display_map_id = market_risk.getDisplay_map_id();

Vector VDELVH_MONTH = market_risk.getVDELVH_MONTH();
Vector VDURATION = market_risk.getVDURATION();
Vector VCURVE_NM = market_risk.getVCURVE_NM();
Vector VSETTLE_PRICE = market_risk.getVSETTLE_PRICE();
Vector VPRICE_TYPE = market_risk.getVPRICE_TYPE();
Vector VEFF_PRICE = market_risk.getVEFF_PRICE();
Vector VPREM_DISC_RATE = market_risk.getVPREM_DISC_RATE();
Vector VFINAL_PRICE = market_risk.getVFINAL_PRICE();
Vector VPRICE_DECI = market_risk.getVPRICE_DECI();
Vector VFINAL_PRICE_DECI = market_risk.getVFINAL_PRICE_DECI();

      out.write("\r\n<body>\r\n");
      out.write("<div id=\"loading\" style=\"visibility: hidden;\">\n	<div id=\"loading-image\">\n		<div class=\"btn-group\">\n			<label class=\"btn\" style=\"color:var(--header_color);border:none;font-size:20px;align-self: center;font-weight:bold;\">\n				<i class=\"fa fa-spinner fa-pulse fa-lg\"></i>&nbsp;Loading\n			</label>\n		</div>\n	</div>\n</div>");
      out.write("\r\n<form method=\"post\" action=\"\">\r\n\r\n<div class=\"box-body\">\r\n	<div class=\"row\">\r\n		<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n			");
if(!msg.equals("")){
				if(msg_type.equals("S")){
      out.write("\r\n					<div class=\"fadealert\">");
      out.print(utilmsg.successMessage(msg));
      out.write("</div>\r\n				");
}else if(msg_type.equals("E")){
      out.write("\r\n					<div class=\"fadealert\">");
      out.print( utilmsg.errorMessage(msg));
      out.write("</div>\r\n				");
}
			} 
      out.write("\r\n			<div class=\"card cardmain\">\r\n				<div class=\"card-header cdheader\">\r\n					<div class=\"d-flex justify-content-between\">\r\n					    <div class=\"topheader\">\r\n					    	Price Detail ");
      out.print(counterparty_abbr);
      out.write(' ');
      out.write('(');
      out.print(display_map_id);
      out.write(") [Contract Period : ");
      out.print(cont_start_dt );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(cont_end_dt );
      out.write("] as on ");
      out.print(sysdate );
      out.write("\r\n					    </div>\r\n					</div>\r\n				</div>\r\n				<div class=\"card-body cdbody\">\r\n					<div class=\"row\">\r\n						<div class=\"table-responsive\">\r\n							<table class=\"table table-bordered table-hover\" id=\"example\">\r\n								<thead>\r\n									<tr>\r\n										<th>Delivery Month</th>										\r\n										<th>Price Type</th>										\r\n										<th>Duration</th>\r\n										<th>Curve Name</th>\r\n										<!-- <th>Settle Price</th>\r\n										<th>Eff. Price</th>	 -->									\r\n										<!-- <th>Premium(+)/Discount(-)</th>	 -->									\r\n										<th>Final Eff. Price</th>										\r\n										<!-- <th>Settle Price/Mth Logic</th>\r\n										<th>Slope</th>\r\n										<th>Constant</th>\r\n										<th>Physical Curve</th>\r\n										<th>Price Formula</th>\r\n										<th>Remark</th> -->\r\n									</tr>\r\n								</thead>\r\n								<tbody>\r\n									");
if(VDELVH_MONTH.size()>0){
      out.write("\r\n										");
for(int i=0;i<VDELVH_MONTH.size();i++){
      out.write("\r\n											<tr>\r\n												<td align=\"center\">");
      out.print(VDELVH_MONTH.elementAt(i) );
      out.write("</td>\r\n												<td align=\"center\">");
      out.print(VPRICE_TYPE.elementAt(i) );
      out.write("</td>\r\n												<td align=\"center\">");
      out.print(VDURATION.elementAt(i) );
      out.write("</td>\r\n												<td align=\"center\">");
      out.print(VCURVE_NM.elementAt(i) );
      out.write("</td>\r\n												");
      out.write("\r\n		 										");
      out.write("\r\n												<td align=\"right\" title=\"");
      out.print(VFINAL_PRICE_DECI.elementAt(i));
      out.write(" decimal places\">");
      out.print(VFINAL_PRICE.elementAt(i) );
      out.write("</td>\r\n												<!--<td></td>\r\n												<td></td>\r\n												<td></td>\r\n												<td></td> -->\r\n											</tr>\r\n										");
}
      out.write("\r\n									");
}else{
      out.write("\r\n										<tr>\r\n											<td colspan=\"8\">\r\n												<div align=\"center\">");
      out.print(utilmsg.infoMessage("<b>No Price Line Configured!</b>"));
      out.write("</div>\r\n											</td>\r\n										</tr>	\r\n									");
} 
      out.write("\r\n								</tbody>\r\n							</table>\r\n						</div>\r\n					</div>\r\n				</div>\r\n			</div>\r\n		</div>\r\n	</div>\r\n</div>\r\n</body>\r\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
