/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2026-03-03 05:56:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.contract_005fmaster;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Vector;
import com.etrm.fms.util.CommonVariable;
import com.etrm.fms.util.EncryptTest;

public final class frm_005fcont_005fliability_005fdtl_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/contract_master/../util/common_js.jsp", Long.valueOf(1772512616937L));
    _jspx_dependants.put("/contract_master/../util/../sess/Expire.jsp", Long.valueOf(1754630867476L));
    _jspx_dependants.put("/contract_master/../util/common_val.jsp", Long.valueOf(1747068186000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("com.etrm.fms.util.CommonVariable");
    _jspx_imports_classes.add("com.etrm.fms.util.EncryptTest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n<html>\n<head>\n");
      out.write('\n');

String expire_msg = request.getParameter("expire_msg")==null?"":request.getParameter("expire_msg");
if(session.getAttribute("emp_uid")==null || session.getAttribute("emp_uid") == ""|| session.getAttribute("emp_uid").toString().equals("null"))
{
      out.write("\r\n		<script>\r\n			alert(\"Please Enter Login Detail!\")\r\n			var url = \"../home/login.jsp\";\r\n			location.replace(url);\r\n		</script>\r\n");
}
else
{
	if(expire_msg.equals("Timeout"))
	{
		session.invalidate();
	
      out.write("\r\n		<script>\r\n		var url = \"../home/login.jsp?sess=Session Expired\";\r\n		location.replace(url);\r\n		</script>\r\n	");

	}
	else if(expire_msg.equals("PwdChng"))
	{
		session.invalidate();
	
      out.write("\r\n		<script>\r\n		var url = \"../home/login.jsp\";\r\n		location.replace(url);\r\n		</script>\r\n	");
}
}

      out.write("\r\n\r\n");
      out.write('\n');
String COMMlogo="";
if(session.getAttribute("comp_logo")==null||session.getAttribute("comp_logo")==""||session.getAttribute("comp_logo").toString().equals("null"))
{
	COMMlogo="";
}  
else
{
	COMMlogo=""+session.getAttribute("comp_logo");
}

String sel_comp_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	sel_comp_cd="";
}  
else
{
	sel_comp_cd=""+session.getAttribute("comp_cd");
}
String wmk_comp_abbr="";
if(session.getAttribute("comp_abbr")==null||session.getAttribute("comp_abbr")==""||session.getAttribute("comp_abbr").toString().equals("null"))
{
	wmk_comp_abbr="";
}  
else
{
	wmk_comp_abbr=""+session.getAttribute("comp_abbr");
}

      out.write("\n<link rel=\"SHORTCUT ICON\" href=\"../images/");
      out.print(COMMlogo);
      out.write("\">\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<meta http-equiv=\"refresh\" content=\"");
      out.print(session.getMaxInactiveInterval());
      out.write(";url=../sess/Expire.jsp?expire_msg=Timeout\"/>\n<title>");
      out.print(CommonVariable.app_name);
      out.write("</title>\n\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap/bootstrap5/css/bootstrap.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../font-awesome-4.7.0/css/font-awesome.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/datepicker/bootstrap-datepicker3.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/util.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/main.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/navbar.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/responsive.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">\n\n");
 if ("2".equals(sel_comp_cd)) { 
      out.write("\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common_2.css\">  <!-- CSS for comp_cd = \"2\" -->\n");
 } else { 
      out.write("\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">  <!-- CSS for comp_cd = \"1\" -->\n");
 } 
      out.write("\n\n<script type=\"text/javascript\" src=\"../js/jquery.min.js\"></script>\n<script type=\"text/javascript\" src=\"../bootstrap/bootstrap5/js/bootstrap.bundle.min.js\"></script>\n<script type=\"text/javascript\" src=\"../js/datepicker/bootstrap-datepicker.min.js\"></script>\n<script type=\"text/javascript\" src=\"../js/datepicker/bootstrap-datepicker.es.min.js\"></script>\n\n<!-- HM20251210 : Bootstrap Searchable Select -->\n<link href=\"../css/serchable_select.css\" rel=\"stylesheet\" />\n<script src=\"../js/searchable_select.js\"></script>\n\n<script type=\"text/javascript\" src=\"../js/util.js\"></script>\n<script type=\"text/javascript\" src=\"../js/tableUtil.js\"></script>\n");
      out.write("\n<script type=\"text/javascript\" src=\"../js/session.js\"></script>\n\n");
      out.write('\n');
      com.etrm.fms.util.DataBean_Menu menu_access = null;
      menu_access = (com.etrm.fms.util.DataBean_Menu) _jspx_page_context.getAttribute("menu_access", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (menu_access == null){
        menu_access = new com.etrm.fms.util.DataBean_Menu();
        _jspx_page_context.setAttribute("menu_access", menu_access, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');

String formCd="";
String mod_cd="";
String u=request.getParameter("u")==null?"":request.getParameter("u");

String msg=request.getParameter("msg")==null?"":request.getParameter("msg");
String msg_type=request.getParameter("msg_type")==null?"":request.getParameter("msg_type");

String owner_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	owner_cd="";
}  
else
{
	owner_cd=""+session.getAttribute("comp_cd");
}

String owner_abbr="";
if(session.getAttribute("comp_abbr")==null||session.getAttribute("comp_abbr")==""||session.getAttribute("comp_abbr").toString().equals("null"))
{
	owner_abbr="";
}  
else
{
	owner_abbr=""+session.getAttribute("comp_abbr");
}

String emp_cd="";
if(session.getAttribute("emp_cd")==null||session.getAttribute("emp_cd")==""||session.getAttribute("emp_cd").toString().equals("null"))
{
	emp_cd="";
}  
else
{
	emp_cd=""+session.getAttribute("emp_cd");
}

if(!u.equals(""))
{
	StringBuffer decryt=new EncryptTest().URLdecrypt(u);
	String dec=""+decryt;
	if(!dec.equals("") && dec.contains("-"))
	{
		String temp[]=dec.split("-");
		if(temp.length==2)
		{
			formCd=temp[0];
			mod_cd=temp[1];
		}
	}
}

menu_access.setCallFlag("MENU_ACCESS");
menu_access.setEmpCd(emp_cd);
menu_access.setComp_cd(owner_cd);
menu_access.setModule_cd(mod_cd);
menu_access.setForm_cd(formCd);
menu_access.init();


String formNm = menu_access.getForm_nm();
String mod_nm = menu_access.getModule_nm();
String read_access = menu_access.getRead_access();
String write_access = menu_access.getWrite_access();
String check_access = menu_access.getCheck_access();
String print_access = menu_access.getPrint_access();
String delete_access = menu_access.getDelete_access();
String audit_access = menu_access.getAudit_access();
String authorize_access = menu_access.getAuthorize_access();
String approve_access = menu_access.getApprove_access();
String execute_access = menu_access.getExecute_access();


      out.write("\n\n<script type=\"text/javascript\">\ndocument.title = \"");
      out.print(CommonVariable.app_name);
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(owner_abbr);
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(formNm);
      out.write("\";\n</script>\n<script>\n$(function () {\n    function initSelect2(container) {\n        $(container).find('.searchable-select').each(function () {\n            if (!$(this).data('select2')) {\n                $(this).select2({\n                    theme: 'bootstrap-5',\n                    width: '100%',\n                    minimumResultsForSearch: 0,\n                    dropdownParent: $(this).closest('.modal').length \n                        ? $(this).closest('.modal') \n                        : $('body')\n                });\n            }\n        });\n    }\n\n    // Initialize non-modal selects\n    initSelect2(document);\n\n    // Initialize selects when ANY modal opens\n    $(document).on('shown.bs.modal', function (e) {\n        initSelect2(e.target);\n    });\n});\n</script>\n\n\n<!-- TAB Counter -->\n<script>\n(function() {\n    // Always generate a unique tabId for this tab (even if duplicated)\n    const tabId = 'tab_' + crypto.randomUUID();\n    sessionStorage.setItem('tabId', tabId);\n\n    const servletURL = '");
      out.print(request.getContextPath());
      out.write("/TabTrackerServlet';\n\n    // Notify server that tab is opened\n    fetch(servletURL, {\n        method: 'POST',\n        body: new URLSearchParams({ action: 'open', tabId: tabId })\n    })\n    .then(res => res.json())\n    .then(data => {\n        const tabCountElem = document.getElementById('tabCount');\n        if (tabCountElem) tabCountElem.innerText = data.tabCount;\n    });\n\n    // Notify server when tab closes\n    window.addEventListener('beforeunload', () => {\n        navigator.sendBeacon(servletURL, new URLSearchParams({ action: 'close', tabId: tabId }));\n    });\n\n})();\n</script>\n<script>\n//HM20260213:Added this Script to handle In-Active/E-Rate Counterparty actions restriction accross system\n//Global variable to track Counterparty status and allow or block edit\nvar editAllowedOnCpStatus= true;\nvar max_eff_dt  = \"\";\nvar enableButton = false;\n\nfunction fetchCounterpartyDetails()\n{\n	// Check if form exists\n    if (!document.forms || document.forms.length === 0) {\n        return;\n    }\n    var form = document.forms[0];\n");
      out.write("    // Check if counterparty_cd field exists in form\n    if (!form.counterparty_cd) {\n        return;\n    }\n\n	var counterparty_cd = document.forms[0].counterparty_cd.value;\n	if(counterparty_cd != \"\" && counterparty_cd!=\"0\")\n	{\n		$.post(\"../servlet/DBCounterpartyInfo?counterparty_cd=\" + counterparty_cd + \"&setCallType=fetchCounterpartyDetails\",\n		function(responseJson) \n		{\n			if (responseJson.length > 0) \n			{\n				var counterpartyInfo = responseJson[0].COUNTERPARTY_INFO;\n				if (counterpartyInfo.length > 0) \n				{\n					var status = counterpartyInfo[0].STATUS;\n					max_eff_dt = counterpartyInfo[0].EFF_DT;\n					\n					if(status == \"N\")//HM20260217: Removed as per Vijay feedback only for deacive CP edit is disabled || status == \"E\"\n					{\n						editAllowedOnCpStatus = false;\n					} else {\n						editAllowedOnCpStatus = true;\n					}\n					\n					// Gettinh today's system date (without time)\n					var today = new Date();\n					today.setHours(0,0,0,0);\n\n					var isFutureEffective = false;\n					if (max_eff_dt && max_eff_dt !== \"\") {\n");
      out.write("\n						// Split DD/MM/YYYY\n						var parts = max_eff_dt.split(\"/\");\n\n						var day   = parseInt(parts[0], 10);\n						var month = parseInt(parts[1], 10) - 1;\n						var year  = parseInt(parts[2], 10);\n\n						var effDate = new Date(year, month, day);\n						effDate.setHours(0,0,0,0);\n\n						if (effDate > today) {\n							isFutureEffective = true;\n						}\n					}\n					\n					if (editAllowedOnCpStatus === false && !isFutureEffective) {\n						//disableAllInputs();\n						if(!enableButton)\n						{\n							disableSubmitButtons();\n						}\n					}\n					\n					var alertHtml = \"\";\n					if(status == \"N\")\n					{\n						alertHtml = \n						'<div class=\"row m-b-5 dynamic-alert\" >' +\n							'<div class=\"col-sm-3 col-xs-3 col-md-3\"></div>' +\n							'<div class=\"col-sm-6 col-xs-6 col-md-6\">' +\n								'<div class=\"form-group row\">' +\n									'<div class=\"col-sm-12 col-xs-12 col-md-12\">' +\n										'<div class=\"container\">' +\n											'<div class=\"alert alert-danger\">' +\n												'<i class=\"fa fa-exclamation-triangle fa-lg\"></i>&nbsp;' +\n");
      out.write("												'<b>Counterparty Status : Deactive (Effective from : '+ max_eff_dt +')</b>' +\n											'</div>' +\n										'</div>' +\n									'</div>' +\n								'</div>' +\n							'</div>' +\n						'</div>';\n					}\n					else if(status == \"E\")\n					{\n						alertHtml = \n						'<div class=\"row m-b-5 dynamic-alert\" >' +\n							'<div class=\"col-sm-3 col-xs-3 col-md-3\"></div>' +\n							'<div class=\"col-sm-6 col-xs-6 col-md-6\">' +\n								'<div class=\"form-group row\">' +\n									'<div class=\"col-sm-12 col-xs-12 col-md-12\">' +\n										'<div class=\"container\">' +\n											'<div class=\"alert alert-warning\">' +\n												'<i class=\"fa fa-exclamation-triangle fa-lg\"></i>&nbsp;' +\n												'<b>Counterparty Status : E-Rate (Effective from : '+ max_eff_dt +')</b>' +\n											'</div>' +\n										'</div>' +\n									'</div>' +\n								'</div>' +\n							'</div>' +\n						'</div>';\n					}\n					// Remove old alert if already added\n					$(\".dynamic-alert\").remove();\n\n					// Insert INSIDE as first element\n					$(\".card-body.cdbody\").first().prepend(alertHtml);\n");
      out.write("				}\n			}\n		});\n	}\n}\n$(document).ready(function() {\n    fetchCounterpartyDetails();\n});\n\nfunction disableSubmitButtons() {\n   $(\"input[type='button'][value='Submit']\")\n    .prop(\"disabled\", true);\n}\n\n/* function disableAllInputs() {\n    var form = document.forms[0];\n    if (!form) return;\n\n    $(form).find(\"input, select, textarea\").each(function () {\n\n        // Skip hidden fields\n        if (this.tagName.toLowerCase() === \"input\" && this.type === \"hidden\") {\n            return;\n        }\n\n        // Skip buttons (button, submit, reset)\n        if (this.tagName.toLowerCase() === \"input\" && \n            (this.type === \"button\" || this.type === \"submit\" || this.type === \"reset\")) {\n            return;\n        }\n\n        // Skip <button> elements\n        if (this.tagName.toLowerCase() === \"button\") {\n            return;\n        }\n\n        this.disabled = true;\n    });\n} */\n\n\n//Override the native submit function\n(function() {\n	const originalSubmit = HTMLFormElement.prototype.submit;\n	HTMLFormElement.prototype.submit = function() {\n");
      out.write("		\n		// Gettinh today's system date (without time)\n		var today = new Date();\n		today.setHours(0,0,0,0);\n\n		var isFutureEffective = false;\n		if (max_eff_dt && max_eff_dt !== \"\") {\n\n			// Split DD/MM/YYYY\n			var parts = max_eff_dt.split(\"/\");\n\n			var day   = parseInt(parts[0], 10);\n			var month = parseInt(parts[1], 10) - 1;\n			var year  = parseInt(parts[2], 10);\n\n			var effDate = new Date(year, month, day);\n			effDate.setHours(0,0,0,0);\n\n			if (effDate > today) {\n				isFutureEffective = true;\n			}\n		}\n		\n		if(!editAllowedOnCpStatus && !isFutureEffective) \n		{\n			alert(\"Submission Blocked! Counterparty Status must be Active!!\");\n			document.getElementById(\"loading\").style.visibility = \"hidden\";\n			return false; // block submission\n		} \n		else\n		{\n			return originalSubmit.apply(this, arguments); // allow submission\n		}\n	};\n})();\n\n</script>\n\n<!-- Watermark CSS -->\n<style type=\"text/css\">\n    /* Apply the watermark globally on the body */\n    body {\n        position: relative;\n        height: 100vh; /* Ensuring here that body takes the full viewport height */\n");
      out.write("        margin: 0; /* Remove default margin */\n    }\n\n    body::after {\n        content: \"");
      out.print(wmk_comp_abbr);
      out.write("\";  /* Watermark text */\n        font-size: 10vw; /* This is used for viewport width for scalability */\n        /*color: var(--header_color); */        /* Header color */\n    	color: rgba(0, 0, 0, 0.1);\n    	opacity: 0.4;                       /* 40% opacity to watermark */\n    	position: fixed;  /* Make it fixed so it stays in place */\n        top: 50%;  /* Center vertically */\n        left: 50%;  /* Center horizontally */\n        transform: translate(-50%, -50%) rotate(-45deg); /* Center it properly and rotate */\n        pointer-events: none;  /* Make sure it doesn't block any interactions */\n        z-index: 9999;  /* Make sure it's on top */\n        white-space: nowrap;\n        transform-origin: center;\n    }\n\n    /* Make the watermark size smaller on mobile devices */\n    @media screen and (max-width: 767px) {\n        body::after {\n            font-size: 20vw; /* Larger watermark on small screens */\n        }\n    }\n\n    /* Adjust watermark for tablets or medium devices */\n    @media screen and (max-width: 1024px) and (min-width: 768px) {\n");
      out.write("        body::after {\n            font-size: 15vw; /* Moderate size for tablet screens */\n        }\n    }\n    \n    /* Adjust watermark for larger screens (Desktops) */\n    @media screen and (min-width: 1025px) {\n        body::after {\n            font-size: 10vw; /* Default size for desktops */\n        }\n    }\n</style>");
      out.write("\n\n<script>\nfunction doSubmit()\n{\n	var ld_price_per = document.forms[0].ld_price_per.value;	\n	var top_price_per = document.forms[0].top_price_per.value;	\n	var mug_price_per = document.forms[0].mug_price_per.value;\n	var msg=\"\";\n	var flag=true;\n	\n	if(document.forms[0].liab_lq_damg.checked==true)\n 	{\n	 	if(ld_price_per==null || trim(ld_price_per)=='')\n		{\n				msg += \"Please Select Price (% of Contract Price) Field  of Liquidated Damages !!!\\n\";\n				flag = false;\n		}\n	}\n	if(document.forms[0].liab_take_pay.checked==true)\n 	{\n		if(top_price_per==null || trim(top_price_per)=='')\n		{\n				msg += \"Please Select Price (% of Contract Price) Field of Take Or Pay  !!!\\n\";\n				flag = false;\n		}\n	}\n	\n	if(document.forms[0].liab_makeup.checked==true)\n 	{\n		if(mug_price_per==null || trim(mug_price_per)=='')\n		{\n				msg += \"Please Select Price (% of Contract Price) Field of Make Up Gas  !!!\\n\";\n				flag = false;\n		}\n	}  \n	if(flag)\n	{\n		var a = confirm(\"Do You Want To Submit Liability Clause?\");	\n		if(a)\n		{\n			alert(\"Proceed and Submit Contract! \");\n");
      out.write("			document.forms[0].submit();\n		}\n	}\n	else\n	{\n		alert(msg);\n	}\n}\n\nfunction enableLDDetails()\n{\n	if(document.forms[0].liab_lq_damg.checked)\n	{\n		document.forms[0].ld_price_per.disabled=false;\n		document.forms[0].ld_promise.disabled=false;\n		document.forms[0].ld_low_per.disabled=false;\n		document.forms[0].ld_chk.disabled=false;\n		document.forms[0].remark.disabled=false;\n		document.forms[0].ld_from.disabled=false;\n		document.forms[0].ld_to.disabled=false;\n		\n	}\n	else \n	{\n		document.forms[0].ld_price_per.disabled=true;\n		document.forms[0].ld_promise.disabled=true;\n		document.forms[0].ld_low_per.disabled=true;\n		document.forms[0].ld_chk.disabled=true;\n		document.forms[0].remark.disabled=true;\n		document.forms[0].ld_from.disabled=true;\n		document.forms[0].ld_to.disabled=true;\n	}\n}\n\nfunction enableTOPDetails()\n{\n	if(document.forms[0].liab_take_pay.checked)\n	{\n		document.forms[0].top_price_per.disabled=false;\n		document.forms[0].top_per.disabled=false;\n		document.forms[0].top_obligation.disabled=false;\n		document.forms[0].top_remark.disabled=false;\n");
      out.write("		document.forms[0].top_promise.disabled=false;\n		document.forms[0].top_chk.disabled=false;\n		document.forms[0].top_from.disabled=false;\n		document.forms[0].top_to.disabled=false;\n	}\n	else\n	{\n		document.forms[0].top_price_per.disabled=true;\n		document.forms[0].top_per.disabled=true;\n		document.forms[0].top_obligation.disabled=true;\n		document.forms[0].top_remark.disabled=true;\n		document.forms[0].top_promise.disabled=true;\n		document.forms[0].top_chk.disabled=true;\n		document.forms[0].top_from.disabled=true;\n		document.forms[0].top_to.disabled=true;\n	}\n}\n\nfunction enableMUGDetails()\n{\n	if(document.forms[0].liab_makeup.checked)\n	{\n		document.forms[0].mug_period_per.disabled=false;\n		document.forms[0].recovery_day.disabled=false;\n		document.forms[0].mug_price_per.disabled=false;\n		document.forms[0].mug_remark.disabled=false;\n	}\n	else\n	{\n		document.forms[0].mug_period_per.disabled=true;\n		document.forms[0].recovery_day.disabled=true;\n		document.forms[0].mug_price_per.disabled=true;\n		document.forms[0].mug_remark.disabled=true;\n");
      out.write("	}\n}\n\nfunction checkValuePrecision(value,precision,maxVal,id)\n{\n	try\n	{\n		if(value == \"\" || value == null)\n		{\n			\n		}\n		else\n		{\n			var number = parseFloat(value);\n	        if (isNaN(number))\n	        {\n	            alert(\"Value is not a valid number!!\");\n	            \n	            document.getElementById(id).value = \"\";\n	        }\n	        else\n	        {\n	        	if(value.includes('.'))\n				{\n					var parts = value.split('.');\n					var integerPart = parts[0];\n					var decimalPart = parts[1] || '';\n					 \n					\n					if (integerPart.length <= maxVal)\n					{\n						//return true;\n					}\n					else\n					{\n						alert(\"Provided Value should be in (\"+maxVal+\", \"+precision+\") format!!\");\n						document.getElementById(id).value = \"\";\n						//return false;\n					}\n					\n					if (decimalPart.length <= precision)\n					{\n						//return true;\n					}\n					else\n					{\n						alert(\"Provided Value should be in (\"+maxVal+\", \"+precision+\") format!!\");\n						document.getElementById(id).value = \"\";\n					}\n				}\n				else\n				{\n					if (value.length <= maxVal)\n");
      out.write("					 {\n						 //return true;\n					 }\n					 else\n					 {\n						 alert(\"Provided Value should be in (\"+maxVal+\", \"+precision+\") format!!\");\n						 document.getElementById(id).value = \"\";\n					 }\n				}\n	        }\n		}\n    }\n	catch (error)\n	{\n        //alert(error);\n        return false;\n    }\n}\n\nfunction countLdEffPrice()\n{\n	var per = document.forms[0].ld_price_per.value;\n	var cont_price = document.forms[0].cont_price.value;\n	var cont_price_unit = document.forms[0].cont_price_unit.value;\n	var eff_price = \"\";\n	\n	if(cont_price!=\"\" && per!=\"\")\n	{\n		eff_price = (cont_price*per)/100;\n	}\n	\n	if(cont_price_unit==\"USD\")\n	{\n		document.forms[0].ld_eff_price.value=eff_price.toFixed(4);\n	}\n	else\n	{\n		document.forms[0].ld_eff_price.value=eff_price.toFixed(2);\n	}\n}\n\nfunction countTopEffPrice()\n{\n	var per = document.forms[0].top_price_per.value;\n	var cont_price = document.forms[0].cont_price.value;\n	var cont_price_unit = document.forms[0].cont_price_unit.value;\n	var eff_price = \"\";\n	\n	if(cont_price!=\"\" && per!=\"\")\n	{\n		eff_price = (cont_price*per)/100;\n");
      out.write("	}\n	\n	if(cont_price_unit==\"USD\")\n	{\n		document.forms[0].top_eff_price.value=eff_price.toFixed(4);\n	}\n	else\n	{\n		document.forms[0].top_eff_price.value=eff_price.toFixed(2);\n	}\n}\n\nfunction countMugEffPrice()\n{\n	var per = document.forms[0].mug_price_per.value;\n	var cont_price = document.forms[0].cont_price.value;\n	var cont_price_unit = document.forms[0].cont_price_unit.value;\n	var eff_price = \"\";\n	\n	if(cont_price!=\"\" && per!=\"\")\n	{\n		eff_price = (cont_price*per)/100;\n	}\n	\n	if(cont_price_unit==\"USD\")\n	{\n		document.forms[0].mug_eff_price.value=eff_price.toFixed(4);\n	}\n	else\n	{\n		document.forms[0].mug_eff_price.value=eff_price.toFixed(2);\n	}\n}\n\nfunction countActObligationQty()\n{\n	var top_per = document.forms[0].top_per.value;\n	var top_chk = document.forms[0].top_chk.value;\n	var qty = \"\";\n	var act_Obligation_qty = \"\";\n	\n	if(trim(top_per)!=\"\" && top_chk!=\"\")\n	{\n		if(top_chk==\"D\")\n		{\n			qty=document.forms[0].cont_dcq.value;\n		}\n		else if(top_chk==\"T\")\n		{\n			qty=document.forms[0].cont_tcq.value;\n		}\n		\n		act_Obligation_qty=(qty*top_per)/100;\n");
      out.write("	}\n	\n	document.forms[0].top_obligation.value=act_Obligation_qty;\n	\n}\n</script>\n</head>\n");
      com.etrm.fms.contract_master.DataBean_ContractMaster cont = null;
      cont = (com.etrm.fms.contract_master.DataBean_ContractMaster) _jspx_page_context.getAttribute("cont", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (cont == null){
        cont = new com.etrm.fms.contract_master.DataBean_ContractMaster();
        _jspx_page_context.setAttribute("cont", cont, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      com.etrm.fms.util.MessageUtil utilmsg = null;
      utilmsg = (com.etrm.fms.util.MessageUtil) _jspx_page_context.getAttribute("utilmsg", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (utilmsg == null){
        utilmsg = new com.etrm.fms.util.MessageUtil();
        _jspx_page_context.setAttribute("utilmsg", utilmsg, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');

String clearance=request.getParameter("clearance")==null?"":request.getParameter("clearance");
String counterparty_cd=request.getParameter("counterparty_cd")==null?"":request.getParameter("counterparty_cd");
String agreement_type = request.getParameter("agreement_type")==null?"F":request.getParameter("agreement_type");
String agmt_no=request.getParameter("agmt_no")==null?"":request.getParameter("agmt_no");
String agmt_rev_no=request.getParameter("agmt_rev_no")==null?"":request.getParameter("agmt_rev_no");
String start_dt=request.getParameter("start_dt")==null?"":request.getParameter("start_dt");
String end_dt=request.getParameter("end_dt")==null?"":request.getParameter("end_dt");
String contract_type=request.getParameter("contract_type")==null?"":request.getParameter("contract_type");
String cont_no=request.getParameter("cont_no")==null?"":request.getParameter("cont_no");
String cont_rev_no=request.getParameter("cont_rev_no")==null?"":request.getParameter("cont_rev_no");
String rate=request.getParameter("rate")==null?"":request.getParameter("rate");
String rate_unit=request.getParameter("rate_unit")==null?"":request.getParameter("rate_unit");
String tcq=request.getParameter("tcq")==null?"":request.getParameter("tcq");
String dcq=request.getParameter("dcq")==null?"":request.getParameter("dcq");

cont.setCallFlag("CONT_LIABILITY_CLAUSE");
cont.setComp_cd(owner_cd);
cont.setCont_start_dt(start_dt);
//cont.setCont_end_dt(end_dt);
cont.setCounterparty_cd(counterparty_cd);
cont.setAgmt_no(agmt_no);
cont.setAgmt_rev_no(agmt_rev_no);
cont.setAgreement_type(agreement_type);
cont.setContract_type(contract_type);
cont.setCont_no(cont_no);
cont.setCont_rev_no(cont_rev_no);
cont.init();

String liab_lq_damg=cont.getLiab_lq_damg();
String ld_price_per=cont.getLd_price_per();
String ld_promise=cont.getLd_promise();
String ld_low_per=cont.getLd_low_per();
String ld_chk=cont.getLd_chk();
String remark=cont.getRemark();
String liab_take_pay=cont.getLiab_take_pay();
String top_price_per=cont.getTop_price_per();
String top_promise=cont.getTop_promise();
String top_per=cont.getTop_per();
String top_chk=cont.getTop_chk();
String top_obligation=cont.getTop_obligation();
String top_remark=cont.getTop_remark();
String liab_makeup=cont.getLiab_makeup();
String mug_price_per=cont.getMug_price_per();
String mug_period_per=cont.getMug_period_per();
String recovery_day=cont.getRecovery_day();
String mug_remark=cont.getMug_remark();
String ld_from = cont.getLd_from();
String ld_to = cont.getLd_to();
String top_from = cont.getTop_from();
String top_to = cont.getTop_to();
String couterparty_abbr = cont.getCouterparty_abbr();
String display_map_id = cont.getDisplay_map_id();

if(rate_unit.equals("1"))
{
	rate_unit="INR";
}
else if(rate_unit.equals("2"))
{
	rate_unit="USD";
}


      out.write("\n<body onload=\"enableLDDetails();enableTOPDetails();enableMUGDetails();countLdEffPrice();countTopEffPrice();countMugEffPrice();countActObligationQty();\">\n<form method=\"post\" action=\"../servlet/Frm_ContracMaster\">\n<div class=\"box-body\">\n	<div class=\"row\">\n		<div class=\"col-md-12 col-sm-12 col-xs-12\">\n			");
if(!msg.equals("")){
				if(msg_type.equals("S")){
      out.write("\n					<div class=\"fadealert\">");
      out.print(utilmsg.successMessage(msg));
      out.write("</div>\n				");
}else if(msg_type.equals("E")){
      out.write("\n					<div class=\"fadealert\">");
      out.print( utilmsg.errorMessage(msg));
      out.write("</div>\n				");
}
			} 
      out.write("\n			<div class=\"card cardmain\">\n				<div class=\"card-header cdheader\">\n					<div class=\"d-flex justify-content-between\">\n					    <div class=\"topheader\">\n					    	");
      out.print(couterparty_abbr);
      out.write(' ');
      out.write('[');
      out.print(display_map_id);
      out.write("] Liability Clause\n					    </div>\n					</div>\n				</div>\n				<div class=\"card-body cdbody\">\n					<div class=\"row m-b-5\">\n						<div class=\"col-sm-2 col-xs-2 col-md-2\">\n							<input type=\"checkbox\" class=\"form-check-input\" name=\"liab_lq_damg\" value=\"Y\" onclick=\"enableLDDetails()\" ");
if(liab_lq_damg.equals("Y")){ 
      out.write("checked");
} 
      out.write(">&nbsp;<label class=\"form-label\"><b>Liquidated Damages</b></label>  \n						</div>\n					</div>\n					<!-- <div class=\"row m-b-5\">\n						<label class=\"form-label subheader\"><i class=\"fa fa-snowflake-o\"></i> Price (% of Contract Price)</label>\n					</div> -->\n					<div class=\"row m-b-5\">\n						<div class=\"col-sm-2 col-xs-2 col-md-2\">\n							<label class=\"form-label\"><b>Price (% of Contract Price)<span class=\"s-red\">*</span></b></label>\n						</div>\n						<div class=\"col-sm-4 col-xs-4 col-md-4\">\n							<div class=\"form-group row\">\n				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\n				    				<div class=\"input-group input-group-sm\" >\n			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"ld_price_per\" id=\"ld_price_per\" value=\"");
      out.print(ld_price_per );
      out.write("\" size=\"8\" maxlength=\"8\" onblur=\"checkValuePrecision(this.value,'2','3','ld_price_per');negNumber(this);appPercentage(this);countLdEffPrice();\" >\n			      						<span class=\"input-group-text\">%</span>\n		      						</div>\n				    			</div>\n				    		</div>\n				    	</div>\n				    	<div class=\"col-sm-2 col-xs-2 col-md-2\">\n							<label class=\"form-label\"><b>Effective Price</b></label>\n						</div>\n						<div class=\"col-sm-4 col-xs-4 col-md-4\">\n							<div class=\"form-group row\">\n				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\n				    				<div class=\"input-group input-group-sm\" >\n			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"ld_eff_price\" id=\"ld_eff_price\" value=\"\" size=\"8\" maxlength=\"8\" readonly>\n			      						<span class=\"input-group-text\">");
      out.print(rate_unit );
      out.write("/MMBTU</span>\n		      						</div>\n				    			</div>\n				    		</div>\n				    	</div>\n					</div>\n					<div class=\"row m-b-5\">\n				    	<div class=\"col-sm-2 col-xs-2 col-md-2\">\n		    				<font color=\"\"><b>Promise Quantity Frequency</b></font>\n		    			</div>\n				    	<div class=\"col-sm-4 col-xs-4 col-md-4\">\n							<div class=\"form-group row\">\n								<div class=\"col-sm-12 col-xs-12 col-md-12\">\n									<div class=\"input-group input-group-sm\" >\n					    				<select class=\"form-select form-select-sm\" name=\"ld_promise\">\n					    					<option value=\"D\">Daily</option>\n					                        <option value=\"W\">Weekly</option>\n					                        <option value=\"F\">Fortnightly </option>\n					                        <option value=\"M\">Monthly </option>\n					                        <option value=\"Q\">Quarterly </option>\n					                        <option value=\"IC\">Invoice Cycle</option>\n					                        <option value=\"T\">TCQ</option>\n					                        <option value=\"DP\">Defined Period</option>\n");
      out.write("					                        <option value=\"SP\">Supply Period</option>\n					    				</select>\n					    				<script>document.forms[0].ld_promise.value=\"");
      out.print(ld_promise);
      out.write("\"</script>\n					    			</div>\n				    			</div>\n				    		</div>\n				    	</div>\n				    	<div class=\"col-sm-6 col-xs-6 col-md-6\">\n							<div class=\"form-group row\">  \n								<div class=\"col-sm-1 col-xs-1 col-md-1\">\n									<div class=\"form-group row\">				    			\n										<div class=\"col-auto\">\n											<label class=\"form-label\">&nbsp;<b>From</b></label>\n										</div>\n									</div>\n								</div>\n								<div class=\"col-sm-5 col-xs-5 col-md-5\">\n									<div class=\"input-group input-group-sm\"\">\n										<input type=\"text\" class=\"form-control form-control-sm date fmsdtpick\" name=\"ld_from\" id=\"ld_from\" value=\"");
      out.print(ld_from );
      out.write("\" onblur=\"validateDate(this);\" onchange=\"validateDate(this);\" autocomplete=\"off\">	\n										<span class=\"input-group-text\"><i class=\"fa fa-calendar fa-lg\"></i></span>	\n									</div>							\n								</div>	\n								<div class=\"col-sm-1 col-xs-1 col-md-1\">\n									<div class=\"form-group row\">				    			\n										<div class=\"col-auto\">\n											<label class=\"form-label\">&nbsp;<b>To</b></label>\n										</div>\n									</div>\n								</div>\n								<div class=\"col-sm-5 col-xs-5 col-md-5\">\n									<div class=\"input-group input-group-sm\"\">\n										<input type=\"text\" class=\"form-control form-control-sm date fmsdtpick\" name=\"ld_to\" id=\"ld_to\" value=\"");
      out.print(ld_to );
      out.write("\" onblur=\"validateDate(this);\" onchange=\"validateDate(this);\" autocomplete=\"off\">	\n										<span class=\"input-group-text\"><i class=\"fa fa-calendar fa-lg\"></i></span>\n									</div>							\n								</div>\n							</div>\n						</div>\n				    </div>\n				    <div class=\"row m-b-5\">\n				    	<div class=\"col-sm-2 col-xs-2 col-md-2\">\n		    				<font color=\"\"><b>Liability</b></font>\n		    			</div>\n				    	<div class=\"col-sm-4 col-xs-4 col-md-4\">\n							<div class=\"form-group row\">  \n								<div class=\"col-sm-3 col-xs-3 col-md-3\">\n									<div class=\"input-group input-group-sm\"\">\n										<input type=\"text\" class=\"form-control form-control-sm\" name=\"ld_low_per\" id=\"ld_low_per\" value=\"");
      out.print(ld_low_per);
      out.write("\" onblur=\"checkValuePrecision(this.value,'2','3','ld_low_per');negNumber(this);appPercentage(this);\">	\n										<span class=\"input-group-text\">%</span>	\n									</div>							\n								</div>	\n								<div class=\"col-sm-3 col-xs-3 col-md-3\">\n									<div class=\"form-group row\">				    			\n										<div class=\"col-auto\">\n											<label class=\"form-label\">&nbsp;<b>of Lower of</b></label>\n										</div>\n									</div>\n								</div>\n								<div class=\"col-sm-6 col-xs-6 col-md-6\">\n									<div class=\"form-group row\">				    			\n						  				<div class=\"input-group input-group-sm\" >\n						    				<select class=\"form-select form-select-sm\" name=\"ld_chk\">\n						    					<option value=\"L\" selected=\"selected\"> DCQ/PNDCQ/MDCQ </option>\n						    					<!-- <option value=\"\" selected=\"selected\">--Select--</option>\n						    					<option value=\"D\">DCQ</option>\n						                        <option value=\"P\">PNDCQ</option>\n						                        <option value=\"M\">MDCQ </option> -->\n						    				</select>\n						    				<script>document.forms[0].ld_chk.value=\"");
      out.print(ld_chk);
      out.write("\"</script>\n						    			</div>\n									</div>\n								</div>\n							</div>\n						</div>	\n				    </div>\n				    <div class=\"row m-b-5\">\n						<div class=\"col-sm-2 col-xs-2 col-md-2\">\n							<label class=\"form-label\"><b>Remark</b></label>\n						</div>\n						\n						<div class=\"col-sm-10 col-xs-10 col-md-10\">\n							<div class=\"form-group row\">\n				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\n				    				<div class=\"input-group input-group-sm\" >\n			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"remark\" value=\"");
      out.print(remark );
      out.write("\" size=\"80\" maxlength=\"200\">\n		      						</div>\n				    			</div>\n				    		</div>\n				    	</div>\n					</div>\n				</div>\n				<div class=\"card-body cdbody\">\n					<div class=\"row m-b-5\">\n						<div class=\"col-sm-2 col-xs-2 col-md-2\">\n							<input type=\"checkbox\" class=\"form-check-input\" name=\"liab_take_pay\" value=\"Y\" onclick=\"enableTOPDetails()\" ");
if(liab_take_pay.equals("Y")){ 
      out.write("checked");
} 
      out.write(">&nbsp;<label class=\"form-label\"><b>Take or Pay</b></label> \n						</div>\n					</div>\n					<!-- <div class=\"row m-b-5\">\n						<label class=\"form-label subheader\"><i class=\"fa fa-snowflake-o\"></i> Price (% of Contract Price)</label>\n					</div> -->\n					<div class=\"row m-b-5\">\n						<div class=\"col-sm-2 col-xs-2 col-md-2\">\n							<label class=\"form-label\"><b>Price (% of Contract Price)<span class=\"s-red\">*</span></b></label>\n						</div>\n						<div class=\"col-sm-4 col-xs-4 col-md-4\">\n							<div class=\"form-group row\">\n				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\n				    				<div class=\"input-group input-group-sm\" >\n			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"top_price_per\" id=\"top_price_per\" value=\"");
      out.print(top_price_per );
      out.write("\" size=\"8\" maxlength=\"8\" onblur=\"checkValuePrecision(this.value,'2','3','top_price_per');negNumber(this);appPercentage(this);countTopEffPrice()\">\n			      						<span class=\"input-group-text\">%</span>\n		      						</div>\n				    			</div>\n				    		</div>\n				    	</div>\n				    	<div class=\"col-sm-2 col-xs-2 col-md-2\">\n							<label class=\"form-label\"><b>Effective Price</b></label>\n						</div>\n						<div class=\"col-sm-4 col-xs-4 col-md-4\">\n							<div class=\"form-group row\">\n				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\n				    				<div class=\"input-group input-group-sm\" >\n			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"top_eff_price\" id=\"top_eff_price\" value=\"\" size=\"8\" maxlength=\"8\" readonly >\n			      						<span class=\"input-group-text\">");
      out.print(rate_unit );
      out.write("/MMBTU</span>\n		      						</div>\n				    			</div>\n				    		</div>\n				    	</div>\n					</div>\n					 <div class=\"row m-b-5\">\n				    	<div class=\"col-sm-2 col-xs-2 col-md-2\">\n		    				<font color=\"\"><b>Promise Quantity Frequency</b></font>\n		    			</div>\n				    	<div class=\"col-sm-4 col-xs-4 col-md-4\">\n							<div class=\"form-group row\">\n								<div class=\"col-sm-12 col-xs-12 col-md-12\">\n								<div class=\"input-group input-group-sm\" >\n				    				<select class=\"form-select form-select-sm\" name=\"top_promise\">\n				    					<option value=\"D\">Daily</option>\n				                        <option value=\"W\">Weekly</option>\n				                        <option value=\"F\">Fortnightly </option>\n				                        <option value=\"M\">Monthly </option>\n				                        <option value=\"Q\">Quarterly </option>\n				                        <option value=\"IC\">Invoice Cycle</option>\n				                        <option value=\"T\">TCQ</option>\n				                        <option value=\"DP\">Defined Period</option>\n");
      out.write("				                        <option value=\"SP\">Supply Period</option>\n				    				</select>\n				    				<script>document.forms[0].top_promise.value=\"");
      out.print(top_promise);
      out.write("\"</script>\n				    			</div>\n				    			</div>\n				    		</div>\n				    	</div>\n				    	<div class=\"col-sm-6 col-xs-6 col-md-6\">\n							<div class=\"form-group row\">  \n								<div class=\"col-sm-1 col-xs-1 col-md-1\">\n									<div class=\"form-group row\">				    			\n										<div class=\"col-auto\">\n											<label class=\"form-label\">&nbsp;<b>From</b></label>\n										</div>\n									</div>\n								</div>\n								<div class=\"col-sm-5 col-xs-5 col-md-5\">\n									<div class=\"input-group input-group-sm\"\">\n										<input type=\"text\" class=\"form-control form-control-sm date fmsdtpick\" name=\"top_from\" id=\"top_from\" value=\"");
      out.print(top_from );
      out.write("\" onblur=\"validateDate(this);\" onchange=\"validateDate(this);\" autocomplete=\"off\">	\n										<span class=\"input-group-text\"><i class=\"fa fa-calendar fa-lg\"></i></span>	\n									</div>							\n								</div>	\n								<div class=\"col-sm-1 col-xs-1 col-md-1\">\n									<div class=\"form-group row\">				    			\n										<div class=\"col-auto\">\n											<label class=\"form-label\">&nbsp;<b>To</b></label>\n										</div>\n									</div>\n								</div>\n								<div class=\"col-sm-5 col-xs-5 col-md-5\">\n									<div class=\"input-group input-group-sm\"\">\n										<input type=\"text\" class=\"form-control form-control-sm date fmsdtpick\" name=\"top_to\" id=\"top_to\" value=\"");
      out.print(top_to );
      out.write("\" onblur=\"validateDate(this);\" onchange=\"validateDate(this);\" autocomplete=\"off\">	\n										<span class=\"input-group-text\"><i class=\"fa fa-calendar fa-lg\"></i></span>	\n									</div>							\n								</div>\n							</div>\n						</div>\n				    </div>\n					<div class=\"row m-b-5\">\n				    	<div class=\"col-sm-2 col-xs-2 col-md-2\">\n		    				<font color=\"\"><b>Take or Pay</b></font>\n		    			</div>\n		    			<div class=\"col-sm-4 col-xs-4 col-md-4\">\n							<div class=\"form-group row\">  \n								<div class=\"col-sm-5 col-xs-5 col-md-5\">\n									<div class=\"input-group input-group-sm\" >\n										<input type=\"text\" class=\"form-control form-control-sm\" name=\"top_per\" id=\"top_per\" value=\"");
      out.print(top_per );
      out.write("\" size=\"5\" maxlength=\"8\" onblur=\"checkValuePrecision(this.value,'2','3','top_per');negNumber(this);appPercentage(this);countActObligationQty();\">\n										<span class=\"input-group-text\">%</span>\n									</div>\n								</div>\n								<div class=\"col-sm-1 col-xs-1 col-md-1\">\n									<div class=\"form-group row\">				    			\n										<div class=\"col-auto\">\n											<label class=\"form-label\">&nbsp;of</label>\n										</div>\n									</div>\n								</div>\n								<div class=\"col-sm-6 col-xs-6 col-md-6\">\n									<div class=\"form-group row\">				    			\n						  				<div class=\"input-group input-group-sm\" >\n						    				<select class=\"form-select form-select-sm\" name=\"top_chk\" onchange=\"countActObligationQty();\">\n						    					<option value=\"\" selected=\"selected\">--Select--</option>\n						    					<option value=\"D\">DCQ</option>\n						                        <option value=\"T\">TCQ</option>\n						    				</select>\n						    				<script>document.forms[0].top_chk.value=\"");
      out.print(top_chk);
      out.write("\"</script>\n						    			</div>\n									</div>\n								</div>\n							</div>\n						</div>\n				    </div>\n				    <div class=\"row m-b-5\">\n				    	<div class=\"col-sm-2 col-xs-2 col-md-2\">\n		    				<font color=\"\"><b>Actual Obligation To Take</b></font>\n		    			</div>\n				    	<div class=\"col-sm-4 col-xs-4 col-md-4\">\n							<div class=\"form-group row\">\n								<div class=\"col-sm-12 col-xs-12 col-md-12\">\n									<div class=\"input-group input-group-sm\" >\n			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"top_obligation\" value=\"");
      out.print(top_obligation );
      out.write("\" size=\"8\" maxlength=\"11\" onblur=\"negNumber(this);\" readonly>\n			      						<span class=\"input-group-text\">MMBTU</span>\n		      						</div>\n				    			</div>\n				    		</div>\n				    	</div>\n				    </div>\n				   \n				    <div class=\"row m-b-5\">\n						<div class=\"col-sm-2 col-xs-2 col-md-2\">\n							<label class=\"form-label\"><b>Remark</b></label>\n						</div>\n						<div class=\"col-sm-10 col-xs-10 col-md-10\">\n							<div class=\"form-group row\">\n				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\n				    				<div class=\"input-group input-group-sm\" >\n			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"top_remark\" value=\"");
      out.print(top_remark );
      out.write("\" size=\"80\" maxlength=\"200\">\n		      						</div>\n				    			</div>\n				    		</div>\n				    	</div>\n					</div>\n				</div>\n				<div class=\"card-body cdbody\">\n					<div class=\"row m-b-5\">\n						<div class=\"col-sm-2 col-xs-2 col-md-2\">\n							<input type=\"checkbox\" class=\"form-check-input\" name=\"liab_makeup\" value=\"Y\" onclick=\"enableMUGDetails()\" ");
if(liab_makeup.equals("Y")){ 
      out.write("checked");
} 
      out.write(">&nbsp;<label class=\"form-label\"><b>Make Up Gas</b></label> \n						</div>\n					</div>\n					<!-- <div class=\"row m-b-5\">\n						<label class=\"form-label subheader\"><i class=\"fa fa-snowflake-o\"></i> Price (% of Contract Price)</label>\n					</div> -->\n					<div class=\"row m-b-5\">\n						<div class=\"col-sm-2 col-xs-2 col-md-2\">\n							<label class=\"form-label\"><b>Price (% of Contract Price)<span class=\"s-red\">*</span></b></label>\n						</div>\n						<div class=\"col-sm-4 col-xs-4 col-md-4\">\n							<div class=\"form-group row\">\n				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\n				    				<div class=\"input-group input-group-sm\" >\n			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"mug_price_per\" id=\"mug_price_per\" value=\"");
      out.print(mug_price_per );
      out.write("\" size=\"8\" maxlength=\"8\" onblur=\"checkValuePrecision(this.value,'2','3','mug_price_per');negNumber(this);appPercentage(this);countMugEffPrice();\">\n			      						<span class=\"input-group-text\">%</span>\n		      						</div>\n				    			</div>\n				    		</div>\n				    	</div>\n				    	<div class=\"col-sm-2 col-xs-2 col-md-2\">\n							<label class=\"form-label\"><b>Effective Price</b></label>\n						</div>\n						<div class=\"col-sm-4 col-xs-4 col-md-4\">\n							<div class=\"form-group row\">\n				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\n				    				<div class=\"input-group input-group-sm\" >\n			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"mug_eff_price\" id=\"mug_eff_price\" value=\"\" size=\"8\" maxlength=\"8\" readonly>\n			      						<span class=\"input-group-text\">");
      out.print(rate_unit );
      out.write("/MMBTU</span>\n		      						</div>\n				    			</div>\n				    		</div>\n				    	</div>\n					</div>\n					<div class=\"row m-b-5\">\n						<div class=\"col-sm-2 col-xs-2 col-md-2\">\n							<label class=\"form-label\"><b>Make Up Period</b></label>\n						</div>\n						<div class=\"col-sm-4 col-xs-4 col-md-4\">\n							<div class=\"form-group row\">  \n								<div class=\"col-sm-6 col-xs-6 col-md-6\">\n									<div class=\"input-group input-group-sm\" >\n			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"mug_period_per\" id=\"mug_period_per\" value=\"");
      out.print(mug_period_per );
      out.write("\" size=\"5\" maxlength=\"8\" onblur=\"checkValuePrecision(this.value,'2','2','mug_period_per');negNumber(this);appPercentage(this);\">\n			      						<span class=\"input-group-text\">%</span>\n		      						</div>\n								</div>\n								<div class=\"col-sm-6 col-xs-6 col-md-6\">\n									<div class=\"form-group row\">				    			\n										<div class=\"col-auto\">\n											<label class=\"form-label\">&nbsp;of Supply Period</label>\n										</div>\n									</div>\n								</div>\n							</div>\n						</div>\n					</div>\n					<div class=\"row m-b-5\">\n						<div class=\"col-sm-2 col-xs-2 col-md-2\">\n							<label class=\"form-label\"><b>Recovery Period</b></label>\n						</div>\n						<div class=\"col-sm-4 col-xs-4 col-md-4\">\n							<div class=\"form-group row\">\n				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\n				    				<div class=\"input-group input-group-sm\" >\n			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"recovery_day\" id=\"recovery_day\" value=\"");
      out.print(recovery_day );
      out.write("\" size=\"5\" maxlength=\"5\" onblur=\"checkValuePrecision(this.value,'0','3','recovery_day');negNumber(this);\">\n			      						<span class=\"input-group-text\">Days</span>\n		      						</div>\n				    			</div>\n				    		</div>\n				    	</div>\n					</div>\n					\n				    <div class=\"row m-b-5\">\n						<div class=\"col-sm-2 col-xs-2 col-md-2\">\n							<label class=\"form-label\"><b>Remark</b></label>\n						</div>\n						<div class=\"col-sm-10 col-xs-10 col-md-10\">\n							<div class=\"form-group row\">\n				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\n				    				<div class=\"input-group input-group-sm\" >\n			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"mug_remark\" value=\"");
      out.print(mug_remark );
      out.write("\" size=\"80\" maxlength=\"200\">\n		      						</div>\n				    			</div>\n				    		</div>\n				    	</div>\n					</div>\n				</div>\n				<div class=\"card-footer cdfooter text-center\">\n					<div class=\"d-flex justify-content-between\">\n						<input type=\"button\" class=\"btn btn-warning com-btn\" value=\"Reset\" onclick=\"location.reload();\">\n						");
if(write_access.equals("Y")){ 
      out.write("\n						<input type=\"button\" class=\"btn btn-warning com-btn\" value=\"Submit\" onclick=\"doSubmit();\">\n						");
}else{ 
      out.write("\n						<input type=\"button\" class=\"btn btn-warning com-btn\" value=\"Submit\" disabled>\n						");
} 
      out.write("\n					</div>\n				</div>\n			</div>\n		</div>\n	</div>\n</div>\n\n<input type=\"hidden\" name=\"option\" value=\"CONT_LIABILITY_CLAUSE\">\n<input type=\"hidden\" name=\"counterparty_cd\" value=\"");
      out.print(counterparty_cd);
      out.write("\">\n<input type=\"hidden\" name=\"agmt_no\" value=\"");
      out.print(agmt_no);
      out.write("\">\n<input type=\"hidden\" name=\"agmt_rev_no\" value=\"");
      out.print(agmt_rev_no);
      out.write("\">\n<input type=\"hidden\" name=\"clearance\" value=\"");
      out.print(clearance);
      out.write("\">\n<input type=\"hidden\" name=\"start_dt\" value=\"");
      out.print(start_dt);
      out.write("\">\n<input type=\"hidden\" name=\"agreement_type\" value=\"");
      out.print(agreement_type);
      out.write("\">\n<input type=\"hidden\" name=\"contract_type\" value=\"");
      out.print(contract_type);
      out.write("\">\n<input type=\"hidden\" name=\"cont_no\" value=\"");
      out.print(cont_no);
      out.write("\">\n<input type=\"hidden\" name=\"cont_rev_no\" value=\"");
      out.print(cont_rev_no);
      out.write("\">\n<input type=\"hidden\" name=\"cont_price\" value=\"");
      out.print(rate);
      out.write("\">\n<input type=\"hidden\" name=\"cont_price_unit\" value=\"");
      out.print(rate_unit);
      out.write("\">\n<input type=\"hidden\" name=\"cont_tcq\" value=\"");
      out.print(tcq);
      out.write("\">\n<input type=\"hidden\" name=\"cont_dcq\" value=\"");
      out.print(dcq);
      out.write("\">\n\n<input type=\"hidden\" name=\"read_access\" value=\"");
      out.print(read_access);
      out.write("\">\n<input type=\"hidden\" name=\"write_access\" value=\"");
      out.print(write_access);
      out.write("\">\n<input type=\"hidden\" name=\"check_access\" value=\"");
      out.print(check_access);
      out.write("\">\n<input type=\"hidden\" name=\"print_access\" value=\"");
      out.print(print_access);
      out.write("\">\n<input type=\"hidden\" name=\"delete_access\" value=\"");
      out.print(delete_access);
      out.write("\">  	\n<input type=\"hidden\" name=\"audit_access\" value=\"");
      out.print(audit_access);
      out.write("\">\n<input type=\"hidden\" name=\"authorize_access\" value=\"");
      out.print(authorize_access);
      out.write("\">\n<input type=\"hidden\" name=\"approve_access\" value=\"");
      out.print(approve_access);
      out.write("\">\n<input type=\"hidden\" name=\"execute_access\" value=\"");
      out.print(execute_access);
      out.write("\">\n<input type=\"hidden\" name=\"form_cd\" value=\"");
      out.print(formCd);
      out.write("\">\n<input type=\"hidden\" name=\"form_nm\" value=\"");
      out.print(formNm);
      out.write("\">\n<input type=\"hidden\" name=\"mod_cd\" value=\"");
      out.print(mod_cd);
      out.write("\">\n<input type=\"hidden\" name=\"mod_nm\" value=\"");
      out.print(mod_nm);
      out.write("\">\n<input type=\"hidden\" name=\"u\" value=\"");
      out.print(u);
      out.write("\">\n</form>\n</body>\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
