/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2025-09-12 07:16:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.gta;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Vector;

public final class rpt_005fgta_005fview_005fattachment1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Vector");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n<html>\n<head>\n</head>\n");
      com.etrm.fms.gta.DataBean_GtaMaster gta = null;
      gta = (com.etrm.fms.gta.DataBean_GtaMaster) _jspx_page_context.getAttribute("gta", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (gta == null){
        gta = new com.etrm.fms.gta.DataBean_GtaMaster();
        _jspx_page_context.setAttribute("gta", gta, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      com.etrm.fms.util.MessageUtil utilmsg = null;
      utilmsg = (com.etrm.fms.util.MessageUtil) _jspx_page_context.getAttribute("utilmsg", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (utilmsg == null){
        utilmsg = new com.etrm.fms.util.MessageUtil();
        _jspx_page_context.setAttribute("utilmsg", utilmsg, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      com.etrm.fms.util.DateUtil utildate = null;
      utildate = (com.etrm.fms.util.DateUtil) _jspx_page_context.getAttribute("utildate", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (utildate == null){
        utildate = new com.etrm.fms.util.DateUtil();
        _jspx_page_context.setAttribute("utildate", utildate, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');

String sysdate=utildate.getSysdate();

String counterparty_cd = request.getParameter("counterparty_cd")==null?"0":request.getParameter("counterparty_cd");
String customer_cd = request.getParameter("customer_cd")==null?"0":request.getParameter("customer_cd");
String contract_type=request.getParameter("contract_type")==null?"C":request.getParameter("contract_type");
String cont_map_id=request.getParameter("cont_map_id")==null?"":request.getParameter("cont_map_id");

String agmt_no = request.getParameter("agmt_no")==null?"":request.getParameter("agmt_no");
String agmt_rev_no = request.getParameter("agmt_rev_no")==null?"":request.getParameter("agmt_rev_no");
String cont_no = request.getParameter("cont_no")==null?"":request.getParameter("cont_no");
String cont_rev_no = request.getParameter("cont_rev_no")==null?"":request.getParameter("cont_rev_no");

String from_dt=request.getParameter("from_dt")==null?"":request.getParameter("from_dt");
String to_dt=request.getParameter("to_dt")==null?"":request.getParameter("to_dt");

String owner_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	owner_cd="";
}  
else
{
	owner_cd=""+session.getAttribute("comp_cd");
}

gta.setCallFlag("GTC_IMBALANCE");
gta.setComp_cd(owner_cd);
gta.setCounterparty_cd(counterparty_cd);
gta.setContract_type(contract_type);
gta.setAgmt_no(agmt_no);
gta.setAgmt_rev_no(agmt_rev_no);
gta.setCont_no(cont_no);
gta.setCont_rev_no(cont_rev_no);
gta.setFrom_dt(from_dt);
gta.setTo_dt(to_dt);
gta.init();

Vector VCOUNTERPARTY_CD = gta.getVCOUNTERPARTY_CD();
Vector VCOUNTERPARTY_NM = gta.getVCOUNTERPARTY_NM();
Vector VCOUNTERPARTY_ABBR = gta.getVCOUNTERPARTY_ABBR();

Vector VCUSTOMER_CD = gta.getVCUSTOMER_CD();
Vector VCUSTOMER_NM = gta.getVCUSTOMER_NM();
Vector VCUSTOMER_ABBR = gta.getVCUSTOMER_ABBR();

String cont_ref_no = gta.getCont_ref_no();
String start_dt = gta.getStart_dt();
String end_dt = gta.getEnd_dt();
String entry_pt_mapping_id =gta.getEntry_pt_mapping_id();
String exit_pt_mapping_id =gta.getExit_pt_mapping_id();
String entry_pt_nm = gta.getEntry_pt_nm();
String exit_pt_nm = gta.getExit_pt_nm();
String linked_sales_cont_map=gta.getLinked_sales_cont_map();
String bu_plant_seq=gta.getBu_plant_seq();
String sip_pay_freq=gta.getSip_pay_freq();
String counterparty_name=gta.getCounterparty_name();

String cont_name="";
String cont_mapping=contract_type+agmt_no+"-"+agmt_rev_no+"-"+cont_no+"-"+cont_rev_no;

if(!cont_ref_no.equals(""))
{
	cont_name=cont_mapping+" ("+cont_ref_no+") ["+start_dt+" - "+end_dt+"]";
}

if(from_dt.equals(""))
{
	from_dt=gta.getFrom_dt();
}
if(to_dt.equals(""))
{
	to_dt=gta.getTo_dt();
}

Vector VGAS_DT = gta.getVGAS_DT();
Vector VMDQ = gta.getVMDQ();
Vector VNOM_ENTRY_QTY = gta.getVNOM_ENTRY_QTY();
Vector VNOM_EXIT_QTY = gta.getVNOM_EXIT_QTY();
Vector VSCH_ENTRY_QTY = gta.getVSCH_ENTRY_QTY();
Vector VSCH_EXIT_QTY = gta.getVSCH_EXIT_QTY();
Vector VALLOC_ENTRY_QTY = gta.getVALLOC_ENTRY_QTY();
Vector VALLOC_EXIT_QTY = gta.getVALLOC_EXIT_QTY();

Vector VTRANSMISSION_QTY = gta.getVTRANSMISSION_QTY();
Vector VDAILY_IMBALANCE = gta.getVDAILY_IMBALANCE();
Vector VADJ_IMBALANCE = gta.getVADJ_IMBALANCE();
Vector VCUMULATIVE_IMBALANCE = gta.getVCUMULATIVE_IMBALANCE();
Vector VDAILY_UNAUTHORIZED_OVERRUN = gta.getVDAILY_UNAUTHORIZED_OVERRUN();
Vector VCHARGEABLE_OVERRUN = gta.getVCHARGEABLE_OVERRUN();
Vector VCHARGEABLE_POSITIVE_IMBALANCE = gta.getVCHARGEABLE_POSITIVE_IMBALANCE();
Vector VCHARGEABLE_NEGETIVE_IMBALANCE = gta.getVCHARGEABLE_NEGETIVE_IMBALANCE();

String total_nom_entry_qty=gta.getTotal_nom_entry_qty();
String total_nom_exit_qty=gta.getTotal_nom_exit_qty();
String total_sch_entry_qty=gta.getTotal_sch_entry_qty();
String total_sch_exit_qty=gta.getTotal_sch_exit_qty();
String total_alloc_entry_qty=gta.getTotal_alloc_entry_qty();
String total_alloc_exit_qty=gta.getTotal_alloc_exit_qty();
String total_var_mdq=gta.getTotal_var_mdq();
String total_transmission_qty=gta.getTotal_transmission_qty();
String total_chargeable_overrun=gta.getTotal_chargeable_overrun();
String total_positive_imbalance=gta.getTotal_positive_imbalance();
String total_negitive_imbalance=gta.getTotal_negitive_imbalance();

String att_note="Note : This is System generated data and might differ for Party generated remittance";

      out.write("\n<body>\n<table width=\"100%\"  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\n	<tr valign=\"middle\">\n		<td colspan=\"7\">\n			<div align=\"center\">\n				<font size=\"4\" face=\"Arial\">\n					<b>");
      out.print(counterparty_name);
      out.write("</b>\n				</font>\n			</div>\n		</td>\n	</tr>\n</table>\n<br>\n<font size=\"2\" face=\"Arial\"><b>Attachment 1 - GTA Contract&nbsp;(");
      out.print(cont_ref_no);
      out.write(") Imbalance Report From ");
      out.print(from_dt);
      out.write(" To ");
      out.print(to_dt);
      out.write("</b></font>\n<table>\n<tr><td>&nbsp;</td></tr>\n</table>\n<table border=\"1\" cellpadding=\"2\" cellspacing=\"0\">\n	<tr>\n		<td rowspan=\"2\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Gas Day</b></font></div></td>\n		<td rowspan=\"2\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>CT MDQ<br>(MMBTU)</b></font></div></td>\n		<td colspan=\"3\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Transporter Entry Point</b></font></div></td>\n		<td colspan=\"3\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Transporter Exit Point</b></font></div></td>\n		<td rowspan=\"2\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Transmission<br>(MMBTU)</b></font></div></td>\n		<td rowspan=\"2\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Daily Imbalance(+/-)<br>(MMBTU)</b></font></div></td>\n		<td rowspan=\"2\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Adjusted Imbalance<br>(MMBTU)</b></font></div></td>	\n		<td rowspan=\"2\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Cumulative Imbalance<br>(MMBTU)</b></font></div></td>\n");
      out.write("		<td rowspan=\"2\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Daily Unautdorized Overrun<br>(MMBTU)</b></font></div></td>\n		<td rowspan=\"2\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Chargeable Overrun<br>(MMBTU)</b></font></div></td>\n		<td rowspan=\"2\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Chargeable +Ve Imbalance<br>(MMBTU)</b></font></div></td>\n		<td rowspan=\"2\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Chargeable -Ve Imbalance<br>(MMBTU)</b></font></div></td>\n	</tr>\n	<tr>\n		<td><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Nomination<br>(MMBTU)</b></font></div></td>\n		<td><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Scheduling<br>(MMBTU)</b></font></div></td>\n		<td><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Allocation<br>(MMBTU)</b></font></div></td>\n		<td><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Nomination<br>(MMBTU)</b></font></div></td>\n		<td><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Scheduling<br>(MMBTU)</b></font></div></td>\n");
      out.write("		<td><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Allocation<br>(MMBTU)</b></font></div></td>\n	</tr>\n	<tbody>\n		");
for(int i=0; i<VGAS_DT.size(); i++){ 
      out.write("\n		<tr>\n			<td align=\"center\"><font size=\"1.5px\" face=\"Arial\">&nbsp;");
      out.print(VGAS_DT.elementAt(i));
      out.write("&nbsp;</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(VMDQ.elementAt(i) );
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(VNOM_ENTRY_QTY.elementAt(i));
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(VSCH_ENTRY_QTY.elementAt(i));
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(VALLOC_ENTRY_QTY.elementAt(i));
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(VNOM_EXIT_QTY.elementAt(i));
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(VSCH_EXIT_QTY.elementAt(i) );
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(VALLOC_EXIT_QTY.elementAt(i) );
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(VTRANSMISSION_QTY.elementAt(i));
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(VDAILY_IMBALANCE.elementAt(i) );
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(VADJ_IMBALANCE.elementAt(i) );
      out.write("</font></td>			\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(VCUMULATIVE_IMBALANCE.elementAt(i) );
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(VDAILY_UNAUTHORIZED_OVERRUN.elementAt(i) );
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(VCHARGEABLE_OVERRUN.elementAt(i));
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(VCHARGEABLE_POSITIVE_IMBALANCE.elementAt(i));
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(VCHARGEABLE_NEGETIVE_IMBALANCE.elementAt(i));
      out.write("</font></td>	\n		</tr>\n		");
} 
      out.write("\n		<tr style=\"font-weight: bold;\">\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">Total :</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(total_var_mdq);
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(total_nom_entry_qty);
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(total_sch_entry_qty);
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(total_alloc_entry_qty);
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(total_nom_exit_qty);
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(total_sch_exit_qty);
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(total_alloc_exit_qty);
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(total_transmission_qty);
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">-</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">-</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">-</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">-</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(total_chargeable_overrun);
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(total_positive_imbalance);
      out.write("</font></td>\n			<td align=\"right\"><font size=\"1.5px\" face=\"Arial\">");
      out.print(total_negitive_imbalance);
      out.write("</font></td>	\n		</tr>\n	</tbody>\n</table>\n<br>\n<p><font size=\"1.5px\" face=\"Arial\"><b>");
      out.print(att_note);
      out.write("</b></font></p>\n</body>\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
