/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2025-01-29 12:05:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.dlng;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Vector;
import com.etrm.fms.util.CommonVariable;
import com.etrm.fms.util.EncryptTest;

public final class frm_005fdlng_005ftmsa_005fliability_005fclause_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/dlng/../util/../sess/Expire.jsp", Long.valueOf(1723527594814L));
    _jspx_dependants.put("/dlng/../util/common_js.jsp", Long.valueOf(1736230394777L));
    _jspx_dependants.put("/dlng/../util/common_val.jsp", Long.valueOf(1730878735626L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("com.etrm.fms.util.CommonVariable");
    _jspx_imports_classes.add("com.etrm.fms.util.EncryptTest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write('\r');
      out.write('\n');

String expire_msg = request.getParameter("expire_msg")==null?"":request.getParameter("expire_msg");
if(session.getAttribute("emp_uid")==null || session.getAttribute("emp_uid") == ""|| session.getAttribute("emp_uid").toString().equals("null"))
{
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("			alert(\"Please Enter Login Detail!\")\r\n");
      out.write("			var url = \"../home/login.jsp\";\r\n");
      out.write("			location.replace(url);\r\n");
      out.write("		</script>\r\n");
}
else
{
	if(expire_msg.equals("Timeout"))
	{
		session.invalidate();
	
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("		var url = \"../home/login.jsp?sess=Session Expired\";\r\n");
      out.write("		location.replace(url);\r\n");
      out.write("		</script>\r\n");
      out.write("	");

	}
	else if(expire_msg.equals("PwdChng"))
	{
		session.invalidate();
	
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("		var url = \"../home/login.jsp\";\r\n");
      out.write("		location.replace(url);\r\n");
      out.write("		</script>\r\n");
      out.write("	");
}
}

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
String COMMlogo="";
if(session.getAttribute("comp_logo")==null||session.getAttribute("comp_logo")==""||session.getAttribute("comp_logo").toString().equals("null"))
{
	COMMlogo="";
}  
else
{
	COMMlogo=""+session.getAttribute("comp_logo");
}

String sel_comp_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	sel_comp_cd="";
}  
else
{
	sel_comp_cd=""+session.getAttribute("comp_cd");
}

      out.write("\r\n");
      out.write("<link rel=\"SHORTCUT ICON\" href=\"../images/");
      out.print(COMMlogo);
      out.write("\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"refresh\" content=\"");
      out.print(session.getMaxInactiveInterval());
      out.write(";url=../sess/Expire.jsp?expire_msg=Timeout\"/>\r\n");
      out.write("<title>");
      out.print(CommonVariable.app_name);
      out.write("</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap/bootstrap5/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/datepicker/bootstrap-datepicker3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/util.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/navbar.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/responsive.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">\r\n");
      out.write("\r\n");
 if ("2".equals(sel_comp_cd)) { 
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common_2.css\">  <!-- CSS for comp_cd = \"1\" -->\r\n");
 } else { 
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">  <!-- CSS for comp_cd = \"2\" -->\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../bootstrap/bootstrap5/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/datepicker/bootstrap-datepicker.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/datepicker/bootstrap-datepicker.es.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/util.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/session.js\"></script>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      com.etrm.fms.util.DataBean_Menu menu_access = null;
      menu_access = (com.etrm.fms.util.DataBean_Menu) _jspx_page_context.getAttribute("menu_access", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (menu_access == null){
        menu_access = new com.etrm.fms.util.DataBean_Menu();
        _jspx_page_context.setAttribute("menu_access", menu_access, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

String formCd="";
String mod_cd="";
String u=request.getParameter("u")==null?"":request.getParameter("u");

String msg=request.getParameter("msg")==null?"":request.getParameter("msg");
String msg_type=request.getParameter("msg_type")==null?"":request.getParameter("msg_type");

String owner_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	owner_cd="";
}  
else
{
	owner_cd=""+session.getAttribute("comp_cd");
}

String owner_abbr="";
if(session.getAttribute("comp_abbr")==null||session.getAttribute("comp_abbr")==""||session.getAttribute("comp_abbr").toString().equals("null"))
{
	owner_abbr="";
}  
else
{
	owner_abbr=""+session.getAttribute("comp_abbr");
}

String emp_cd="";
if(session.getAttribute("emp_cd")==null||session.getAttribute("emp_cd")==""||session.getAttribute("emp_cd").toString().equals("null"))
{
	emp_cd="";
}  
else
{
	emp_cd=""+session.getAttribute("emp_cd");
}

if(!u.equals(""))
{
	StringBuffer decryt=new EncryptTest().URLdecrypt(u);
	String dec=""+decryt;
	if(!dec.equals("") && dec.contains("-"))
	{
		String temp[]=dec.split("-");
		if(temp.length==2)
		{
			formCd=temp[0];
			mod_cd=temp[1];
		}
	}
}

menu_access.setCallFlag("MENU_ACCESS");
menu_access.setEmpCd(emp_cd);
menu_access.setComp_cd(owner_cd);
menu_access.setModule_cd(mod_cd);
menu_access.setForm_cd(formCd);
menu_access.init();


String formNm = menu_access.getForm_nm();
String mod_nm = menu_access.getModule_nm();
String read_access = menu_access.getRead_access();
String write_access = menu_access.getWrite_access();
String check_access = menu_access.getCheck_access();
String print_access = menu_access.getPrint_access();
String delete_access = menu_access.getDelete_access();
String audit_access = menu_access.getAudit_access();
String authorize_access = menu_access.getAuthorize_access();
String approve_access = menu_access.getApprove_access();
String execute_access = menu_access.getExecute_access();


      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("document.title = \"");
      out.print(CommonVariable.app_name);
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(owner_abbr);
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(formNm);
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function doSubmit()\r\n");
      out.write("{\r\n");
      out.write("	var ld_price_per = document.forms[0].ld_price_per.value;	\r\n");
      out.write("	var top_price_per = document.forms[0].top_price_per.value;	\r\n");
      out.write("	var mug_price_per = document.forms[0].mug_price_per.value;\r\n");
      out.write("	var msg=\"\";\r\n");
      out.write("	var flag=true;\r\n");
      out.write("	\r\n");
      out.write("	if(document.forms[0].liab_lq_damg.checked==true)\r\n");
      out.write(" 	{\r\n");
      out.write("	 	if(ld_price_per==null || trim(ld_price_per)=='')\r\n");
      out.write("		{\r\n");
      out.write("				msg += \"Please Select Price (% of Contract Price) Field  of Liquidated Damages !!!\\n\";\r\n");
      out.write("				flag = false;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	if(document.forms[0].liab_take_pay.checked==true)\r\n");
      out.write(" 	{\r\n");
      out.write("		if(top_price_per==null || trim(top_price_per)=='')\r\n");
      out.write("		{\r\n");
      out.write("				msg += \"Please Select Price (% of Contract Price) Field of Take Or Pay  !!!\\n\";\r\n");
      out.write("				flag = false;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(document.forms[0].liab_makeup.checked==true)\r\n");
      out.write(" 	{\r\n");
      out.write("		if(mug_price_per==null || trim(mug_price_per)=='')\r\n");
      out.write("		{\r\n");
      out.write("				msg += \"Please Select Price (% of Contract Price) Field of Make Up Gas  !!!\\n\";\r\n");
      out.write("				flag = false;\r\n");
      out.write("		}\r\n");
      out.write("	}  \r\n");
      out.write("	if(flag)\r\n");
      out.write("	{\r\n");
      out.write("		var a = confirm(\"Do You Want To submit Liability Clause?\");	\r\n");
      out.write("		if(a)\r\n");
      out.write("		{\r\n");
      out.write("			document.forms[0].submit();\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	else\r\n");
      out.write("	{\r\n");
      out.write("		alert(msg);\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function enableLDDetails()\r\n");
      out.write("{\r\n");
      out.write("	if(document.forms[0].liab_lq_damg.checked)\r\n");
      out.write("	{\r\n");
      out.write("		document.forms[0].ld_price_per.disabled=false;\r\n");
      out.write("		document.forms[0].ld_promise.disabled=false;\r\n");
      out.write("		document.forms[0].ld_low_per.disabled=false;\r\n");
      out.write("		document.forms[0].ld_chk.disabled=false;\r\n");
      out.write("		document.forms[0].remark.disabled=false;\r\n");
      out.write("	}\r\n");
      out.write("	else \r\n");
      out.write("	{\r\n");
      out.write("		document.forms[0].ld_price_per.disabled=true;\r\n");
      out.write("		document.forms[0].ld_promise.disabled=true;\r\n");
      out.write("		document.forms[0].ld_low_per.disabled=true;\r\n");
      out.write("		document.forms[0].ld_chk.disabled=true;\r\n");
      out.write("		document.forms[0].remark.disabled=true;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function enableTOPDetails()\r\n");
      out.write("{\r\n");
      out.write("	if(document.forms[0].liab_take_pay.checked)\r\n");
      out.write("	{\r\n");
      out.write("		document.forms[0].top_price_per.disabled=false;\r\n");
      out.write("		document.forms[0].top_per.disabled=false;\r\n");
      out.write("		document.forms[0].top_obligation.disabled=false;\r\n");
      out.write("		document.forms[0].top_remark.disabled=false;\r\n");
      out.write("		document.forms[0].top_promise.disabled=false;\r\n");
      out.write("		document.forms[0].top_chk.disabled=false;\r\n");
      out.write("	}\r\n");
      out.write("	else\r\n");
      out.write("	{\r\n");
      out.write("		document.forms[0].top_price_per.disabled=true;\r\n");
      out.write("		document.forms[0].top_per.disabled=true;\r\n");
      out.write("		document.forms[0].top_obligation.disabled=true;\r\n");
      out.write("		document.forms[0].top_remark.disabled=true;\r\n");
      out.write("		document.forms[0].top_promise.disabled=true;\r\n");
      out.write("		document.forms[0].top_chk.disabled=true;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function enableMUGDetails()\r\n");
      out.write("{\r\n");
      out.write("	if(document.forms[0].liab_makeup.checked)\r\n");
      out.write("	{\r\n");
      out.write("		document.forms[0].mug_period_per.disabled=false;\r\n");
      out.write("		document.forms[0].recovery_day.disabled=false;\r\n");
      out.write("		document.forms[0].mug_price_per.disabled=false;\r\n");
      out.write("		document.forms[0].mug_remark.disabled=false;\r\n");
      out.write("		document.forms[0].makeup_liab_on.disabled=false;\r\n");
      out.write("	}\r\n");
      out.write("	else\r\n");
      out.write("	{\r\n");
      out.write("		document.forms[0].mug_period_per.disabled=true;\r\n");
      out.write("		document.forms[0].recovery_day.disabled=true;\r\n");
      out.write("		document.forms[0].mug_price_per.disabled=true;\r\n");
      out.write("		document.forms[0].mug_remark.disabled=true;\r\n");
      out.write("		document.forms[0].makeup_liab_on.disabled=true;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkValuePrecision(value,precision,maxVal,id)\r\n");
      out.write("{\r\n");
      out.write("	try\r\n");
      out.write("	{\r\n");
      out.write("		if(value == \"\" || value == null)\r\n");
      out.write("		{\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		else\r\n");
      out.write("		{\r\n");
      out.write("			var number = parseFloat(value);\r\n");
      out.write("	        if (isNaN(number))\r\n");
      out.write("	        {\r\n");
      out.write("	            alert(\"Value is not a valid number!!\");\r\n");
      out.write("	            \r\n");
      out.write("	            document.getElementById(id).value = \"\";\r\n");
      out.write("	        }\r\n");
      out.write("	        else\r\n");
      out.write("	        {\r\n");
      out.write("	        	if(value.includes('.'))\r\n");
      out.write("				{\r\n");
      out.write("					var parts = value.split('.');\r\n");
      out.write("					var integerPart = parts[0];\r\n");
      out.write("					var decimalPart = parts[1] || '';\r\n");
      out.write("					 \r\n");
      out.write("					\r\n");
      out.write("					if (integerPart.length <= maxVal)\r\n");
      out.write("					{\r\n");
      out.write("						//return true;\r\n");
      out.write("					}\r\n");
      out.write("					else\r\n");
      out.write("					{\r\n");
      out.write("						alert(\"Provided Value should be in (\"+maxVal+\", \"+precision+\") format!!\");\r\n");
      out.write("						document.getElementById(id).value = \"\";\r\n");
      out.write("						//return false;\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					if (decimalPart.length <= precision)\r\n");
      out.write("					{\r\n");
      out.write("						//return true;\r\n");
      out.write("					}\r\n");
      out.write("					else\r\n");
      out.write("					{\r\n");
      out.write("						alert(\"Provided Value should be in (\"+maxVal+\", \"+precision+\") format!!\");\r\n");
      out.write("						document.getElementById(id).value = \"\";\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("				else\r\n");
      out.write("				{\r\n");
      out.write("					if (value.length <= maxVal)\r\n");
      out.write("					 {\r\n");
      out.write("						 //return true;\r\n");
      out.write("					 }\r\n");
      out.write("					 else\r\n");
      out.write("					 {\r\n");
      out.write("						 alert(\"Provided Value should be in (\"+maxVal+\", \"+precision+\") format!!\");\r\n");
      out.write("						 document.getElementById(id).value = \"\";\r\n");
      out.write("					 }\r\n");
      out.write("				}\r\n");
      out.write("	        }\r\n");
      out.write("		}\r\n");
      out.write("    }\r\n");
      out.write("	catch (error)\r\n");
      out.write("	{\r\n");
      out.write("        //alert(error);\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      com.etrm.fms.ltcora.DataBean_LtcoraMaster ltcora = null;
      ltcora = (com.etrm.fms.ltcora.DataBean_LtcoraMaster) _jspx_page_context.getAttribute("ltcora", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (ltcora == null){
        ltcora = new com.etrm.fms.ltcora.DataBean_LtcoraMaster();
        _jspx_page_context.setAttribute("ltcora", ltcora, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.etrm.fms.util.MessageUtil utilmsg = null;
      utilmsg = (com.etrm.fms.util.MessageUtil) _jspx_page_context.getAttribute("utilmsg", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (utilmsg == null){
        utilmsg = new com.etrm.fms.util.MessageUtil();
        _jspx_page_context.setAttribute("utilmsg", utilmsg, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.etrm.fms.util.UtilBean utilBean = null;
      utilBean = (com.etrm.fms.util.UtilBean) _jspx_page_context.getAttribute("utilBean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (utilBean == null){
        utilBean = new com.etrm.fms.util.UtilBean();
        _jspx_page_context.setAttribute("utilBean", utilBean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');

String clearance=request.getParameter("clearance")==null?"":request.getParameter("clearance");
String counterparty_cd=request.getParameter("counterparty_cd")==null?"":request.getParameter("counterparty_cd");
String agreement_type = request.getParameter("agreement_type")==null?"F":request.getParameter("agreement_type");
String agmt_no=request.getParameter("agmt_no")==null?"":request.getParameter("agmt_no");
String agmt_rev_no=request.getParameter("agmt_rev_no")==null?"":request.getParameter("agmt_rev_no");
String start_dt=request.getParameter("start_dt")==null?"":request.getParameter("start_dt");
String end_dt=request.getParameter("end_dt")==null?"":request.getParameter("end_dt");
String buy_sale=request.getParameter("buy_sale")==null?"T":request.getParameter("buy_sale");
String display_agmt_id=utilBean.NewAgmtMappingId(owner_cd, counterparty_cd, agmt_no, agmt_rev_no, agreement_type);

ltcora.setCallFlag("LTCORA_AGMT_LIABILITY_CLAUSE");
ltcora.setComp_cd(owner_cd);
ltcora.setCont_start_dt(start_dt);
//ltcora.setCont_end_dt(end_dt);
ltcora.setBuy_sale(buy_sale);
ltcora.setCounterparty_cd(counterparty_cd);
ltcora.setAgmt_no(agmt_no);
ltcora.setAgmt_rev_no(agmt_rev_no);
ltcora.setAgmt_type(agreement_type);
ltcora.init();

String liab_lq_damg=ltcora.getLiab_lq_damg();
String ld_price_per=ltcora.getLd_price_per();
String ld_promise=ltcora.getLd_promise();
String ld_low_per=ltcora.getLd_low_per();
String ld_chk=ltcora.getLd_chk();
String remark=ltcora.getRemark();
String liab_take_pay=ltcora.getLiab_take_pay();
String top_price_per=ltcora.getTop_price_per();
String top_promise=ltcora.getTop_promise();
String top_per=ltcora.getTop_per();
String top_chk=ltcora.getTop_chk();
String top_obligation=ltcora.getTop_obligation();
String top_remark=ltcora.getTop_remark();
String liab_makeup=ltcora.getLiab_makeup();
String mug_price_per=ltcora.getMug_price_per();
String mug_period_per=ltcora.getMug_period_per();
String makeup_liab_on=ltcora.getMakeup_liab_on();
String recovery_day=ltcora.getRecovery_day();
String mug_remark=ltcora.getMug_remark();


      out.write("\r\n");
      out.write("<body onload=\"enableLDDetails();enableTOPDetails();enableMUGDetails();\">\r\n");
      out.write("<form method=\"post\" action=\"../servlet/Frm_LtcoraMaster\">\r\n");
      out.write("<div class=\"box-body\">\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("			");
if(!msg.equals("")){
				if(msg_type.equals("S")){
      out.write("\r\n");
      out.write("					<div class=\"fadealert\">");
      out.print(utilmsg.successMessage(msg));
      out.write("</div>\r\n");
      out.write("				");
}else if(msg_type.equals("E")){
      out.write("\r\n");
      out.write("					<div class=\"fadealert\">");
      out.print( utilmsg.errorMessage(msg));
      out.write("</div>\r\n");
      out.write("				");
}
			} 
      out.write("\r\n");
      out.write("			<div class=\"card cardmain\">\r\n");
      out.write("				<div class=\"card-header cdheader\">\r\n");
      out.write("					<div class=\"d-flex justify-content-between\">\r\n");
      out.write("					    <div class=\"topheader\">\r\n");
      out.write("						TMSA Liability Clause\r\n");
      out.write("					    </div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"card-body cdbody\">\r\n");
      out.write("					<div class=\"row m-b-5\">\r\n");
      out.write("						<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("							<input type=\"checkbox\" class=\"form-check-input\" name=\"liab_lq_damg\" value=\"Y\" onclick=\"enableLDDetails()\" ");
if(liab_lq_damg.equals("Y")){ 
      out.write("checked");
} 
      out.write(">&nbsp;<label class=\"form-label\"><b>Liquidated Damages</b></label>  \r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- <div class=\"row m-b-5\">\r\n");
      out.write("						<label class=\"form-label subheader\"><i class=\"fa fa-snowflake-o\"></i> Price (% of Contract Price)</label>\r\n");
      out.write("					</div> -->\r\n");
      out.write("					<div class=\"row m-b-5\">\r\n");
      out.write("						<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("							<label class=\"form-label\"><b>Price (% of Contract Price)<span class=\"s-red\">*</span></b></label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-4 col-xs-4 col-md-4\">\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\r\n");
      out.write("				    				<div class=\"input-group input-group-sm\" >\r\n");
      out.write("			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"ld_price_per\" id=\"ld_price_per\" value=\"");
      out.print(ld_price_per );
      out.write("\" size=\"8\" maxlength=\"8\" onblur=\"negNumber(this);appPercentage(this);\"> <!-- onblur=\"checkValuePrecision(this.value,'2','3','ld_price_per')\" -->\r\n");
      out.write("			      						<span class=\"input-group-text\">%</span>\r\n");
      out.write("		      						</div>\r\n");
      out.write("				    			</div>\r\n");
      out.write("				    		</div>\r\n");
      out.write("				    	</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row m-b-5\">\r\n");
      out.write("				    	<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("		    				<font color=\"\"><b>Promise Quantity Frequency</b></font>\r\n");
      out.write("		    			</div>\r\n");
      out.write("				    	<div class=\"col-sm-4 col-xs-4 col-md-4\">\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("								<div class=\"col-sm-12 col-xs-12 col-md-12\">\r\n");
      out.write("									<div class=\"input-group input-group-sm\" >\r\n");
      out.write("					    				<select class=\"form-select form-select-sm\" name=\"ld_promise\">\r\n");
      out.write("					    					<option value=\"D\">Daily</option>\r\n");
      out.write("					                        <option value=\"W\">Weekly</option>\r\n");
      out.write("					                        <option value=\"F\">Fortnightly </option>\r\n");
      out.write("					                        <option value=\"M\">Monthly </option>\r\n");
      out.write("					                        <option value=\"IC\">Invoice Cycle</option>\r\n");
      out.write("					                        <option value=\"T\">TCQ</option>\r\n");
      out.write("					                        <option value=\"DP\">Defined Period</option>\r\n");
      out.write("					                        <option value=\"SP\">Supply Period</option>\r\n");
      out.write("					                        <option value=\"DV\">Delivery Period</option>\r\n");
      out.write("					    				</select>\r\n");
      out.write("					    				<script>document.forms[0].ld_promise.value=\"");
      out.print(ld_promise);
      out.write("\"</script>\r\n");
      out.write("					    			</div>\r\n");
      out.write("				    			</div>\r\n");
      out.write("				    		</div>\r\n");
      out.write("				    	</div>\r\n");
      out.write("				    </div>\r\n");
      out.write("				    <div class=\"row m-b-5\">\r\n");
      out.write("				    	<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("		    				<font color=\"\"><b>Liability</b></font>\r\n");
      out.write("		    			</div>\r\n");
      out.write("				    	<div class=\"col-sm-4 col-xs-4 col-md-4\">\r\n");
      out.write("							<div class=\"form-group row\">  \r\n");
      out.write("								<div class=\"col-sm-5 col-xs-5 col-md-5\">\r\n");
      out.write("									<div class=\"input-group input-group-sm\"\">\r\n");
      out.write("										<input type=\"text\" class=\"form-control form-control-sm\" name=\"ld_low_per\" id=\"ld_low_per\" value=\"");
      out.print(ld_low_per);
      out.write("\" onblur=\"negNumber(this);appPercentage(this);\"> <!-- onblur=\"checkValuePrecision(this.value,'2','3','ld_low_per')\" -->	\r\n");
      out.write("										<span class=\"input-group-text\">%</span>	\r\n");
      out.write("									</div>							\r\n");
      out.write("								</div>	\r\n");
      out.write("								<div class=\"col-sm-1 col-xs-1 col-md-1\">\r\n");
      out.write("									<div class=\"form-group row\">				    			\r\n");
      out.write("										<div class=\"col-auto\">\r\n");
      out.write("											<label class=\"form-label\">&nbsp;of</label>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-sm-6 col-xs-6 col-md-6\">\r\n");
      out.write("									<div class=\"form-group row\">				    			\r\n");
      out.write("						  				<div class=\"input-group input-group-sm\" >\r\n");
      out.write("						    				<select class=\"form-select form-select-sm\" name=\"ld_chk\">\r\n");
      out.write("						    					<option value=\"\" selected=\"selected\">--Select--</option>\r\n");
      out.write("						    					<option value=\"E\">EDQ</option>\r\n");
      out.write("						                        <option value=\"A\">ADQ</option>\r\n");
      out.write("						                        <option value=\"L\">BL </option>\r\n");
      out.write("						                        <option value=\"B\">BOE </option>\r\n");
      out.write("						    				</select>\r\n");
      out.write("						    				<script>document.forms[0].ld_chk.value=\"");
      out.print(ld_chk);
      out.write("\"</script>\r\n");
      out.write("						    			</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>	\r\n");
      out.write("				    </div>\r\n");
      out.write("				    <div class=\"row m-b-5\">\r\n");
      out.write("						<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("							<label class=\"form-label\"><b>Remark</b></label>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"col-sm-10 col-xs-10 col-md-10\">\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\r\n");
      out.write("				    				<div class=\"input-group input-group-sm\" >\r\n");
      out.write("			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"remark\" value=\"");
      out.print(remark );
      out.write("\" size=\"80\" maxlength=\"200\">\r\n");
      out.write("		      						</div>\r\n");
      out.write("				    			</div>\r\n");
      out.write("				    		</div>\r\n");
      out.write("				    	</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"card-body cdbody\">\r\n");
      out.write("					<div class=\"row m-b-5\">\r\n");
      out.write("						<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("							<input type=\"checkbox\" class=\"form-check-input\" name=\"liab_take_pay\" value=\"Y\" onclick=\"enableTOPDetails()\" ");
if(liab_take_pay.equals("Y")){ 
      out.write("checked");
} 
      out.write(">&nbsp;<label class=\"form-label\"><b>Take or Pay</b></label> \r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- <div class=\"row m-b-5\">\r\n");
      out.write("						<label class=\"form-label subheader\"><i class=\"fa fa-snowflake-o\"></i> Price (% of Contract Price)</label>\r\n");
      out.write("					</div> -->\r\n");
      out.write("					<div class=\"row m-b-5\">\r\n");
      out.write("						<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("							<label class=\"form-label\"><b>Price (% of Contract Price)<span class=\"s-red\">*</span></b></label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-4 col-xs-4 col-md-4\">\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\r\n");
      out.write("				    				<div class=\"input-group input-group-sm\" >\r\n");
      out.write("			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"top_price_per\" id=\"top_price_per\" value=\"");
      out.print(top_price_per );
      out.write("\" size=\"8\" maxlength=\"8\" onblur=\"negNumber(this);appPercentage(this);\"><!--  onblur=\"checkValuePrecision(this.value,'2','3','top_price_per')\" -->\r\n");
      out.write("			      						<span class=\"input-group-text\">%</span>\r\n");
      out.write("		      						</div>\r\n");
      out.write("				    			</div>\r\n");
      out.write("				    		</div>\r\n");
      out.write("				    	</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					 <div class=\"row m-b-5\">\r\n");
      out.write("				    	<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("		    				<font color=\"\"><b>Promise Quantity Frequency</b></font>\r\n");
      out.write("		    			</div>\r\n");
      out.write("				    	<div class=\"col-sm-4 col-xs-4 col-md-4\">\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("								<div class=\"col-sm-12 col-xs-12 col-md-12\">\r\n");
      out.write("								<div class=\"input-group input-group-sm\" >\r\n");
      out.write("				    				<select class=\"form-select form-select-sm\" name=\"top_promise\">\r\n");
      out.write("				    					<option value=\"D\">Daily</option>\r\n");
      out.write("				                        <option value=\"W\">Weekly</option>\r\n");
      out.write("				                        <option value=\"F\">Fortnightly </option>\r\n");
      out.write("				                        <option value=\"M\">Monthly </option>\r\n");
      out.write("				                        <option value=\"IC\">Invoice Cycle</option>\r\n");
      out.write("				                        <option value=\"T\">TCQ</option>\r\n");
      out.write("				                        <option value=\"DP\">Defined Period</option>\r\n");
      out.write("				                        <option value=\"SP\">Supply Period</option>\r\n");
      out.write("				                        <option value=\"DV\">Delivery Period</option>\r\n");
      out.write("				    				</select>\r\n");
      out.write("				    				<script>document.forms[0].top_promise.value=\"");
      out.print(top_promise);
      out.write("\"</script>\r\n");
      out.write("				    			</div>\r\n");
      out.write("				    			</div>\r\n");
      out.write("				    		</div>\r\n");
      out.write("				    	</div>\r\n");
      out.write("				    </div>\r\n");
      out.write("					<div class=\"row m-b-5\">\r\n");
      out.write("				    	<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("		    				<font color=\"\"><b>Take or Pay</b></font>\r\n");
      out.write("		    			</div>\r\n");
      out.write("		    			<div class=\"col-sm-4 col-xs-4 col-md-4\">\r\n");
      out.write("							<div class=\"form-group row\">  \r\n");
      out.write("								<div class=\"col-sm-5 col-xs-5 col-md-5\">\r\n");
      out.write("									<div class=\"input-group input-group-sm\" >\r\n");
      out.write("										<input type=\"text\" class=\"form-control form-control-sm\" name=\"top_per\" id=\"top_per\" value=\"");
      out.print(top_per );
      out.write("\" size=\"5\" maxlength=\"8\" onblur=\"negNumber(this);appPercentage(this);\"><!--  onblur=\"checkValuePrecision(this.value,'2','3','top_per')\" -->\r\n");
      out.write("										<span class=\"input-group-text\">%</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-sm-1 col-xs-1 col-md-1\">\r\n");
      out.write("									<div class=\"form-group row\">				    			\r\n");
      out.write("										<div class=\"col-auto\">\r\n");
      out.write("											<label class=\"form-label\">&nbsp;of</label>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-sm-6 col-xs-6 col-md-6\">\r\n");
      out.write("									<div class=\"form-group row\">				    			\r\n");
      out.write("						  				<div class=\"input-group input-group-sm\" >\r\n");
      out.write("						    				<select class=\"form-select form-select-sm\" name=\"top_chk\">\r\n");
      out.write("						    					<option value=\"\" selected=\"selected\">--Select--</option>\r\n");
      out.write("						    					<option value=\"E\">EDQ</option>\r\n");
      out.write("						                        <option value=\"A\">ADQ</option>\r\n");
      out.write("						                        <option value=\"L\">BL </option>\r\n");
      out.write("						                        <option value=\"B\">BOE </option>\r\n");
      out.write("						    				</select>\r\n");
      out.write("						    				<script>document.forms[0].top_chk.value=\"");
      out.print(top_chk);
      out.write("\"</script>\r\n");
      out.write("						    			</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("				    </div>\r\n");
      out.write("				    <div class=\"row m-b-5\">\r\n");
      out.write("				    	<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("		    				<font color=\"\"><b>Actual Obligation To Take</b></font>\r\n");
      out.write("		    			</div>\r\n");
      out.write("				    	<div class=\"col-sm-4 col-xs-4 col-md-4\">\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("								<div class=\"col-sm-12 col-xs-12 col-md-12\">\r\n");
      out.write("									<div class=\"input-group input-group-sm\" >\r\n");
      out.write("			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"top_obligation\" value=\"");
      out.print(top_obligation );
      out.write("\" size=\"8\" maxlength=\"11\" onblur=\"negNumber(this);\">\r\n");
      out.write("			      						<span class=\"input-group-text\">MMBTU</span>\r\n");
      out.write("		      						</div>\r\n");
      out.write("				    			</div>\r\n");
      out.write("				    		</div>\r\n");
      out.write("				    	</div>\r\n");
      out.write("				    </div>\r\n");
      out.write("				   \r\n");
      out.write("				    <div class=\"row m-b-5\">\r\n");
      out.write("						<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("							<label class=\"form-label\"><b>Remark</b></label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-10 col-xs-10 col-md-10\">\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\r\n");
      out.write("				    				<div class=\"input-group input-group-sm\" >\r\n");
      out.write("			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"top_remark\" value=\"");
      out.print(top_remark );
      out.write("\" size=\"80\" maxlength=\"200\">\r\n");
      out.write("		      						</div>\r\n");
      out.write("				    			</div>\r\n");
      out.write("				    		</div>\r\n");
      out.write("				    	</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"card-body cdbody\">\r\n");
      out.write("					<div class=\"row m-b-5\">\r\n");
      out.write("						<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("							<input type=\"checkbox\" class=\"form-check-input\" name=\"liab_makeup\" value=\"Y\" onclick=\"enableMUGDetails()\" ");
if(liab_makeup.equals("Y")){ 
      out.write("checked");
} 
      out.write(">&nbsp;<label class=\"form-label\"><b>Make Up Gas</b></label> \r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- <div class=\"row m-b-5\">\r\n");
      out.write("						<label class=\"form-label subheader\"><i class=\"fa fa-snowflake-o\"></i> Price (% of Contract Price)</label>\r\n");
      out.write("					</div> -->\r\n");
      out.write("					<div class=\"row m-b-5\">\r\n");
      out.write("						<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("							<label class=\"form-label\"><b>Price (% of Contract Price)<span class=\"s-red\">*</span></b></label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-4 col-xs-4 col-md-4\">\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\r\n");
      out.write("				    				<div class=\"input-group input-group-sm\" >\r\n");
      out.write("			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"mug_price_per\" id=\"mug_price_per\" value=\"");
      out.print(mug_price_per );
      out.write("\" size=\"8\" maxlength=\"8\" onblur=\"negNumber(this);appPercentage(this);\" ><!-- onblur=\"checkValuePrecision(this.value,'2','3','mug_price_per')\" -->\r\n");
      out.write("			      						<span class=\"input-group-text\">%</span>\r\n");
      out.write("		      						</div>\r\n");
      out.write("				    			</div>\r\n");
      out.write("				    		</div>\r\n");
      out.write("				    	</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row m-b-5\">\r\n");
      out.write("						<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("							<label class=\"form-label\"><b>Make Up Period</b></label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-4 col-xs-4 col-md-4\">\r\n");
      out.write("							<div class=\"form-group row\">  \r\n");
      out.write("								<div class=\"col-sm-6 col-xs-6 col-md-6\">\r\n");
      out.write("									<div class=\"input-group input-group-sm\" >\r\n");
      out.write("			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"mug_period_per\" id=\"mug_period_per\" value=\"");
      out.print(mug_period_per );
      out.write("\" size=\"5\" maxlength=\"8\" onblur=\"negNumber(this);appPercentage(this);\"><!--  onblur=\"checkValuePrecision(this.value,'2','2','mug_period_per')\" -->\r\n");
      out.write("		      						</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-sm-6 col-xs-6 col-md-6\">\r\n");
      out.write("									<div class=\"input-group input-group-sm\" >\r\n");
      out.write("					    				<select class=\"form-select form-select-sm\" name=\"makeup_liab_on\">\r\n");
      out.write("					    					<option value=\"P\">% of Supply Period</option>\r\n");
      out.write("					                        <option value=\"D\">Days</option>\r\n");
      out.write("					    				</select>\r\n");
      out.write("					    				<script>document.forms[0].makeup_liab_on.value=\"");
      out.print(makeup_liab_on);
      out.write("\"</script>\r\n");
      out.write("				    				</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row m-b-5\">\r\n");
      out.write("						<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("							<label class=\"form-label\"><b>Recovery Period</b></label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-4 col-xs-4 col-md-4\">\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\r\n");
      out.write("				    				<div class=\"input-group input-group-sm\" >\r\n");
      out.write("			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"recovery_day\" id=\"recovery_day\" value=\"");
      out.print(recovery_day );
      out.write("\" size=\"5\" maxlength=\"5\" onblur=\"checkValuePrecision(this.value,'0','3','recovery_day');negNumber(this);\">\r\n");
      out.write("			      						<span class=\"input-group-text\">Days</span>\r\n");
      out.write("		      						</div>\r\n");
      out.write("				    			</div>\r\n");
      out.write("				    		</div>\r\n");
      out.write("				    	</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("				    <div class=\"row m-b-5\">\r\n");
      out.write("						<div class=\"col-sm-2 col-xs-2 col-md-2\">\r\n");
      out.write("							<label class=\"form-label\"><b>Remark</b></label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-10 col-xs-10 col-md-10\">\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("				    			<div class=\"col-sm-12 col-xs-12 col-md-12\">\r\n");
      out.write("				    				<div class=\"input-group input-group-sm\" >\r\n");
      out.write("			      						<input type=\"text\" class=\"form-control form-control-sm\" name=\"mug_remark\" value=\"");
      out.print(mug_remark );
      out.write("\" size=\"80\" maxlength=\"200\">\r\n");
      out.write("		      						</div>\r\n");
      out.write("				    			</div>\r\n");
      out.write("				    		</div>\r\n");
      out.write("				    	</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"card-footer cdfooter text-center\">\r\n");
      out.write("					<div class=\"d-flex justify-content-between\">\r\n");
      out.write("						<input type=\"button\" class=\"btn btn-warning com-btn\" value=\"Reset\" onclick=\"location.reload();\">\r\n");
      out.write("						");
if(write_access.equals("Y")){ 
      out.write("\r\n");
      out.write("						<input type=\"button\" class=\"btn btn-warning com-btn\" value=\"Submit\" onclick=\"doSubmit();\">\r\n");
      out.write("						");
}else{ 
      out.write("\r\n");
      out.write("						<input type=\"button\" class=\"btn btn-warning com-btn\" value=\"Submit\" disabled>\r\n");
      out.write("						");
} 
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"option\" value=\"LTCORA_AGMT_LIABILITY_CLAUSE\">\r\n");
      out.write("<input type=\"hidden\" name=\"counterparty_cd\" value=\"");
      out.print(counterparty_cd);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"agmt_no\" value=\"");
      out.print(agmt_no);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"agmt_rev_no\" value=\"");
      out.print(agmt_rev_no);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"clearance\" value=\"");
      out.print(clearance);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"start_dt\" value=\"");
      out.print(start_dt);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"agreement_type\" value=\"");
      out.print(agreement_type);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"buy_sale\" value=\"");
      out.print(buy_sale);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"read_access\" value=\"");
      out.print(read_access);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"write_access\" value=\"");
      out.print(write_access);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"check_access\" value=\"");
      out.print(check_access);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"print_access\" value=\"");
      out.print(print_access);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"delete_access\" value=\"");
      out.print(delete_access);
      out.write("\">  	\r\n");
      out.write("<input type=\"hidden\" name=\"audit_access\" value=\"");
      out.print(audit_access);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"authorize_access\" value=\"");
      out.print(authorize_access);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"approve_access\" value=\"");
      out.print(approve_access);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"execute_access\" value=\"");
      out.print(execute_access);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"form_cd\" value=\"");
      out.print(formCd);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"form_nm\" value=\"");
      out.print(formNm);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"mod_cd\" value=\"");
      out.print(mod_cd);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"mod_nm\" value=\"");
      out.print(mod_nm);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"u\" value=\"");
      out.print(u);
      out.write("\">\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
