/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2025-08-20 08:18:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.dlng;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.File;
import com.etrm.fms.util.CommonVariable;
import java.util.Vector;
import com.etrm.fms.util.CommonVariable;
import com.etrm.fms.util.EncryptTest;

public final class frm_005fsign_005fpdf_005fmail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/dlng/../util/../sess/Expire.jsp", Long.valueOf(1754630867476L));
    _jspx_dependants.put("/dlng/../home/loading.jsp", Long.valueOf(1754630775663L));
    _jspx_dependants.put("/dlng/../util/common_js.jsp", Long.valueOf(1754630867617L));
    _jspx_dependants.put("/dlng/../util/common_val.jsp", Long.valueOf(1754630867617L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("com.etrm.fms.util.CommonVariable");
    _jspx_imports_classes.add("com.etrm.fms.util.EncryptTest");
    _jspx_imports_classes.add("java.io.File");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n");
      out.write('\n');

String expire_msg = request.getParameter("expire_msg")==null?"":request.getParameter("expire_msg");
if(session.getAttribute("emp_uid")==null || session.getAttribute("emp_uid") == ""|| session.getAttribute("emp_uid").toString().equals("null"))
{
      out.write("\r\n		<script>\r\n			alert(\"Please Enter Login Detail!\")\r\n			var url = \"../home/login.jsp\";\r\n			location.replace(url);\r\n		</script>\r\n");
}
else
{
	if(expire_msg.equals("Timeout"))
	{
		session.invalidate();
	
      out.write("\r\n		<script>\r\n		var url = \"../home/login.jsp?sess=Session Expired\";\r\n		location.replace(url);\r\n		</script>\r\n	");

	}
	else if(expire_msg.equals("PwdChng"))
	{
		session.invalidate();
	
      out.write("\r\n		<script>\r\n		var url = \"../home/login.jsp\";\r\n		location.replace(url);\r\n		</script>\r\n	");
}
}

      out.write("\r\n\r\n");
      out.write('\n');
String COMMlogo="";
if(session.getAttribute("comp_logo")==null||session.getAttribute("comp_logo")==""||session.getAttribute("comp_logo").toString().equals("null"))
{
	COMMlogo="";
}  
else
{
	COMMlogo=""+session.getAttribute("comp_logo");
}

String sel_comp_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	sel_comp_cd="";
}  
else
{
	sel_comp_cd=""+session.getAttribute("comp_cd");
}

      out.write("\n<link rel=\"SHORTCUT ICON\" href=\"../images/");
      out.print(COMMlogo);
      out.write("\">\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<meta http-equiv=\"refresh\" content=\"");
      out.print(session.getMaxInactiveInterval());
      out.write(";url=../sess/Expire.jsp?expire_msg=Timeout\"/>\n<title>");
      out.print(CommonVariable.app_name);
      out.write("</title>\n\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap/bootstrap5/css/bootstrap.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../font-awesome-4.7.0/css/font-awesome.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/datepicker/bootstrap-datepicker3.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/util.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/main.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/navbar.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/responsive.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">\n\n");
 if ("2".equals(sel_comp_cd)) { 
      out.write("\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common_2.css\">  <!-- CSS for comp_cd = \"2\" -->\n");
 } else { 
      out.write("\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">  <!-- CSS for comp_cd = \"1\" -->\n");
 } 
      out.write("\n\n<script type=\"text/javascript\" src=\"../bootstrap/bootstrap5/js/bootstrap.bundle.min.js\"></script>\n<script type=\"text/javascript\" src=\"../js/jquery.min.js\"></script>\n<script type=\"text/javascript\" src=\"../js/datepicker/bootstrap-datepicker.min.js\"></script>\n<script type=\"text/javascript\" src=\"../js/datepicker/bootstrap-datepicker.es.min.js\"></script>\n\n<script type=\"text/javascript\" src=\"../js/util.js\"></script>\n");
      out.write("\n<script type=\"text/javascript\" src=\"../js/session.js\"></script>\n\n");
      out.write('\r');
      out.write('\n');
      com.etrm.fms.util.DataBean_Menu menu_access = null;
      menu_access = (com.etrm.fms.util.DataBean_Menu) _jspx_page_context.getAttribute("menu_access", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (menu_access == null){
        menu_access = new com.etrm.fms.util.DataBean_Menu();
        _jspx_page_context.setAttribute("menu_access", menu_access, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

String formCd="";
String mod_cd="";
String u=request.getParameter("u")==null?"":request.getParameter("u");

String msg=request.getParameter("msg")==null?"":request.getParameter("msg");
String msg_type=request.getParameter("msg_type")==null?"":request.getParameter("msg_type");

String owner_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	owner_cd="";
}  
else
{
	owner_cd=""+session.getAttribute("comp_cd");
}

String owner_abbr="";
if(session.getAttribute("comp_abbr")==null||session.getAttribute("comp_abbr")==""||session.getAttribute("comp_abbr").toString().equals("null"))
{
	owner_abbr="";
}  
else
{
	owner_abbr=""+session.getAttribute("comp_abbr");
}

String emp_cd="";
if(session.getAttribute("emp_cd")==null||session.getAttribute("emp_cd")==""||session.getAttribute("emp_cd").toString().equals("null"))
{
	emp_cd="";
}  
else
{
	emp_cd=""+session.getAttribute("emp_cd");
}

if(!u.equals(""))
{
	StringBuffer decryt=new EncryptTest().URLdecrypt(u);
	String dec=""+decryt;
	if(!dec.equals("") && dec.contains("-"))
	{
		String temp[]=dec.split("-");
		if(temp.length==2)
		{
			formCd=temp[0];
			mod_cd=temp[1];
		}
	}
}

menu_access.setCallFlag("MENU_ACCESS");
menu_access.setEmpCd(emp_cd);
menu_access.setComp_cd(owner_cd);
menu_access.setModule_cd(mod_cd);
menu_access.setForm_cd(formCd);
menu_access.init();


String formNm = menu_access.getForm_nm();
String mod_nm = menu_access.getModule_nm();
String read_access = menu_access.getRead_access();
String write_access = menu_access.getWrite_access();
String check_access = menu_access.getCheck_access();
String print_access = menu_access.getPrint_access();
String delete_access = menu_access.getDelete_access();
String audit_access = menu_access.getAudit_access();
String authorize_access = menu_access.getAuthorize_access();
String approve_access = menu_access.getApprove_access();
String execute_access = menu_access.getExecute_access();


      out.write("\n\n<script type=\"text/javascript\">\ndocument.title = \"");
      out.print(CommonVariable.app_name);
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(owner_abbr);
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(formNm);
      out.write("\";\n</script>\n");
      out.write("\r\n<script>\r\nfunction openPdfFile(url)\r\n{\r\n	window.open(url);\r\n}\r\n\r\nfunction Do_close()\r\n{\r\n	window.opener.refresh();\r\n	window.close();\r\n}\r\n\r\nfunction doSubmit(index)\r\n{\r\n	var execute_access = document.forms[0].execute_access.value;\r\n	\r\n	var email_from = document.getElementById(\"email_from\"+index).value;\r\n	var email_to = document.getElementById(\"email_to\"+index).value;\r\n	var email_cc = document.getElementById(\"email_cc\"+index).value;\r\n	var email_bcc = document.getElementById(\"email_bcc\"+index).value;\r\n	var subject = document.getElementById(\"subject\"+index).value;\r\n	//var attachment = document.getElementById(\"attachment\"+index).value;\r\n	var temp_email_body = document.getElementById(\"temp_email_body\"+index).value;\r\n	var pdf_type_nm = document.getElementById(\"pdf_type_nm\"+index).value;\r\n	\r\n	document.getElementById(\"email_body\"+index).value=temp_email_body;\r\n	var email_body = document.getElementById(\"email_body\"+index).value;\r\n	var u = document.forms[0].u.value;\r\n	var msg=\"\";\r\n	var flag=true;\r\n	\r\n	if(execute_access==\"N\")\r\n");
      out.write("	{\r\n		msg+=\"You don't have Execute Rights!\\n\";\r\n		flag=false;\r\n	}\r\n	\r\n	if(trim(email_from)==\"\")\r\n	{\r\n		msg+=\"From Mail Id Missing!\\n\";\r\n		flag=false;\r\n	}\r\n	if(trim(email_to)==\"\")\r\n	{\r\n		msg+=\"To Mail Id Missing!\\n\";\r\n		flag=false;\r\n	}\r\n	/* if(trim(email_cc)==\"\")\r\n	{\r\n		msg+=\"Cc Mail Id Missing!\\n\";\r\n		flag=false;\r\n	} */\r\n	if(trim(subject)==\"\")\r\n	{\r\n		msg+=\"Subject line cann't be blank!\\n\";\r\n		flag=false;\r\n	}\r\n	/* if(trim(attachment)==\"\")\r\n	{\r\n		msg+=\"Attachment Missing!\\n\";\r\n		flag=false;\r\n	} */\r\n	if(trim(email_body)==\"\")\r\n	{\r\n		msg+=\"Email Body Empty!\\n\";\r\n		flag=false;\r\n	}\r\n	\r\n	if(flag)\r\n	{\r\n		var a = confirm(\"Do you want to Send Mail with \"+pdf_type_nm+\"?\")\r\n		if(a)\r\n		{\r\n			setEnable(index);\r\n			document.getElementById(\"loading\").style.visibility = \"visible\";\r\n			document.forms[0].submit();\r\n		}\r\n	}\r\n	else\r\n	{\r\n		alert(msg);\r\n		setDisable();\r\n	}\r\n}\r\n\r\nfunction doSendAll()\r\n{\r\n	var email_from = document.forms[0].email_from;\r\n	var email_to = document.forms[0].email_to;\r\n	var email_cc = document.forms[0].email_cc;\r\n");
      out.write("	var email_bcc = document.forms[0].email_bcc;\r\n	var subject = document.forms[0].subject;\r\n	//var attachment = document.forms[0].attachment;\r\n	\r\n	var execute_access = document.forms[0].execute_access.value;\r\n	\r\n	var msg=\"\";\r\n	var flag=true;\r\n	\r\n	if(execute_access==\"N\")\r\n	{\r\n		msg+=\"You don't have Execute Rights!\\n\";\r\n		flag=false;\r\n	}\r\n	\r\n	for(var i=0;i<subject.length;i++)\r\n	{ \r\n		setEnable(i);\r\n		\r\n		var temp_email_body = document.getElementById(\"temp_email_body\"+i).value;\r\n		document.getElementById(\"email_body\"+i).value=temp_email_body;\r\n		\r\n		var email_body = document.forms[0].email_body;\r\n		\r\n		if(trim(email_from[i].value)==\"\")\r\n		{\r\n			msg+=\"From Mail Id Missing!\\n\";\r\n			flag=false;\r\n		}\r\n		if(trim(email_to[i].value)==\"\")\r\n		{\r\n			msg+=\"To Mail Id Missing!\\n\";\r\n			flag=false;\r\n		}\r\n		/* if(trim(email_cc[i].value)==\"\")\r\n		{\r\n			msg+=\"Cc Mail Id Missing!\\n\";\r\n			flag=false;\r\n		} */\r\n		if(trim(subject[i].value)==\"\")\r\n		{\r\n			msg+=\"Subject line cann't be blank!\\n\";\r\n			flag=false;\r\n		}\r\n		/* if(trim(attachment[i].value)==\"\")\r\n");
      out.write("		{\r\n			msg+=\"Attachment Missing!\\n\";\r\n			flag=false;\r\n		} */\r\n		if(trim(email_body[i].value)==\"\")\r\n		{\r\n			msg+=\"Email Body Empty!\\n\";\r\n			flag=false;\r\n		}\r\n	}	\r\n	\r\n	if(flag)\r\n	{\r\n		var a = confirm(\"Do you want to Send All Mails together?\")\r\n		if(a)\r\n		{			\r\n			document.getElementById(\"loading\").style.visibility = \"visible\";\r\n			document.forms[0].submit();\r\n		}\r\n	}\r\n	else\r\n	{\r\n		alert(msg);\r\n		setDisable();\r\n	}\r\n}\r\n\r\nfunction setEnable(index) \r\n{\r\n	var email_from = document.getElementById(\"email_from\"+index);\r\n	var email_to = document.getElementById(\"email_to\"+index);\r\n	var email_cc = document.getElementById(\"email_cc\"+index);\r\n	var email_bcc = document.getElementById(\"email_bcc\"+index);\r\n	var subject = document.getElementById(\"subject\"+index);\r\n	//var attachment = document.getElementById(\"attachment\"+index);\r\n	var email_body = document.getElementById(\"email_body\"+index);\r\n	var temp_index = document.getElementById(\"index\"+index);\r\n	var pdf_size = document.getElementById(\"pdf_size\"+index);\r\n	\r\n	email_from.disabled=false;\r\n");
      out.write("	email_to.disabled=false;\r\n	email_cc.disabled=false;\r\n	email_bcc.disabled=false;\r\n	subject.disabled=false;\r\n	//attachment.disabled=false;\r\n	email_body.disabled=false;\r\n	temp_index.disabled=false;\r\n	\r\n	for(var i=0;i<parseInt(pdf_size.value);i++)\r\n	{\r\n		document.getElementById(\"attachment\"+index+\"_\"+i).disabled=false;\r\n	}\r\n}\r\n\r\nfunction setDisable() \r\n{\r\n	var email_from = document.forms[0].email_from;\r\n	var email_to = document.forms[0].email_to;\r\n	var email_cc = document.forms[0].email_cc;\r\n	var email_bcc = document.forms[0].email_bcc;\r\n	var subject = document.forms[0].subject;\r\n	//var attachment = document.forms[0].attachment;\r\n	var email_body = document.forms[0].email_body;\r\n	var temp_index = document.forms[0].index;\r\n	var pdf_size = document.forms[0].pdf_size;\r\n	\r\n	if(email_to!=null && email_to!=undefined)\r\n	{\r\n		if(email_to.length!=undefined)\r\n		{\r\n			for(var i=0;i<email_to.length; i++)\r\n			{\r\n				email_from[i].disabled=true;\r\n				email_to[i].disabled=true;\r\n				email_cc[i].disabled=true;\r\n				email_bcc[i].disabled=true;\r\n");
      out.write("				subject[i].disabled=true;\r\n				//attachment[i].disabled=true;\r\n				email_body[i].disabled=true;\r\n				temp_index[i].disabled=true;\r\n				\r\n				for(var j=0;j<parseInt(pdf_size.value);j++)\r\n				{\r\n					document.getElementById(\"attachment\"+i+\"_\"+j).disabled=false;\r\n				}\r\n			}\r\n		}\r\n		else\r\n		{\r\n			email_from.disabled=true;\r\n			email_to.disabled=true;\r\n			email_cc.disabled=true;\r\n			email_bcc.disabled=true;\r\n			subject.disabled=true;\r\n			//attachment.disabled=true;\r\n			email_body.disabled=true;\r\n			temp_index.disabled=true;\r\n			\r\n			for(var j=0;j<parseInt(pdf_size.value);j++)\r\n			{\r\n				document.getElementById(\"attachment0_\"+j).disabled=false;\r\n			}\r\n		}\r\n	}\r\n}\r\n</script>\r\n</head>\r\n");
      com.etrm.fms.dlng.DataBean_DLNG_Invoice dlng_inv = null;
      dlng_inv = (com.etrm.fms.dlng.DataBean_DLNG_Invoice) _jspx_page_context.getAttribute("dlng_inv", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (dlng_inv == null){
        dlng_inv = new com.etrm.fms.dlng.DataBean_DLNG_Invoice();
        _jspx_page_context.setAttribute("dlng_inv", dlng_inv, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.etrm.fms.util.MessageUtil utilmsg = null;
      utilmsg = (com.etrm.fms.util.MessageUtil) _jspx_page_context.getAttribute("utilmsg", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (utilmsg == null){
        utilmsg = new com.etrm.fms.util.MessageUtil();
        _jspx_page_context.setAttribute("utilmsg", utilmsg, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');

String counterparty_cd=request.getParameter("counterparty_cd")==null?"":request.getParameter("counterparty_cd");
String contract_type=request.getParameter("contract_type")==null?"":request.getParameter("contract_type");
String cont_no=request.getParameter("cont_no")==null?"":request.getParameter("cont_no");
String cont_rev=request.getParameter("cont_rev")==null?"":request.getParameter("cont_rev");
String agmt_no=request.getParameter("agmt_no")==null?"":request.getParameter("agmt_no");
String agmt_rev=request.getParameter("agmt_rev")==null?"":request.getParameter("agmt_rev");
String plant_seq=request.getParameter("plant_seq")==null?"":request.getParameter("plant_seq");
String billing_cycle=request.getParameter("billing_cycle")==null?"":request.getParameter("billing_cycle");
String period_start_dt=request.getParameter("period_start_dt")==null?"":request.getParameter("period_start_dt");
String period_end_dt=request.getParameter("period_end_dt")==null?"":request.getParameter("period_end_dt");
String bu_unit=request.getParameter("bu_unit")==null?"":request.getParameter("bu_unit");
String financial_year=request.getParameter("financial_year")==null?"":request.getParameter("financial_year");
String bu_state_tin=request.getParameter("bu_state_tin")==null?"":request.getParameter("bu_state_tin");
String invoice_seq=request.getParameter("invoice_seq")==null?"":request.getParameter("invoice_seq");
String mail_pdf_type=request.getParameter("mail_pdf_type")==null?"":request.getParameter("mail_pdf_type");
String mail_inv_type=request.getParameter("mail_inv_type")==null?"":request.getParameter("mail_inv_type");
String invoice_type=request.getParameter("invoice_type")==null?"":request.getParameter("invoice_type");

dlng_inv.setCallFlag("DLNG_SEND_INVOICE_MAIL");
dlng_inv.setComp_cd(owner_cd);
dlng_inv.setCounterparty_cd(counterparty_cd);
dlng_inv.setAgmt_no(agmt_no);
dlng_inv.setAgmt_rev_no(agmt_rev);
dlng_inv.setCont_no(cont_no);
dlng_inv.setCont_rev_no(cont_rev);
dlng_inv.setContract_type(contract_type);
dlng_inv.setPlant_seq(plant_seq);
dlng_inv.setBilling_cycle(billing_cycle);
dlng_inv.setPeriod_start_dt(period_start_dt);
dlng_inv.setPeriod_end_dt(period_end_dt);
dlng_inv.setBu_unit(bu_unit);
dlng_inv.setFinancial_year(financial_year);
dlng_inv.setBu_state_tin(bu_state_tin);
dlng_inv.setInvoice_seq(invoice_seq);
dlng_inv.setMail_pdf_type(mail_pdf_type);
dlng_inv.setMail_inv_type(mail_inv_type);
dlng_inv.setInvoice_type(invoice_type);
dlng_inv.init();

Vector VMAIL_PDF_TYPE = dlng_inv.getVMAIL_PDF_TYPE();
Vector VMAIL_PDF_TYPE_NM = dlng_inv.getVMAIL_PDF_TYPE_NM();
Vector VMAIL_FROM_LIST = dlng_inv.getVMAIL_FROM_LIST();
Vector VMAIL_TO_LIST = dlng_inv.getVMAIL_TO_LIST();
Vector VMAIL_CC_LIST = dlng_inv.getVMAIL_CC_LIST();
Vector VMAIL_BCC_LIST = dlng_inv.getVMAIL_BCC_LIST();
Vector VMAIL_SUBJECT = dlng_inv.getVMAIL_SUBJECT();
Vector VMAIL_ATTACHMENT = dlng_inv.getVMAIL_ATTACHMENT();
Vector VMAIL_ATTACHMENT_PATH = dlng_inv.getVMAIL_ATTACHMENT_PATH();
Vector VMAIL_BODY = dlng_inv.getVMAIL_BODY();
Vector VMAIL_ANNEXURE_ATTACHMENT_PATH = dlng_inv.getVMAIL_ANNEXURE_ATTACHMENT_PATH();
Vector VMAIL_ANNEXURE_ATTACHMENT_FLAG = dlng_inv.getVMAIL_ANNEXURE_ATTACHMENT_FLAG();

String context_nm = request.getContextPath();
String server_nm = request.getServerName();
String server_port = ""+request.getServerPort();
String url=CommonVariable.app_protocol+"://"+server_nm+":"+server_port+context_nm+"//"+CommonVariable.work_dir+owner_cd;

String path ="/"+CommonVariable.work_dir+owner_cd+"/"+CommonVariable.signed_dlng_sales_inv_path;
String annexure_path="";
if(mail_inv_type.equals("F"))
{
	path ="/"+CommonVariable.work_dir+owner_cd+"/"+CommonVariable.signed_freeflow_inv_path;
	annexure_path="/"+CommonVariable.work_dir+owner_cd+"/"+CommonVariable.freeflow_annexure_path+"/"+invoice_type+"_"+financial_year+"_"+bu_state_tin+"_"+invoice_seq+"/";
}
String file_path = request.getRealPath(path);
String annexure_file_path = request.getRealPath(annexure_path);
//System.out.println(file_path);

String form402_path ="/"+CommonVariable.work_dir+owner_cd+"/"+CommonVariable.form_402_dir;
String file402_path = request.getRealPath(form402_path);

      out.write("\r\n<body ");
if(!msg.equals("")){ 
      out.write("onload=\"Do_close();\"");
} 
      out.write('>');
      out.write('\r');
      out.write('\n');
      out.write("<div id=\"loading\" style=\"visibility: hidden;\">\n	<div id=\"loading-image\">\n		<div class=\"btn-group\">\n			<label class=\"btn\" style=\"color:var(--header_color);border:none;font-size:20px;align-self: center;font-weight:bold;\">\n				<i class=\"fa fa-spinner fa-pulse fa-lg\"></i>&nbsp;Loading\n			</label>\n		</div>\n	</div>\n</div>");
      out.write("\r\n<form method=\"post\" action=\"../servlet/Frm_DLNG_Invoice\">\r\n<div class=\"box-body\">\r\n	<div class=\"row\">\r\n		<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n			<div class=\"card cardmain\">\r\n				<div class=\"card-header cdheader\">\r\n					<div class=\"d-flex justify-content-between\">\r\n					    <div class=\"topheader\">\r\n					    	Send Mail\r\n					    </div>\r\n					    ");
if(VMAIL_PDF_TYPE.size()>1){ 
      out.write("\r\n					    <div class=\"btn-group\">\r\n							<label class=\"btn btn-outline-secondary btngrp\" onclick=\"doSendAll()\">\r\n								<i class=\"fa fa-envelope-o fa-lg\"></i>&nbsp;Send All\r\n							</label>\r\n						</div>\r\n						");
} 
      out.write("\r\n					</div>\r\n				</div>\r\n				<div class=\"card-body cdbody\">\r\n				");
for(int i=0; i<VMAIL_PDF_TYPE.size(); i++)
				{ 
      out.write("\r\n					");
if(i!=0){ 
      out.write("&nbsp;");
} 
      out.write("\r\n					<div class=\"accordion\">\r\n						<div class=\"accordion-item accor_item\">\r\n							<h2 class=\"accordion-header\" id=\"heading");
      out.print(i);
      out.write("\">\r\n 								<button class=\"accordion-button collapsed accor-btn\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapse");
      out.print(i);
      out.write("\" aria-expanded=\"false\" aria-controls=\"collapse");
      out.print(i);
      out.write("\">\r\n					    		");
      out.print(VMAIL_PDF_TYPE_NM.elementAt(i));
      out.write("\r\n					      		</button>\r\n					    	</h2>\r\n					    	<div id=\"collapse");
      out.print(i);
      out.write("\" class=\"accordion-collapse collapse\" aria-labelledby=\"heading");
      out.print(i);
      out.write("\">\r\n					      		<div class=\"accordion-body accor-body\">	\r\n									<div class=\"card-body cdbody\" style=\"background:#c2d1f0;\">\r\n										<div class=\"row m-b-5\">\r\n											<div class=\"col-auto\">\r\n												<div class=\"row h-100\">\r\n													<div class=\"col-12\">\r\n														<div class=\"btn card h-100 p-2\" onclick=\"doSubmit('");
      out.print(i);
      out.write("');\" style=\"text-align:center;background: #e9ecef;border: 1px solid #ced4da; justify-content: center;\">\r\n															<span>\r\n																<i class=\"fa fa-envelope fa-2x\" style=\"color:var(--header_color)\"></i>\r\n																<br>\r\n																<span style=\"font-weight: bold\">Send Mail</span>\r\n															</span>\r\n														</div>\r\n													</div>\r\n												</div>\r\n											</div>\r\n											<div class=\"col\">\r\n												<div class=\"row\">\r\n													<div class=\"col-12\">\r\n														<div class=\"input-group mb-1\">				\r\n															<span class=\"input-group-text\" style=\"font-weight: bold\">From:</span>\r\n															<input type=\"text\" class=\"form-control\" size=\"100\" name=\"email_from\" id=\"email_from");
      out.print(i);
      out.write("\" readonly=\"readonly\" style=\"background-color: white;\" value=\"");
      out.print(VMAIL_FROM_LIST.elementAt(i));
      out.write("\" disabled>\r\n														</div>\r\n														<input type=\"hidden\" class=\"form-control\" size=\"100\" name=\"pdf_type_nm\" id=\"pdf_type_nm");
      out.print(i);
      out.write("\" readonly=\"readonly\" style=\"background-color: white;\" value=\"");
      out.print(VMAIL_PDF_TYPE_NM.elementAt(i));
      out.write("\" disabled>\r\n													</div>\r\n													<div class=\"col-12\">\r\n														<div class=\"input-group mb-1\">				\r\n															<span class=\"input-group-text\" style=\"font-weight: bold\">To...</span>\r\n															<input type=\"text\" class=\"form-control\" name=\"email_to\" id=\"email_to");
      out.print(i);
      out.write("\" size=\"100\" value=\"");
      out.print(VMAIL_TO_LIST.elementAt(i));
      out.write("\" readonly=\"readonly\" style=\"background-color: white;\" disabled>\r\n														</div>\r\n													</div>\r\n													<div class=\"col-12\">\r\n														<div class=\"input-group mb-1\">				\r\n															<span class=\"input-group-text\" style=\"font-weight: bold\">Cc...</span>\r\n															<input type=\"text\" class=\"form-control\" name=\"email_cc\" id=\"email_cc");
      out.print(i);
      out.write("\" size=\"100\" value=\"");
      out.print(VMAIL_CC_LIST.elementAt(i));
      out.write("\" readonly=\"readonly\" style=\"background-color: white;\" disabled>\r\n														</div>\r\n													</div>\r\n													<div class=\"col-12\">\r\n														<div class=\"input-group mb-1\">				\r\n															<span class=\"input-group-text\" style=\"font-weight: bold\">Bcc..</span>\r\n															<input type=\"text\" class=\"form-control\" name=\"email_bcc\" id=\"email_bcc");
      out.print(i);
      out.write("\" size=\"100\" value=\"");
      out.print(VMAIL_BCC_LIST.elementAt(i));
      out.write("\" readonly=\"readonly\" style=\"background-color: white;\" disabled>\r\n														</div>\r\n													</div>\r\n												</div>\r\n											</div>\r\n										</div>\r\n										<div class=\"row m-b-5\">\r\n											<div class=\"col\">	\r\n												<div class=\"row\">\r\n													<div class=\"col-12\">\r\n														<div class=\"input-group mb-1\">				\r\n															<span class=\"input-group-text\" style=\"font-weight: bold\">Subject:</span>\r\n															<input type=\"text\" class=\"form-control\" name=\"subject\" id=\"subject");
      out.print(i);
      out.write("\" size=\"100\" value=\"");
      out.print(VMAIL_SUBJECT.elementAt(i));
      out.write("\" \r\n																readonly=\"readonly\" style=\"background-color: white;\" disabled>\r\n														</div>\r\n														<input type=\"hidden\" class=\"form-control\" name=\"index\" id=\"index");
      out.print(i);
      out.write("\" value=\"");
      out.print(i);
      out.write("\" disabled>\r\n													</div>\r\n													<div class=\"col-12\">\r\n														");
      out.write("\r\n														\r\n														<div class=\"input-group mb-1\">				\r\n															<span class=\"input-group-text\" style=\"font-weight: bold\">Attached:</span>\r\n															");
if(VMAIL_PDF_TYPE_NM.elementAt(i).equals("Form 402")) {
      out.write("\r\n															<span class=\"form-control\" style=\"cursor: pointer;\" title=\"Click to Download Form 402\">\r\n															");
for(int k=0;k<((Vector)VMAIL_ATTACHMENT.elementAt(i)).size();k++){ 
      out.write("\r\n																<a href=\"../");
      out.print(CommonVariable.work_dir+owner_cd);
      out.write('/');
      out.write('/');
      out.print(VMAIL_ATTACHMENT_PATH.elementAt(i));
      out.print(((Vector)VMAIL_ATTACHMENT.elementAt(i)).elementAt(k));
      out.write("\">\r\n																	<i class=\"fa fa-file-excel-o\" style=\"color:green;\"></i>&nbsp;");
      out.print(((Vector)VMAIL_ATTACHMENT.elementAt(i)).elementAt(k));
      out.write("\r\n																</a>\r\n															");
} 
      out.write("\r\n															</span>\r\n															");
}else{
      out.write("\r\n															<span class=\"form-control\" style=\"cursor: pointer;\" title=\"Click to View Attachment\">\r\n															");
for(int k=0;k<((Vector)VMAIL_ATTACHMENT.elementAt(i)).size();k++){ 
      out.write("\r\n																<spnn\r\n																");
if(((Vector)VMAIL_ANNEXURE_ATTACHMENT_FLAG.elementAt(i)).elementAt(k).equals("Y")){ 
      out.write(" \r\n																	onclick=\"openPdfFile('");
      out.print(url);
      out.print(VMAIL_ANNEXURE_ATTACHMENT_PATH.elementAt(i));
      out.print(((Vector)VMAIL_ATTACHMENT.elementAt(i)).elementAt(k));
      out.write("');\"\r\n																");
}else{ 
      out.write("\r\n																	onclick=\"openPdfFile('");
      out.print(url);
      out.print(VMAIL_ATTACHMENT_PATH.elementAt(i));
      out.print(((Vector)VMAIL_ATTACHMENT.elementAt(i)).elementAt(k));
      out.write("');\"\r\n																");
}
      out.write("	\r\n																>\r\n																	<i class=\"fa fa-file-pdf-o\" style=\"color:red;\"></i>&nbsp;");
      out.print(((Vector)VMAIL_ATTACHMENT.elementAt(i)).elementAt(k));
      out.write("\r\n																</spnn>\r\n															");
} 
      out.write("\r\n															</span>\r\n															");
} 
      out.write("\r\n															<input type=\"hidden\" name=\"pdf_size\" id=\"pdf_size");
      out.print(i);
      out.write("\" value=\"");
      out.print(((Vector)VMAIL_ATTACHMENT.elementAt(i)).size());
      out.write("\">\r\n														</div>\r\n														");
for(int k=0;k<((Vector)VMAIL_ATTACHMENT.elementAt(i)).size();k++){ 
      out.write("\r\n															<input type=\"hidden\" class=\"form-control\" name=\"attachment");
      out.print(i);
      out.write("\" id=\"attachment");
      out.print(i);
      out.write('_');
      out.print(k);
      out.write("\" title=\"Click to View Attachment\" size=\"100\" \r\n															");
if(VMAIL_PDF_TYPE_NM.elementAt(i).equals("Form 402")) {
      out.write("\r\n																value=\"");
      out.print(file402_path);
      out.print(File.separator);
      out.print(((Vector)VMAIL_ATTACHMENT.elementAt(i)).elementAt(k));
      out.write("\" \r\n															");
}else{ 
      out.write("\r\n																");
if(((Vector)VMAIL_ANNEXURE_ATTACHMENT_FLAG.elementAt(i)).elementAt(k).equals("Y")){ 
      out.write("\r\n																	value=\"");
      out.print(annexure_file_path);
      out.print(File.separator);
      out.print(((Vector)VMAIL_ATTACHMENT.elementAt(i)).elementAt(k));
      out.write("\" \r\n																");
}else{ 
      out.write("\r\n																	value=\"");
      out.print(file_path);
      out.print(File.separator);
      out.print(((Vector)VMAIL_ATTACHMENT.elementAt(i)).elementAt(k));
      out.write("\" \r\n																");
}
      out.write(" \r\n															");
}
      out.write("\r\n															disabled>\r\n														");
} 
      out.write("																\r\n													</div>				\r\n												</div>\r\n											</div>\r\n										</div>	\r\n									</div>\r\n									<div class=\"card-body cdbody\" style=\"background:#e6e6e6;\">	\r\n										<div class=\"form-group\">\r\n							  				<textarea class=\"form-control\" rows=\"12\" cols=\"95\" style=\"overflow: auto;\" name=\"temp_email_body\" id=\"temp_email_body");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(VMAIL_BODY.elementAt(i) );
      out.write("</textarea>\r\n							  				<textarea class=\"form-control\" rows=\"12\" cols=\"95\" style=\"overflow: auto;display:none;\" name=\"email_body\" id=\"email_body");
      out.print(i);
      out.write("\" disabled></textarea>\r\n										</div>\r\n									</div>	\r\n								</div>\r\n							</div>\r\n						</div>\r\n					</div>				\r\n				");
} 
      out.write("						\r\n				</div>\r\n			</div>\r\n		</div>\r\n	</div>\r\n</div>\r\n\r\n<input type=\"hidden\" name=\"option\" value=\"DLNG_SEND_INVOICE_MAIL\">\r\n\r\n<input type=\"hidden\" name=\"read_access\" value=\"");
      out.print(read_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"write_access\" value=\"");
      out.print(write_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"check_access\" value=\"");
      out.print(check_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"print_access\" value=\"");
      out.print(print_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"delete_access\" value=\"");
      out.print(delete_access);
      out.write("\">  	\r\n<input type=\"hidden\" name=\"audit_access\" value=\"");
      out.print(audit_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"authorize_access\" value=\"");
      out.print(authorize_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"approve_access\" value=\"");
      out.print(approve_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"execute_access\" value=\"");
      out.print(execute_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"form_cd\" value=\"");
      out.print(formCd);
      out.write("\">\r\n<input type=\"hidden\" name=\"form_nm\" value=\"");
      out.print(formNm);
      out.write("\">\r\n<input type=\"hidden\" name=\"mod_cd\" value=\"");
      out.print(mod_cd);
      out.write("\">\r\n<input type=\"hidden\" name=\"mod_nm\" value=\"");
      out.print(mod_nm);
      out.write("\">\r\n<input type=\"hidden\" name=\"u\" value=\"");
      out.print(u);
      out.write("\">\r\n	\r\n</form>\r\n</body>\r\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
