/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2026-01-08 04:35:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sales_005finvoice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.etrm.fms.util.CommonVariable;
import com.etrm.fms.util.CommonVariable;
import com.etrm.fms.util.EncryptTest;
import com.etrm.fms.util.CommonVariable;
import java.util.Vector;

public final class frm_005fprepare_005fdebit_005fcredit_005fnote_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/sales_invoice/../home/loading.jsp", Long.valueOf(1766569344000L));
    _jspx_dependants.put("/sales_invoice/../home/../menu/menu.jsp", Long.valueOf(1766569350000L));
    _jspx_dependants.put("/sales_invoice/../util/common_val.jsp", Long.valueOf(1754630867617L));
    _jspx_dependants.put("/sales_invoice/../home/header.jsp", Long.valueOf(1766569344000L));
    _jspx_dependants.put("/sales_invoice/../util/common_js.jsp", Long.valueOf(1754630867617L));
    _jspx_dependants.put("/sales_invoice/../util/../sess/Expire.jsp", Long.valueOf(1754630867476L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("com.etrm.fms.util.CommonVariable");
    _jspx_imports_classes.add("com.etrm.fms.util.EncryptTest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n");
      out.write('\n');

String expire_msg = request.getParameter("expire_msg")==null?"":request.getParameter("expire_msg");
if(session.getAttribute("emp_uid")==null || session.getAttribute("emp_uid") == ""|| session.getAttribute("emp_uid").toString().equals("null"))
{
      out.write("\r\n		<script>\r\n			alert(\"Please Enter Login Detail!\")\r\n			var url = \"../home/login.jsp\";\r\n			location.replace(url);\r\n		</script>\r\n");
}
else
{
	if(expire_msg.equals("Timeout"))
	{
		session.invalidate();
	
      out.write("\r\n		<script>\r\n		var url = \"../home/login.jsp?sess=Session Expired\";\r\n		location.replace(url);\r\n		</script>\r\n	");

	}
	else if(expire_msg.equals("PwdChng"))
	{
		session.invalidate();
	
      out.write("\r\n		<script>\r\n		var url = \"../home/login.jsp\";\r\n		location.replace(url);\r\n		</script>\r\n	");
}
}

      out.write("\r\n\r\n");
      out.write('\n');
String COMMlogo="";
if(session.getAttribute("comp_logo")==null||session.getAttribute("comp_logo")==""||session.getAttribute("comp_logo").toString().equals("null"))
{
	COMMlogo="";
}  
else
{
	COMMlogo=""+session.getAttribute("comp_logo");
}

String sel_comp_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	sel_comp_cd="";
}  
else
{
	sel_comp_cd=""+session.getAttribute("comp_cd");
}

      out.write("\n<link rel=\"SHORTCUT ICON\" href=\"../images/");
      out.print(COMMlogo);
      out.write("\">\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<meta http-equiv=\"refresh\" content=\"");
      out.print(session.getMaxInactiveInterval());
      out.write(";url=../sess/Expire.jsp?expire_msg=Timeout\"/>\n<title>");
      out.print(CommonVariable.app_name);
      out.write("</title>\n\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap/bootstrap5/css/bootstrap.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../font-awesome-4.7.0/css/font-awesome.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/datepicker/bootstrap-datepicker3.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/util.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/main.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/navbar.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/responsive.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">\n\n");
 if ("2".equals(sel_comp_cd)) { 
      out.write("\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common_2.css\">  <!-- CSS for comp_cd = \"2\" -->\n");
 } else { 
      out.write("\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">  <!-- CSS for comp_cd = \"1\" -->\n");
 } 
      out.write("\n\n<script type=\"text/javascript\" src=\"../bootstrap/bootstrap5/js/bootstrap.bundle.min.js\"></script>\n<script type=\"text/javascript\" src=\"../js/jquery.min.js\"></script>\n<script type=\"text/javascript\" src=\"../js/datepicker/bootstrap-datepicker.min.js\"></script>\n<script type=\"text/javascript\" src=\"../js/datepicker/bootstrap-datepicker.es.min.js\"></script>\n\n<script type=\"text/javascript\" src=\"../js/util.js\"></script>\n");
      out.write("\n<script type=\"text/javascript\" src=\"../js/session.js\"></script>\n\n");
      out.write('\r');
      out.write('\n');
      com.etrm.fms.util.DataBean_Menu menu_access = null;
      menu_access = (com.etrm.fms.util.DataBean_Menu) _jspx_page_context.getAttribute("menu_access", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (menu_access == null){
        menu_access = new com.etrm.fms.util.DataBean_Menu();
        _jspx_page_context.setAttribute("menu_access", menu_access, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

String formCd="";
String mod_cd="";
String u=request.getParameter("u")==null?"":request.getParameter("u");

String msg=request.getParameter("msg")==null?"":request.getParameter("msg");
String msg_type=request.getParameter("msg_type")==null?"":request.getParameter("msg_type");

String owner_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	owner_cd="";
}  
else
{
	owner_cd=""+session.getAttribute("comp_cd");
}

String owner_abbr="";
if(session.getAttribute("comp_abbr")==null||session.getAttribute("comp_abbr")==""||session.getAttribute("comp_abbr").toString().equals("null"))
{
	owner_abbr="";
}  
else
{
	owner_abbr=""+session.getAttribute("comp_abbr");
}

String emp_cd="";
if(session.getAttribute("emp_cd")==null||session.getAttribute("emp_cd")==""||session.getAttribute("emp_cd").toString().equals("null"))
{
	emp_cd="";
}  
else
{
	emp_cd=""+session.getAttribute("emp_cd");
}

if(!u.equals(""))
{
	StringBuffer decryt=new EncryptTest().URLdecrypt(u);
	String dec=""+decryt;
	if(!dec.equals("") && dec.contains("-"))
	{
		String temp[]=dec.split("-");
		if(temp.length==2)
		{
			formCd=temp[0];
			mod_cd=temp[1];
		}
	}
}

menu_access.setCallFlag("MENU_ACCESS");
menu_access.setEmpCd(emp_cd);
menu_access.setComp_cd(owner_cd);
menu_access.setModule_cd(mod_cd);
menu_access.setForm_cd(formCd);
menu_access.init();


String formNm = menu_access.getForm_nm();
String mod_nm = menu_access.getModule_nm();
String read_access = menu_access.getRead_access();
String write_access = menu_access.getWrite_access();
String check_access = menu_access.getCheck_access();
String print_access = menu_access.getPrint_access();
String delete_access = menu_access.getDelete_access();
String audit_access = menu_access.getAudit_access();
String authorize_access = menu_access.getAuthorize_access();
String approve_access = menu_access.getApprove_access();
String execute_access = menu_access.getExecute_access();


      out.write("\n\n<script type=\"text/javascript\">\ndocument.title = \"");
      out.print(CommonVariable.app_name);
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(owner_abbr);
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(formNm);
      out.write("\";\n</script>\n");
      out.write("\r\n\r\n<script>\r\nfunction refresh(accroid)\r\n{\r\n	/* var month = document.forms[0].month.value;\r\n	var year = document.forms[0].year.value;\r\n	var billing_cycle = document.forms[0].billing_cycle.value;\r\n	var prev_billing_cycle = document.forms[0].prev_billing_cycle.value; */\r\n	\r\n	var from_dt = document.forms[0].from_dt.value;\r\n	var to_dt = document.forms[0].to_dt.value;\r\n	\r\n	\r\n	var pdf_type=\"O\";\r\n	var ff_pdf_type=\"O\";\r\n	if(document.getElementById(\"pdf_type_\"+accroid)!=null && document.getElementById(\"pdf_type_\"+accroid)!=undefined)\r\n	{\r\n		pdf_type = document.getElementById(\"pdf_type_\"+accroid).value;\r\n	}\r\n	\r\n	\r\n	var msg=\"\";\r\n	var flag = true;\r\n	\r\n	var count = compareDate(from_dt,to_dt);\r\n	if(parseInt(count) == 1)\r\n	{\r\n		msg+=\"From Date should be less or equal To Date!\";\r\n		flag=false;\r\n	}\r\n	var u = document.forms[0].u.value;\r\n	\r\n	if(flag)\r\n	{\r\n		var url = \"../sales_invoice/frm_prepare_debit_credit_note.jsp?&u=\"+u+\"&pdf_type=\"+pdf_type+\"&from_dt=\"+from_dt+\"&to_dt=\"+to_dt+\"&accroid=\"+accroid;\r\n	\r\n		document.getElementById(\"loading\").style.visibility = \"visible\";\r\n");
      out.write("		location.replace(url);\r\n	}\r\n	else\r\n	{\r\n		alert(msg);\r\n		document.forms[0].from_dt.value=\"\";\r\n	}\r\n}\r\n\r\nfunction checkStartEndDate(flag)\r\n{\r\n	var period_start_dt=document.forms[0].period_start_dt;\r\n	var period_end_dt=document.forms[0].period_end_dt;\r\n	\r\n	var obj = period_start_dt;\r\n	var obj1 = period_end_dt;\r\n	\r\n	if((obj.value!=\"\" && trim(obj.value) != \"\" && obj.value != null) && (obj1.value!=\"\" && trim(obj1.value) != \"\" && obj1.value != null))\r\n	{\r\n		if(flag==\"F\")\r\n		{\r\n			var count = compareDate(obj.value,obj1.value);\r\n			if(parseInt(count) == 1)\r\n			{\r\n				alert(\"Billing Period Start Date should be less or equal Period End Date!\")\r\n				obj.value=\"\";\r\n				return false;\r\n			}\r\n		}\r\n		else if(flag==\"T\")\r\n		{\r\n			var count = compareDate(obj.value,obj1.value);\r\n			if(parseInt(count) == 1)\r\n			{\r\n				alert(\"Billing Period End Date should be grater or equal Period Start Date!\")\r\n				obj1.value=\"\";\r\n				return false;\r\n			}\r\n		}\r\n	}\r\n}\r\n\r\n\r\nvar newWindow;\r\nfunction openActivity1(counterparty_cd,agmt_no,agmt_rev,cont_no,cont_rev,cont_type,\r\n");
      out.write("		plant_seq,period_st_dt,period_end_dt,bu,billing_cycle,drcr_fin_yr,bu_st_cd,\r\n		temp_period_st_dt,temp_period_end_dt,cargo_no,operation,accroid,inv_flag,criteria,drcr_flag,drcr_seq,remark,fin_yr)\r\n{\r\n	var u = document.forms[0].u.value;\r\n	\r\n	var url = \"frm_generate_debit_credit_note.jsp?counterparty_cd=\"+counterparty_cd+\"&contract_type=\"+cont_type+\"&cont_no=\"+cont_no+\r\n			\"&cont_rev=\"+cont_rev+\"&agmt_no=\"+agmt_no+\"&agmt_rev=\"+agmt_rev+\"&plant_seq=\"+plant_seq+\"&period_start_dt=\"+period_st_dt+\r\n			\"&period_end_dt=\"+period_end_dt+\"&billing_cycle=\"+billing_cycle+\"&bu_unit=\"+bu+\"&operation=\"+operation+\r\n			\"&drcr_fin_yr=\"+drcr_fin_yr+\"&bu_state_tin=\"+bu_st_cd+\"&temp_period_start_dt=\"+temp_period_st_dt+\"&temp_period_end_dt=\"+temp_period_end_dt+\r\n			\"&cargo_no=\"+cargo_no+\"&accroid=\"+accroid+\"&inv_flag=\"+inv_flag+\"&criteria=\"+criteria+\"&drcr_flag=\"+drcr_flag+\"&drcr_seq=\"+drcr_seq+\r\n			\"&remark=\"+remark+\"&exist_financial_year=\"+fin_yr+\"&u=\"+u;\r\n	\r\n	if(!newWindow || newWindow.closed)\r\n	{\r\n		newWindow = window.open(url,\"Prepare Sales Invoice\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n");
      out.write("	}\r\n	else\r\n	{\r\n		newWindow.close();\r\n		newWindow = window.open(url,\"Prepare Sales Invoice\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n	}\r\n}\r\n\r\nfunction openActivity3(counterparty_cd,agmt_no,agmt_rev,cont_no,cont_rev,cont_type,plant_seq,period_st_dt,period_end_dt,bu,\r\n		billing_cycle,drcr_fin_yr,bu_st_cd,inv_seq,cargo_no,activityFlag,accroid,inv_flag,drcr_flag,drcr_seq,fin_yr)\r\n{\r\n	var u = document.forms[0].u.value;\r\n	\r\n	var url = \"rpt_drcr_view_chk_aprv_dtl.jsp?counterparty_cd=\"+counterparty_cd+\"&contract_type=\"+cont_type+\"&cont_no=\"+cont_no+\r\n			\"&cont_rev=\"+cont_rev+\"&agmt_no=\"+agmt_no+\"&agmt_rev=\"+agmt_rev+\"&plant_seq=\"+plant_seq+\"&period_start_dt=\"+period_st_dt+\r\n			\"&period_end_dt=\"+period_end_dt+\"&billing_cycle=\"+billing_cycle+\"&bu_unit=\"+bu+\"&activityFlag=\"+activityFlag+\r\n			\"&drcr_fin_yr=\"+drcr_fin_yr+\"&bu_state_tin=\"+bu_st_cd+\"&invoice_seq=\"+inv_seq+\"&cargo_no=\"+cargo_no+\"&accroid=\"+accroid+\r\n			\"&inv_flag=\"+inv_flag+\"&drcr_flag=\"+drcr_flag+\"&drcr_seq=\"+drcr_seq+\"&financial_year=\"+fin_yr+\"&u=\"+u;\r\n");
      out.write("	\r\n	if(!newWindow || newWindow.closed)\r\n	{\r\n		newWindow = window.open(url,\"Prepare Sales Invoice\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n	}\r\n	else\r\n	{\r\n		newWindow.close();\r\n		newWindow = window.open(url,\"Prepare Sales Invoice\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n	}\r\n}\r\n\r\nfunction PrintPDF(counterparty_cd,agmt_no,agmt_rev,cont_no,cont_rev,cont_type,plant_seq,\r\n		period_st_dt,period_end_dt,bu,billing_cycle,drcr_fin_yr,bu_st_cd,inv_seq,index,cargo_no,accroid,inv_flag,drcr_flag,drcr_seq,criteria,fin_yr)\r\n{\r\n	var print_access = document.forms[0].print_access.value;\r\n\r\n	\r\n	var drcr_pdf_type=\"\";\r\n	if(document.getElementById(\"drcr_pdf_type_\"+accroid)!=null && document.getElementById(\"drcr_pdf_type_\"+accroid)!=undefined)\r\n	{\r\n		drcr_pdf_type = document.getElementById(\"drcr_pdf_type_\"+accroid).value;\r\n	}\r\n	\r\n	var all_pdf_type = document.getElementById(\"all_pdf_type\"+index).value;\r\n	\r\n	if(drcr_pdf_type == \"All\")\r\n	{\r\n		pdf_type=all_pdf_type;\r\n	}\r\n	\r\n	var u = document.forms[0].u.value;\r\n");
      out.write("	\r\n	if(print_access==\"N\")\r\n	{\r\n		alert(\"You don't have Print Rights!\");	\r\n	}\r\n	else\r\n	{\r\n		var url = \"pdf_drcr_note.jsp?counterparty_cd=\"+counterparty_cd+\"&contract_type=\"+cont_type+\"&cont_no=\"+cont_no+\r\n			\"&cont_rev=\"+cont_rev+\"&agmt_no=\"+agmt_no+\"&agmt_rev=\"+agmt_rev+\"&plant_seq=\"+plant_seq+\"&period_start_dt=\"+period_st_dt+\r\n			\"&period_end_dt=\"+period_end_dt+\"&billing_cycle=\"+billing_cycle+\"&bu_unit=\"+bu+\r\n			\"&drcr_fin_yr=\"+drcr_fin_yr+\"&bu_state_tin=\"+bu_st_cd+\"&invoice_seq=\"+inv_seq+\"&cargo_no=\"+cargo_no+\"&accroid=\"+accroid+\"&inv_flag=\"+inv_flag+\r\n			\"&print_pdf_type=\"+drcr_pdf_type+\"&drcr_flag=\"+drcr_flag+\"&drcr_seq=\"+drcr_seq+\"&criteria=\"+criteria+\"&financial_year=\"+fin_yr+\"&u=\"+u;\r\n	\r\n		if(!newWindow || newWindow.closed)\r\n		{\r\n			newWindow = window.open(url,\"PDF Debit/Credit Note\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n		}\r\n		else\r\n		{\r\n			newWindow.close();\r\n			newWindow = window.open(url,\"PDF Debit/Credit Note\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n		}\r\n	}\r\n}\r\n\r\nfunction refershPar(sub_msg,msg_type,accroid)\r\n");
      out.write("{\r\n	/* var month = document.forms[0].month.value;\r\n	var year = document.forms[0].year.value;\r\n	var billing_cycle = document.forms[0].billing_cycle.value;\r\n	var prev_billing_cycle = document.forms[0].prev_billing_cycle.value; */\r\n	\r\n	\r\n	var from_dt = document.forms[0].from_dt.value;\r\n	var to_dt = document.forms[0].to_dt.value;\r\n	\r\n	var pdf_type=\"O\";\r\n	if(document.getElementById(\"pdf_type_\"+accroid)!=null && document.getElementById(\"pdf_type_\"+accroid)!=undefined)\r\n	{\r\n		pdf_type = document.getElementById(\"pdf_type_\"+accroid).value;\r\n	}\r\n	\r\n	var msg=\"\";\r\n	var flag = true;\r\n	\r\n	var u = document.forms[0].u.value;\r\n	\r\n	if(flag)\r\n	{\r\n		var url = \"frm_prepare_debit_credit_note.jsp?&u=\"+u+\"&pdf_type=\"+pdf_type+\"&from_dt=\"+from_dt+\"&to_dt=\"+to_dt+\"&accroid=\"+accroid+\"&msg=\"+sub_msg+\"&msg_type=\"+msg_type;\r\n	\r\n		document.getElementById(\"loading\").style.visibility = \"visible\";\r\n		location.replace(url);\r\n	}\r\n	else\r\n	{\r\n		alert(msg)\r\n	}\r\n}\r\n\r\nfunction openPdfFile(url)\r\n{\r\n	window.open(url);\r\n}\r\n\r\nfunction openAllPdfFile(fin_yr,bu_st_cd,inv_seq)\r\n");
      out.write("{\r\n	var url = \"rpt_view_all_pdf.jsp?financial_year=\"+fin_yr+\"&bu_state_tin=\"+bu_st_cd+\"&invoice_seq=\"+inv_seq;\r\n	\r\n	if(!newWindow || newWindow.closed)\r\n	{\r\n		newWindow = window.open(url,\"PDF Sales Invoice\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n	}\r\n	else\r\n	{\r\n		newWindow.close();\r\n		newWindow = window.open(url,\"PDF Sales Invoice\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n	}\r\n}\r\n\r\nfunction openAllFfPdfFile(fin_yr,inv_type,bu_st_cd,inv_seq,flag)\r\n{\r\n	var url = \"rpt_view_all_pdf.jsp?financial_year=\"+fin_yr+\"&bu_state_tin=\"+bu_st_cd+\"&invoice_seq=\"+inv_seq+\"&invoice_type=\"+inv_type+\"&flag=\"+flag;\r\n	\r\n	if(!newWindow || newWindow.closed)\r\n	{\r\n		newWindow = window.open(url,\"PDF Sales Invoice\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n	}\r\n	else\r\n	{\r\n		newWindow.close();\r\n		newWindow = window.open(url,\"PDF Sales Invoice\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n	}\r\n}\r\n\r\n\r\nfunction openMailBody(counterparty_cd,agmt_no,agmt_rev,cont_no,cont_rev,cont_type,plant_seq,\r\n");
      out.write("		period_st_dt,period_end_dt,bu,billing_cycle,drcr_fin_yr,bu_st_cd,inv_seq,index,accroid,inv_flag,drcr_flag,drcr_seq,criteria,fin_yr)\r\n{\r\n	var drcr_pdf_type=\"\";\r\n	if(document.getElementById(\"drcr_pdf_type_\"+accroid)!=null && document.getElementById(\"drcr_pdf_type_\"+accroid)!=undefined)\r\n	{\r\n		drcr_pdf_type = document.getElementById(\"drcr_pdf_type_\"+accroid).value;\r\n	}\r\n\r\n	\r\n	var drcr_all_mail_pdf_type = document.getElementById(\"drcr_all_mail_pdf_type\"+index).value;\r\n	\r\n	if(drcr_pdf_type == \"All\")\r\n	{\r\n		drcr_pdf_type=drcr_all_mail_pdf_type;\r\n	}\r\n	\r\n	var u = document.forms[0].u.value;\r\n	\r\n	var url = \"frm_drcr_sign_pdf_mail.jsp?counterparty_cd=\"+counterparty_cd+\"&contract_type=\"+cont_type+\"&cont_no=\"+cont_no+\r\n			\"&cont_rev=\"+cont_rev+\"&agmt_no=\"+agmt_no+\"&agmt_rev=\"+agmt_rev+\"&plant_seq=\"+plant_seq+\"&period_start_dt=\"+period_st_dt+\r\n			\"&period_end_dt=\"+period_end_dt+\"&billing_cycle=\"+billing_cycle+\"&bu_unit=\"+bu+\r\n			\"&drcr_fin_yr=\"+drcr_fin_yr+\"&bu_state_tin=\"+bu_st_cd+\"&invoice_seq=\"+inv_seq+\"&mail_pdf_type=\"+drcr_pdf_type+\r\n");
      out.write("			\"&mail_inv_type=S&inv_flag=\"+inv_flag+\"&drcr_flag=\"+drcr_flag+\"&drcr_seq=\"+drcr_seq+\"&criteria=\"+criteria+\"&financial_year=\"+fin_yr;\r\n			\"&u=\"+u;\r\n	\r\n	if(!newWindow || newWindow.closed)\r\n	{\r\n		newWindow= window.open(url,\"Mail Body\",\"top=10,left=70,width=900,height=700,scrollbars=1\");\r\n	}\r\n	else\r\n	{\r\n		newWindow.close();\r\n		newWindow= window.open(url,\"Mail Body\",\"top=10,left=70,width=900,height=700,scrollbars=1\");\r\n	}\r\n}\r\n\r\n\r\nfunction doGenXML(couterpty_cd,invoice_no,financial_year,invoice_seq,contract_type,type_flag,invoice_type,\r\n		bu_state_tin,sap_approval_flag,agmt_no,cont_no, inv_pdf_flag,accroid)\r\n{\r\n	if(inv_pdf_flag==\"\")\r\n	{\r\n		inv_pdf_flag=\"N\";\r\n	}\r\n	else\r\n	{\r\n		inv_pdf_flag=\"Y\";\r\n	}\r\n	\r\n	var u = document.forms[0].u.value;\r\n	\r\n	var url = \"../accounting/rpt_view_sales_invoice_sap_approval.jsp?financial_year=\"+financial_year+\"&invoice_seq=\"+invoice_seq+\r\n			\"&contract_type=\"+contract_type+\"&type_flag=\"+type_flag+\"&invoice_type=\"+invoice_type+\r\n			\"&counterparty_cd=\"+couterpty_cd+\"&invoice_no=\"+invoice_no+\"&bu_state_tin=\"+bu_state_tin+\r\n");
      out.write("			\"&sap_approval_flag=\"+sap_approval_flag+\"&agmt_no=\"+agmt_no+\"&cont_no=\"+cont_no+\"&inv_pdf_flag=\"+inv_pdf_flag+\"&accroid=\"+accroid+\r\n			\"&u=\"+u;\r\n\r\n	if(!newWindow || newWindow.closed)\r\n	{\r\n		newWindow = window.open(url,\"Sales SAP Approval\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n	}\r\n	else\r\n	{\r\n		newWindow.close();\r\n		newWindow = window.open(url,\"Sales SAP Approval\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n	}\r\n}\r\n</script>\r\n</head>\r\n");
      com.etrm.fms.sales_invoice.DataBean_Sales_Drcr_note Drcr_note = null;
      Drcr_note = (com.etrm.fms.sales_invoice.DataBean_Sales_Drcr_note) _jspx_page_context.getAttribute("Drcr_note", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (Drcr_note == null){
        Drcr_note = new com.etrm.fms.sales_invoice.DataBean_Sales_Drcr_note();
        _jspx_page_context.setAttribute("Drcr_note", Drcr_note, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.etrm.fms.util.MessageUtil utilmsg = null;
      utilmsg = (com.etrm.fms.util.MessageUtil) _jspx_page_context.getAttribute("utilmsg", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (utilmsg == null){
        utilmsg = new com.etrm.fms.util.MessageUtil();
        _jspx_page_context.setAttribute("utilmsg", utilmsg, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.etrm.fms.util.DateUtil utildate = null;
      utildate = (com.etrm.fms.util.DateUtil) _jspx_page_context.getAttribute("utildate", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (utildate == null){
        utildate = new com.etrm.fms.util.DateUtil();
        _jspx_page_context.setAttribute("utildate", utildate, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');

String sysdate = utildate.getSysdate();
String sys_date_num = "0"; 
int currentYear = 0;
int currentMonth = 0;
String temp_billing_cycle="";
if(!sysdate.equals(""))
{
	String[] sys_temp = sysdate.split("/");
	sys_date_num=sys_temp[0];
}

String prvMonthDate="";
if(Integer.parseInt(sys_date_num) <= 15)
{
	temp_billing_cycle="2";
	prvMonthDate=utildate.getFirstDateOfPreviousMonth(sysdate);
}
else
{
	temp_billing_cycle="1";
	prvMonthDate=sysdate;
}

String date_num = "0"; 
if(!prvMonthDate.equals(""))
{
	String[] temp = prvMonthDate.split("/");
	date_num=temp[0];
	currentMonth=Integer.parseInt(temp[1]);
	currentYear=Integer.parseInt(temp[2]);
}
//int currentYear = utildate.getCurrentYear();
//int currentMonth = utildate.getCurrentMonth();

String accroid =request.getParameter("accroid")==null?"":request.getParameter("accroid");

/* String month=request.getParameter("month")==null?""+currentMonth:request.getParameter("month");
String year=request.getParameter("year")==null?""+currentYear:request.getParameter("year");
String billing_cycle=request.getParameter("billing_cycle")==null?"":request.getParameter("billing_cycle"); */
int curr_year=utildate.getCurrentYear();
String from_dt = request.getParameter("from_dt")==null?"01/01/"+curr_year:request.getParameter("from_dt");
String to_dt = request.getParameter("to_dt")==null?"31/12/"+curr_year:request.getParameter("to_dt");
String drcr_pdf_type=request.getParameter("drcr_pdf_type")==null?"O":request.getParameter("drcr_pdf_type"); //DhvaniT20250818 for Dr/Cr Note

/* if(billing_cycle.equals(""))
{
	billing_cycle=temp_billing_cycle;
}

if(month.length() == 1)
{
	month="0"+month; 
} */

Drcr_note.setCallFlag("DEBIT_CREDIT_NOTE_LIST");
Drcr_note.setComp_cd(owner_cd);
/* Drcr_note.setMonth(month);
Drcr_note.setYear(year);
Drcr_note.setBilling_cycle(billing_cycle); */
Drcr_note.setFrom_dt(from_dt);
Drcr_note.setTo_dt(to_dt);
Drcr_note.setPrint_pdf_type(drcr_pdf_type);
Drcr_note.setView_pdf_type(drcr_pdf_type);
Drcr_note.setMail_pdf_type(drcr_pdf_type);
Drcr_note.init();

//Deep22082025 
Vector VINVOICE_LIST_ABBR = Drcr_note.getVINVOICE_LIST_ABBR();
Vector VINVOICE_LIST_NAME = Drcr_note.getVINVOICE_LIST_NAME();
Vector VINDEX = Drcr_note.getVINDEX();

//DhvaniT25050818 for Dr/Cr Note
Vector VCOUNTERPARTY_CD = Drcr_note.getVCOUNTERPARTY_CD();
Vector VCOUNTERPARTY_ABBR = Drcr_note.getVCOUNTERPARTY_ABBR();
Vector VCOUNTERPARTY_NM = Drcr_note.getVCOUNTERPARTY_NM();
Vector VDRCR_CONT_NO = Drcr_note.getVDRCR_CONT_NO();
Vector VDRCR_CONT_REV_NO = Drcr_note.getVDRCR_CONT_REV_NO();
Vector VDRCR_AGMT_NO = Drcr_note.getVDRCR_AGMT_NO();
Vector VDRCR_AGMT_REV_NO = Drcr_note.getVDRCR_AGMT_REV_NO();
Vector VDRCR_START_DT = Drcr_note.getVDRCR_START_DT();
Vector VDRCR_END_DT = Drcr_note.getVDRCR_END_DT();
Vector VDRCR_CONT_NAME = Drcr_note.getVDRCR_CONT_NAME();
Vector VDRCR_CONT_REF_NO = Drcr_note.getVDRCR_CONT_REF_NO();
Vector VDRCR_CONTRACT_TYPE = Drcr_note.getVDRCR_CONTRACT_TYPE();
Vector VDRCR_PLANT_SEQ = Drcr_note.getVDRCR_PLANT_SEQ();
Vector VDRCR_PLANT_ABBR = Drcr_note.getVDRCR_PLANT_ABBR();
Vector VDRCR_BU_PLANT_SEQ = Drcr_note.getVDRCR_BU_PLANT_SEQ();
Vector VDRCR_BU_PLANT_ABBR = Drcr_note.getVDRCR_BU_PLANT_ABBR();
Vector VDRCR_DEAL_NO = Drcr_note.getVDRCR_DEAL_NO();
Vector VDRCR_PERIOD_START_DT = Drcr_note.getVDRCR_PERIOD_START_DT();
Vector VDRCR_PERIOD_END_DT = Drcr_note.getVDRCR_PERIOD_END_DT();
Vector VDRCR_INVOICE_NO = Drcr_note.getVDRCR_INVOICE_NO();
Vector VDRCR_STATUS = Drcr_note.getVDRCR_STATUS();
Vector VDRCR_BILLING_FREQ_FLAG = Drcr_note.getVDRCR_BILLING_FREQ_FLAG();
Vector VDRCR_BILLING_FREQ_NM = Drcr_note.getVDRCR_BILLING_FREQ_NM();
Vector VDRCR_INV_CHECKED_FLAG = Drcr_note.getVDRCR_INV_CHECKED_FLAG();
Vector VDRCR_INV_APPROVED_FLAG = Drcr_note.getVDRCR_INV_APPROVED_FLAG();
Vector VDRCR_BU_STATE_TIN = Drcr_note.getVDRCR_BU_STATE_TIN();
Vector VDRCR_FINANCIAL_YEAR = Drcr_note.getVDRCR_FINANCIAL_YEAR();
Vector VDRCR_INVOICE_EXIST = Drcr_note.getVDRCR_INVOICE_EXIST();
Vector VDRCR_INVOICE_SEQ=Drcr_note.getVDRCR_INVOICE_SEQ();
Vector VDRCR_NO=Drcr_note.getVDRCR_NO();
Vector VDRCR_PDF_INV_FLAG=Drcr_note.getVDRCR_PDF_INV_FLAG();
Vector VDRCR_PDF_TYPE=Drcr_note.getVDRCR_PDF_TYPE();
Vector VDRCR_PDF_FILE_NAME=Drcr_note.getVDRCR_PDF_FILE_NAME();
Vector VDRCR_PDF_FILE_PATH=Drcr_note.getVDRCR_PDF_FILE_PATH();
Vector VDRCR_PDF_SIGNED_FLAG=Drcr_note.getVDRCR_PDF_SIGNED_FLAG();
Vector VDRCR_SIGN_PDF_TYPE=Drcr_note.getVDRCR_SIGN_PDF_TYPE();
/* Vector VDRCR_INVOICE_TYPE=Drcr_note.getVDRCR_INVOICE_TYPE();
Vector VDRCR_MAPPING_ID=Drcr_note.getVDRCR_MAPPING_ID(); */
Vector VDRCR_SAP_APPROVAL_FLAG = Drcr_note.getVDRCR_SAP_APPROVAL_FLAG();
Vector VDRCR_IS_IRN_GENERATED = Drcr_note.getVDRCR_IS_IRN_GENERATED();
Vector VDRCR_ITEM_DESC = Drcr_note.getVDRCR_ITEM_DESC();
Vector VDEAL_NO = Drcr_note.getVDEAL_NO();
Vector VDEAL_CONT_REF_NO = Drcr_note.getVDEAL_CONT_REF_NO();
Vector VDRCR_CARGO_NO = Drcr_note.getVDRCR_CARGO_NO();
Vector VDRCR_INV_FLAG = Drcr_note.getVDRCR_INV_FLAG();
Vector VDRCR_SEQ = Drcr_note.getVDRCR_SEQ();
Vector VDRCR_REF = Drcr_note.getVDRCR_REF();
Vector VDRCR_FLAG = Drcr_note.getVDRCR_FLAG();
Vector VDRCR_CRITERIA = Drcr_note.getVDRCR_CRITERIA();
Vector VDRCR1_SEQ = Drcr_note.getVDRCR1_SEQ();
Vector VDRCR_REMARK = Drcr_note.getVDRCR_REMARK();
Vector VFINANCIAL_YEAR = Drcr_note.getVFINANCIAL_YEAR();
String criteria=Drcr_note.getcriteria();


String context_nm = request.getContextPath();
String server_nm = request.getServerName();
String server_port = ""+request.getServerPort();
String url=CommonVariable.app_protocol+"://"+server_nm+":"+server_port+context_nm+"//";
String file_url = CommonVariable.app_protocol+"://"+server_nm+":"+server_port+context_nm+"//"+CommonVariable.work_dir+owner_cd;



      out.write("\r\n<body>\r\n");
      out.write("\r\n\r\n\r\n<script>\r\nfunction changePage(form_path,u)\r\n{\r\n	document.getElementById(\"loading\").style.visibility = \"visible\";\r\n	var url = form_path+\"?u=\"+u;\r\n			\r\n	location.replace(url);\r\n}\r\n\r\nfunction logout()\r\n{\r\n	var url = \"../home/logout.jsp\";\r\n	location.replace(url);\r\n	\r\n}\r\n\r\nfunction homepage()\r\n{\r\n	var url = \"../home/fms.jsp\";\r\n	location.replace(url);\r\n	\r\n}\r\n\r\nfunction changeProfile(comp_cd,exists_comp_abbr,comp_abbr)\r\n{\r\n	var a = confirm(\"Do you want to Switch Profile \"+exists_comp_abbr+\" to \"+comp_abbr+\"?\");\r\n	if(a)\r\n	{\r\n		document.getElementById(\"loading\").style.visibility = \"visible\";\r\n		var url = \"../home/profile_selection.jsp?comp_profile=\"+comp_cd;\r\n			\r\n		location.replace(url);\r\n	}\r\n}\r\n</script>\r\n\r\n<style type=\"text/css\">\r\n.navbar .megamenu{ padding: 1rem; }\r\n/* ============ desktop view ============ */\r\n@media all and (min-width: 992px) {\r\n	.navbar .has-megamenu{position:static!important;}\r\n	.navbar .megamenu{left:15%; right:15%; width:auto; margin-top:0;  }\r\n}	\r\n/* ============ desktop view .end// ============ */\r\n");
      out.write("/* ============ mobile view ============ */\r\n@media(max-width: 991px){\r\n	.navbar.fixed-top .navbar-collapse, .navbar.sticky-top .navbar-collapse{\r\n		overflow-y: auto;\r\n	    max-height: 90vh;\r\n	    margin-top:10px;\r\n	}\r\n}\r\n/* ============ mobile view .end// ============ */\r\n</style>\r\n\r\n");
      com.etrm.fms.util.DataBean_Menu menu = null;
      menu = (com.etrm.fms.util.DataBean_Menu) _jspx_page_context.getAttribute("menu", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (menu == null){
        menu = new com.etrm.fms.util.DataBean_Menu();
        _jspx_page_context.setAttribute("menu", menu, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

String username = "";
String menu_emp_cd = "";
String comp_cd="";
String comp_logo="";
if(session.getAttribute("emp_uid")==null||session.getAttribute("emp_uid")==""||session.getAttribute("emp_uid").toString().equals("null"))
{
	username="";
}  
else
{
	username=""+session.getAttribute("emp_uid");
}

if(session.getAttribute("emp_cd")==null||session.getAttribute("emp_cd")==""||session.getAttribute("emp_cd").toString().equals("null"))
{
	menu_emp_cd="";
}  
else
{
	menu_emp_cd=""+session.getAttribute("emp_cd");
}

if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	comp_cd="";
}  
else
{
	comp_cd=""+session.getAttribute("comp_cd");
}

if(session.getAttribute("comp_logo")==null||session.getAttribute("comp_logo")==""||session.getAttribute("comp_logo").toString().equals("null"))
{
	comp_logo="";
}  
else
{
	comp_logo=""+session.getAttribute("comp_logo");
}

menu.setCallFlag("MODULE_MST");
menu.setUsername(username);
menu.setComp_cd(comp_cd);
menu.setEmpCd(menu_emp_cd);
menu.init();

Vector VMENU_MODULE_CD = menu.getVMENU_MODULE_CD();
Vector VMENU_MODULE_NM = menu.getVMENU_MODULE_NM();

Vector VMENU_COMPANY_CD = menu.getVMENU_COMPANY_CD();
Vector VMENU_COMPANY_NM = menu.getVMENU_COMPANY_NM();
Vector VMENU_COMPANY_ABBR = menu.getVMENU_COMPANY_ABBR();
String menu_default_prof=menu.getDefault_profile();

      out.write("\r\n<nav class=\"navbar navbar-expand-lg navbar-dark\" style=\"background-color: var(--header_color);\">\r\n	<div class=\"container-fluid\">\r\n    	<a class=\"navbar-brand\" href=\"#\" style=\"padding-top: 2px;padding-left: 4px;padding-right: 2px;\" onclick=\"homepage();\">\r\n    		<img src=\"");
if(!comp_logo.equals("")){
      out.write('.');
      out.write('.');
      out.write('/');
      out.print(CommonVariable.company_logo_path );
      out.write('/');
      out.print(comp_logo);
} 
      out.write("\" height=\"30px\">&nbsp;<font style=\"color:var(--header_font_color); font-size:24px;\"> ");
      out.print(CommonVariable.app_name);
      out.write("</font>\r\n    	</a>\r\n    	<button class=\"navbar-toggler\" style=\"border-color:var(--header_font_color);\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n      		<!-- <span class=\"navbar-toggler-icon\"></span> -->\r\n      		<font><i class=\"fa fa-bars\" style=\"color:var(--header_font_color);\"></i></font>\r\n    	</button>\r\n    	<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n      		<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\" style=\"flex-wrap: wrap;\">\r\n      		");
for(int i=0; i < VMENU_MODULE_CD.size(); i++){
      out.write("\r\n        		<li class=\"nav-item dropdown has-megamenu\" >\r\n          			<a class=\"nav-link dropdown-toggle\" style=\"padding: 3px;\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n            		");
      out.print(VMENU_MODULE_NM.elementAt(i));
      out.write("\r\n          			</a>\r\n          			<div class=\"dropdown-menu megamenu\" role=\"menu\">\r\n						<div class=\"row g-3\">\r\n							<div class=\"col-sm-12 col-xs-12 col-md-12\">  \r\n								<div class=\"form-group row\">\r\n					          	");

					    		menu.setCallFlag("MENU_MST");
					    		menu.setUsername(username);
					    		menu.setComp_cd(comp_cd);
					    		menu.setModule_cd(""+VMENU_MODULE_CD.elementAt(i));
					    		menu.init();
					    		
					    		Vector VFORM_CD = menu.getVFORM_CD();
					    		Vector VFORM_NM = menu.getVFORM_NM();
					    		Vector VFORM_PATH = menu.getVFORM_PATH();
					    		Vector VREAD_ACCESS = menu.getVREAD_ACCESS();
					    		Vector VWRITE_ACCESS = menu.getVWRITE_ACCESS();
					    		Vector VCHECK_ACCESS = menu.getVCHECK_ACCESS();
					    		Vector VPRINT_ACCESS = menu.getVPRINT_ACCESS();
					    		Vector VDELETE_ACCESS = menu.getVDELETE_ACCESS();
					    		Vector VAUDIT_ACCESS = menu.getVAUDIT_ACCESS();
					    		Vector VAUTHORIZE_ACCESS = menu.getVAUTHORIZE_ACCESS();
					    		Vector VAPPROVE_ACCESS = menu.getVAPPROVE_ACCESS();
					    		Vector VEXECUTE_ACCESS = menu.getVEXECUTE_ACCESS();
					    		Vector VGRP_CD = menu.getVGRP_CD();
					    		Vector VU = menu.getVU();
					    		Vector VSEI_CENTRAL = menu.getVSEI_CENTRAL();
					    		
					    		Vector VSUB_MENU_CD = menu.getVSUB_MENU_CD();
					    		Vector VSUB_MENU_NM = menu.getVSUB_MENU_NM();
					    		
					    		for(int k=0; k<VSUB_MENU_CD.size(); k++)
					    		{
      out.write("\r\n					    			<div class=\"col-auto\"> \r\n										<div class=\"col-megamenu\">\r\n					            			<ul>\r\n					              				<li><a class=\"dropdown-item\">");
      out.print(VSUB_MENU_NM.elementAt(k));
      out.write("</a></li>\r\n								              	");
for(int j=0; j<VFORM_CD.size(); j++)
									    		{
									    			if(VSUB_MENU_CD.elementAt(k).equals(VGRP_CD.elementAt(j)))
									    			{
      out.write("\r\n											    		<li>\r\n											            	<a class=\"dropdown-item\" href=\"#\" onclick=\"changePage('");
      out.print(VFORM_PATH.elementAt(j));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VU.elementAt(j));
      out.write("')\">\r\n																");
      out.print(VFORM_NM.elementAt(j));
if(VSEI_CENTRAL.elementAt(j).toString().equals("Y")){
      out.write("&nbsp;<span style=\"color:var(--top_header_font_color);\"><i class=\"fa fa-universal-access\" aria-hidden=\"true\"></i></span>");
}
      out.write("\r\n															</a>\r\n														</li>\r\n											         ");
} 
      out.write("\r\n											     ");
} 
      out.write("\r\n					            			</ul>\r\n					            		</div>\r\n					            	</div>\r\n			            		");
} 
			            		VFORM_CD.clear();
			            		VFORM_NM.clear();
			            		VFORM_PATH.clear();
			            		VREAD_ACCESS.clear();
			            		VWRITE_ACCESS.clear();
			            		VCHECK_ACCESS.clear();
			            		VPRINT_ACCESS.clear();
			            		VDELETE_ACCESS.clear();
			            		VAUDIT_ACCESS.clear();
			            		VAUTHORIZE_ACCESS.clear();
			            		VAPPROVE_ACCESS.clear();
			            		VEXECUTE_ACCESS.clear();
			            		VGRP_CD.clear();
			            		VU.clear();
			            		VSEI_CENTRAL.clear();
			            		VSUB_MENU_CD.clear();
			            		VSUB_MENU_NM.clear();
			            		
      out.write("\r\n			            		</div>\r\n			            	</div>\r\n			            </div>\r\n        			</div>\r\n        		</li>\r\n        		");
} 
      out.write("\r\n      		</ul>\r\n      		<div class=\"d-flex navbar-brand\">\r\n	      		<label class=\"btn\" onclick=\"\" style=\"color:var(--header_font_color); padding-left:0px;\"><b><span id = \"min\"></span>:<span id = \"sec\"></span></b></label>\r\n	      		<label class=\"btn\" onclick=\"\" style=\"color:var(--header_font_color); padding-left:0px;\">\r\n	      			<b>\r\n	      				<i class=\"fa fa-building-o fa-lg\"></i>&nbsp;");
      out.print(session.getAttribute("comp_abbr")==null?"":session.getAttribute("comp_abbr"));
      out.write("\r\n	      			</b>\r\n	      		</label>\r\n	      		<div class=\"flex-shrink-0 dropdown\">\r\n			   		<a href=\"#\" class=\"d-block link-dark text-decoration-none dropdown-toggle\" id=\"dropdownUser2\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" style=\"color:var(--header_font_color);\">\r\n			  			<!--  <img src=\"../");
      out.print(CommonVariable.company_logo_path );
      out.write("/default_user.png\" alt=\"mdo\" width=\"32\" height=\"32\" class=\"rounded-circle\"> -->\r\n			            <i class=\"fa fa-user-circle-o fa-2x\" aria-hidden=\"true\" > </i>\r\n			   		</a>\r\n			   		<ul class=\"dropdown-menu profile_dp_menu dropdown-menu-end text-small shadow\" aria-labelledby=\"dropdownUser2\" data-popper-placement=\"bottom-end\"> \r\n			   		<!-- style=\"position: absolute;inset: 0px auto auto 0px;margin: 0px;transform: translate(-80px, 34px);\" -->\r\n	            		<li><a class=\"dropdown-item\" href=\"#\"><i class=\"fa fa-user-circle fa-lg\"></i>&nbsp;");
      out.print(session.getAttribute("emp_nm")==null?"":session.getAttribute("emp_nm"));
      out.write("</a></li>\r\n	            		<li><hr class=\"dropdown-divider\"></li>\r\n	            		<li><a class=\"dropdown-item\" href=\"#\" style=\"font-weight: bold;font-size: var(--header_font_size);text-transform: uppercase;color: #dc3545; pointer-events: none;\">Switch Profile</a></li>\r\n			            ");
for(int i=0; i<VMENU_COMPANY_CD.size(); i++){ 
      out.write("\r\n			            <li>\r\n			            	<a class=\"dropdown-item\" href=\"#\" onclick=\"changeProfile('");
      out.print(VMENU_COMPANY_CD.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(session.getAttribute("comp_abbr")==null?"":session.getAttribute("comp_abbr"));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VMENU_COMPANY_ABBR.elementAt(i));
      out.write("');\"\r\n			            	");
if(comp_cd.equals(VMENU_COMPANY_CD.elementAt(i).toString())) { 
      out.write("\r\n			            		style=\"background-color: #95c674;color:white;font-weight:bold;pointer-events: none;\"\r\n			            	");
} 
      out.write(">\r\n			            	");
      out.print(VMENU_COMPANY_ABBR.elementAt(i));
      out.write("&nbsp;");
if(menu_default_prof.equals(VMENU_COMPANY_CD.elementAt(i).toString())){ 
      out.write("<i class=\"fa fa-dot-circle-o\"></i>");
} 
      out.write("\r\n			            	</a>\r\n			           	</li>\r\n			            ");
}
      out.write("\r\n			            <li><hr class=\"dropdown-divider\"></li>\r\n			            <li><a class=\"dropdown-item\" href=\"#\" onclick=\"logout();\"><b><i title=\"Logout\" class=\"fa fa-sign-out fa-lg\"></i>&nbsp;Sign Out</b></a></li>\r\n					</ul>\r\n				</div>\r\n			</div>\r\n    	</div>\r\n  	</div>\r\n</nav>\r\n\r\n");
      out.write("\r\n\r\n<!-- Alert Model -->\r\n<div class=\"modal fade\" id=\"myAlertModal\" style=\"z-index: 3055;\" data-bs-backdrop=\"static\" data-bs-keyboard=\"false\"> \r\n	<div class=\"modal-dialog modal-dialog-scrollable\">\r\n    	<div class=\"modal-content\">\r\n    		<div class=\"modal-header\">\r\n        		<div class=\"topheader\">\r\n					Alert\r\n				</div>\r\n      		</div>\r\n      		<div class=\"modal-body\">\r\n      			<p id=\"alertMsg\"></p>\r\n      		</div>\r\n      		<div class=\"modal-footer\" align=\"right\">\r\n        		<input type=\"button\" class=\"btn btn-primary\" id=\"alertok\" value=\"Ok\" onclick=\"alertHide();\">\r\n        		<!-- <input type=\"button\" class=\"btn btn-danger\" value=\"Cancel\"> -->\r\n      		</div>\r\n      	</div>\r\n	</div>\r\n</div>  \r\n\r\n<script>\r\nfunction alertShow(msg)\r\n{\r\n	$(\"#myAlertModal\").modal(\"show\");\r\n	document.getElementById(\"alertMsg\").innerHTML=msg;\r\n}\r\nfunction alertHide()\r\n{\r\n	$(\"#myAlertModal\").modal(\"hide\");\r\n}\r\n</script>   ");
      out.write('\n');
      out.write("<div id=\"loading\" style=\"visibility: hidden;\">\n	<div id=\"loading-image\">\n		<div class=\"btn-group\">\n			<label class=\"btn\" style=\"color:var(--header_color);border:none;font-size:20px;align-self: center;font-weight:bold;\">\n				<i class=\"fa fa-spinner fa-pulse fa-lg\"></i>&nbsp;Loading\n			</label>\n		</div>\n	</div>\n</div>");
      out.write('\n');
      out.write("\r\n<form action=\"\">\r\n<div class=\"box-body\">\r\n	<div class=\"row\">\r\n		<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n			");
if(!msg.equals("")){
				if(msg_type.equals("S")){
      out.write("\r\n					<div class=\"fadealert\">");
      out.print(utilmsg.successMessage(msg));
      out.write("</div>\r\n				");
}else if(msg_type.equals("E")){
      out.write("\r\n					<div class=\"fadealert\">");
      out.print( utilmsg.errorMessage(msg));
      out.write("</div>\r\n				");
}
			} 
      out.write("\r\n			<div class=\"card cardmain\">\r\n				<div class=\"card-header cdheader\">\r\n					<div class=\"d-flex justify-content-between\">\r\n					    <div class=\"topheader\">\r\n					    	Sales Debit/Credit Note Generation\r\n					    </div>\r\n					</div>\r\n				</div>\r\n				<div class=\"card-body cdbody\">\r\n					<div class=\"row m-b-5\">\r\n						<div class=\"col-sm-3 col-xs-3 col-md-3\"></div>\r\n						");
      out.write("\r\n					  	<div class=\"col-sm-6 col-xs-6 col-md-6\">\r\n							<div class=\"d-flex justify-content-center\">\r\n								<div class=\"form-group row\">\r\n									<div class=\"col-auto\">\r\n										<label class=\"form-label\"><b>From</b></label>\r\n									</div>\r\n									<div class=\"col-auto\">\r\n										<div class=\"input-group input-group-sm\" >\r\n											<input type=\"text\" class=\"form-control form-control-sm date fmsdtpick\" name=\"from_dt\" value=\"");
      out.print(from_dt);
      out.write("\" size=\"8\" maxLength=\"10\" \r\n											onblur=\"validateDate(this);\" onchange=\"validateDate(this);refresh();\" autocomplete=\"off\">\r\n											<span class=\"input-group-text\"><i class=\"fa fa-calendar fa-lg\"></i></span>\r\n											<script>document.forms[0].from_dt.value=\"");
      out.print(from_dt);
      out.write("\"</script>\r\n										</div>\r\n									</div>\r\n									<div class=\"col-auto\">\r\n										<label class=\"form-label\"><b>To</b></label>\r\n									</div>\r\n									<div class=\"col-auto\">\r\n										<div class=\"input-group input-group-sm\" >\r\n											<input type=\"text\" class=\"form-control form-control-sm date fmsdtpick\" name=\"to_dt\" value=\"");
      out.print(to_dt);
      out.write("\" size=\"8\" maxLength=\"10\" \r\n											onblur=\"validateDate(this);\" onchange=\"validateDate(this);refresh();\" autocomplete=\"off\">\r\n											<span class=\"input-group-text\"><i class=\"fa fa-calendar fa-lg\"></i></span>\r\n											<script>document.forms[0].to_dt.value=\"");
      out.print(to_dt);
      out.write("\"</script>\r\n										</div>\r\n									</div>\r\n								</div>\r\n							</div>\r\n						</div>\r\n					  	");
      out.write("\r\n					</div>\r\n				</div>\r\n				<div class=\"card-body cdbody\">\r\n					<!-- Deep23082025 for Dr/Cr Note  -->\r\n					");
int i=0,k=0,l=0,m=0;
					for(int j=0; j<VINVOICE_LIST_NAME.size(); j++)
					{ 
						int index=Integer.parseInt(""+VINDEX.elementAt(j));
						String heading = ""+VINVOICE_LIST_ABBR.elementAt(j);
						
      out.write("\r\n						<div class=\"row\">\r\n						<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n							<div class=\"accordion\">\r\n								<div class=\"accordion-item accor_item\">\r\n									<h2 class=\"accordion-header\" id=\"");
      out.print(heading);
      out.write("\">\r\n   										<button name=\"sub_module_cd\" class=\"accordion-button ");
if(!accroid.equals(heading)){
      out.write("collapsed");
}
      out.write(" accor-btn\" type=\"button\" \r\n   											data-bs-toggle=\"collapse\" data-bs-target=\"#collapse");
      out.print(j);
      out.write("\" aria-expanded=\"");
if(accroid.equals(heading)){
      out.write("true");
}else{
      out.write("false");
} 
      out.write("\" aria-controls=\"collapse");
      out.print(j);
      out.write("\">\r\n							    			");
      out.print(VINVOICE_LIST_NAME.elementAt(j));
      out.write(" &nbsp;<font color=\"blue\">(");
      out.print(index);
      out.write(" Items)</font>\r\n							      		</button>	\r\n							    	</h2>\r\n									<div id=\"collapse");
      out.print(j);
      out.write("\" class=\"accordion-collapse collapse ");
if(accroid.equals(heading)){
      out.write("show");
}
      out.write("\" aria-labelledby=\"");
      out.print(heading);
      out.write("\">\r\n							      		<div class=\"accordion-body accor-body\">\r\n											");
      out.write("\r\n											<div class=\"row\">\r\n												<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n													<div class=\"table-responsive\">\r\n														<table class=\"table table-bordered table-hover\">\r\n															<thead>\r\n																<tr>\r\n																	<th rowspan=\"2\">Customer</th>\r\n																	<th rowspan=\"2\">Contract No<br>[Contract/Trade Ref#]</th>\r\n																	<th rowspan=\"2\">Contract Period</th>\r\n																	<th rowspan=\"2\">Plant</th>\r\n																	<th rowspan=\"2\">Business Unit</th>\r\n																	<th rowspan=\"2\">Billing Cycle</th>\r\n																	<th rowspan=\"2\">Billing Period</th>\r\n																	<th rowspan=\"2\">Item Description</th>\r\n																	<th rowspan=\"2\">Invoice#</th>\r\n																	<th rowspan=\"2\">DR/CR#</th>\r\n																	<th rowspan=\"2\">Generate/View IRP</th>\r\n																	<th rowspan=\"2\">Modify IRP</th>\r\n																	<th rowspan=\"2\">IRP Check</th>	\r\n																	<th rowspan=\"2\">Fin Ops<br>Finalization</th>				\r\n																	<th rowspan=\"2\">SAP Xml</th>\r\n");
      out.write("																	");
if(heading.equals("LTCORA_INV_HEAD")) {
      out.write("<th rowspan=\"2\">IRN Status</th>");
} 
      out.write("\r\n																	<th colspan=\"3\">\r\n																		<div align=\"center\">\r\n																		");
      out.write("	\r\n																			\r\n																				<select class=\"form-select form-select-sm\" name=\"drcr_pdf_type\" id=\"drcr_pdf_type_");
      out.print(heading);
      out.write("\" style=\"width:80px;\" onchange=\"refresh('");
      out.print(heading);
      out.write("');\">\r\n																				<option value=\"O\">Original</option>\r\n																				<option value=\"D\">Duplicate</option>\r\n																				<option value=\"T\">Triplicate</option>\r\n																				<option value=\"All\">All</option>\r\n																			</select>\r\n																			<script>document.getElementById(\"drcr_pdf_type_");
      out.print(heading);
      out.write("\").value=\"");
      out.print(drcr_pdf_type);
      out.write("\"</script>\r\n																		</div>\r\n																	</th>\r\n																</tr>\r\n																<tr>\r\n																	<th>Print PDF</th>\r\n																	<th>View PDF</th>\r\n																	<th>Send Mail</th>\r\n																</tr>\r\n															</thead>\r\n															<tbody>\r\n															");
k=0;
															if(index>0)
															{
																for(i=i; i<VCOUNTERPARTY_CD.size(); i++)
																{ 
																	k+=1;
																
      out.write("\r\n																<tr>\r\n																	<td align=\"center\">\r\n																		");
      out.print(VCOUNTERPARTY_ABBR.elementAt(i));
      out.write("\r\n																	</td>\r\n																	<td align=\"center\">\r\n																		<font color=\"blue\">");
      out.print(VDEAL_NO.elementAt(i));
      out.write("</font><br>[");
      out.print(VDEAL_CONT_REF_NO.elementAt(i));
      out.write("]\r\n																	</td>\r\n																	<td align=\"center\">");
      out.print(VDRCR_START_DT.elementAt(i));
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(VDRCR_END_DT.elementAt(i));
      out.write("</td>\r\n																	<td align=\"center\">");
      out.print(VDRCR_PLANT_ABBR.elementAt(i));
      out.write("</td>\r\n																	<td align=\"center\">");
      out.print(VDRCR_BU_PLANT_ABBR.elementAt(i));
      out.write("</td>\r\n																	<td align=\"center\">\r\n																		<span \r\n								    									");
if(VDRCR_BILLING_FREQ_NM.elementAt(i).equals("1st-Fortnight")){ 
      out.write("\r\n								    										class=\"alert alert-info\"\r\n								    									");
}else if(VDRCR_BILLING_FREQ_NM.elementAt(i).equals("2nd-Fortnight")){ 
      out.write("\r\n								    										class=\"alert alert-warning\"\r\n								    									");
}else if(VDRCR_BILLING_FREQ_NM.elementAt(i).equals("1st-Weekly")){ 
      out.write("\r\n								    										class=\"alert\" style=\"background:#eeccff;color: #660099;\"\r\n								    									");
}else if(VDRCR_BILLING_FREQ_NM.elementAt(i).equals("2nd-Weekly")){ 
      out.write("\r\n								    										class=\"alert alert-dark\"\r\n								    									");
}else if(VDRCR_BILLING_FREQ_NM.elementAt(i).equals("3rd-Weekly")){ 
      out.write("\r\n								    										class=\"alert alert-success\"\r\n								    									");
}else if(VDRCR_BILLING_FREQ_NM.elementAt(i).equals("4th-Weekly")){ 
      out.write("\r\n								    										class=\"alert alert-danger\"\r\n								    									");
}else if(VDRCR_BILLING_FREQ_NM.elementAt(i).equals("5th-Weekly")){ 
      out.write("\r\n								    										class=\"alert\" style=\"background:#e6ccff;color:#330066;\"\r\n								    									");
}else if(VDRCR_BILLING_FREQ_NM.elementAt(i).equals("Monthly")){ 
      out.write("\r\n								    										class=\"alert alert-primary\"\r\n								    									");
}else if(VDRCR_BILLING_FREQ_NM.elementAt(i).equals("Other")){ 
      out.write("\r\n								    										class=\"alert\" style=\"background:#b3ffb3;color: #008000;\"\r\n								    									");
} 
      out.write("\r\n								    									><b>");
      out.print(VDRCR_BILLING_FREQ_NM.elementAt(i));
      out.write("</b></span>												\r\n																	</td>\r\n																	<td align=\"center\">\r\n																	");
      out.print(VDRCR_PERIOD_START_DT.elementAt(i));
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(VDRCR_PERIOD_END_DT.elementAt(i));
      out.write("\r\n																	</td>\r\n																	<td align =\"center\">");
      out.print(VDRCR_FLAG.elementAt(i));
      out.write(' ');
      out.write(':');
      out.write(' ');
      out.print(VDRCR_ITEM_DESC.elementAt(i));
      out.write("</td>\r\n																	<td align=\"center\">");
      out.print(VDRCR_INVOICE_NO.elementAt(i));
      out.write("</td>\r\n																	<td align=\"center\">");
      out.print(VDRCR_NO.elementAt(i));
      out.write("</td>\r\n																	<td align=\"center\">											\r\n																		<i class=\"fa ");
if(VDRCR_SEQ.elementAt(i).equals("")){ 
      out.write("fa-cogs");
}else{
      out.write("fa-eye");
} 
      out.write(" fa-2x\" \r\n																			onclick=\"openActivity1('");
      out.print(VCOUNTERPARTY_CD.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_AGMT_NO.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_AGMT_REV_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CONT_NO.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_CONT_REV_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CONTRACT_TYPE.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_PLANT_SEQ.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_PERIOD_START_DT.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_PERIOD_END_DT.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_BU_PLANT_SEQ.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_BILLING_FREQ_FLAG.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_FINANCIAL_YEAR.elementAt(i) );
      out.write("',\r\n																								'");
      out.print(VDRCR_BU_STATE_TIN.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_START_DT.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_END_DT.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CARGO_NO.elementAt(i));
      out.write("','INSERT','");
      out.print(heading);
      out.write("',\r\n																								'");
      out.print(VDRCR_INV_FLAG.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CRITERIA.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_FLAG.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR1_SEQ.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_REMARK.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VFINANCIAL_YEAR.elementAt(i));
      out.write("');\"\r\n																			style=\"");
if(!VDRCR_SEQ.elementAt(i).equals("")){ 
      out.write("\r\n																				color:black;\r\n																				");
}else{
      out.write("\r\n																				color: #008080; \r\n																				");
} 
      out.write("\"\r\n																				>																		\r\n																			</i>		\r\n																	</td>\r\n																	<td align=\"center\">\r\n																		 <i class=\"fa fa-pencil fa-2x\" \r\n																			onclick=\"openActivity1('");
      out.print(VCOUNTERPARTY_CD.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_AGMT_NO.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_AGMT_REV_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CONT_NO.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_CONT_REV_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CONTRACT_TYPE.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_PLANT_SEQ.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_PERIOD_START_DT.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_PERIOD_END_DT.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_BU_PLANT_SEQ.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_BILLING_FREQ_FLAG.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_FINANCIAL_YEAR.elementAt(i) );
      out.write("',\r\n																								'");
      out.print(VDRCR_BU_STATE_TIN.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_START_DT.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_END_DT.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CARGO_NO.elementAt(i));
      out.write("','MODIFY','");
      out.print(heading);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_INV_FLAG.elementAt(i) );
      out.write("');\"\r\n																			style=\"");
if(!VCOUNTERPARTY_CD.elementAt(i).equals("")){ 
      out.write("\r\n																					pointer-events: none; opacity: .65;color: gray;\r\n																					");
} else {
      out.write("\r\n																						color:#ff9900;\r\n																					");
}
      out.write("\">\r\n																			</i>\r\n																	</td>\r\n																	<td align=\"center\">\r\n																	<i class=\"fa fa-stethoscope fa-2x\"												\r\n																			onclick=\"openActivity3('");
      out.print(VCOUNTERPARTY_CD.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_AGMT_NO.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_AGMT_REV_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CONT_NO.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_CONT_REV_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CONTRACT_TYPE.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_PLANT_SEQ.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_PERIOD_START_DT.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_PERIOD_END_DT.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_BU_PLANT_SEQ.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_BILLING_FREQ_FLAG.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_FINANCIAL_YEAR.elementAt(i) );
      out.write("',\r\n																								'");
      out.print(VDRCR_BU_STATE_TIN.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_INVOICE_SEQ.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CARGO_NO.elementAt(i));
      out.write("',\r\n																								'CHECK','");
      out.print(heading);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_INV_FLAG.elementAt(i) );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_FLAG.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_SEQ.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VFINANCIAL_YEAR.elementAt(i));
      out.write("');\"\r\n																			style=\"");
if(VDRCR_INV_APPROVED_FLAG.elementAt(i).equals("Y") || VDRCR_INVOICE_EXIST.elementAt(i).equals("N")){ 
      out.write("\r\n																					pointer-events: none; opacity: .65; color: gray;\r\n																					");
} else {
      out.write("\r\n																						color:#ff3399;\r\n																					");
}
      out.write("\">\r\n																	</i>\r\n																	</td>\r\n																	<td align=\"center\">												\r\n																		<i class=\"fa fa-flag fa-2x\"\r\n																			onclick=\"openActivity3('");
      out.print(VCOUNTERPARTY_CD.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_AGMT_NO.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_AGMT_REV_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CONT_NO.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_CONT_REV_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CONTRACT_TYPE.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_PLANT_SEQ.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_PERIOD_START_DT.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_PERIOD_END_DT.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_BU_PLANT_SEQ.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_BILLING_FREQ_FLAG.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_FINANCIAL_YEAR.elementAt(i) );
      out.write("',\r\n																								'");
      out.print(VDRCR_BU_STATE_TIN.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_INVOICE_SEQ.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CARGO_NO.elementAt(i));
      out.write("',\r\n																								'APPROVE','");
      out.print(heading);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_INV_FLAG.elementAt(i) );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_FLAG.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_SEQ.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VFINANCIAL_YEAR.elementAt(i));
      out.write("');\"\r\n\r\n																				");
if(heading.equals("LTCORA_INV_HEAD")) {
      out.write("\r\n																			style=\"");
if(!VDRCR_PDF_INV_FLAG.elementAt(i).equals("") || !VDRCR_INV_CHECKED_FLAG.elementAt(i).equals("Y") || VDRCR_IS_IRN_GENERATED.elementAt(i).equals("Y")){ 
      out.write("\r\n																					pointer-events: none; opacity: .65; color: gray;\r\n																					");
} else{
      out.write("\r\n																					color:#00cc00;\r\n																					");
}
      out.write("\">\r\n																			");
}else{ 
      out.write("\r\n																			style=\"");
if(!VDRCR_PDF_INV_FLAG.elementAt(i).equals("") || !VDRCR_INV_CHECKED_FLAG.elementAt(i).equals("Y")){ 
      out.write("\r\n																					pointer-events: none; opacity: .65; color: gray;\r\n																					");
} else{
      out.write("\r\n																					color:#00cc00;\r\n																					");
}
      out.write("\">\r\n																			");
} 
      out.write("\r\n																		</i>				 										\r\n																	</td>\r\n																	<td align=\"center\">\r\n																		 <i class=\"fa ");
if(!VDRCR_SAP_APPROVAL_FLAG.elementAt(i).equals("Y")){ 
      out.write("fa-file-code-o");
}else{
      out.write("fa-eye");
} 
      out.write(" fa-2x\" \r\n																		onclick=\"doGenXML('");
      out.print(VCOUNTERPARTY_CD.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_INVOICE_NO.elementAt(i));
      out.write("',\r\n																		 		'");
      out.print(VDRCR_FINANCIAL_YEAR.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_INVOICE_SEQ.elementAt(i));
      out.write("',\r\n																		 		'");
      out.print(VDRCR_CONTRACT_TYPE.elementAt(i));
      out.write("','DRCR',\r\n																		 		'");
      out.print(VDRCR_BU_STATE_TIN.elementAt(i));
      out.write("',\r\n																		 		'");
      out.print(VDRCR_SAP_APPROVAL_FLAG.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_AGMT_NO.elementAt(i));
      out.write("',\r\n																		 		'");
      out.print(VDRCR_CONT_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_PDF_INV_FLAG.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(heading);
      out.write("');\"\r\n																		");
      out.write("\r\n																		style=\"");
if(!VDRCR_SAP_APPROVAL_FLAG.elementAt(i).equals("Y")){ 
      out.write("\r\n																			pointer-events: none; opacity: .65; color: gray;\r\n																			");
} else{
      out.write("\r\n																				");
if(!VDRCR_SAP_APPROVAL_FLAG.elementAt(i).equals("Y")){ 
      out.write("\r\n																					color: orange;\r\n																				");
} else{
      out.write("\r\n																					color: brown;\r\n																				");
}
      out.write("	\r\n																			");
}
      out.write("\">													\r\n																		</i>\r\n																	</td>\r\n																	</td>\r\n																		");
if(heading.equals("LTCORA_INV_HEAD")) {
      out.write("\r\n																		<td align=\"center\">\r\n																			<i class=\"fa fa-qrcode fa-2x\"\r\n																				");
if(VDRCR_IS_IRN_GENERATED.elementAt(i).equals("Y")) {
      out.write("\r\n																				title=\"IRN Generated!\"\r\n																				style=\"color: #0099cc;\"\r\n																				");
}else{ 
      out.write("\r\n																				title=\"Generation of IRN is Pending!\"\r\n																				style=\"opacity: .65; color: gray;\"\r\n																				");
} 
      out.write("	\r\n																			></i>\r\n																		</td>\r\n																		");
} 
      out.write("\r\n																	<td align=\"center\">\r\n																			<i class=\"fa fa-print fa-2x\" title=\"");
      out.print(VDRCR_PDF_TYPE.elementAt(i));
      out.write("\"\r\n																				onclick=\"PrintPDF('");
      out.print(VCOUNTERPARTY_CD.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_AGMT_NO.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_AGMT_REV_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CONT_NO.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_CONT_REV_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CONTRACT_TYPE.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_PLANT_SEQ.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_PERIOD_START_DT.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_PERIOD_END_DT.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_BU_PLANT_SEQ.elementAt(i));
      out.write("',\r\n																								'");
      out.print(VDRCR_BILLING_FREQ_FLAG.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_FINANCIAL_YEAR.elementAt(i) );
      out.write("',\r\n																								'");
      out.print(VDRCR_BU_STATE_TIN.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_INVOICE_SEQ.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(i);
      out.write("',\r\n																								'");
      out.print(VDRCR_CARGO_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(heading);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_INV_FLAG.elementAt(i) );
      out.write("',\r\n																								'");
      out.print(VDRCR_FLAG.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_SEQ.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CRITERIA.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VFINANCIAL_YEAR.elementAt(i));
      out.write("');\"\r\n																				style=\"");
if(!VDRCR_INV_APPROVED_FLAG.elementAt(i).equals("Y") || !VDRCR_IS_IRN_GENERATED.elementAt(i).equals("Y") || VDRCR_PDF_TYPE.elementAt(i).equals(drcr_pdf_type)){ 
      out.write("\r\n																				pointer-events: none; opacity: .65; color: gray;\r\n																				");
} else{
      out.write("\r\n																				color:#800000;\r\n																				");
}
      out.write("\">\r\n																			</i>\r\n																			<input type=\"hidden\" name=\"all_pdf_type\" id=\"all_pdf_type");
      out.print(i);
      out.write("\" value=\"");
      out.print(VDRCR_PDF_TYPE.elementAt(i));
      out.write("\">\r\n																		</td>\r\n																	<td align=\"center\">\r\n																		<i class=\"fa fa-file-pdf-o fa-2x\"\r\n																			onclick=\"openPdfFile('");
      out.print(file_url);
      out.print(VDRCR_PDF_FILE_PATH.elementAt(i));
      out.print(VDRCR_PDF_FILE_NAME.elementAt(i));
      out.write("')\"\r\n																			style=\"");
if(VDRCR_PDF_FILE_NAME.elementAt(i).equals("")){ 
      out.write("\r\n																			pointer-events: none; opacity: .65; color: gray;\r\n																			");
} else{
      out.write("\r\n																			color:red;\r\n																			");
}
      out.write("\">\r\n																		</i>\r\n																	</td>\r\n																	<td align=\"center\">\r\n																		<i class=\"fa fa-envelope-o fa-2x\" title=\"");
      out.print(VDRCR_SIGN_PDF_TYPE.elementAt(i));
      out.write("\"\r\n																			onclick=\"openMailBody('");
      out.print(VCOUNTERPARTY_CD.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_AGMT_NO.elementAt(i));
      out.write("',\r\n																				'");
      out.print(VDRCR_AGMT_REV_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CONT_NO.elementAt(i));
      out.write("',\r\n																				'");
      out.print(VDRCR_CONT_REV_NO.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CONTRACT_TYPE.elementAt(i));
      out.write("',\r\n																				'");
      out.print(VDRCR_PLANT_SEQ.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_PERIOD_START_DT.elementAt(i));
      out.write("',\r\n																				'");
      out.print(VDRCR_PERIOD_END_DT.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_BU_PLANT_SEQ.elementAt(i));
      out.write("',\r\n																				'");
      out.print(VDRCR_BILLING_FREQ_FLAG.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_FINANCIAL_YEAR.elementAt(i) );
      out.write("',\r\n																				'");
      out.print(VDRCR_BU_STATE_TIN.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_INVOICE_SEQ.elementAt(i));
      out.write("',\r\n																				'");
      out.print(i);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(heading);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_INV_FLAG.elementAt(i) );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_FLAG.elementAt(i));
      out.write("',\r\n																				'");
      out.print(VDRCR_SEQ.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VDRCR_CRITERIA.elementAt(i));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(VFINANCIAL_YEAR.elementAt(i));
      out.write("');\"\r\n																			style=\"");
if(VDRCR_SIGN_PDF_TYPE.elementAt(i).equals("")){ 
      out.write("\r\n																			pointer-events: none; opacity: .65; color: gray;\r\n																			");
} else{
      out.write("\r\n																			color:blue;\r\n																			");
}
      out.write("\">\r\n																		</i>\r\n																		<input type=\"hidden\" name=\"drcr_all_mail_pdf_type\" id=\"drcr_all_mail_pdf_type");
      out.print(i);
      out.write("\" value=\"");
      out.print(VDRCR_SIGN_PDF_TYPE.elementAt(i));
      out.write("\">\r\n																	</td>\r\n																</tr>\r\n																		");
if(k==index){
																			i=i+1;
																			break;
																		} 
      out.write("\r\n																	");
} 
      out.write("	\r\n																");
}else{ 
      out.write("\r\n																<tr>\r\n																	<td align=\"center\" colspan=\"16\">");
      out.print(utilmsg.infoMessage("<b>No Debit/Credit Note is Ready for Generate!</b>") );
      out.write("</td>\r\n																</tr>\r\n															");
} 
      out.write("\r\n															</tbody>	\r\n														</table>\r\n													</div>\r\n												</div>\r\n											</div>\r\n										</div>\r\n									</div>\r\n								</div>\r\n							</div>\r\n						</div>\r\n					</div>\r\n					");
} 
      out.write("			\r\n				</div>\r\n			</div>\r\n		</div>\r\n	</div>\r\n</div>\r\n\r\n");
      out.write("\r\n<input type=\"hidden\" name=\"sysdate\" value=\"");
      out.print(sysdate);
      out.write("\">\r\n\r\n<input type=\"hidden\" name=\"read_access\" value=\"");
      out.print(read_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"write_access\" value=\"");
      out.print(write_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"check_access\" value=\"");
      out.print(check_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"print_access\" value=\"");
      out.print(print_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"delete_access\" value=\"");
      out.print(delete_access);
      out.write("\">  	\r\n<input type=\"hidden\" name=\"audit_access\" value=\"");
      out.print(audit_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"authorize_access\" value=\"");
      out.print(authorize_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"approve_access\" value=\"");
      out.print(approve_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"execute_access\" value=\"");
      out.print(execute_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"form_cd\" value=\"");
      out.print(formCd);
      out.write("\">\r\n<input type=\"hidden\" name=\"form_nm\" value=\"");
      out.print(formNm);
      out.write("\">\r\n<input type=\"hidden\" name=\"mod_cd\" value=\"");
      out.print(mod_cd);
      out.write("\">\r\n<input type=\"hidden\" name=\"mod_nm\" value=\"");
      out.print(mod_nm);
      out.write("\">\r\n<input type=\"hidden\" name=\"u\" value=\"");
      out.print(u);
      out.write("\">\r\n\r\n<input type=\"hidden\" name=\"accroid\" value=\"\">\r\n\r\n</form>\r\n</body>\r\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
