/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2025-09-09 05:54:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sales_005finvoice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Vector;
import com.etrm.fms.util.EncryptTest;

public final class rpt_005fdrcr_005fview_005fchk_005faprv_005fdtl_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/sales_invoice/../home/loading.jsp", Long.valueOf(1754630775663L));
    _jspx_dependants.put("/sales_invoice/../util/common_val.jsp", Long.valueOf(1754630867617L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("com.etrm.fms.util.EncryptTest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<title>Debit/Credit Note</title>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../font-awesome-4.7.0/css/font-awesome.min.css\">\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/common.css\">\r\n");
      out.write('\r');
      out.write('\n');
      com.etrm.fms.util.DataBean_Menu menu_access = null;
      menu_access = (com.etrm.fms.util.DataBean_Menu) _jspx_page_context.getAttribute("menu_access", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (menu_access == null){
        menu_access = new com.etrm.fms.util.DataBean_Menu();
        _jspx_page_context.setAttribute("menu_access", menu_access, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

String formCd="";
String mod_cd="";
String u=request.getParameter("u")==null?"":request.getParameter("u");

String msg=request.getParameter("msg")==null?"":request.getParameter("msg");
String msg_type=request.getParameter("msg_type")==null?"":request.getParameter("msg_type");

String owner_cd="";
if(session.getAttribute("comp_cd")==null||session.getAttribute("comp_cd")==""||session.getAttribute("comp_cd").toString().equals("null"))
{
	owner_cd="";
}  
else
{
	owner_cd=""+session.getAttribute("comp_cd");
}

String owner_abbr="";
if(session.getAttribute("comp_abbr")==null||session.getAttribute("comp_abbr")==""||session.getAttribute("comp_abbr").toString().equals("null"))
{
	owner_abbr="";
}  
else
{
	owner_abbr=""+session.getAttribute("comp_abbr");
}

String emp_cd="";
if(session.getAttribute("emp_cd")==null||session.getAttribute("emp_cd")==""||session.getAttribute("emp_cd").toString().equals("null"))
{
	emp_cd="";
}  
else
{
	emp_cd=""+session.getAttribute("emp_cd");
}

if(!u.equals(""))
{
	StringBuffer decryt=new EncryptTest().URLdecrypt(u);
	String dec=""+decryt;
	if(!dec.equals("") && dec.contains("-"))
	{
		String temp[]=dec.split("-");
		if(temp.length==2)
		{
			formCd=temp[0];
			mod_cd=temp[1];
		}
	}
}

menu_access.setCallFlag("MENU_ACCESS");
menu_access.setEmpCd(emp_cd);
menu_access.setComp_cd(owner_cd);
menu_access.setModule_cd(mod_cd);
menu_access.setForm_cd(formCd);
menu_access.init();


String formNm = menu_access.getForm_nm();
String mod_nm = menu_access.getModule_nm();
String read_access = menu_access.getRead_access();
String write_access = menu_access.getWrite_access();
String check_access = menu_access.getCheck_access();
String print_access = menu_access.getPrint_access();
String delete_access = menu_access.getDelete_access();
String audit_access = menu_access.getAudit_access();
String authorize_access = menu_access.getAuthorize_access();
String approve_access = menu_access.getApprove_access();
String execute_access = menu_access.getExecute_access();


      out.write("\r\n<script>\r\nfunction setInvoiceNo()\r\n{\r\n	var e = document.forms[0].invoice_id_seq;\r\n	var invoiceNo = e.options[e.selectedIndex].text;\r\n	if(document.forms[0].invoice_id_seq.value==\"\")\r\n	{\r\n		document.forms[0].drcr_invoice_no.value=\"\";\r\n	}\r\n	else\r\n	{\r\n		document.forms[0].drcr_invoice_no.value=invoiceNo;\r\n	}\r\n}\r\nfunction doSubmit()\r\n{\r\n	var msg=\"\";\r\n	var flag=true;\r\n	\r\n	var activityFlag = document.forms[0].activityFlag.value;\r\n	var check_access = document.forms[0].check_access.value;\r\n	var approve_access = document.forms[0].approve_access.value;\r\n	var drcr_flag = document.forms[0].drcr_flag.value;\r\n	\r\n	\r\n	var drcr_invoice_no = document.forms[0].drcr_invoice_no.value;\r\n	if(activityFlag==\"APPROVE\")\r\n	{\r\n		if(approve_access==\"N\")\r\n		{\r\n			msg+=\"You don't have Approval Rights!\\n\";\r\n			flag=false;\r\n		}\r\n	}\r\n	else if(activityFlag==\"CHECK\")\r\n	{\r\n		if(check_access==\"N\")\r\n		{\r\n			msg+=\"You don't have Check Rights!\\n\";\r\n			flag=false;\r\n		}\r\n	}\r\n	\r\n	if(flag)\r\n	{\r\n		var drcr = \"\";\r\n		if(drcr_flag == \"DR\") {\r\n			drcr = \"Debit\";\r\n");
      out.write("		}\r\n		else {\r\n			drcr = \"Credit\";\r\n		}\r\n		var activity_nm=\"\"\r\n		var invNo=\"\";\r\n		if(activityFlag==\"CHECK\")\r\n		{\r\n			if(document.forms[0].rd[0].checked)\r\n			{\r\n				activity_nm=\"Check\"\r\n					invNo+=\"Do you want to \"+activity_nm+\" \"+drcr_flag+\" Note?\"	\r\n			}\r\n			else if(document.forms[0].rd[1].checked)\r\n			{\r\n				activity_nm=\"Reject\"\r\n				invNo+=\"Do you want to \"+activity_nm+\" \"+drcr_flag+\" Note?\\n\\n\"	\r\n			}\r\n		}\r\n		else if(activityFlag==\"APPROVE\")\r\n		{\r\n			if(document.forms[0].rd[0].checked)\r\n			{\r\n				activity_nm=\"Approve\"\r\n					invNo+=\"Do you want to \"+activity_nm+\" \"+drcr_flag+\" Note?\\n\\n\"	\r\n			}\r\n			else if(document.forms[0].rd[1].checked)\r\n			{\r\n				activity_nm=\"Reject\"\r\n				invNo+=\"Do you want to \"+activity_nm+\" \"+drcr_flag+\" Note?\\n\\n\"	\r\n				invNo+=\"Selected Invoice# will be Removed!\";\r\n				\r\n				document.forms[0].invoice_id_seq.value=\"\";\r\n				document.forms[0].invoice_no.value=\"\";\r\n			}\r\n		}\r\n		var a=confirm(invNo);\r\n		if(a)\r\n		{\r\n			document.getElementById(\"loading\").style.visibility = \"visible\";\r\n			document.forms[0].submit();\r\n");
      out.write("		}\r\n	}\r\n	else\r\n	{\r\n		alert(msg);\r\n	}\r\n}\r\nfunction Do_close(msg,msg_type,accroid)\r\n{\r\n	window.opener.refershPar(msg,msg_type,accroid);\r\n	window.close();\r\n}\r\n\r\nvar newWindow_att1;\r\nfunction openAtt1(url)\r\n{\r\n	if(!newWindow_att1 || newWindow_att1.closed)\r\n	{\r\n		newWindow_att1 = window.open(url,\"Attachment1\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n	}\r\n	else\r\n	{\r\n		newWindow_att1.close();\r\n		newWindow_att1 = window.open(url,\"Attachment1\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n	}\r\n}\r\n\r\nvar newWindow_att2;\r\nfunction openAtt2(url)\r\n{\r\n	if(!newWindow_att2 || newWindow_att2.closed)\r\n	{\r\n		newWindow_att2 = window.open(url,\"Attachment2\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n	}\r\n	else\r\n	{\r\n		newWindow_att2.close();\r\n		newWindow_att2 = window.open(url,\"Attachment2\",\"top=10,left=10,width=1100,height=900,scrollbars=1\");\r\n	}\r\n}\r\n</script>\r\n</head>\r\n");
      com.etrm.fms.sales_invoice.DataBean_Sales_Drcr_note Drcr_note = null;
      Drcr_note = (com.etrm.fms.sales_invoice.DataBean_Sales_Drcr_note) _jspx_page_context.getAttribute("Drcr_note", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (Drcr_note == null){
        Drcr_note = new com.etrm.fms.sales_invoice.DataBean_Sales_Drcr_note();
        _jspx_page_context.setAttribute("Drcr_note", Drcr_note, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');

//String owner_cd=session.getAttribute("comp_cd").toString().equals("null")?"":""+session.getAttribute("comp_cd");
//String owner_abbr=""+session.getAttribute("comp_abbr")==null?"":""+session.getAttribute("comp_abbr");
String owner_nm=""+session.getAttribute("comp_nm")==null?"":""+session.getAttribute("comp_nm");

String counterparty_cd=request.getParameter("counterparty_cd")==null?"":request.getParameter("counterparty_cd");
String contract_type=request.getParameter("contract_type")==null?"":request.getParameter("contract_type");
String cont_no=request.getParameter("cont_no")==null?"":request.getParameter("cont_no");
String cont_rev=request.getParameter("cont_rev")==null?"":request.getParameter("cont_rev");
String agmt_no=request.getParameter("agmt_no")==null?"":request.getParameter("agmt_no");
String agmt_rev=request.getParameter("agmt_rev")==null?"":request.getParameter("agmt_rev");
String plant_seq=request.getParameter("plant_seq")==null?"":request.getParameter("plant_seq");
String billing_cycle=request.getParameter("billing_cycle")==null?"":request.getParameter("billing_cycle");
String period_start_dt=request.getParameter("period_start_dt")==null?"":request.getParameter("period_start_dt");
String period_end_dt=request.getParameter("period_end_dt")==null?"":request.getParameter("period_end_dt");
String bu_unit=request.getParameter("bu_unit")==null?"":request.getParameter("bu_unit");
String financial_year=request.getParameter("financial_year")==null?"":request.getParameter("financial_year");
String bu_state_tin=request.getParameter("bu_state_tin")==null?"":request.getParameter("bu_state_tin");
String invoice_seq=request.getParameter("invoice_seq")==null?"":request.getParameter("invoice_seq");
String activityFlag=request.getParameter("activityFlag")==null?"":request.getParameter("activityFlag");
String cargo_no=request.getParameter("cargo_no")==null?"":request.getParameter("cargo_no");
String accroid=request.getParameter("accroid")==null?"":request.getParameter("accroid");
String inv_flag=request.getParameter("inv_flag")==null?"":request.getParameter("inv_flag");
String drcr_flag=request.getParameter("drcr_flag")==null?"":request.getParameter("drcr_flag");
String drcr_seq=request.getParameter("drcr_seq")==null?"":request.getParameter("drcr_seq");
String drcr_fin_yr=request.getParameter("drcr_fin_yr")==null?"":request.getParameter("drcr_fin_yr");

//String msg=request.getParameter("msg")==null?"":request.getParameter("msg");
//String msg_type=request.getParameter("msg_type")==null?"":request.getParameter("msg_type");

Drcr_note.setCallFlag("DRCR_NOTE_REPORT");
Drcr_note.setComp_cd(owner_cd);
Drcr_note.setCounterparty_cd(counterparty_cd);
Drcr_note.setAgmt_no(agmt_no);
Drcr_note.setAgmt_rev_no(agmt_rev);
Drcr_note.setCont_no(cont_no);
Drcr_note.setCont_rev_no(cont_rev);
Drcr_note.setCargo_no(cargo_no);
Drcr_note.setContract_type(contract_type);
Drcr_note.setPlant_seq(plant_seq);
Drcr_note.setBilling_cycle(billing_cycle);
Drcr_note.setPeriod_start_dt(period_start_dt);
Drcr_note.setPeriod_end_dt(period_end_dt);
Drcr_note.setBu_unit(bu_unit);
Drcr_note.setFinancial_year(financial_year);
Drcr_note.setBu_state_tin(bu_state_tin);
Drcr_note.setActivityFlag(activityFlag);
Drcr_note.setInvoice_seq(invoice_seq);
Drcr_note.setInv_flag(inv_flag);
Drcr_note.setdrcr_seq(drcr_seq);
Drcr_note.setdrcr_flag(drcr_flag);
Drcr_note.setdrcr_fin_yr(drcr_fin_yr);
Drcr_note.init();

String couterpty_nm = Drcr_note.getCouterpty_nm();
String bu_contact_person_cd = Drcr_note.getBu_contact_person_cd();
String contact_person_cd = Drcr_note.getContact_person_cd();
String invoice_no=Drcr_note.getInvoice_no();
String invoice_id_seq=Drcr_note.getInvoice_id_seq();
String invoice_dt = Drcr_note.getInvoice_dt();
String invoice_due_dt = Drcr_note.getInvoice_due_dt();
String invoice_amt = Drcr_note.getInvoice_amt();
String inv_period_start_dt=Drcr_note.getInv_period_start_dt();
String inv_period_end_dt=Drcr_note.getInv_period_end_dt();
String remark_1 =Drcr_note.getRemark_1();
String remark_2 =Drcr_note.getRemark_2();
String invoice_raised_in=Drcr_note.getInvoice_raised_in();
String drcr_invoice_no=Drcr_note.getdrcr_invoice_no();

String drcr_dt=Drcr_note.getdrcr_dt();

String bu_contact_person_nm = Drcr_note.getBu_contact_person_nm();
String contact_person_nm = Drcr_note.getContact_person_nm();
String plantAddress=Drcr_note.getPlantAddress();
String plantCity=Drcr_note.getPlantCity();
String plantState=Drcr_note.getPlantState();
String plantPin=Drcr_note.getPlantPin();
String plantNm=Drcr_note.getPlantNm();

String bu_plantAddress=Drcr_note.getBu_plantAddress();
String bu_plantCity=Drcr_note.getBu_plantCity();
String bu_plantState=Drcr_note.getBu_plantState();
String bu_plantPin=Drcr_note.getBu_plantPin();
String bu_plantNm=Drcr_note.getBu_plantNm();

String tax_info=Drcr_note.getTax_info();
String bu_tax_info=Drcr_note.getBu_tax_info();
String activity_value = Drcr_note.getActivity_value();
String contRef=Drcr_note.getContRef();
String dda_dt=Drcr_note.getDda_dt();
String signingDt=Drcr_note.getSigningDt();
String agmtSigningDt=Drcr_note.getAgmtSigningDt();

Vector VPDF_COL1 = Drcr_note.getVPDF_COL1();
Vector VPDF_COL2 = Drcr_note.getVPDF_COL2();
Vector VPDF_COL3 = Drcr_note.getVPDF_COL3();
Vector VPDF_COL4 = Drcr_note.getVPDF_COL4();
Vector VPDF_COL5 = Drcr_note.getVPDF_COL5();
Vector VPDF_COL6 = Drcr_note.getVPDF_COL6();
Vector VPDF_COL7 = Drcr_note.getVPDF_COL7();

Vector VINVOICE_ID_SEQ = Drcr_note.getVINVOICE_ID_SEQ();
Vector VINVOICE_NO = Drcr_note.getVINVOICE_NO();

      out.write("\r\n<body ");
if(!msg.equals("")){ 
      out.write("onload=\"Do_close('");
      out.print(msg);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(msg_type);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(accroid);
      out.write("');\"");
} 
      out.write(" onload=\"setInvoiceNo();\">\r\n\r\n");
      out.write("<div id=\"loading\" style=\"visibility: hidden;\">\n	<div id=\"loading-image\">\n		<div class=\"btn-group\">\n			<label class=\"btn\" style=\"color:var(--header_color);border:none;font-size:20px;align-self: center;font-weight:bold;\">\n				<i class=\"fa fa-spinner fa-pulse fa-lg\"></i>&nbsp;Loading\n			</label>\n		</div>\n	</div>\n</div>");
      out.write("\r\n\r\n<form method=\"post\" action=\"../servlet/Frm_Sales_Drcr_note\">\r\n<table width=\"100%\"  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n	<tr valign=\"middle\">\r\n		<td colspan=\"7\">\r\n			<div align=\"center\">\r\n				<font size=\"2\" face=\"Arial\">\r\n					<b>ORIGINAL</b>\r\n					<br>\r\n				</font>\r\n				<font size=\"4\" face=\"Arial\">\r\n					<b>");
      out.print(owner_nm);
      out.write("</b>\r\n					<br>\r\n					");
if(drcr_flag.equals("DR")) {
      out.write("\r\n					<b>DEBIT NOTE </b>\r\n					");
}else{ 
      out.write("\r\n					<b>CREDIT NOTE</b>\r\n					");
} 
      out.write("\r\n				</font>\r\n				");
if(contract_type.equals("Q") || contract_type.equals("O")) {
      out.write("\r\n				<font size=\"2\" face=\"Arial\">\r\n					<br>\r\n					<b>Tax Invoice issued under Rule 46 of the Central Goods and Services Tax Rules, 2017</b>\r\n				</font>\r\n				");
} 
      out.write("\r\n			</div>\r\n		</td>\r\n	</tr>\r\n	<tr valign=\"middle\">\r\n		<td colspan=\"7\">\r\n			<div align=\"center\">\r\n				<font size=\"1px\" face=\"Arial\">\r\n					<b></b>\r\n				</font>\r\n			</div>\r\n		</td>\r\n	</tr>\r\n	<tr valign=\"middle\">\r\n		<td colspan=\"7\">\r\n			<div align=\"center\">&nbsp;</div>\r\n		</td>\r\n	</tr>\r\n	<tr valign=\"middle\">\r\n		<td colspan=\"7\">\r\n			<div align=\"center\">\r\n				<font size=\"1px\" face=\"Arial\">\r\n					");
      out.write("\r\n					\r\n					In respect of \r\n					");
if(contract_type.equals("S")){ 
      out.write("Supply Notice (");
      out.print(contRef);
      out.write(") executed on ");
      out.print(signingDt);
      out.write(" pursuant to Framework Gas Sales Agreement executed on ");
      out.print(agmtSigningDt);
      out.write("\r\n					");
}else if(contract_type.equals("O")){ 
      out.write(" LTCORA Agreement executed on ");
      out.print(agmtSigningDt);
      out.write(" & CN (");
      out.print(contRef);
      out.write(") executed on ");
      out.print(signingDt);
      out.write("\r\n					");
}else if(contract_type.equals("Q")){ 
      out.write(" LTCORA Agreement executed on ");
      out.print(agmtSigningDt);
      out.write("\r\n					");
}else if(contract_type.equals("L")){ 
      out.write("Letter of Agreement (");
      out.print(contRef);
      out.write(") executed on ");
      out.print(signingDt);
      out.write(" \r\n					");
}else if(contract_type.equals("X")){ 
      out.write("Exchange Transaction (");
      out.print(contRef);
      out.write(") executed on ");
      out.print(signingDt);
      out.write("\r\n					");
} 
      out.write(" \r\n					<br>\r\n					between ");
      out.print(owner_nm);
      out.write(" and ");
      out.print(couterpty_nm );
      out.write("\r\n				</font>\r\n			</div>\r\n		</td>\r\n	</tr>\r\n	<tr valign=\"middle\">\r\n		<td colspan=\"7\">\r\n			<div align=\"center\">&nbsp;</div>\r\n		</td>\r\n	</tr>\r\n	<tr valign=\"top\">\r\n		<td colspan=\"3\" width=\"50%\">\r\n			<div align=\"left\">\r\n				<font size=\"1.5px\" face=\"Arial\">\r\n					Business Unit:");
      out.write("\r\n					<br>");
      out.print(owner_nm);
      out.write("\r\n					<br>");
      out.print(bu_plantAddress);
      out.write(',');
      out.print(bu_plantCity);
      out.write("\r\n					<br>");
      out.print(bu_plantState);
      out.write("&nbsp;-&nbsp;");
      out.print(bu_plantPin);
      out.write("\r\n				</font>\r\n			</div>\r\n		</td>\r\n		<td colspan=\"1\" width=\"10%\"><div align=\"left\"><font size=\"1.5px\" face=\"Arial\"><b>To:</b></font></div></td>\r\n		<td colspan=\"3\" width=\"40%\">\r\n			<div align=\"left\">\r\n				<font size=\"1.5px\" face=\"Arial\">\r\n					");
      out.print(contact_person_nm);
      out.write(",\r\n					<br>");
      out.print(couterpty_nm);
      out.write("\r\n					<br>");
      out.print(plantAddress);
      out.write(',');
      out.print(plantCity);
      out.write("\r\n					<br>");
      out.print(plantState );
      out.write("&nbsp;-&nbsp;");
      out.print(plantPin);
      out.write("\r\n				</font>\r\n			</div>\r\n		</td>\r\n	</tr>\r\n	<tr valign=\"top\"><td colspan=\"7\"><div align=\"center\">&nbsp;</div></td></tr>\r\n	<tr valign=\"top\">\r\n		<td colspan=\"3\">\r\n			<div>\r\n				<font size=\"1.5px\" face=\"Arial\">\r\n					");
      out.print(bu_tax_info );
      out.write("\r\n				</font>\r\n			</div>\r\n		</td>\r\n		<td colspan=\"1\">&nbsp;</td>\r\n 		<td colspan=\"3\">\r\n 			<div>\r\n 				<font size=\"1.5px\" face=\"Arial\">\r\n 					");
      out.print(tax_info );
      out.write("\r\n				</font>\r\n			</div>\r\n		</td>\r\n	</tr>\r\n	<tr valign=\"top\">\r\n		<td colspan=\"7\">&nbsp;</td>\r\n	</tr>\r\n	<tr valign=\"middle\">\r\n		<td colspan=\"4\"></td>\r\n		<td colspan=\"2\" width=\"25%\">\r\n			<div align=\"center\">\r\n				<table width=\"100%\"  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n					<tr>\r\n						<td>\r\n							<div align=\"right\">\r\n							");
if(drcr_flag.equals("DR")) {
      out.write("\r\n								<font size=\"1.5px\" face=\"Arial\"><b>Debit Note Date:&nbsp;</b></font>\r\n							");
} else {
      out.write("\r\n								<font size=\"1.5px\" face=\"Arial\"><b>Credit Note Date:&nbsp;</b></font>\r\n							");
} 
      out.write("\r\n							</div>\r\n						</td>\r\n					</tr>\r\n					");
if(invoice_due_dt.equals("")) {
      out.write("\r\n					\r\n					");
} else {
      out.write("\r\n					<tr>\r\n						<td>\r\n							<div align=\"right\">\r\n								<font size=\"1.5px\" face=\"Arial\"><b>Payment Due Date:&nbsp;</b></font>\r\n							</div>\r\n						</td>\r\n					</tr>\r\n					");
 }
      out.write("\r\n					<tr>\r\n						<td>\r\n							<div align=\"right\">\r\n								");
if(drcr_flag.equals("DR")) {
      out.write("\r\n									<font size=\"1.5px\" face=\"Arial\"><b>");
      out.print(owner_abbr);
      out.write(" Debit Note No:&nbsp;</b></font>\r\n								");
} else {
      out.write("\r\n									<font size=\"1.5px\" face=\"Arial\"><b>");
      out.print(owner_abbr);
      out.write(" Credit Note No:&nbsp;</b></font>\r\n								");
} 
      out.write("								\r\n							</div>\r\n						</td>\r\n					</tr>\r\n				</table>\r\n			</div>\r\n		</td>\r\n		<td colspan=\"1\" width=\"15%\">\r\n			<div align=\"center\">\r\n				<table width=\"100%\"  border=\"1\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n					<tr>\r\n						<td>\r\n							<div align=\"right\">\r\n								<font size=\"1.5px\" face=\"Arial\"><b>");
      out.print(drcr_dt);
      out.write("&nbsp;</b></font>\r\n							</div>\r\n						</td>\r\n					</tr>\r\n					");
if(invoice_due_dt.equals("")) {
      out.write("\r\n					\r\n					");
} else {
      out.write("\r\n					<tr>\r\n						<td>\r\n							<div align=\"right\">\r\n								<font size=\"1.5px\" face=\"Arial\"><b>");
      out.print(invoice_due_dt);
      out.write("&nbsp;</b></font>\r\n							</div>\r\n						</td>\r\n					</tr>\r\n					");
 }
      out.write("\r\n					<tr>\r\n						<td>\r\n						");
if(activityFlag.equals("APPROVE")){ 
      out.write("\r\n							\r\n							\r\n							<select name=\"invoice_id_seq\" style=\"background:yellow;font-weight:bold;\" onchange=\"setInvoiceNo();\">\r\n								<option value=\"\">--Select--</option>\r\n								");
for(int i=0; i<VINVOICE_ID_SEQ.size();i++){ 
      out.write("\r\n								<option value=\"");
      out.print(VINVOICE_ID_SEQ.elementAt(i));
      out.write('"');
      out.write('>');
      out.print(VINVOICE_NO.elementAt(i));
      out.write("</option>\r\n								 ");
} 
      out.write(" \r\n							</select> \r\n										");
      out.write("\r\n\r\n							<script>document.forms[0].invoice_id_seq.value=\"");
      out.print(invoice_id_seq);
      out.write("\"</script>\r\n						");
}else{ 
      out.write("\r\n							<div align=\"right\">\r\n								<font size=\"1.5px\" face=\"Arial\"><b>");
      out.print(drcr_invoice_no);
      out.write("&nbsp;</b></font>\r\n							</div>\r\n						");
} 
      out.write("\r\n						</td>\r\n					</tr>\r\n				</table>\r\n			</div>\r\n		</td>\r\n	</tr>\r\n	");
if(!inv_flag.equals("UG") && !inv_flag.equals("ST")){ 
      out.write("\r\n	<tr valign=\"middle\">\r\n		<td colspan=\"3\">\r\n			<div align=\"right\">\r\n				<font size=\"1.5px\" face=\"Arial\"><b>For the Billing Period</b></font>\r\n			</div>\r\n		</td>\r\n		<td colspan=\"1\">\r\n			<div align=\"right\">&nbsp;</div>\r\n		</td>\r\n		<td colspan=\"1\" width=\"15%\">\r\n			<div align=\"center\">\r\n				<table width=\"100%\"  border=\"1\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n					<tr>\r\n						<td>\r\n							<div align=\"right\">\r\n								<font size=\"1.5px\" face=\"Arial\"><b>");
      out.print(inv_period_start_dt);
      out.write("&nbsp;</b></font>\r\n							</div>\r\n						</td>\r\n					</tr>\r\n				</table>\r\n			</div>\r\n		</td>\r\n		<td colspan=\"1\" width=\"10%\">\r\n			<div align=\"center\">\r\n				<font size=\"1.5px\" face=\"Arial\"><b>to</b></font>\r\n			</div>\r\n		</td>\r\n		<td colspan=\"1\" width=\"15%\">\r\n			<div align=\"center\">\r\n				<table width=\"100%\"  border=\"1\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n					<tr>\r\n						<td>\r\n							<div align=\"right\">\r\n								<font size=\"1.5px\" face=\"Arial\"><b>");
      out.print(inv_period_end_dt);
      out.write("&nbsp;</b></font>\r\n							</div>\r\n						</td>\r\n					</tr>\r\n				</table>\r\n			</div>\r\n		</td>\r\n	</tr>\r\n	");
} 
      out.write("\r\n	<tr valign=\"middle\"><td colspan=\"7\">&nbsp;</td></tr>\r\n</table>\r\n<table width=\"100%\"  border=\"1\" align=\"center\" cellpadding=\"2\" cellspacing=\"0\">\r\n	<tr valign=\"bottom\">\r\n		<td width=\"6%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Sr. No.</b></font></div></td>\r\n		<td width=\"34%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Item</b></font></div></td>\r\n		<td width=\"10%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Attachment<br>Reference</b></font></div></td>\r\n		<td width=\"10%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Currency</b></font></div></td>\r\n		<td width=\"15%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Quantity<br>(MMBTU)</b></font></div></td>\r\n		<td width=\"10%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Rate</b></font></div></td>\r\n		<td width=\"15%\"><div align=\"center\"><font size=\"1.5px\" face=\"Arial\"><b>Amount</b></font></div></td>\r\n	</tr>\r\n	");
for(int i=0; i<VPDF_COL1.size(); i++){ 
      out.write("\r\n	<tr valign=\"top\">\r\n		<td>\r\n			<div align=\"center\">\r\n				<font size=\"1.5px\" face=\"Arial\">");
      out.print(VPDF_COL1.elementAt(i) );
      out.write("</font>\r\n			</div>\r\n		</td>\r\n		<td>\r\n			<div ");
if(Double.parseDouble(""+VPDF_COL1.elementAt(i))/(int)Double.parseDouble(""+VPDF_COL1.elementAt(i))>1){
      out.write("align=\"right\"");
}else{
      out.write("align=\"left\"");
} 
      out.write(">\r\n				<font size=\"1.5px\" face=\"Arial\">");
      out.print(VPDF_COL2.elementAt(i) );
      out.write("</font>\r\n			</div>\r\n		</td>\r\n		<td>\r\n			<div align=\"center\">\r\n				<font size=\"1.5px\" face=\"Arial\" color=\"blue\">");
      out.print(VPDF_COL3.elementAt(i) );
      out.write("</font>\r\n			</div>\r\n		</td>\r\n		<td>\r\n			<div align=\"center\">\r\n				<font size=\"1.5px\" face=\"Arial\">");
      out.print(VPDF_COL4.elementAt(i) );
      out.write("</font>\r\n			</div>\r\n		</td>\r\n		");
if(inv_flag.equals("ST") && i==0) {
      out.write("\r\n		<td>\r\n			<div align=\"center\">\r\n				<font size=\"1.5px\" face=\"Arial\" color=\"blue\">");
      out.print(VPDF_COL5.elementAt(i) );
      out.write("</font>\r\n			</div>\r\n		</td>\r\n		<td>\r\n			<div align=\"center\">\r\n				<font size=\"1.5px\" face=\"Arial\" color=\"blue\">");
      out.print(VPDF_COL6.elementAt(i) );
      out.write("</font>\r\n			</div>\r\n		</td>\r\n		");
}else{ 
      out.write("\r\n		<td>\r\n			<div align=\"right\">\r\n				<font size=\"1.5px\" face=\"Arial\">");
      out.print(VPDF_COL5.elementAt(i) );
      out.write("</font>\r\n			</div>\r\n		</td>\r\n		<td>\r\n			<div align=\"right\">\r\n				<font size=\"1.5px\" face=\"Arial\">");
      out.print(VPDF_COL6.elementAt(i) );
      out.write("</font>\r\n			</div>\r\n		</td>\r\n		");
} 
      out.write("\r\n		<td>\r\n			<div ");
if(Double.parseDouble(""+VPDF_COL1.elementAt(i))/(int)Double.parseDouble(""+VPDF_COL1.elementAt(i))>1){
      out.write("align=\"left\"");
}else{
      out.write("align=\"right\"");
} 
      out.write(">\r\n				<font size=\"1.5px\" face=\"Arial\">");
      out.print(VPDF_COL7.elementAt(i) );
      out.write("</font>\r\n			</div>\r\n		</td>\r\n	</tr>\r\n	");
} 
      out.write("\r\n</table>\r\n<table border=\"0\" width=\"100%\" align=\"center\" cellpadding=\"2\" cellspacing=\"0\">\r\n	<tr align=\"center\"><td colspan=\"7\">&nbsp;</td></tr>\r\n	<tr valign=\"middle\">\r\n		<td colspan=\"7\">\r\n			<div align=\"left\">\r\n				<font size=\"1px\" face=\"Arial\">\r\n				");
      out.print(remark_1);
      out.write("\r\n				</font>\r\n			</div>\r\n		</td>\r\n	</tr>\r\n	<tr valign=\"middle\">\r\n		<td colspan=\"7\">\r\n			<div align=\"left\">\r\n				<font size=\"1px\" face=\"Arial\">");
      out.print(remark_2);
      out.write("</font>\r\n			</div>\r\n		</td>\r\n	</tr>\r\n	<tr valign=\"middle\"><td colspan=\"7\"><div align=\"center\">&nbsp;</div></td></tr>\r\n	<tr valign=\"middle\">\r\n		<td colspan=\"7\">\r\n			<div align=\"left\">\r\n				<font size=\"1.5px\" face=\"Arial\"><b>For ");
      out.print(owner_nm);
      out.write("<br><br><br><br>Authorised Signatory</b></font>\r\n			</div>\r\n		</td>\r\n	</tr>\r\n	<tr valign=\"middle\"><td colspan=\"7\"><div align=\"center\">&nbsp;</div></td></tr>\r\n	<tr valign=\"middle\">\r\n		<td colspan=\"7\">\r\n			<div align=\"center\">\r\n			");
if(activityFlag.equals("CHECK") || activityFlag.equals("APPROVE")){ 
      out.write("\r\n				");
 if(activityFlag.equals("CHECK")){
      out.write("Checked");
}else if(activityFlag.equals("APPROVE")){ 
      out.write("Approved");
} 
      out.write(" OK:&nbsp;\r\n				<input type=\"radio\" name=\"rd\" value=\"Y\" onClick=\"doSubmit();\" ");
if(activity_value.equals("Y")){ 
      out.write("checked");
} 
      out.write(">&nbsp;<b>Yes</b>&nbsp;&nbsp;&nbsp;&nbsp;\r\n				<input type=\"radio\" name=\"rd\" value=\"N\" onClick=\"doSubmit();\" ");
if(activity_value.equals("N")){ 
      out.write("checked");
} 
      out.write(">&nbsp;<b>No</b>\r\n			");
} 
      out.write("\r\n			</div>\r\n		</td>\r\n	</tr>\r\n</table>\r\n\r\n<input type=\"hidden\" name=\"option\" value=\"DRCR_NOTE_APPROVAL\">\r\n<input type=\"hidden\" name=\"activityFlag\" value=\"");
      out.print(activityFlag);
      out.write("\">\r\n\r\n<input type=\"hidden\" name=\"counterparty_cd\" value=\"");
      out.print(counterparty_cd);
      out.write("\">\r\n<input type=\"hidden\" name=\"agmt_no\" value=\"");
      out.print(agmt_no);
      out.write("\">\r\n<input type=\"hidden\" name=\"agmt_rev\" value=\"");
      out.print(agmt_rev);
      out.write("\">\r\n<input type=\"hidden\" name=\"cont_no\" value=\"");
      out.print(cont_no);
      out.write("\">\r\n<input type=\"hidden\" name=\"cont_rev\" value=\"");
      out.print(cont_rev);
      out.write("\">\r\n<input type=\"hidden\" name=\"cargo_no\" value=\"");
      out.print(cargo_no);
      out.write("\">\r\n<input type=\"hidden\" name=\"contract_type\" value=\"");
      out.print(contract_type);
      out.write("\">\r\n<input type=\"hidden\" name=\"plant_seq\" value=\"");
      out.print(plant_seq);
      out.write("\">\r\n<input type=\"hidden\" name=\"period_start_dt\" value=\"");
      out.print(period_start_dt);
      out.write("\">\r\n<input type=\"hidden\" name=\"period_end_dt\" value=\"");
      out.print(period_end_dt);
      out.write("\">\r\n<input type=\"hidden\" name=\"billing_cycle\" value=\"");
      out.print(billing_cycle);
      out.write("\">\r\n<input type=\"hidden\" name=\"bu_unit\" value=\"");
      out.print(bu_unit);
      out.write("\">\r\n<input type=\"hidden\" name=\"bu_state_tin\" value=\"");
      out.print(bu_state_tin);
      out.write("\">\r\n<input type=\"hidden\" name=\"financial_year\" value=\"");
      out.print(financial_year);
      out.write("\">\r\n<input type=\"hidden\" name=\"invoice_seq\" value=\"");
      out.print(invoice_seq);
      out.write("\">\r\n<input type=\"hidden\" name=\"contract_ref\" value=\"");
      out.print(contRef);
      out.write("\">\r\n<input type=\"hidden\" name=\"invoice_raised_in\" value=\"");
      out.print(invoice_raised_in);
      out.write("\">\r\n\r\n<input type=\"hidden\" name=\"drcr_invoice_no\" value=\"");
      out.print(drcr_invoice_no);
      out.write("\">\r\n<input type=\"hidden\" name=\"invoice_dt\" value=\"");
      out.print(invoice_dt);
      out.write("\">\r\n<input type=\"hidden\" name=\"invoice_due_dt\" value=\"");
      out.print(invoice_due_dt);
      out.write("\">\r\n<input type=\"hidden\" name=\"invoice_amt\" value=\"");
      out.print(invoice_amt);
      out.write("\">\r\n\r\n\r\n<input type=\"hidden\" name=\"drcr_flag\" value=\"");
      out.print(drcr_flag);
      out.write("\">\r\n<input type=\"hidden\" name=\"drcr_seq\" value=\"");
      out.print(drcr_seq);
      out.write("\">\r\n\r\n<input type=\"hidden\" name=\"accroid\" value=\"");
      out.print(accroid);
      out.write("\">\r\n<input type=\"hidden\" name=\"inv_flag\" value=\"");
      out.print(inv_flag);
      out.write("\">\r\n\r\n<input type=\"hidden\" name=\"read_access\" value=\"");
      out.print(read_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"write_access\" value=\"");
      out.print(write_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"check_access\" value=\"");
      out.print(check_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"print_access\" value=\"");
      out.print(print_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"delete_access\" value=\"");
      out.print(delete_access);
      out.write("\">  	\r\n<input type=\"hidden\" name=\"audit_access\" value=\"");
      out.print(audit_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"authorize_access\" value=\"");
      out.print(authorize_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"approve_access\" value=\"");
      out.print(approve_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"execute_access\" value=\"");
      out.print(execute_access);
      out.write("\">\r\n<input type=\"hidden\" name=\"form_cd\" value=\"");
      out.print(formCd);
      out.write("\">\r\n<input type=\"hidden\" name=\"form_nm\" value=\"");
      out.print(formNm);
      out.write("\">\r\n<input type=\"hidden\" name=\"mod_cd\" value=\"");
      out.print(mod_cd);
      out.write("\">\r\n<input type=\"hidden\" name=\"mod_nm\" value=\"");
      out.print(mod_nm);
      out.write("\">\r\n<input type=\"hidden\" name=\"u\" value=\"");
      out.print(u);
      out.write("\">\r\n\r\n</form>\r\n</body>\r\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
